Repository opensearch-project/k-NN, pull requests merged in 2021-06, with the labels that each got.

#36 Add Google tests for unit testing jni
  .gitignore
  jni/CMakeLists.txt
  jni/CMakeLists.txt.in
  jni/include/faiss_wrapper.h
  jni/include/jni_util.h
  jni/include/nmslib_wrapper.h
  jni/src/faiss_wrapper.cpp
  jni/src/jni_util.cpp
  jni/src/nmslib_wrapper.cpp
  jni/tests/faiss_wrapper_test.cpp
  jni/tests/nmslib_wrapper_test.cpp
  jni/tests/test_util.cpp
  jni/tests/test_util.h
  jni/tmp/.gitignore
Labels: Infrastructure

#52 Include codecov badge
  README.md
Labels: Documentation

#54 Comment out flaky test
  src/test/java/org/opensearch/knn/plugin/action/RestKNNStatsHandlerIT.java
Labels: Infrastructure, v1.0.0, v1.1.0

#59 Add release notes for 1.0.0.0
  release-notes/opensearch-knn.release-notes-1.0.0.0.md
Labels: v1.0.0, v1.1.0
