Repository opensearch-project/k-NN, pull requests merged in 2021-11, with the labels that each got.

#179 Include Model Index status as part of Stats API
  src/main/java/org/opensearch/knn/indices/ModelDao.java
  src/main/java/org/opensearch/knn/plugin/stats/KNNStatsConfig.java
  src/main/java/org/opensearch/knn/plugin/stats/StatNames.java
  src/main/java/org/opensearch/knn/plugin/stats/suppliers/ModelIndexStatusSupplier.java
  src/test/java/org/opensearch/knn/indices/ModelDaoTests.java
  src/test/java/org/opensearch/knn/plugin/action/RestKNNStatsHandlerIT.java
Labels: Enhancements

#188 Include index model degraded status as stats for given node
  src/main/java/org/opensearch/knn/common/KNNConstants.java
  src/main/java/org/opensearch/knn/indices/ModelCache.java
  src/main/java/org/opensearch/knn/plugin/stats/KNNStatsConfig.java
  src/main/java/org/opensearch/knn/plugin/stats/StatNames.java
  src/main/java/org/opensearch/knn/plugin/stats/suppliers/EventOccurredWithinThresholdSupplier.java
  src/main/java/org/opensearch/knn/plugin/stats/suppliers/ModelIndexingDegradingSupplier.java
  src/test/java/org/opensearch/knn/indices/ModelCacheTests.java
  src/test/java/org/opensearch/knn/plugin/action/RestKNNStatsHandlerIT.java
  src/test/java/org/opensearch/knn/plugin/stats/suppliers/EventOccurredWithinThresholdSupplierTests.java
Labels: Enhancements

#207 Fix field validation in VectorReader
  src/main/java/org/opensearch/knn/index/IndexUtil.java
  src/main/java/org/opensearch/knn/index/memory/NativeMemoryEntryContext.java
  src/main/java/org/opensearch/knn/index/memory/NativeMemoryLoadStrategy.java
  src/main/java/org/opensearch/knn/plugin/transport/TrainingModelRequest.java
  src/main/java/org/opensearch/knn/plugin/transport/TrainingModelTransportAction.java
  src/main/java/org/opensearch/knn/training/TrainingJob.java
  src/main/java/org/opensearch/knn/training/VectorReader.java
  src/test/java/org/opensearch/knn/index/memory/NativeMemoryEntryContextTests.java
  src/test/java/org/opensearch/knn/training/VectorReaderTests.java
Labels: Bug Fixes

#211 Change googletest from master to main
  jni/CMakeLists.txt.in
Labels: Bug Fixes

#212 Change googletest from master to main
  jni/CMakeLists.txt.in
Labels: Bug Fixes

#219 Update testEndToEnd_fromMethod (#218)
  src/test/java/org/opensearch/knn/index/FaissIT.java
Labels: Infrastructure
