Repository opensearch-project/k-NN, pull requests merged in 2021-12, with the labels that each got.

#235 Add auto backport functionality to k-NN
  .github/workflows/backport.yml
  DEVELOPER_GUIDE.md
Labels: Infrastructure, backport 1.2

#237 Add reset for vector
  .github/workflows/links.yml
  src/main/java/org/opensearch/knn/index/KNNVectorFieldMapper.java
  src/test/java/org/opensearch/knn/KNNRestTestCase.java
  src/test/java/org/opensearch/knn/index/OpenSearchIT.java
Labels: Features, v1.3.0

#240 Add benchmark code to repo
  .gitignore
  THIRD-PARTY
  benchmarks/perf-tool/.pylintrc
  benchmarks/perf-tool/.style.yapf
  benchmarks/perf-tool/README.md
  benchmarks/perf-tool/dataset/data.hdf5
  benchmarks/perf-tool/knn-perf-tool.py
  benchmarks/perf-tool/okpt/__init__.py
  benchmarks/perf-tool/okpt/diff/diff.py
  benchmarks/perf-tool/okpt/io/args.py
  benchmarks/perf-tool/okpt/io/config/parsers/base.py
  benchmarks/perf-tool/okpt/io/config/parsers/test.py
  benchmarks/perf-tool/okpt/io/config/parsers/util.py
  benchmarks/perf-tool/okpt/io/config/schemas/test.yml
  benchmarks/perf-tool/okpt/io/utils/reader.py
  benchmarks/perf-tool/okpt/io/utils/writer.py
  benchmarks/perf-tool/okpt/main.py
  benchmarks/perf-tool/okpt/test/__init__.py
  benchmarks/perf-tool/okpt/test/profile.py
  benchmarks/perf-tool/okpt/test/runner.py
  benchmarks/perf-tool/okpt/test/steps/base.py
  benchmarks/perf-tool/okpt/test/steps/factory.py
  benchmarks/perf-tool/okpt/test/steps/steps.py
  benchmarks/perf-tool/okpt/test/test.py
  benchmarks/perf-tool/requirements.in
  benchmarks/perf-tool/requirements.txt
  benchmarks/perf-tool/sample-configs/faiss-sift-ivf/index-spec.json
  benchmarks/perf-tool/sample-configs/faiss-sift-ivf/method-spec.json
  benchmarks/perf-tool/sample-configs/faiss-sift-ivf/test.yml
  benchmarks/perf-tool/sample-configs/faiss-sift-ivf/train-index-spec.json
  benchmarks/perf-tool/sample-configs/nmslib-sift-hnsw/index-spec.json
  benchmarks/perf-tool/sample-configs/nmslib-sift-hnsw/test.yml
Labels: Infrastructure

#246 Incremented version to 1.2.3.
  .github/workflows/CI.yml
  build.gradle
  jni/CMakeLists.txt
Labels: v1.2.3
