Repository opensearch-project/k-NN, pull requests merged in 2021-07, with the labels that each got.

#58 Update OpenSearch upstream to 1.0.0
  .github/workflows/CI.yml
  build.gradle
Labels: Infrastructure, v1.0.0, v1.1.0

#46 Add Model cache to cache model templates in memory
  src/main/java/org/opensearch/knn/index/KNNSettings.java
  src/main/java/org/opensearch/knn/indices/ModelCache.java
  src/main/java/org/opensearch/knn/indices/ModelDao.java
  src/main/java/org/opensearch/knn/indices/ModelIndex.java
  src/main/java/org/opensearch/knn/plugin/KNNPlugin.java
  src/test/java/org/opensearch/knn/indices/ModelCacheTests.java
  src/test/java/org/opensearch/knn/indices/ModelDaoTests.java
Labels: Enhancements

#62 Update release note
  release-notes/opensearch-knn.release-notes-1.0.0.0.md
Labels: Documentation

#44 Add Integtest.sh for OpenSearch integtest setups
  integtest.sh
Labels: Infrastructure

#65 Update model index to include additional meta data
  src/main/java/org/opensearch/knn/index/KNNVectorFieldMapper.java
  src/main/java/org/opensearch/knn/indices/Model.java
  src/main/java/org/opensearch/knn/indices/ModelCache.java
  src/main/java/org/opensearch/knn/indices/ModelDao.java
  src/main/resources/mappings/model-index.json
  src/test/java/org/opensearch/knn/indices/ModelCacheTests.java
  src/test/java/org/opensearch/knn/indices/ModelDaoTests.java
  src/test/java/org/opensearch/knn/indices/ModelTests.java
Labels: Enhancements
