Repository opensearch-project/k-NN, pull requests merged in 2021-05, with the labels that each got.

#15 Update library description
  jni/CMakeLists.txt
Labels: Documentation

#22 Update upstream and qualifier
  .github/workflows/CI.yml
  build.gradle
Labels: Infrastructure

#23 Update upstream to branch instead of tag
  .github/workflows/CI.yml
Labels: Infrastructure

#20 Refactor interface to support method configuration in field mapping
  jni/src/org_opensearch_knn_index_v2011_KNNIndex.cpp
  src/main/java/org/opensearch/knn/common/KNNConstants.java
  src/main/java/org/opensearch/knn/index/KNNIndexCache.java
  src/main/java/org/opensearch/knn/index/KNNMethod.java
  src/main/java/org/opensearch/knn/index/KNNMethodContext.java
  src/main/java/org/opensearch/knn/index/KNNSettings.java
  src/main/java/org/opensearch/knn/index/KNNVectorFieldMapper.java
  src/main/java/org/opensearch/knn/index/KNNWeight.java
  src/main/java/org/opensearch/knn/index/MethodComponent.java
  src/main/java/org/opensearch/knn/index/MethodComponentContext.java
  src/main/java/org/opensearch/knn/index/Parameter.java
  src/main/java/org/opensearch/knn/index/SpaceType.java
  src/main/java/org/opensearch/knn/index/SpaceTypes.java
  src/main/java/org/opensearch/knn/index/codec/KNN80Codec/KNN80DocValuesConsumer.java
  src/main/java/org/opensearch/knn/index/util/KNNEngine.java
  src/main/java/org/opensearch/knn/index/util/KNNLibrary.java
  src/main/java/org/opensearch/knn/index/util/NmsLibVersion.java
  src/main/java/org/opensearch/knn/index/v2011/KNNIndex.java
  src/main/java/org/opensearch/knn/plugin/script/KNNScoringSpaceFactory.java
  src/test/java/org/opensearch/knn/KNNTestCase.java
  src/test/java/org/opensearch/knn/ODFERestTestCase.java
  src/test/java/org/opensearch/knn/index/KNNESIT.java
  src/test/java/org/opensearch/knn/index/KNNESSettingsTestIT.java
  src/test/java/org/opensearch/knn/index/KNNJNITests.java
  src/test/java/org/opensearch/knn/index/KNNMethodContextTests.java
  src/test/java/org/opensearch/knn/index/KNNMethodTests.java
  src/test/java/org/opensearch/knn/index/KNNVectorFieldMapperTests.java
  src/test/java/org/opensearch/knn/index/MethodComponentContextTests.java
  src/test/java/org/opensearch/knn/index/MethodComponentTests.java
  src/test/java/org/opensearch/knn/index/ParameterTests.java
  src/test/java/org/opensearch/knn/index/codec/KNNCodecTestCase.java
  src/test/java/org/opensearch/knn/index/util/KNNEngineTests.java
  src/test/java/org/opensearch/knn/index/util/KNNLibraryTests.java
  src/test/java/org/opensearch/knn/plugin/action/RestKNNStatsHandlerIT.java
  src/test/java/org/opensearch/knn/plugin/action/RestLegacyKNNStatsHandlerIT.java
  src/test/java/org/opensearch/knn/plugin/script/KNNScoringSpaceFactoryTests.java
  src/test/java/org/opensearch/knn/plugin/script/KNNScriptScoringIT.java
Labels: Features, enhancement

#24 Update workflow
  .github/workflows/CI.yml
Labels: Infrastructure

#30 Update upstream to use 1.0
  .github/workflows/CI.yml
Labels: Infrastructure

#32 Add release note for rc1
  release-notes/opensearch-knn.release-notes-1.0.0.0-rc1.md
Labels: Infrastructure

#33 Update PACKAGE_VERSION to k-NN plugin version
  jni/CMakeLists.txt
Labels: Documentation
