Repository opensearch-project/k-NN, pull requests merged in 2022-02, with the labels that each got.

#276 [BUG FIX] Add space type default and ef search parameter in warmup
  src/main/java/org/opensearch/knn/index/IndexUtil.java
  src/main/java/org/opensearch/knn/index/KNNIndexShard.java
  src/main/java/org/opensearch/knn/index/KNNWeight.java
  src/test/java/org/opensearch/knn/index/IndexUtilTests.java
Labels: backport 1.x, backport 1.2

#278 Add CI to run every night
  .github/workflows/CI.yml
Labels: backport 1.x

#292 Updates Guava versions to address CVE
  build.gradle
  checkstyle/checkstyle.xml
Labels: backport 1.x, security fix
