Repository opensearch-project/k-NN, pull requests merged in 2022-12, with the labels that each got.

#641 [1.x] Increment version to 1.3.7
  .github/workflows/CI.yml
  build.gradle
  jni/CMakeLists.txt
Labels: Infrastructure, v1.3.7

#642 [1.x] Add windows support (#583)
  .github/workflows/CI.yml
  LICENSE.txt
  THIRD-PARTY
  build-tools/knnplugin-coverage.gradle
  build.gradle
  jni/CMakeLists.txt
  scripts/windowsScript.ps1
Labels: windows, backport 1.3, v1.3.7

#645 [Backport 1.x] Add windows build script changes here
  scripts/build.sh
Labels: Infrastructure, backport 1.3, v1.3.7

#644 [Backport 1.3] Add windows support (#583)
  .github/workflows/CI.yml
  LICENSE.txt
  THIRD-PARTY
  build-tools/knnplugin-coverage.gradle
  build.gradle
  jni/CMakeLists.txt
  scripts/windowsScript.ps1
Labels: windows

#646 [Backport 1.3] Add windows build script changes here
  scripts/build.sh
Labels: Infrastructure, windows

#648 Get rid of Rachet to fix failing build
  gradle/formatting.gradle
  src/main/java/org/opensearch/knn/index/SpaceType.java
  src/test/java/org/opensearch/knn/plugin/action/RestLegacyKNNStatsHandlerIT.java
  src/test/java/org/opensearch/knn/plugin/action/RestLegacyKNNWarmupHandlerIT.java
Labels: Infrastructure

#649 [Backport 1.3]Get rid of Rachet to fix failing build
  gradle/formatting.gradle
  src/main/java/org/opensearch/knn/index/SpaceType.java
  src/test/java/org/opensearch/knn/plugin/action/RestLegacyKNNStatsHandlerIT.java
  src/test/java/org/opensearch/knn/plugin/action/RestLegacyKNNWarmupHandlerIT.java
Labels: Infrastructure

#652 Exclude jacocoTestReport in distribution build script
  scripts/build.sh
Labels: Infrastructure

#659 Update build script to build JNI lib and gradlew assemble
  scripts/build.sh
Labels: Infrastructure, v1.3.7

#672 Add Release notes for opensearch release 1.3.7
  release-notes/opensearch-knn.release-notes-1.3.7.0.md
Labels: backport 1.x, backport 1.3, v1.3.7

#630 Extend SystemIndexPlugin for k-NN model system index
  src/main/java/org/opensearch/knn/plugin/KNNPlugin.java
Labels: Enhancements, backport 2.x, v2.5.0

#663 Adding release configs for lucene filtering
  benchmarks/perf-tool/release-configs/lucene-hnsw/filtering/relaxed-filter/index.json
  benchmarks/perf-tool/release-configs/lucene-hnsw/filtering/relaxed-filter/relaxed-filter-spec.json
  benchmarks/perf-tool/release-configs/lucene-hnsw/filtering/relaxed-filter/relaxed-filter-test.yml
  benchmarks/perf-tool/release-configs/lucene-hnsw/filtering/restrictive-filter/index.json
  benchmarks/perf-tool/release-configs/lucene-hnsw/filtering/restrictive-filter/restrictive-filter-spec.json
  benchmarks/perf-tool/release-configs/lucene-hnsw/filtering/restrictive-filter/restrictive-filter-test.yml
Labels: Infrastructure, backport 2.x, v2.5.0

#685 Allow mapping service to be null for scenarios of shard recovery from translog
  src/main/java/org/opensearch/knn/index/codec/KNNCodecVersion.java
  src/test/java/org/opensearch/knn/index/codec/KNNCodecServiceTests.java
Labels: bug, backport 2.x, v2.5.0

#692 Add Backward Compatibility and Validation checks to ModelGraveyard XContent Bugfix
  src/main/java/org/opensearch/knn/indices/ModelGraveyard.java
  src/test/java/org/opensearch/knn/indices/ModelGraveyardTests.java
Labels: Bug Fixes, backport 2.x, backport 2.3, backport 2.4, backport 2.2

#693 Adding integ test for index close/open scenario
  src/test/java/org/opensearch/knn/index/LuceneEngineIT.java
Labels: Maintenance, backport 2.x, v2.5.0, backport 2.3, backport 2.4, backport 2.2
