Repository opensearch-project/k-NN, pull requests merged in 2022-03, with the labels that each got.

#304 Update numpy version to 1.22
  benchmarks/perf-tool/requirements.txt
Labels: v1.3.0, security fix

#305 Update numpy version to 1.22.1
  benchmarks/perf-tool/requirements.txt
Labels: security vulnerability

#302 Run CI on JDK 8
  .github/workflows/CI.yml
Labels: v1.3.0

#309 [BUG FIX] Fix knn index shard to get bwc engine paths
  src/main/java/org/opensearch/knn/index/KNNIndexShard.java
  src/main/java/org/opensearch/knn/index/codec/util/KNNCodecUtil.java
  src/test/java/org/opensearch/knn/KNNSingleNodeTestCase.java
  src/test/java/org/opensearch/knn/index/KNNIndexShardTests.java
Labels: Bug Fixes, backport 1.x, backport 1.2

#316 Add release notes for 1.3.0.0
  release-notes/opensearch-knn.release-notes-1.3.0.0.md
Labels: backport 1.x, backport 1.3

#313 [BUG FIX] Fix knn index shard to get bwc engine paths (#310)
  src/main/java/org/opensearch/knn/index/KNNIndexShard.java
  src/main/java/org/opensearch/knn/index/codec/KNNCodecUtil.java
  src/test/java/org/opensearch/knn/KNNSingleNodeTestCase.java
  src/test/java/org/opensearch/knn/index/KNNIndexShardTests.java
Labels: Bug Fixes

#321 Change minimum supported JDK version from 8 to 11
  build.gradle
Labels: v2.0.0

#322 Adding JDK 17 to CI
  .github/workflows/CI.yml
  DEVELOPER_GUIDE.md
Labels: Enhancements, v2.0.0

#319 Refactor KNNCodec to use new extension point
  gradle.properties
  src/main/java/org/opensearch/knn/index/codec/KNN80Codec/KNN80BinaryDocValues.java
  src/main/java/org/opensearch/knn/index/codec/KNN80Codec/KNN80CompoundFormat.java
  src/main/java/org/opensearch/knn/index/codec/KNN80Codec/KNN80DocValuesConsumer.java
  src/main/java/org/opensearch/knn/index/codec/KNN80Codec/KNN80DocValuesFormat.java
  src/main/java/org/opensearch/knn/index/codec/KNN80Codec/KNN80DocValuesReader.java
  src/main/java/org/opensearch/knn/index/codec/KNN87Codec/KNN87Codec.java
  src/main/java/org/opensearch/knn/index/codec/KNNCodecService.java
  src/main/java/org/opensearch/knn/index/codec/util/BinaryDocValuesSub.java
  src/main/java/org/opensearch/knn/plugin/KNNCodecService.java
  src/main/java/org/opensearch/knn/plugin/KNNEngineFactory.java
  src/main/java/org/opensearch/knn/plugin/KNNPlugin.java
  src/test/java/org/opensearch/knn/index/codec/KNN80Codec/KNN80BinaryDocValuesTests.java
  src/test/java/org/opensearch/knn/index/codec/KNN80Codec/KNN80CompoundFormatTests.java
  src/test/java/org/opensearch/knn/index/codec/KNN80Codec/KNN80DocValuesConsumerTests.java
  src/test/java/org/opensearch/knn/index/codec/KNN87Codec/KNN87CodecTests.java
  src/test/java/org/opensearch/knn/index/codec/KNNCodecTestCase.java
  src/test/java/org/opensearch/knn/index/codec/KNNCodecTestUtil.java
  src/test/java/org/opensearch/knn/index/codec/util/BinaryDocValuesSubTests.java
  src/test/java/org/opensearch/knn/index/codec/util/KNNVectorSerializerTests.java
Labels: Refactoring, v2.0.0

#325 Remove version from CMakeLists.txt
  benchmarks/perf-tool/requirements.txt
  build.gradle
  jni/CMakeLists.txt
Labels: Infrastructure

#327 Manually add footer to engine files
  src/main/java/org/opensearch/knn/index/codec/KNN80Codec/KNN80DocValuesConsumer.java
Labels: Enhancements

#330 Applying build qualifier only to knn plugin version
  build.gradle
Labels: v2.0.0, release

#328 Integration with base OpenSearch 2.0
  .github/workflows/CI.yml
  build.gradle
  src/main/java/org/opensearch/knn/index/KNNQuery.java
  src/main/java/org/opensearch/knn/index/KNNWeight.java
  src/main/java/org/opensearch/knn/index/codec/KNN80Codec/KNN80Codec.java
  src/main/java/org/opensearch/knn/index/codec/KNN80Codec/KNN80CompoundFormat.java
  src/main/java/org/opensearch/knn/index/codec/KNN80Codec/KNN80DocValuesFormat.java
  src/main/java/org/opensearch/knn/index/codec/KNN84Codec/KNN84Codec.java
  src/main/java/org/opensearch/knn/index/codec/KNN86Codec/KNN86Codec.java
  src/main/java/org/opensearch/knn/index/codec/KNN87Codec/KNN87Codec.java
  src/main/java/org/opensearch/knn/index/codec/KNN910Codec/KNN910Codec.java
  src/main/java/org/opensearch/knn/index/codec/KNNCodecFactory.java
  src/main/java/org/opensearch/knn/index/codec/KNNCodecService.java
  src/main/java/org/opensearch/knn/index/codec/KNNFormatFacade.java
  src/main/java/org/opensearch/knn/index/codec/KNNFormatFactory.java
  src/main/java/org/opensearch/knn/indices/ModelDao.java
  src/main/resources/META-INF/services/org.apache.lucene.codecs.Codec
  src/test/java/org/opensearch/knn/TestUtils.java
  src/test/java/org/opensearch/knn/index/KNNCreateIndexFromModelTests.java
  src/test/java/org/opensearch/knn/index/KNNVectorDVLeafFieldDataTests.java
  src/test/java/org/opensearch/knn/index/KNNVectorIndexFieldDataTests.java
  src/test/java/org/opensearch/knn/index/KNNVectorScriptDocValuesTests.java
  src/test/java/org/opensearch/knn/index/codec/KNN87Codec/KNN87CodecTests.java
  src/test/java/org/opensearch/knn/index/codec/KNN910Codec/KNN910CodecTests.java
  src/test/java/org/opensearch/knn/index/codec/KNNCodecFactoryTests.java
  src/test/java/org/opensearch/knn/index/codec/KNNCodecTestCase.java
  src/test/java/org/opensearch/knn/index/codec/KNNCodecTestUtil.java
  src/test/java/org/opensearch/knn/index/codec/KNNFormatFactoryTests.java
  src/test/java/org/opensearch/knn/plugin/script/KNNScoringUtilTests.java
Labels: Enhancements, v2.0.0

#334 Remove hardcoding of version in knn CI
  .github/workflows/CI.yml
Labels: v2.0.0, release

#335 Remove remaining mapping type
  src/test/java/org/opensearch/knn/KNNSingleNodeTestCase.java
Labels: Maintenance

#337 Adding documentation on codec versioning
  DEVELOPER_GUIDE.md
Labels: Documentation, v2.0.0

#338 remove hardcoded URL
  build-tools/knnplugin-coverage.gradle
  src/test/java/org/opensearch/knn/KNNRestTestCase.java
Labels: backport 1.x

#339 Adding clear cache test step
  benchmarks/perf-tool/okpt/test/steps/factory.py
  benchmarks/perf-tool/okpt/test/steps/steps.py
Labels: Enhancements, v2.0.0, backport 1.x

#344 Dropping support for JDK 14
  .github/workflows/CI.yml
Labels: v2.0.0
