Repository opensearch-project/k-NN, pull requests merged in 2022-04, with the labels that each got.

#349 Update knn with dynamic version assignment
  build.gradle
Labels: v2.0.0, release

#354 Allow null value for params in method mappings
  src/main/java/org/opensearch/knn/index/KNNMethodContext.java
  src/main/java/org/opensearch/knn/index/MethodComponentContext.java
  src/test/java/org/opensearch/knn/bwc/KNNBackwardsCompatibilityIT.java
  src/test/java/org/opensearch/knn/index/KNNMethodContextTests.java
  src/test/java/org/opensearch/knn/index/MethodComponentContextTests.java
Labels: Bug Fixes, backport 1.x, backport 1.2, backport 1.3

#370 Adding release notes for 2.0.0 rc1
  release-notes/opensearch-knn.release-notes-2.0.0.0-rc1.md
Labels: v2.0.0

#258 Backport #256 to 1.1
  .github/workflows/CI.yml
  src/main/java/org/opensearch/knn/index/KNNWeight.java
Labels: Bug Fixes

#371 Update jacoco version to 0.8.7 to support JDK 17
  build.gradle
Labels: Maintenance, v2.1.0, backport 2.0

#364 Add OpenSearch Benchmark index workload for k-NN
  benchmarks/osb/README.md
  benchmarks/osb/__init__.py
  benchmarks/osb/extensions/__init__.py
  benchmarks/osb/extensions/data_set.py
  benchmarks/osb/extensions/param_sources.py
  benchmarks/osb/extensions/registry.py
  benchmarks/osb/extensions/runners.py
  benchmarks/osb/extensions/util.py
  benchmarks/osb/indices/faiss-index.json
  benchmarks/osb/indices/model-index.json
  benchmarks/osb/indices/nmslib-index.json
  benchmarks/osb/indices/train-index.json
  benchmarks/osb/operations/default.json
  benchmarks/osb/params/no-train-params.json
  benchmarks/osb/params/train-params.json
  benchmarks/osb/procedures/no-train-test.json
  benchmarks/osb/procedures/train-test.json
  benchmarks/osb/requirements.in
  benchmarks/osb/requirements.txt
  benchmarks/osb/workload.json
  benchmarks/osb/workload.py
Labels: Infrastructure, v2.1.0
