Repository opensearch-project/k-NN, pull requests merged in 2022-10, with the labels that each got.

#567 Increment version to 1.3.6-SNAPSHOT
  .github/workflows/CI.yml
  build.gradle
  jni/CMakeLists.txt
Labels: release, v1.3.6

#571 Fix KNNCodecUtil FieldInfo construction
  src/test/java/org/opensearch/knn/index/codec/KNNCodecTestUtil.java
Labels: Bug Fixes

#574 [Backport 2.x] Replace Forum link in k-NN plugin README.md
  README.md
Labels: Documentation

#578 add groupId to pluginzip publication
  build.gradle
Labels: backport 2.x, 2.4.0

#577 Replacing BaseNodeRequest by TransportRequest
  qa/restart-upgrade/src/test/java/org/opensearch/knn/bwc/ModelIT.java
  qa/restart-upgrade/src/test/java/org/opensearch/knn/bwc/ScriptScoringIT.java
  qa/rolling-upgrade/src/test/java/org/opensearch/knn/bwc/IndexingIT.java
  qa/rolling-upgrade/src/test/java/org/opensearch/knn/bwc/StatsIT.java
  qa/rolling-upgrade/src/test/java/org/opensearch/knn/bwc/WarmupIT.java
  src/main/java/org/opensearch/knn/plugin/transport/KNNStatsNodeRequest.java
  src/main/java/org/opensearch/knn/plugin/transport/RemoveModelFromCacheNodeRequest.java
  src/main/java/org/opensearch/knn/plugin/transport/TrainingJobRouteDecisionInfoNodeRequest.java
  src/test/java/org/opensearch/knn/index/FaissIT.java
  src/test/java/org/opensearch/knn/index/KNNCircuitBreakerIT.java
  src/test/java/org/opensearch/knn/index/KNNESSettingsTestIT.java
  src/test/java/org/opensearch/knn/index/KNNMapperSearcherIT.java
  src/test/java/org/opensearch/knn/index/LuceneEngineIT.java
  src/test/java/org/opensearch/knn/index/NmslibIT.java
  src/test/java/org/opensearch/knn/index/OpenSearchIT.java
  src/test/java/org/opensearch/knn/plugin/action/RestDeleteModelHandlerIT.java
  src/test/java/org/opensearch/knn/plugin/action/RestGetModelHandlerIT.java
  src/test/java/org/opensearch/knn/plugin/action/RestKNNStatsHandlerIT.java
  src/test/java/org/opensearch/knn/plugin/action/RestKNNWarmupHandlerIT.java
  src/test/java/org/opensearch/knn/plugin/action/RestLegacyKNNStatsHandlerIT.java
  src/test/java/org/opensearch/knn/plugin/action/RestLegacyKNNWarmupHandlerIT.java
  src/test/java/org/opensearch/knn/plugin/action/RestSearchModelHandlerIT.java
  src/test/java/org/opensearch/knn/plugin/action/RestTrainModelHandlerIT.java
  src/test/java/org/opensearch/knn/plugin/script/KNNScriptScoringIT.java
  src/test/java/org/opensearch/knn/plugin/script/PainlessScriptIT.java
  src/testFixtures/java/org/opensearch/knn/KNNRestTestCase.java
  src/testFixtures/java/org/opensearch/knn/ODFERestTestCase.java
Labels: Maintenance

#581 Read min cluster version directly from DiscoveryNodes
  src/main/java/org/opensearch/knn/index/KNNClusterContext.java
  src/test/java/org/opensearch/knn/index/KNNClusterContextTests.java
  src/test/java/org/opensearch/knn/index/KNNClusterTestUtils.java
  src/test/java/org/opensearch/knn/index/query/KNNQueryBuilderTests.java
Labels: Enhancements, 2.4.0, feature branch

#582 Refactor kNN codec related classes
  src/main/java/org/opensearch/knn/index/codec/BasePerFieldKnnVectorsFormat.java
  src/main/java/org/opensearch/knn/index/codec/KNN910Codec/KNN910Codec.java
  src/main/java/org/opensearch/knn/index/codec/KNN920Codec/KNN920Codec.java
  src/main/java/org/opensearch/knn/index/codec/KNN920Codec/KNN920PerFieldKnnVectorsFormat.java
  src/main/java/org/opensearch/knn/index/codec/KNN940Codec/KNN940Codec.java
  src/main/java/org/opensearch/knn/index/codec/KNN940Codec/KNN940PerFieldKnnVectorsFormat.java
  src/main/java/org/opensearch/knn/index/codec/KNNCodecFactory.java
  src/main/java/org/opensearch/knn/index/codec/KNNCodecService.java
  src/main/java/org/opensearch/knn/index/codec/KNNCodecVersion.java
  src/main/java/org/opensearch/knn/index/codec/KNNFormatFactory.java
  src/test/java/org/opensearch/knn/index/codec/KNN920Codec/KNN920CodecTests.java
  src/test/java/org/opensearch/knn/index/codec/KNN940Codec/KNN940CodecTests.java
  src/test/java/org/opensearch/knn/index/codec/KNNCodecFactoryTests.java
  src/test/java/org/opensearch/knn/index/codec/KNNCodecTestCase.java
  src/test/java/org/opensearch/knn/index/codec/KNNFormatFactoryTests.java
Labels: Refactoring, backport 2.x

#584 [Backport 2.x] Refactor kNN codec related classes (#582)
  src/main/java/org/opensearch/knn/index/codec/BasePerFieldKnnVectorsFormat.java
  src/main/java/org/opensearch/knn/index/codec/KNN910Codec/KNN910Codec.java
  src/main/java/org/opensearch/knn/index/codec/KNN920Codec/KNN920Codec.java
  src/main/java/org/opensearch/knn/index/codec/KNN920Codec/KNN920PerFieldKnnVectorsFormat.java
  src/main/java/org/opensearch/knn/index/codec/KNN940Codec/KNN940Codec.java
  src/main/java/org/opensearch/knn/index/codec/KNN940Codec/KNN940PerFieldKnnVectorsFormat.java
  src/main/java/org/opensearch/knn/index/codec/KNNCodecFactory.java
  src/main/java/org/opensearch/knn/index/codec/KNNCodecService.java
  src/main/java/org/opensearch/knn/index/codec/KNNCodecVersion.java
  src/main/java/org/opensearch/knn/index/codec/KNNFormatFactory.java
  src/test/java/org/opensearch/knn/index/codec/KNN920Codec/KNN920CodecTests.java
  src/test/java/org/opensearch/knn/index/codec/KNN940Codec/KNN940CodecTests.java
  src/test/java/org/opensearch/knn/index/codec/KNNCodecFactoryTests.java
  src/test/java/org/opensearch/knn/index/codec/KNNCodecTestCase.java
  src/test/java/org/opensearch/knn/index/codec/KNNFormatFactoryTests.java
Labels: Refactoring

#587 Adding stat for query with filter
  src/main/java/org/opensearch/knn/index/query/KNNQueryBuilder.java
  src/main/java/org/opensearch/knn/plugin/stats/KNNCounter.java
  src/main/java/org/opensearch/knn/plugin/stats/KNNStatsConfig.java
  src/main/java/org/opensearch/knn/plugin/stats/StatNames.java
  src/test/java/org/opensearch/knn/plugin/action/RestKNNStatsHandlerIT.java
Labels: Enhancements, v2.4.0, feature branch

#583 Add windows support
  .github/workflows/CI.yml
  LICENSE.txt
  THIRD-PARTY
  build-tools/knnplugin-coverage.gradle
  build.gradle
  jni/CMakeLists.txt
  scripts/windowsScript.ps1
Labels: Enhancements, windows, 2.4.0

#596 Update build script to publish to maven local
  scripts/build.sh
Labels: Infrastructure, backport 2.x

#595 Add Windows Build.sh Related Changes in k-NN
  scripts/build.sh
Labels: Enhancements, enhancement, windows

#592 Remove min cluster version checks
  qa/rolling-upgrade/src/test/java/org/opensearch/knn/bwc/LuceneFilteringIT.java
  src/main/java/org/opensearch/knn/index/query/KNNQueryBuilder.java
  src/test/java/org/opensearch/knn/index/query/KNNQueryBuilderTests.java
Labels: Enhancements

#599 Add windows support (#583)
  .github/workflows/CI.yml
  LICENSE.txt
  THIRD-PARTY
  build-tools/knnplugin-coverage.gradle
  build.gradle
  jni/CMakeLists.txt
  scripts/windowsScript.ps1
Labels: Enhancements, windows

#603 Disable Code Coverage for Windows and Mac Platforms
  .github/workflows/CI.yml
Labels: Infrastructure, backport 2.x, 2.4.0

#602 Add Windows Build.sh Related Changes
  scripts/build.sh
Labels: Enhancements, windows, 2.4.0
