Repository opensearch-project/k-NN, pull requests merged in 2022-08, with the labels that each got.

#483 Change validation error for dimension value
  src/main/java/org/opensearch/knn/index/mapper/KNNVectorFieldMapper.java
  src/test/java/org/opensearch/knn/index/mapper/KNNVectorFieldMapperTests.java
Labels: Severity-Minor, 2.2.0, backport 2.x

#487 Change call to Lucene VectorSimilarityFunction.convertToScore
  src/test/java/org/opensearch/knn/index/LuceneEngineIT.java
Labels: bug

#488 Make innerproduct similarity not supported
  src/main/java/org/opensearch/knn/index/util/Lucene.java
  src/test/java/org/opensearch/knn/index/LuceneEngineIT.java
  src/test/java/org/opensearch/knn/index/mapper/KNNVectorFieldMapperTests.java
Labels: Enhancements, 2.2.0, backport 2.x

#490 Increase max dimension to 16k for nmslib and faiss
  src/main/java/org/opensearch/knn/index/util/KNNEngine.java
  src/main/java/org/opensearch/knn/indices/ModelMetadata.java
Labels: Enhancements, backport 2.x

#492 Remove 1.0.0 for BWC test
  .github/workflows/backwards_compatibility_tests_workflow.yml
Labels: Infrastructure, backport 1.x, backport 2.x

#484 Add 2.2.0.0 release notes
  release-notes/opensearch-knn.release-notes-2.2.0.0.md
Labels: release, 2.2.0, backport 2.x

#501 Remove overallocation in faiss query path
  jni/src/faiss_wrapper.cpp
Labels: Bug Fixes, backport 2.x

#510 [Backport 2.1] Increase max dimension to 16k for nmslib and faiss
  src/main/java/org/opensearch/knn/index/KNNVectorFieldMapper.java
Labels: Enhancements

#502 Change initial size of DocIdSetBuilder
  src/main/java/org/opensearch/knn/index/query/KNNWeight.java
Labels: Enhancements, backport 2.x

#512 Add force merge operation in OSB tests
  benchmarks/osb/README.md
  benchmarks/osb/params/no-train-params.json
  benchmarks/osb/params/train-params.json
  benchmarks/osb/procedures/no-train-test.json
  benchmarks/osb/procedures/train-test.json
Labels: Infrastructure

#515 Adding efficient filtering
  src/main/java/org/opensearch/knn/index/query/KNNQueryBuilder.java
  src/main/java/org/opensearch/knn/index/query/KNNQueryFactory.java
  src/test/java/org/opensearch/knn/index/query/KNNQueryFactoryTests.java
Labels: Enhancements, 2.4.0

#518 Update dev guide with instructions for mac
  DEVELOPER_GUIDE.md
Labels: Documentation

#521 Replace terminology 'master' with 'cluster manager'
  src/main/java/org/opensearch/knn/index/KNNCircuitBreaker.java
  src/main/java/org/opensearch/knn/indices/ModelGraveyard.java
  src/main/java/org/opensearch/knn/plugin/transport/UpdateModelGraveyardTransportAction.java
  src/main/java/org/opensearch/knn/plugin/transport/UpdateModelMetadataTransportAction.java
  src/test/java/org/opensearch/knn/plugin/transport/UpdateModelGraveyardTransportActionTests.java
  src/test/java/org/opensearch/knn/plugin/transport/UpdateModelMetadataTransportActionTests.java
Labels: enhancement, 2.3.0, backport 2.x
