Repository opensearch-project/k-NN, pull requests merged in 2022-01, with the labels that each got.

#248 Incremented version to 1.2.4.
  .github/workflows/CI.yml
  build.gradle
  jni/CMakeLists.txt
Labels: v1.2.4

#247 Clean up flaky tests
  src/test/java/org/opensearch/knn/KNNRestTestCase.java
  src/test/java/org/opensearch/knn/plugin/action/RestKNNStatsHandlerIT.java
  src/test/java/org/opensearch/knn/plugin/action/RestTrainModelHandlerIT.java
  src/test/java/org/opensearch/knn/plugin/transport/RemoveModelFromCacheTransportActionTests.java
Labels: Infrastructure

#257 Backport #256 to 1.2
  src/main/java/org/opensearch/knn/index/KNNWeight.java
Labels: Bug Fixes

#253 Changing serialization for knn vector from single array object to collection of floats
  src/main/java/org/opensearch/knn/index/KNNIndexShard.java
  src/main/java/org/opensearch/knn/index/KNNVectorScriptDocValues.java
  src/main/java/org/opensearch/knn/index/VectorField.java
  src/main/java/org/opensearch/knn/index/codec/KNN80Codec/KNN80CompoundFormat.java
  src/main/java/org/opensearch/knn/index/codec/KNN80Codec/KNN80DocValuesConsumer.java
  src/main/java/org/opensearch/knn/index/codec/util/KNNCodecUtil.java
  src/main/java/org/opensearch/knn/index/codec/util/KNNVectorAsArraySerializer.java
  src/main/java/org/opensearch/knn/index/codec/util/KNNVectorAsCollectionOfFloatsSerializer.java
  src/main/java/org/opensearch/knn/index/codec/util/KNNVectorSerializer.java
  src/main/java/org/opensearch/knn/index/codec/util/KNNVectorSerializerFactory.java
  src/main/java/org/opensearch/knn/index/codec/util/SerializationMode.java
  src/test/java/org/opensearch/knn/TestUtils.java
  src/test/java/org/opensearch/knn/index/codec/KNNVectorSerializerTests.java
Labels: Enhancements, v1.3.0

#261 Removing jcenter repo from repositories blocks in gradle files
  build-tools/repositories.gradle
  build.gradle
Labels: bug, v1.3.0, backport 1.2

#266 Adding gradle task for running integ tests in remote cluster
  DEVELOPER_GUIDE.md
  build.gradle
  src/test/java/org/opensearch/knn/index/KNNCircuitBreakerIT.java
Labels: Enhancements, v1.3.0

#268 Change benchmark ingest took metric to total time
  benchmarks/perf-tool/README.md
  benchmarks/perf-tool/okpt/test/steps/steps.py
Labels: Enhancements

#272 [Benchmark] Remove ingest results collection
  benchmarks/perf-tool/okpt/test/steps/steps.py
Labels: Infrastructure
