Repository opensearch-project/k-NN, pull requests merged in 2022-07, with the labels that each got.

#437 Staging for version increment automation
  build.gradle
Labels: backport 2.0, backport 2.1

#439 Refactor knn type and codecs
  src/main/java/org/opensearch/knn/index/KNNMethod.java
  src/main/java/org/opensearch/knn/index/KNNMethodContext.java
  src/main/java/org/opensearch/knn/index/KNNVectorFieldMapper.java
  src/main/java/org/opensearch/knn/index/MethodComponent.java
  src/main/java/org/opensearch/knn/index/MethodComponentContext.java
  src/main/java/org/opensearch/knn/index/codec/KNNCodecFactory.java
  src/main/java/org/opensearch/knn/index/codec/KNNCodecService.java
  src/main/java/org/opensearch/knn/index/codec/util/CodecBuilder.java
  src/main/java/org/opensearch/knn/training/TrainingJob.java
  src/test/java/org/opensearch/knn/index/KNNMethodContextTests.java
  src/test/java/org/opensearch/knn/index/codec/KNNCodecFactoryTests.java
  src/test/java/org/opensearch/knn/index/codec/KNNFormatFactoryTests.java
  src/test/java/org/opensearch/knn/jni/JNIServiceTests.java
  src/test/java/org/opensearch/knn/plugin/script/KNNScoringSpaceTests.java
  src/test/java/org/opensearch/knn/training/TrainingJobTests.java
Labels: Refactoring, 2.2.0

#438 Move engine and lib components into separate files
  src/main/java/org/opensearch/knn/index/codec/KNN80Codec/KNN80DocValuesConsumer.java
  src/main/java/org/opensearch/knn/index/util/Faiss.java
  src/main/java/org/opensearch/knn/index/util/KNNEngine.java
  src/main/java/org/opensearch/knn/index/util/KNNLibrary.java
  src/main/java/org/opensearch/knn/index/util/NativeLibrary.java
  src/main/java/org/opensearch/knn/index/util/Nmslib.java
  src/test/java/org/opensearch/knn/index/codec/KNN80Codec/KNN80DocValuesConsumerTests.java
  src/test/java/org/opensearch/knn/index/util/FaissTests.java
  src/test/java/org/opensearch/knn/index/util/KNNEngineTests.java
  src/test/java/org/opensearch/knn/index/util/NativeLibraryTests.java
  src/test/java/org/opensearch/knn/plugin/stats/suppliers/LibraryInitializedSupplierTests.java
Labels: Refactoring, 2.2.0, backport 2.x

#444 Adding KNN codec that is based on Lucene92 codec
  src/main/java/org/opensearch/knn/index/codec/KNN920Codec/KNN920Codec.java
  src/main/java/org/opensearch/knn/index/codec/KNNCodecFactory.java
  src/main/java/org/opensearch/knn/index/codec/KNNFormatFactory.java
  src/main/java/org/opensearch/knn/index/codec/util/CodecBuilder.java
  src/main/resources/META-INF/services/org.apache.lucene.codecs.Codec
  src/test/java/org/opensearch/knn/index/codec/KNN920Codec/KNN920CodecTests.java
  src/test/java/org/opensearch/knn/index/codec/KNNCodecFactoryTests.java
  src/test/java/org/opensearch/knn/index/codec/KNNCodecTestCase.java
  src/test/java/org/opensearch/knn/index/codec/KNNFormatFactoryTests.java
Labels: Enhancements, 2.2.0, backport 2.x

#424 Reject delete model request if model is in Training
  qa/restart-upgrade/src/test/java/org/opensearch/knn/bwc/ModelIT.java
  src/main/java/org/opensearch/knn/indices/ModelDao.java
  src/main/java/org/opensearch/knn/indices/ModelGraveyard.java
  src/main/java/org/opensearch/knn/plugin/KNNPlugin.java
  src/main/java/org/opensearch/knn/plugin/transport/GetModelTransportAction.java
  src/main/java/org/opensearch/knn/plugin/transport/TrainingModelRequest.java
  src/main/java/org/opensearch/knn/plugin/transport/UpdateModelGraveyardAction.java
  src/main/java/org/opensearch/knn/plugin/transport/UpdateModelGraveyardRequest.java
  src/main/java/org/opensearch/knn/plugin/transport/UpdateModelGraveyardTransportAction.java
  src/test/java/org/opensearch/knn/indices/ModelDaoTests.java
  src/test/java/org/opensearch/knn/indices/ModelGraveyardTests.java
  src/test/java/org/opensearch/knn/plugin/action/RestDeleteModelHandlerIT.java
  src/test/java/org/opensearch/knn/plugin/transport/TrainingModelRequestTests.java
  src/test/java/org/opensearch/knn/plugin/transport/UpdateModelGraveyardRequestTests.java
  src/test/java/org/opensearch/knn/plugin/transport/UpdateModelGraveyardTransportActionTests.java
Labels: Bug Fixes, backport 2.x

#448 Move mappers to separate files
  src/main/java/org/opensearch/knn/index/IndexUtil.java
  src/main/java/org/opensearch/knn/index/KNNIndexShard.java
  src/main/java/org/opensearch/knn/index/KNNQueryBuilder.java
  src/main/java/org/opensearch/knn/index/codec/KNN80Codec/KNN80DocValuesConsumer.java
  src/main/java/org/opensearch/knn/index/mapper/KNNVectorFieldMapper.java
  src/main/java/org/opensearch/knn/index/mapper/LegacyFieldMapper.java
  src/main/java/org/opensearch/knn/index/mapper/MethodFieldMapper.java
  src/main/java/org/opensearch/knn/index/mapper/ModelFieldMapper.java
  src/main/java/org/opensearch/knn/indices/ModelMetadata.java
  src/main/java/org/opensearch/knn/plugin/KNNPlugin.java
  src/main/java/org/opensearch/knn/plugin/script/KNNScoringSpace.java
  src/main/java/org/opensearch/knn/plugin/script/KNNScoringSpaceUtil.java
  src/test/java/org/opensearch/knn/index/KNNQueryBuilderTests.java
  src/test/java/org/opensearch/knn/index/OpenSearchIT.java
  src/test/java/org/opensearch/knn/index/codec/KNN80Codec/KNN80DocValuesConsumerTests.java
  src/test/java/org/opensearch/knn/index/codec/KNNCodecTestCase.java
  src/test/java/org/opensearch/knn/index/mapper/KNNVectorFieldMapperTests.java
  src/test/java/org/opensearch/knn/indices/ModelTests.java
  src/test/java/org/opensearch/knn/plugin/script/KNNScoringSpaceFactoryTests.java
  src/test/java/org/opensearch/knn/plugin/script/KNNScoringSpaceTests.java
  src/test/java/org/opensearch/knn/plugin/script/KNNScoringSpaceUtilTests.java
  src/test/java/org/opensearch/knn/plugin/script/PainlessScriptIT.java
  src/test/java/org/opensearch/knn/plugin/transport/TrainingModelRequestTests.java
Labels: Refactoring, 2.2.0, backport 2.x

#452 [feature/lucene-knn] Add Lucene as a KNNEngine
  src/main/java/org/opensearch/knn/common/KNNConstants.java
  src/main/java/org/opensearch/knn/index/KNNIndexShard.java
  src/main/java/org/opensearch/knn/index/codec/KNN80Codec/KNN80CompoundFormat.java
  src/main/java/org/opensearch/knn/index/util/AbstractKNNLibrary.java
  src/main/java/org/opensearch/knn/index/util/JVMLibrary.java
  src/main/java/org/opensearch/knn/index/util/KNNEngine.java
  src/main/java/org/opensearch/knn/index/util/Lucene.java
  src/main/java/org/opensearch/knn/index/util/NativeLibrary.java
  src/test/java/org/opensearch/knn/index/util/AbstractKNNLibraryTests.java
  src/test/java/org/opensearch/knn/index/util/LuceneTests.java
  src/test/java/org/opensearch/knn/index/util/NativeLibraryTests.java
Labels: Enhancements

#456 [feature/lucene-knn] Add field mapper and per field format
  src/main/java/org/opensearch/knn/index/codec/KNN80Codec/KNN80DocValuesConsumer.java
  src/main/java/org/opensearch/knn/index/codec/KNN920Codec/KNN920Codec.java
  src/main/java/org/opensearch/knn/index/codec/KNNCodecFactory.java
  src/main/java/org/opensearch/knn/index/mapper/KNNVectorFieldMapper.java
  src/main/java/org/opensearch/knn/index/mapper/LuceneFieldMapper.java
  src/test/java/org/opensearch/knn/index/LuceneIT.java
  src/test/java/org/opensearch/knn/index/codec/KNN920Codec/KNN920CodecTests.java
  src/test/java/org/opensearch/knn/index/codec/KNNCodecFactoryTests.java
  src/test/java/org/opensearch/knn/index/codec/KNNFormatFactoryTests.java
  src/test/java/org/opensearch/knn/index/mapper/KNNVectorFieldMapperTests.java
Labels: Enhancements

#457 Support doc values for fields using Lucene engine
  src/main/java/org/opensearch/knn/index/mapper/LuceneFieldMapper.java
  src/test/java/org/opensearch/knn/index/mapper/KNNVectorFieldMapperTests.java
  src/test/java/org/opensearch/knn/plugin/script/PainlessScriptIT.java
Labels: Enhancements

#447 Incremented version to 2.1.1.
  .github/workflows/backwards_compatibility_tests_workflow.yml
  build.gradle
Labels: v2.1.1

#436 Staging for version increment automation
  build.gradle
Labels: backport 1.3

#442 Staging for version increment automation
  build.gradle
Labels: backport 2.0, backport 2.1, backport 2.x

#463 Add fix to flaky test in ModelDaoTests
  src/test/java/org/opensearch/knn/indices/ModelDaoTests.java
Labels: Infrastructure, backport 2.x

#471 Bump OS version to 2.2.0
  .github/workflows/backwards_compatibility_tests_workflow.yml
  build.gradle
  qa/restart-upgrade/build.gradle
Labels: release, 2.2.0

#476 Read BWC Version from Github workflow
  .github/workflows/backwards_compatibility_tests_workflow.yml
  qa/rolling-upgrade/build.gradle
Labels: Infrastructure, backport 2.x

#477 Bump default bwc version to 1.3.4
  gradle.properties
Labels: Infrastructure, Maintenance, backport 2.x

#472 Bump Gradle version to 7.5
  gradle/wrapper/gradle-wrapper.properties
Labels: Maintenance, backport 2.x
