Repository opensearch-project/k-NN, pull requests merged in 2022-06, with the labels that each got.

#416 Change VectorReaderListener to expect number array
  src/main/java/org/opensearch/knn/training/VectorReader.java
  src/test/java/org/opensearch/knn/training/VectorReaderTests.java
Labels: Bug Fixes, backport 1.x, backport 1.2, backport 1.3, backport 2.0

#409 Add Querying Functionality to OSB
  benchmarks/osb/README.md
  benchmarks/osb/extensions/data_set.py
  benchmarks/osb/extensions/param_sources.py
  benchmarks/osb/params/no-train-params.json
  benchmarks/osb/params/train-params.json
  benchmarks/osb/procedures/no-train-test.json
  benchmarks/osb/procedures/train-test.json
  benchmarks/osb/tests/__init__.py
  benchmarks/osb/tests/data_set_helper.py
  benchmarks/osb/tests/test_param_sources.py
Labels: Infrastructure

#430 Adds release notes for 2.1
  release-notes/opensearch-knn.release-notes-2.1.0.0.md
Labels: v2.1.0, backport 2.1
