Repository opensearch-project/k-NN, pull requests merged in 2022-05, with the labels that each got.

#382 [Backport 1.x] Rename knnlib to lib
  scripts/build.sh
Labels: backport 1.3

#393 Adding support for Lombok
  build.gradle
  lombok.config
  src/test/java/org/opensearch/knn/index/codec/KNN80Codec/KNN80CompoundFormatTests.java
  src/test/java/org/opensearch/knn/index/codec/KNN80Codec/KNN80DocValuesConsumerTests.java
  src/test/java/org/opensearch/knn/index/codec/KNNCodecTestUtil.java
Labels: Refactoring

#394 Remove rc1 build qualifier for 2.0 GA release
  build.gradle
Labels: release, backport 2.0

#389 Add support for multiple BWC Versions
  .github/workflows/CI.yml
  .github/workflows/backwards_compatibility_tests_workflow.yml
  gradle.properties
  qa/build.gradle
  qa/restart-upgrade/build.gradle
  qa/restart-upgrade/src/test/java/org/opensearch/knn/bwc/IndexingIT.java
  qa/rolling-upgrade/build.gradle
Labels: backport 2.0

#400 Use custom plugin to publish zips to maven
  build.gradle
  scripts/build.sh
  settings.gradle
Labels: Infrastructure, v2.0.0, backport 2.0

#410 Set tests.security.manager flag to false in integTestRemote task
  build.gradle
Labels: Infrastructure

#411 Bumping main version to opensearch core 2.1.0
  .github/workflows/backwards_compatibility_tests_workflow.yml
  build.gradle
  gradle/wrapper/gradle-wrapper.properties
  qa/restart-upgrade/build.gradle
  src/main/java/org/opensearch/knn/index/codec/KNNCodecFactory.java
  src/test/java/org/opensearch/knn/index/codec/KNNCodecFactoryTests.java
  src/testFixtures/java/org/opensearch/knn/ODFERestTestCase.java
Labels: release
