Repository opensearch-project/k-NN, pull requests merged in 2022-11, with the labels that each got.

#613 Fixing flaky test for knn codecs
  src/test/java/org/opensearch/knn/index/codec/KNNCodecTestCase.java
Labels: Infrastructure, v2.4.0, backport 2.4

#611 Add release note for 2.4.0
  release-notes/opensearch-knn.release-notes-2.4.0.0.md
Labels: backport 2.x, v2.4.0, backport 2.4

#618 Add fix to fromXContent and toXContent in ModelGraveyard
  src/main/java/org/opensearch/knn/indices/ModelGraveyard.java
  src/test/java/org/opensearch/knn/indices/ModelGraveyardTests.java
Labels: Bug Fixes, v2.4.0

#610 Fixed failing unit test
  src/test/java/org/opensearch/knn/index/codec/KNNCodecTestCase.java
Labels: Infrastructure, v2.4.0

#598 Adding benchmark workflow for queries with filters
  benchmarks/perf-tool/README.md
  benchmarks/perf-tool/add-filters-to-dataset.py
  benchmarks/perf-tool/dataset/data-with-attr-with-filters.hdf5
  benchmarks/perf-tool/dataset/data-with-attr.hdf5
  benchmarks/perf-tool/okpt/io/config/parsers/util.py
  benchmarks/perf-tool/okpt/io/dataset.py
  benchmarks/perf-tool/okpt/test/steps/factory.py
  benchmarks/perf-tool/okpt/test/steps/steps.py
  benchmarks/perf-tool/sample-configs/filter-spec/filter-1-spec.json
  benchmarks/perf-tool/sample-configs/filter-spec/filter-2-spec.json
  benchmarks/perf-tool/sample-configs/filter-spec/filter-3-spec.json
  benchmarks/perf-tool/sample-configs/filter-spec/filter-4-spec.json
  benchmarks/perf-tool/sample-configs/filter-spec/filter-5-spec.json
  benchmarks/perf-tool/sample-configs/lucene-sift-hnsw-filter/index-spec.json
  benchmarks/perf-tool/sample-configs/lucene-sift-hnsw-filter/test.yml
Labels: Enhancements, backport 2.x
