Repository opensearch-project/k-NN, pull requests merged in 2022-09, with the labels that each got.

#534 Nomenclature changes from Whitelist to Allowlist
  src/main/java/org/opensearch/knn/plugin/script/KNNAllowlistExtension.java
  src/main/java/org/opensearch/knn/plugin/script/KNNScoringUtil.java
  src/main/resources/META-INF/services/org.opensearch.painless.spi.PainlessExtension
  src/main/resources/org/opensearch/knn/plugin/script/knn_allowlist.txt
  src/test/java/org/opensearch/knn/plugin/script/KNNScoringUtilTests.java
Labels: enhancement, 2.3.0, backport 2.x

#536 Updated the BWC workflow to have 2.2.0 as the backward supported version in BWC tests
  .github/workflows/backwards_compatibility_tests_workflow.yml
Labels: backwards-compatibility, 2.3.0, backport 2.x, v2.3.0, k-NN

#538 Adding tests and logs for Lucene k-NN filtering
  src/main/java/org/opensearch/knn/index/query/KNNQueryBuilder.java
  src/main/java/org/opensearch/knn/index/query/KNNQueryFactory.java
  src/test/java/org/opensearch/knn/index/LuceneEngineIT.java
  src/test/java/org/opensearch/knn/index/query/KNNQueryBuilderTests.java
Labels: Enhancements, 2.4.0, feature branch

#523 Adding k-NN engine stat
  qa/rolling-upgrade/src/test/java/org/opensearch/knn/bwc/StatsIT.java
  src/main/java/org/opensearch/knn/index/mapper/KNNVectorFieldMapper.java
  src/main/java/org/opensearch/knn/index/mapper/LuceneFieldMapper.java
  src/main/java/org/opensearch/knn/index/util/JVMLibrary.java
  src/main/java/org/opensearch/knn/index/util/Lucene.java
  src/main/java/org/opensearch/knn/plugin/stats/KNNStatsConfig.java
  src/main/java/org/opensearch/knn/plugin/stats/StatNames.java
  src/test/java/org/opensearch/knn/index/mapper/KNNVectorFieldMapperTests.java
  src/test/java/org/opensearch/knn/index/util/LuceneTests.java
  src/test/java/org/opensearch/knn/plugin/action/RestKNNStatsHandlerIT.java
  src/testFixtures/java/org/opensearch/knn/KNNRestTestCase.java
Labels: Enhancements, backport 2.x, 2.4.0

#540 Replace Forum link in k-NN plugin README.md
  README.md
Labels: Documentation, backport 2.x, 2.4.0

#546 Added release notes for version 2.3.0
  release-notes/opensearch-knn.release-notes-2.3.0.0.md
Labels: Documentation, release, backport 2.x, backport 2.3

#549 Fixed the pull request links in the k-nn release notes 2.3.0.
  release-notes/opensearch-knn.release-notes-2.3.0.0.md
Labels: Maintenance, backport 2.x, backport 2.3

#555 [554]Added sample perf-test configs for faiss-ivf, faiss-ivfpq, lucene-hnsw
  benchmarks/perf-tool/release-configs/faiss-ivf/index.json
  benchmarks/perf-tool/release-configs/faiss-ivf/method-spec.json
  benchmarks/perf-tool/release-configs/faiss-ivf/test.yml
  benchmarks/perf-tool/release-configs/faiss-ivf/train-index-spec.json
  benchmarks/perf-tool/release-configs/faiss-ivfpq/index.json
  benchmarks/perf-tool/release-configs/faiss-ivfpq/method-spec.json
  benchmarks/perf-tool/release-configs/faiss-ivfpq/test.yml
  benchmarks/perf-tool/release-configs/faiss-ivfpq/train-index-spec.json
  benchmarks/perf-tool/release-configs/lucene-hnsw/index.json
  benchmarks/perf-tool/release-configs/lucene-hnsw/test.yml
  benchmarks/perf-tool/release-configs/nmslib-hnsw/index.json
  benchmarks/perf-tool/release-configs/nmslib-hnsw/test.yml
Labels: Documentation, backport 2.x

#562 Refactor unit tests for codec
  src/main/java/org/opensearch/knn/index/codec/KNN920Codec/KNN920Codec.java
  src/test/java/org/opensearch/knn/index/codec/KNN920Codec/KNN920CodecTests.java
  src/test/java/org/opensearch/knn/index/codec/KNNCodecTestCase.java
Labels: Refactoring, backport 2.x, 2.4.0
