Repository opensearch-project/k-NN, pull requests merged in 2023-05, with the labels that each got.

#883 Baseline Maintainers
  MAINTAINERS.md
Labels: backport 1.x, backport 1.3, backport 2.x, skip-changelog, backport 2.7

#889 Baseline Codeowners
  .github/CODEOWNERS
Labels: backport 1.x, backport 1.3, backport 2.x, skip-changelog, backport 2.7

#891 [Backport 2.7] Baseline Maintainers (#883)
  MAINTAINERS.md
Labels: skip-changelog

#893 [Backport 1.3] Baseline Maintainers (#883)
  MAINTAINERS.md
Labels: skip-changelog

#892 [Backport 1.x] Baseline Maintainers (#883)
  MAINTAINERS.md
Labels: skip-changelog

#890 [Backport 2.x] Baseline Maintainers (#883)
  MAINTAINERS.md
Labels: skip-changelog

#885 Move ImmutableOpenMap usage to j.u.Map and upgrade gradle to 7.6.1
  .github/workflows/backwards_compatibility_tests_workflow.yml
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  src/main/java/org/opensearch/knn/plugin/transport/TrainingJobRouterTransportAction.java
  src/test/java/org/opensearch/knn/plugin/transport/TrainingJobRouterTransportActionTests.java
  src/test/java/org/opensearch/knn/plugin/transport/TrainingModelRequestTests.java
Labels: skip-changelog

#900 Fix sha256 on gradle 7.6.1
  gradle/wrapper/gradle-wrapper.properties
Labels: backport 2.x, skip-changelog

#902 Fix checksum for gradle
  gradle/wrapper/gradle-wrapper.properties
Labels: skip-changelog

#904 Fix build errors after refactoring of Strings class in core
  CHANGELOG.md
  src/main/java/org/opensearch/knn/common/exception/DeleteModelWhenInTrainStateException.java
  src/main/java/org/opensearch/knn/index/query/KNNQueryBuilder.java
  src/main/java/org/opensearch/knn/plugin/rest/RestDeleteModelHandler.java
  src/main/java/org/opensearch/knn/plugin/rest/RestGetModelHandler.java
  src/main/java/org/opensearch/knn/plugin/rest/RestKNNStatsHandler.java
  src/main/java/org/opensearch/knn/plugin/rest/RestKNNWarmupHandler.java
  src/main/java/org/opensearch/knn/plugin/transport/DeleteModelRequest.java
  src/main/java/org/opensearch/knn/plugin/transport/TrainingJobRouterTransportAction.java
  src/main/java/org/opensearch/knn/training/TrainingJob.java
  src/testFixtures/java/org/opensearch/knn/KNNRestTestCase.java
Labels: backport 2.x

#898 Add Auto Release Workflow
  .github/workflows/auto-release.yml
Labels: backport 1.x, backport 2.x, skip-changelog

#915 Disable index refresh for system indices
  CHANGELOG.md
  src/test/java/org/opensearch/knn/index/FaissIT.java
  src/testFixtures/java/org/opensearch/knn/KNNRestTestCase.java
Labels: Infrastructure, backport 2.x

#913 Bump requests version from 2.26.0 to 2.31.0
  CHANGELOG.md
  benchmarks/perf-tool/requirements.txt
Labels: backport 2.x

#918 Adding release notes for 2.8
  CHANGELOG.md
  release-notes/opensearch-knn.release-notes-2.8.0.0.md
Labels: backport 2.x, skip-changelog
