Repository opensearch-project/k-NN, pull requests merged in 2023-12, with the labels that each got.

#1336 Fix Failing Clear Cache API Test
  src/test/java/org/opensearch/knn/plugin/action/RestClearCacheHandlerIT.java
Labels: skip-changelog, integ-test-failure

#1317 Properly designate model state for actively training models when nodes crash or leave cluster
  CHANGELOG.md
  qa/restart-upgrade/src/test/java/org/opensearch/knn/bwc/ModelIT.java
  src/main/java/org/opensearch/knn/common/KNNConstants.java
  src/main/java/org/opensearch/knn/index/IndexUtil.java
  src/main/java/org/opensearch/knn/indices/ModelDao.java
  src/main/java/org/opensearch/knn/indices/ModelMetadata.java
  src/main/java/org/opensearch/knn/plugin/KNNPlugin.java
  src/main/java/org/opensearch/knn/plugin/transport/TrainingModelTransportAction.java
  src/main/java/org/opensearch/knn/training/TrainingJob.java
  src/main/java/org/opensearch/knn/training/TrainingJobClusterStateListener.java
  src/main/java/org/opensearch/knn/training/TrainingJobRunner.java
  src/test/java/org/opensearch/knn/index/KNNCreateIndexFromModelTests.java
  src/test/java/org/opensearch/knn/index/codec/KNN80Codec/KNN80DocValuesConsumerTests.java
  src/test/java/org/opensearch/knn/index/codec/KNNCodecTestCase.java
  src/test/java/org/opensearch/knn/index/mapper/KNNVectorFieldMapperTests.java
  src/test/java/org/opensearch/knn/indices/ModelCacheTests.java
  src/test/java/org/opensearch/knn/indices/ModelDaoTests.java
  src/test/java/org/opensearch/knn/indices/ModelMetadataTests.java
  src/test/java/org/opensearch/knn/indices/ModelStateTests.java
  src/test/java/org/opensearch/knn/indices/ModelTests.java
  src/test/java/org/opensearch/knn/plugin/action/RestSearchModelHandlerIT.java
  src/test/java/org/opensearch/knn/plugin/transport/GetModelResponseTests.java
  src/test/java/org/opensearch/knn/plugin/transport/RemoveModelFromCacheTransportActionTests.java
  src/test/java/org/opensearch/knn/plugin/transport/TrainingJobRouteDecisionInfoTransportActionTests.java
  src/test/java/org/opensearch/knn/plugin/transport/TrainingModelRequestTests.java
  src/test/java/org/opensearch/knn/plugin/transport/UpdateModelMetadataRequestTests.java
  src/test/java/org/opensearch/knn/plugin/transport/UpdateModelMetadataTransportActionTests.java
  src/test/java/org/opensearch/knn/training/TrainingJobClusterStateListenerTests.java
  src/test/java/org/opensearch/knn/training/TrainingJobRunnerTests.java
  src/test/java/org/opensearch/knn/training/TrainingJobTests.java
  src/testFixtures/java/org/opensearch/knn/KNNRestTestCase.java
Labels: Bug Fixes, backport 2.x, v2.12.0

#1348 [Backport 2.x] Properly designate model state for actively training models when nodes crash or leave cluster
  CHANGELOG.md
  qa/restart-upgrade/src/test/java/org/opensearch/knn/bwc/ModelIT.java
  src/main/java/org/opensearch/knn/common/KNNConstants.java
  src/main/java/org/opensearch/knn/index/IndexUtil.java
  src/main/java/org/opensearch/knn/indices/ModelDao.java
  src/main/java/org/opensearch/knn/indices/ModelMetadata.java
  src/main/java/org/opensearch/knn/plugin/KNNPlugin.java
  src/main/java/org/opensearch/knn/plugin/transport/TrainingModelTransportAction.java
  src/main/java/org/opensearch/knn/training/TrainingJob.java
  src/main/java/org/opensearch/knn/training/TrainingJobClusterStateListener.java
  src/main/java/org/opensearch/knn/training/TrainingJobRunner.java
  src/test/java/org/opensearch/knn/index/KNNCreateIndexFromModelTests.java
  src/test/java/org/opensearch/knn/index/codec/KNN80Codec/KNN80DocValuesConsumerTests.java
  src/test/java/org/opensearch/knn/index/codec/KNNCodecTestCase.java
  src/test/java/org/opensearch/knn/index/mapper/KNNVectorFieldMapperTests.java
  src/test/java/org/opensearch/knn/indices/ModelCacheTests.java
  src/test/java/org/opensearch/knn/indices/ModelDaoTests.java
  src/test/java/org/opensearch/knn/indices/ModelMetadataTests.java
  src/test/java/org/opensearch/knn/indices/ModelStateTests.java
  src/test/java/org/opensearch/knn/indices/ModelTests.java
  src/test/java/org/opensearch/knn/plugin/action/RestSearchModelHandlerIT.java
  src/test/java/org/opensearch/knn/plugin/transport/GetModelResponseTests.java
  src/test/java/org/opensearch/knn/plugin/transport/RemoveModelFromCacheTransportActionTests.java
  src/test/java/org/opensearch/knn/plugin/transport/TrainingJobRouteDecisionInfoTransportActionTests.java
  src/test/java/org/opensearch/knn/plugin/transport/TrainingModelRequestTests.java
  src/test/java/org/opensearch/knn/plugin/transport/UpdateModelMetadataRequestTests.java
  src/test/java/org/opensearch/knn/plugin/transport/UpdateModelMetadataTransportActionTests.java
  src/test/java/org/opensearch/knn/training/TrainingJobClusterStateListenerTests.java
  src/test/java/org/opensearch/knn/training/TrainingJobRunnerTests.java
  src/test/java/org/opensearch/knn/training/TrainingJobTests.java
  src/testFixtures/java/org/opensearch/knn/KNNRestTestCase.java
Labels: Bug Fixes, v2.12.0

#1346 Increase Lucene max dimension limit to 16,000
  CHANGELOG.md
  src/main/java/org/opensearch/knn/index/codec/BasePerFieldKnnVectorsFormat.java
  src/main/java/org/opensearch/knn/index/codec/KNN950Codec/KNN950PerFieldKnnVectorsFormat.java
  src/main/java/org/opensearch/knn/index/mapper/LuceneFieldMapper.java
  src/main/java/org/opensearch/knn/index/util/KNNEngine.java
  src/test/java/org/opensearch/knn/index/codec/KNNCodecTestCase.java
  src/test/java/org/opensearch/knn/index/mapper/KNNVectorFieldMapperTests.java
Labels: Enhancements, backport 2.x, v2.12.0

#1353 Tune default values for ef_search and ef_construction for better indexing and search performance
  CHANGELOG.md
  qa/restart-upgrade/src/test/java/org/opensearch/knn/bwc/IndexingIT.java
  qa/rolling-upgrade/src/test/java/org/opensearch/knn/bwc/IndexingIT.java
  src/main/java/org/opensearch/knn/index/KNNMethod.java
  src/main/java/org/opensearch/knn/index/KNNMethodContext.java
  src/main/java/org/opensearch/knn/index/KNNSettings.java
  src/main/java/org/opensearch/knn/index/MethodComponent.java
  src/main/java/org/opensearch/knn/index/MethodComponentContext.java
  src/main/java/org/opensearch/knn/index/codec/BasePerFieldKnnVectorsFormat.java
  src/main/java/org/opensearch/knn/index/mapper/KNNVectorFieldMapper.java
  src/main/java/org/opensearch/knn/index/mapper/LegacyFieldMapper.java
  src/main/java/org/opensearch/knn/index/mapper/LuceneFieldMapper.java
  src/main/java/org/opensearch/knn/index/mapper/MethodFieldMapper.java
  src/main/java/org/opensearch/knn/index/mapper/ModelFieldMapper.java
  src/main/java/org/opensearch/knn/index/util/AbstractKNNLibrary.java
  src/main/java/org/opensearch/knn/index/util/IndexHyperParametersUtil.java
  src/main/java/org/opensearch/knn/index/util/NativeLibrary.java
  src/main/java/org/opensearch/knn/training/TrainingJob.java
  src/test/java/org/opensearch/knn/KNNTestCase.java
  src/test/java/org/opensearch/knn/index/FaissIT.java
  src/test/java/org/opensearch/knn/index/IndexUtilTests.java
  src/test/java/org/opensearch/knn/index/KNNMethodContextTests.java
  src/test/java/org/opensearch/knn/index/KNNSettingsTests.java
  src/test/java/org/opensearch/knn/index/codec/KNN80Codec/KNN80DocValuesConsumerTests.java
  src/test/java/org/opensearch/knn/index/mapper/KNNVectorFieldMapperTests.java
  src/test/java/org/opensearch/knn/index/util/FaissTests.java
  src/test/java/org/opensearch/knn/index/util/IndexHyperParametersUtilTests.java
  src/test/java/org/opensearch/knn/jni/JNIServiceTests.java
  src/test/java/org/opensearch/knn/training/TrainingJobTests.java
  src/testFixtures/java/org/opensearch/knn/KNNRestTestCase.java
Labels: Enhancements, backport 2.x

#1362 [Backport 2.x] Tuned default values for ef_search and ef_construction for better indexing and search performance (#1353)
  CHANGELOG.md
  qa/restart-upgrade/src/test/java/org/opensearch/knn/bwc/IndexingIT.java
  qa/rolling-upgrade/src/test/java/org/opensearch/knn/bwc/IndexingIT.java
  src/main/java/org/opensearch/knn/index/KNNMethod.java
  src/main/java/org/opensearch/knn/index/KNNMethodContext.java
  src/main/java/org/opensearch/knn/index/KNNSettings.java
  src/main/java/org/opensearch/knn/index/MethodComponent.java
  src/main/java/org/opensearch/knn/index/MethodComponentContext.java
  src/main/java/org/opensearch/knn/index/codec/BasePerFieldKnnVectorsFormat.java
  src/main/java/org/opensearch/knn/index/mapper/KNNVectorFieldMapper.java
  src/main/java/org/opensearch/knn/index/mapper/LegacyFieldMapper.java
  src/main/java/org/opensearch/knn/index/mapper/LuceneFieldMapper.java
  src/main/java/org/opensearch/knn/index/mapper/MethodFieldMapper.java
  src/main/java/org/opensearch/knn/index/mapper/ModelFieldMapper.java
  src/main/java/org/opensearch/knn/index/util/AbstractKNNLibrary.java
  src/main/java/org/opensearch/knn/index/util/IndexHyperParametersUtil.java
  src/main/java/org/opensearch/knn/index/util/NativeLibrary.java
  src/main/java/org/opensearch/knn/training/TrainingJob.java
  src/test/java/org/opensearch/knn/KNNTestCase.java
  src/test/java/org/opensearch/knn/index/FaissIT.java
  src/test/java/org/opensearch/knn/index/IndexUtilTests.java
  src/test/java/org/opensearch/knn/index/KNNMethodContextTests.java
  src/test/java/org/opensearch/knn/index/KNNSettingsTests.java
  src/test/java/org/opensearch/knn/index/codec/KNN80Codec/KNN80DocValuesConsumerTests.java
  src/test/java/org/opensearch/knn/index/mapper/KNNVectorFieldMapperTests.java
  src/test/java/org/opensearch/knn/index/util/FaissTests.java
  src/test/java/org/opensearch/knn/index/util/IndexHyperParametersUtilTests.java
  src/test/java/org/opensearch/knn/jni/JNIServiceTests.java
  src/test/java/org/opensearch/knn/training/TrainingJobTests.java
  src/testFixtures/java/org/opensearch/knn/KNNRestTestCase.java
Labels: Enhancements, v2.12.0

#1358 Add patch to support multi vector in faiss
  .github/workflows/CI.yml
  DEVELOPER_GUIDE.md
  jni/CMakeLists.txt
  jni/patches/faiss/0001-Custom-patch-to-support-multi-vector.patch
Labels: skip-changelog, v2.12.0

#1363 Initialize id_map as null
  jni/patches/faiss/0001-Custom-patch-to-support-multi-vector.patch
Labels: skip-changelog
