Repository opensearch-project/k-NN, pull requests merged in 2023-10, with the labels that each got.

#1177 Removed unnecessary call to find live docs during filtered search
  src/main/java/org/opensearch/knn/index/query/KNNWeight.java
  src/test/java/org/opensearch/knn/index/query/KNNWeightTests.java
Labels: backport 2.x, skip-changelog, v2.11.0

#1141 Add graph creation stats to the KNNStats API
  CHANGELOG.md
  src/main/java/org/opensearch/knn/index/codec/KNN80Codec/KNN80DocValuesConsumer.java
  src/main/java/org/opensearch/knn/index/codec/util/KNNCodecUtil.java
  src/main/java/org/opensearch/knn/index/codec/util/KNNVectorSerializerFactory.java
  src/main/java/org/opensearch/knn/plugin/stats/KNNGraphValue.java
  src/main/java/org/opensearch/knn/plugin/stats/KNNStats.java
  src/main/java/org/opensearch/knn/plugin/stats/StatNames.java
  src/test/java/org/opensearch/knn/index/codec/KNN80Codec/KNN80DocValuesConsumerTests.java
  src/testFixtures/java/org/opensearch/knn/TestUtils.java
Labels: backport 2.x

#1197 Add 2.11 release note
  CHANGELOG.md
  release-notes/opensearch-knn.release-notes-2.11.0.0.md
Labels: backport 2.x, backport 2.11

#1204 Switch from rockylinux8 to centos7 docker image for legacy support before deprecation
  .github/workflows/CI.yml
Labels: Infrastructure, enhancement, backport 2.x, skip-changelog

#1182 Add parent join support for lucene knn
  CHANGELOG.md
  src/main/java/org/opensearch/knn/common/KNNConstants.java
  src/main/java/org/opensearch/knn/index/query/KNNQueryFactory.java
  src/test/java/org/opensearch/knn/index/NestedSearchIT.java
  src/test/java/org/opensearch/knn/index/query/KNNQueryFactoryTests.java
Labels: backport 2.x, v2.12.0

#1235 Fixing the BWC test which is failing due to 2.10.0-snapshot present in the bwc versions
  .github/workflows/backwards_compatibility_tests_workflow.yml
Labels: ci, skip-changelog

#1245 Update bwc test from 2.10 to 2.11
  .github/workflows/backwards_compatibility_tests_workflow.yml
Labels: skip-changelog

#1243 Improvement in release perf test
  benchmarks/perf-tool/release-configs/faiss-hnsw/filtering/relaxed-filter/relaxed-filter-test.yml
  benchmarks/perf-tool/release-configs/faiss-hnsw/filtering/restrictive-filter/restrictive-filter-test.yml
  benchmarks/perf-tool/release-configs/faiss-hnsw/test.yml
  benchmarks/perf-tool/release-configs/faiss-hnswpq/test.yml
  benchmarks/perf-tool/release-configs/faiss-ivf/filtering/relaxed-filter/relaxed-filter-test.yml
  benchmarks/perf-tool/release-configs/faiss-ivf/filtering/restrictive-filter/restrictive-filter-test.yml
  benchmarks/perf-tool/release-configs/faiss-ivf/test.yml
  benchmarks/perf-tool/release-configs/faiss-ivfpq/test.yml
  benchmarks/perf-tool/release-configs/lucene-hnsw/filtering/relaxed-filter/relaxed-filter-test.yml
  benchmarks/perf-tool/release-configs/lucene-hnsw/filtering/restrictive-filter/restrictive-filter-test.yml
  benchmarks/perf-tool/release-configs/lucene-hnsw/test.yml
  benchmarks/perf-tool/release-configs/nmslib-hnsw/test.yml
  benchmarks/perf-tool/release-configs/run_all_tests.sh
Labels: skip-changelog

#1249 Tweak docker retrival method to be simpler
  .github/workflows/CI.yml
Labels: Infrastructure, enhancement, backport 2.x, skip-changelog

#1252 Make sure not hardcoding user name when switching to uid 1000 on CI.yml
  .github/workflows/CI.yml
Labels: Infrastructure, enhancement, backport 2.x, skip-changelog

#1262 Remove print lines
  src/main/java/org/opensearch/knn/index/query/KNNQueryBuilder.java
Labels: skip-changelog

#1264 Reduce number of test run from 10 to 3
  benchmarks/perf-tool/release-configs/faiss-hnsw/filtering/relaxed-filter/relaxed-filter-test.yml
  benchmarks/perf-tool/release-configs/faiss-hnsw/filtering/restrictive-filter/restrictive-filter-test.yml
  benchmarks/perf-tool/release-configs/faiss-hnsw/test.yml
  benchmarks/perf-tool/release-configs/faiss-hnswpq/test.yml
  benchmarks/perf-tool/release-configs/faiss-ivf/filtering/relaxed-filter/relaxed-filter-test.yml
  benchmarks/perf-tool/release-configs/faiss-ivf/filtering/restrictive-filter/restrictive-filter-test.yml
  benchmarks/perf-tool/release-configs/faiss-ivf/test.yml
  benchmarks/perf-tool/release-configs/faiss-ivfpq/test.yml
  benchmarks/perf-tool/release-configs/lucene-hnsw/filtering/relaxed-filter/relaxed-filter-test.yml
  benchmarks/perf-tool/release-configs/lucene-hnsw/filtering/restrictive-filter/restrictive-filter-test.yml
  benchmarks/perf-tool/release-configs/lucene-hnsw/test.yml
  benchmarks/perf-tool/release-configs/nmslib-hnsw/test.yml
Labels: skip-changelog

#1275 Update default test run from 10 to 3
  benchmarks/perf-tool/release-configs/run_all_tests.sh
Labels: skip-changelog

#1283 Add ryanbogan as maintainer and codeowner
  .github/CODEOWNERS
  MAINTAINERS.md
Labels: skip-changelog

#1281 Fix Failing Windows CI
  .github/workflows/CI.yml
  jni/include/jni_util.h
  src/test/java/org/opensearch/knn/index/FaissIT.java
Labels: Infrastructure, backport 2.x, skip-changelog
