Repository opensearch-project/k-NN, pull requests merged in 2023-04, with the labels that each got.

#833 Fix the BWC Version Bump Issues
  build.gradle
Labels: Infrastructure, backport main, skip-changelog

#839 Bump byte-buddy version to 1.14.3
  CHANGELOG.md
  build.gradle
Labels: Maintenance

#827 Support .opensearch-knn-model index as system index with security enabled
  CHANGELOG.md
  build.gradle
  qa/restart-upgrade/src/test/java/org/opensearch/knn/bwc/ModelIT.java
  src/main/java/org/opensearch/knn/indices/ModelDao.java
  src/test/java/org/opensearch/knn/plugin/action/RestDeleteModelHandlerIT.java
  src/test/java/org/opensearch/knn/plugin/action/RestGetModelHandlerIT.java
  src/test/java/org/opensearch/knn/plugin/action/RestKNNStatsHandlerIT.java
  src/test/java/org/opensearch/knn/plugin/action/RestLegacyKNNStatsHandlerIT.java
  src/test/java/org/opensearch/knn/plugin/action/RestSearchModelHandlerIT.java
  src/test/resources/security/sample.pem
  src/test/resources/security/test-kirk.jks
  src/testFixtures/java/org/opensearch/knn/KNNRestTestCase.java
  src/testFixtures/java/org/opensearch/knn/ODFERestTestCase.java
  src/testFixtures/java/org/opensearch/knn/TestUtils.java
Labels: Infrastructure, backport 2.x, v2.7.0, backport 2.7

#844 Set gradle dependency scope for common-utils to testFixturesImplementation
  CHANGELOG.md
  build.gradle
Labels: Infrastructure, backport 2.x, backport 2.7

#847 Add support of .opensearch-knn-model as system index to transport actions
  CHANGELOG.md
  src/main/java/org/opensearch/knn/common/ThreadContextHelper.java
  src/main/java/org/opensearch/knn/indices/ModelDao.java
  src/main/java/org/opensearch/knn/plugin/transport/DeleteModelTransportAction.java
  src/main/java/org/opensearch/knn/plugin/transport/GetModelTransportAction.java
  src/main/java/org/opensearch/knn/plugin/transport/SearchModelTransportAction.java
  src/main/java/org/opensearch/knn/plugin/transport/TrainingJobRouterTransportAction.java
  src/main/java/org/opensearch/knn/plugin/transport/TrainingModelTransportAction.java
  src/test/java/org/opensearch/knn/common/ThreadContextHelperTests.java
Labels: Infrastructure, backport 2.x, backport 2.7

#850 Add client setting to ignore warning exceptions
  CHANGELOG.md
  src/test/java/org/opensearch/knn/index/NmslibIT.java
Labels: Infrastructure, backport 2.x, backport 2.7

#836 Add github action for secure integ tests
  .github/workflows/test_security.yml
  CHANGELOG.md
Labels: Infrastructure, backport 2.x, backport 2.7

#834 Throw errors on model deletion failures
  CHANGELOG.md
  qa/restart-upgrade/src/test/java/org/opensearch/knn/bwc/ModelIT.java
  src/main/java/org/opensearch/knn/common/exception/DeleteModelWhenInTrainStateException.java
  src/main/java/org/opensearch/knn/indices/ModelDao.java
  src/main/java/org/opensearch/knn/plugin/transport/DeleteModelResponse.java
  src/main/java/org/opensearch/knn/plugin/transport/DeleteModelTransportAction.java
  src/test/java/org/opensearch/knn/indices/ModelDaoTests.java
  src/test/java/org/opensearch/knn/plugin/action/RestDeleteModelHandlerIT.java
  src/test/java/org/opensearch/knn/plugin/action/RestSearchModelHandlerIT.java
  src/test/java/org/opensearch/knn/plugin/transport/DeleteModelResponseTests.java
Labels: Bug Fixes, backport 2.x

#857 Add 2.7.0 Release Notes
  CHANGELOG.md
  release-notes/opensearch-knn.release-notes-2.7.0.0.md
Labels: backport 2.x, v2.7.0, skip-changelog, backport 2.7

#876 Fix the filter_spec file name in restrictive-filter-test
  benchmarks/perf-tool/release-configs/lucene-hnsw/filtering/restrictive-filter/restrictive-filter-test.yml
Labels: Bug Fixes, backport 2.x, skip-changelog

#773 Bulk allocate objects for nmslib index creation
  CHANGELOG.md
  jni/CMakeLists.txt
  jni/src/nmslib_wrapper.cpp
Labels: Enhancements, backport 2.x
