Repository opensearch-project/k-NN, pull requests merged in 2023-07, with the labels that each got.

#951 Fixing unit test for Faiss due to faiss upgrade.
  DEVELOPER_GUIDE.md
  jni/tests/faiss_wrapper_test.cpp
  jni/tests/test_util.cpp
  jni/tests/test_util.h
Labels: skip-changelog, v2.9.0, test-failure

#937 Add Indexing Support for Lucene Byte Sized Vector
  CHANGELOG.md
  src/main/java/org/opensearch/knn/common/KNNConstants.java
  src/main/java/org/opensearch/knn/index/VectorDataType.java
  src/main/java/org/opensearch/knn/index/VectorField.java
  src/main/java/org/opensearch/knn/index/mapper/KNNVectorFieldMapper.java
  src/main/java/org/opensearch/knn/index/mapper/KNNVectorFieldMapperUtil.java
  src/main/java/org/opensearch/knn/index/mapper/LuceneFieldMapper.java
  src/test/java/org/opensearch/knn/index/VectorDataTypeIT.java
  src/test/java/org/opensearch/knn/index/mapper/KNNVectorFieldMapperTests.java
Labels: Features, v2.9.0

#955 Move ImmutableOpenMap usage to j.u.Map
  src/main/java/org/opensearch/knn/common/exception/DeleteModelWhenInTrainStateException.java
  src/main/java/org/opensearch/knn/index/query/KNNQueryBuilder.java
  src/main/java/org/opensearch/knn/plugin/rest/RestDeleteModelHandler.java
  src/main/java/org/opensearch/knn/plugin/rest/RestGetModelHandler.java
  src/main/java/org/opensearch/knn/plugin/rest/RestKNNStatsHandler.java
  src/main/java/org/opensearch/knn/plugin/rest/RestKNNWarmupHandler.java
  src/main/java/org/opensearch/knn/plugin/transport/DeleteModelRequest.java
  src/main/java/org/opensearch/knn/plugin/transport/TrainingJobRouterTransportAction.java
  src/main/java/org/opensearch/knn/training/TrainingJob.java
  src/test/java/org/opensearch/knn/plugin/transport/TrainingJobRouterTransportActionTests.java
  src/test/java/org/opensearch/knn/plugin/transport/TrainingModelRequestTests.java
  src/testFixtures/java/org/opensearch/knn/KNNRestTestCase.java
Labels: skip-changelog

#962 Add index settings to super constructor call for knn codec service
  src/main/java/org/opensearch/knn/index/codec/KNNCodecService.java
Labels: backport 2.x, skip-changelog, v2.9.0

#961 Add 2.9.0 release notes
  CHANGELOG.md
  release-notes/opensearch-knn.release-notes-2.9.0.0.md
Labels: backport 2.x, v2.9.0

#956 Add Querying Support to Lucene Byte Sized Vector
  CHANGELOG.md
  src/main/java/org/opensearch/knn/index/query/KNNQueryBuilder.java
  src/main/java/org/opensearch/knn/index/query/KNNQueryFactory.java
  src/test/java/org/opensearch/knn/index/LuceneEngineIT.java
  src/test/java/org/opensearch/knn/index/VectorDataTypeIT.java
  src/test/java/org/opensearch/knn/index/codec/KNNCodecTestCase.java
  src/test/java/org/opensearch/knn/index/query/KNNQueryBuilderTests.java
  src/test/java/org/opensearch/knn/index/query/KNNQueryFactoryTests.java
Labels: Features, v2.9.0

#965 Setting the OMP thread to 1 while doing the query in Faiss to reduce thread creation overhead.
  jni/src/faiss_wrapper.cpp
Labels: backport 2.x, skip-changelog, backport 2.9

#953 Add DocValues Support for Lucene Byte Sized Vector
  CHANGELOG.md
  src/main/java/org/opensearch/knn/index/KNNVectorDVLeafFieldData.java
  src/main/java/org/opensearch/knn/index/KNNVectorIndexFieldData.java
  src/main/java/org/opensearch/knn/index/KNNVectorScriptDocValues.java
  src/main/java/org/opensearch/knn/index/VectorDataType.java
  src/main/java/org/opensearch/knn/index/codec/KNNCodecService.java
  src/main/java/org/opensearch/knn/index/mapper/KNNVectorFieldMapper.java
  src/main/java/org/opensearch/knn/index/mapper/KNNVectorFieldMapperUtil.java
  src/main/java/org/opensearch/knn/index/mapper/LuceneFieldMapper.java
  src/main/java/org/opensearch/knn/plugin/script/KNNScoringSpace.java
  src/main/java/org/opensearch/knn/plugin/script/KNNScoringSpaceUtil.java
  src/main/java/org/opensearch/knn/plugin/script/KNNScoringUtil.java
  src/test/java/org/opensearch/knn/index/KNNVectorDVLeafFieldDataTests.java
  src/test/java/org/opensearch/knn/index/KNNVectorIndexFieldDataTests.java
  src/test/java/org/opensearch/knn/index/KNNVectorScriptDocValuesTests.java
  src/test/java/org/opensearch/knn/index/VectorDataTypeIT.java
  src/test/java/org/opensearch/knn/index/VectorDataTypeTests.java
  src/test/java/org/opensearch/knn/plugin/script/KNNScoringSpaceUtilTests.java
  src/test/java/org/opensearch/knn/plugin/script/KNNScoringUtilTests.java
Labels: Features, v2.9.0

#971 Add Support for Lucene Byte Sized Vector
  release-notes/opensearch-knn.release-notes-2.9.0.0.md
  src/main/java/org/opensearch/knn/common/KNNConstants.java
  src/main/java/org/opensearch/knn/index/KNNVectorDVLeafFieldData.java
  src/main/java/org/opensearch/knn/index/KNNVectorIndexFieldData.java
  src/main/java/org/opensearch/knn/index/KNNVectorScriptDocValues.java
  src/main/java/org/opensearch/knn/index/VectorDataType.java
  src/main/java/org/opensearch/knn/index/VectorField.java
  src/main/java/org/opensearch/knn/index/mapper/KNNVectorFieldMapper.java
  src/main/java/org/opensearch/knn/index/mapper/KNNVectorFieldMapperUtil.java
  src/main/java/org/opensearch/knn/index/mapper/LuceneFieldMapper.java
  src/main/java/org/opensearch/knn/index/query/KNNQueryBuilder.java
  src/main/java/org/opensearch/knn/index/query/KNNQueryFactory.java
  src/main/java/org/opensearch/knn/plugin/script/KNNScoringSpace.java
  src/main/java/org/opensearch/knn/plugin/script/KNNScoringSpaceUtil.java
  src/main/java/org/opensearch/knn/plugin/script/KNNScoringUtil.java
  src/test/java/org/opensearch/knn/index/KNNVectorDVLeafFieldDataTests.java
  src/test/java/org/opensearch/knn/index/KNNVectorIndexFieldDataTests.java
  src/test/java/org/opensearch/knn/index/KNNVectorScriptDocValuesTests.java
  src/test/java/org/opensearch/knn/index/LuceneEngineIT.java
  src/test/java/org/opensearch/knn/index/VectorDataTypeIT.java
  src/test/java/org/opensearch/knn/index/VectorDataTypeTests.java
  src/test/java/org/opensearch/knn/index/codec/KNNCodecTestCase.java
  src/test/java/org/opensearch/knn/index/mapper/KNNVectorFieldMapperTests.java
  src/test/java/org/opensearch/knn/index/query/KNNQueryBuilderTests.java
  src/test/java/org/opensearch/knn/index/query/KNNQueryFactoryTests.java
  src/test/java/org/opensearch/knn/plugin/script/KNNScoringSpaceUtilTests.java
  src/test/java/org/opensearch/knn/plugin/script/KNNScoringUtilTests.java
Labels: Features, backport 2.x, skip-changelog, v2.9.0, backport 2.9

#974 [Backport 2.9] Add Support for Lucene Byte Sized Vector (#971)
  release-notes/opensearch-knn.release-notes-2.9.0.0.md
  src/main/java/org/opensearch/knn/common/KNNConstants.java
  src/main/java/org/opensearch/knn/index/KNNVectorDVLeafFieldData.java
  src/main/java/org/opensearch/knn/index/KNNVectorIndexFieldData.java
  src/main/java/org/opensearch/knn/index/KNNVectorScriptDocValues.java
  src/main/java/org/opensearch/knn/index/VectorDataType.java
  src/main/java/org/opensearch/knn/index/VectorField.java
  src/main/java/org/opensearch/knn/index/mapper/KNNVectorFieldMapper.java
  src/main/java/org/opensearch/knn/index/mapper/KNNVectorFieldMapperUtil.java
  src/main/java/org/opensearch/knn/index/mapper/LuceneFieldMapper.java
  src/main/java/org/opensearch/knn/index/query/KNNQueryBuilder.java
  src/main/java/org/opensearch/knn/index/query/KNNQueryFactory.java
  src/main/java/org/opensearch/knn/plugin/script/KNNScoringSpace.java
  src/main/java/org/opensearch/knn/plugin/script/KNNScoringSpaceUtil.java
  src/main/java/org/opensearch/knn/plugin/script/KNNScoringUtil.java
  src/test/java/org/opensearch/knn/index/KNNVectorDVLeafFieldDataTests.java
  src/test/java/org/opensearch/knn/index/KNNVectorIndexFieldDataTests.java
  src/test/java/org/opensearch/knn/index/KNNVectorScriptDocValuesTests.java
  src/test/java/org/opensearch/knn/index/LuceneEngineIT.java
  src/test/java/org/opensearch/knn/index/VectorDataTypeIT.java
  src/test/java/org/opensearch/knn/index/VectorDataTypeTests.java
  src/test/java/org/opensearch/knn/index/codec/KNNCodecTestCase.java
  src/test/java/org/opensearch/knn/index/mapper/KNNVectorFieldMapperTests.java
  src/test/java/org/opensearch/knn/index/query/KNNQueryBuilderTests.java
  src/test/java/org/opensearch/knn/index/query/KNNQueryFactoryTests.java
  src/test/java/org/opensearch/knn/plugin/script/KNNScoringSpaceUtilTests.java
  src/test/java/org/opensearch/knn/plugin/script/KNNScoringUtilTests.java
Labels: skip-changelog

#973 [Backport 2.x] Add Support for Lucene Byte Sized Vector (#971)
  release-notes/opensearch-knn.release-notes-2.9.0.0.md
  src/main/java/org/opensearch/knn/common/KNNConstants.java
  src/main/java/org/opensearch/knn/index/KNNVectorDVLeafFieldData.java
  src/main/java/org/opensearch/knn/index/KNNVectorIndexFieldData.java
  src/main/java/org/opensearch/knn/index/KNNVectorScriptDocValues.java
  src/main/java/org/opensearch/knn/index/VectorDataType.java
  src/main/java/org/opensearch/knn/index/VectorField.java
  src/main/java/org/opensearch/knn/index/mapper/KNNVectorFieldMapper.java
  src/main/java/org/opensearch/knn/index/mapper/KNNVectorFieldMapperUtil.java
  src/main/java/org/opensearch/knn/index/mapper/LuceneFieldMapper.java
  src/main/java/org/opensearch/knn/index/query/KNNQueryBuilder.java
  src/main/java/org/opensearch/knn/index/query/KNNQueryFactory.java
  src/main/java/org/opensearch/knn/plugin/script/KNNScoringSpace.java
  src/main/java/org/opensearch/knn/plugin/script/KNNScoringSpaceUtil.java
  src/main/java/org/opensearch/knn/plugin/script/KNNScoringUtil.java
  src/test/java/org/opensearch/knn/index/KNNVectorDVLeafFieldDataTests.java
  src/test/java/org/opensearch/knn/index/KNNVectorIndexFieldDataTests.java
  src/test/java/org/opensearch/knn/index/KNNVectorScriptDocValuesTests.java
  src/test/java/org/opensearch/knn/index/LuceneEngineIT.java
  src/test/java/org/opensearch/knn/index/VectorDataTypeIT.java
  src/test/java/org/opensearch/knn/index/VectorDataTypeTests.java
  src/test/java/org/opensearch/knn/index/codec/KNNCodecTestCase.java
  src/test/java/org/opensearch/knn/index/mapper/KNNVectorFieldMapperTests.java
  src/test/java/org/opensearch/knn/index/query/KNNQueryBuilderTests.java
  src/test/java/org/opensearch/knn/index/query/KNNQueryFactoryTests.java
  src/test/java/org/opensearch/knn/plugin/script/KNNScoringSpaceUtilTests.java
  src/test/java/org/opensearch/knn/plugin/script/KNNScoringUtilTests.java
Labels: skip-changelog

#976 Fixing the opensearch-build issue happening due to lower version of gcc.
  jni/src/faiss_wrapper.cpp
Labels: backport 2.x, skip-changelog, backport 2.9

#984 Add gcc version verification before building k-NN
  scripts/build.sh
Labels: enhancement, release, backport 2.x, skip-changelog, v2.9.0, backport 2.9

#987 Add gcc version ceiling verification before building k-NN on arm64
  scripts/build.sh
Labels: Enhancements, enhancement, release, ci, skip-changelog, v2.9.0, backport 2.9

#991 Only check the gcc version ceiling when it is on linux
  scripts/build.sh
Labels: bug, windows, release, backport 2.x, skip-changelog, v2.9.0, backport 2.9

#1000 Fixing the filter-spec files and .yml file with latest dataset.
  benchmarks/perf-tool/release-configs/faiss-hnsw/filtering/relaxed-filter/relaxed-filter-spec.json
  benchmarks/perf-tool/release-configs/faiss-hnsw/filtering/relaxed-filter/relaxed-filter-test.yml
  benchmarks/perf-tool/release-configs/lucene-hnsw/filtering/relaxed-filter/relaxed-filter-test.yml
  benchmarks/perf-tool/sample-configs/filter-spec/filter-4-spec.json
  benchmarks/perf-tool/sample-configs/filter-spec/filter-5-spec.json
Labels: backport 2.x, skip-changelog

#1002 Update bwc version after 2.9 release
  .github/workflows/backwards_compatibility_tests_workflow.yml
  qa/restart-upgrade/src/test/java/org/opensearch/knn/bwc/ModelIT.java
  src/main/java/org/opensearch/knn/index/codec/KNN80Codec/KNN80DocValuesConsumer.java
  src/test/java/org/opensearch/knn/plugin/action/RestDeleteModelHandlerIT.java
  src/test/java/org/opensearch/knn/plugin/action/RestGetModelHandlerIT.java
  src/test/java/org/opensearch/knn/plugin/action/RestKNNStatsHandlerIT.java
  src/test/java/org/opensearch/knn/plugin/action/RestSearchModelHandlerIT.java
  src/test/java/org/opensearch/knn/plugin/action/RestTrainModelHandlerIT.java
  src/test/java/org/opensearch/knn/plugin/script/KNNScriptScoringIT.java
  src/test/java/org/opensearch/knn/plugin/transport/DeleteModelResponseTests.java
  src/test/java/org/opensearch/knn/plugin/transport/GetModelResponseTests.java
  src/testFixtures/java/org/opensearch/knn/KNNRestTestCase.java
  src/testFixtures/java/org/opensearch/knn/ODFERestTestCase.java
  src/testFixtures/java/org/opensearch/knn/TestUtils.java
Labels: Maintenance, skip-changelog

#1010 Bump version certifi and aiohttp to fix vulnerabilities in benchmark tools
  benchmarks/osb/requirements.txt
  benchmarks/perf-tool/requirements.txt
Labels: Maintenance, backport 2.x, skip-changelog

#1013 Enabled the IVF algorithm to work with Filters of K-NN Query.
  CHANGELOG.md
  src/main/java/org/opensearch/knn/index/query/KNNWeight.java
  src/test/java/org/opensearch/knn/index/FaissIT.java
  src/testFixtures/java/org/opensearch/knn/KNNRestTestCase.java
Labels: Enhancements, enhancement, v2.10.0
