Repository opensearch-project/k-NN, pull requests merged in 2023-09, with the labels that each got.

#1089 Add HNSW PQ configuration to perf tests
  benchmarks/perf-tool/release-configs/faiss-hnswpq/index.json
  benchmarks/perf-tool/release-configs/faiss-hnswpq/method-spec.json
  benchmarks/perf-tool/release-configs/faiss-hnswpq/test.yml
  benchmarks/perf-tool/release-configs/faiss-hnswpq/train-index-spec.json
Labels: backport 2.x, skip-changelog, backport 2.10

#1094 Created release notes for 2.10 release
  CHANGELOG.md
  release-notes/opensearch-knn.release-notes-2.10.0.0.md
Labels: backport 2.x, skip-changelog, v2.11.0, backport 2.10

#1099 Adding get-ci-image-tag dynamic retrival on CI workflows
  .github/workflows/CI.yml
Labels: Enhancements, backport 1.3, ci, backport 2.x, skip-changelog

#1105 Downgrading the version of request lib to fix the CVE-2015-2296
  benchmarks/perf-tool/okpt/test/steps/steps.py
  benchmarks/perf-tool/requirements.in
  benchmarks/perf-tool/requirements.txt
Labels: security fix, backport 2.x, skip-changelog, v2.10.0, backport 2.10

#1110 Revert "Downgrading the version of request lib to fix the CVE-2015-2296 (#1105)
  benchmarks/perf-tool/okpt/test/steps/steps.py
  benchmarks/perf-tool/requirements.in
  benchmarks/perf-tool/requirements.txt
Labels: backport 2.x, skip-changelog, v2.10.0, backport 2.10

#1100 Updates demo certs used in integ tests
  src/test/resources/security/sample.pem
  src/test/resources/security/test-kirk.jks
Labels: backport 2.x, skip-changelog, v2.10.0, backport 2.10

#1137 Add Warmup Operation in Perf-tool Benchmarking Tests
  benchmarks/perf-tool/okpt/io/config/parsers/test.py
  benchmarks/perf-tool/okpt/io/config/schemas/test.yml
  benchmarks/perf-tool/okpt/test/steps/factory.py
  benchmarks/perf-tool/okpt/test/steps/steps.py
  benchmarks/perf-tool/release-configs/faiss-hnsw/filtering/relaxed-filter/relaxed-filter-test.yml
  benchmarks/perf-tool/release-configs/faiss-hnsw/filtering/restrictive-filter/restrictive-filter-test.yml
  benchmarks/perf-tool/release-configs/faiss-hnsw/test.yml
  benchmarks/perf-tool/release-configs/faiss-hnswpq/test.yml
  benchmarks/perf-tool/release-configs/faiss-ivf/test.yml
  benchmarks/perf-tool/release-configs/faiss-ivfpq/test.yml
  benchmarks/perf-tool/release-configs/nmslib-hnsw/test.yml
  benchmarks/perf-tool/sample-configs/faiss-sift-ivf/test.yml
  benchmarks/perf-tool/sample-configs/nmslib-sift-hnsw/test.yml
Labels: Infrastructure, skip-changelog

#1147 Change imports to align with core lucene upgrade
  src/main/java/org/opensearch/knn/index/mapper/LuceneFieldMapper.java
  src/main/java/org/opensearch/knn/index/util/KNNEngine.java
Labels: skip-changelog
