Repository opensearch-project/k-NN, pull requests merged in 2023-11, with the labels that each got.

#1289 Upgrade gradle to 8.4
  CHANGELOG.md
  build-tools/knnplugin-coverage.gradle
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  src/testFixtures/java/org/opensearch/knn/KNNRestTestCase.java
Labels: Infrastructure, backport 2.x

#1288 Update CI to use jdk-21
  .github/workflows/CI.yml
  .github/workflows/test_security.yml
  build.gradle
  src/main/java/org/opensearch/knn/indices/ModelDao.java
  src/testFixtures/java/org/opensearch/knn/TestUtils.java
Labels: Infrastructure, backport 2.x, skip-changelog

#1296 Increment version to 2.12.0-SNAPSHOT and change imports to align with core lucene upgrade
  .github/workflows/backwards_compatibility_tests_workflow.yml
  build.gradle
  src/main/java/org/opensearch/knn/index/mapper/LuceneFieldMapper.java
  src/main/java/org/opensearch/knn/index/util/KNNEngine.java
Labels: skip-changelog

#1300 Update bwc workflow to include 2.12.0-SNAPSHOT
  .github/workflows/backwards_compatibility_tests_workflow.yml
Labels: skip-changelog

#1305 Fix use-after-free bug in nmslib engine query path
  CHANGELOG.md
  jni/include/nmslib_wrapper.h
  jni/tests/nmslib_wrapper_test.cpp
Labels: Bug Fixes, backport 2.x

#1302 Add more description about running OpenSearch on MAC M1 to developer guide
  DEVELOPER_GUIDE.md
Labels: backport 2.x, skip-changelog

#1314 Add release note for 2.11.1
  release-notes/opensearch-knn.release-notes-2.11.1.0.md
Labels: backport 2.x, skip-changelog, backport 2.11

#1327 Fix 2.10 Release Notes
  release-notes/opensearch-knn.release-notes-2.10.0.0.md
Labels: skip-changelog
