Repository opensearch-project/k-NN, pull requests merged in 2023-02, with the labels that each got.

#747 Update codec version to 9.5
  DEVELOPER_GUIDE.md
  src/main/java/org/opensearch/knn/index/codec/KNN940Codec/KNN940PerFieldKnnVectorsFormat.java
  src/main/java/org/opensearch/knn/index/codec/KNN950Codec/KNN950Codec.java
  src/main/java/org/opensearch/knn/index/codec/KNN950Codec/KNN950PerFieldKnnVectorsFormat.java
  src/main/java/org/opensearch/knn/index/codec/KNNCodecVersion.java
  src/main/resources/META-INF/services/org.apache.lucene.codecs.Codec
  src/test/java/org/opensearch/knn/index/codec/KNN940Codec/KNN940CodecTests.java
  src/test/java/org/opensearch/knn/index/codec/KNN950Codec/KNN950CodecTests.java
  src/test/java/org/opensearch/knn/index/codec/KNNCodecFactoryTests.java
Labels: Infrastructure

#757 Update 2.5 bwc on 2.x branch
  .github/workflows/backwards_compatibility_tests_workflow.yml
Labels: Maintenance

#756 Update bwc 2.5 to release
  .github/workflows/backwards_compatibility_tests_workflow.yml
Labels: Maintenance

#755 Upgrade 2.5 to 2.5.1
  .github/workflows/backwards_compatibility_tests_workflow.yml
  build.gradle
Labels: Maintenance

#759 Adding test for KNNWeight
  build.gradle
  src/test/java/org/opensearch/knn/index/query/KNNWeightTests.java
  src/test/resources/mockito-extensions/org.mockito.plugins.MockMaker
Labels: Infrastructure, backport 1.x, backport 2.x, v2.6.0

#754 Set NoMergePolicy for codec tests
  src/test/java/org/opensearch/knn/index/codec/KNNCodecTestCase.java
Labels: Infrastructure, backport 2.x, backport 2.5

#767 Replace KnnQueryVector by KnnFloatVectorQuery for Lucene knn
  src/main/java/org/opensearch/knn/index/query/KNNQueryFactory.java
  src/test/java/org/opensearch/knn/index/query/KNNQueryBuilderTests.java
  src/test/java/org/opensearch/knn/index/query/KNNQueryFactoryTests.java
Labels: Maintenance, backport 2.x

#776 Add 2.6 release notes
  release-notes/opensearch-knn.release-notes-2.6.0.0.md
Labels: Documentation, backport 2.x, v2.6.0, backport 2.6

#781 Fixing the imports failures happening due to changes in OpenSearch Core.
  qa/restart-upgrade/src/test/java/org/opensearch/knn/bwc/ModelIT.java
  src/main/java/org/opensearch/knn/index/KNNMethodContext.java
  src/main/java/org/opensearch/knn/index/MethodComponentContext.java
  src/main/java/org/opensearch/knn/index/codec/KNN80Codec/KNN80DocValuesConsumer.java
  src/main/java/org/opensearch/knn/index/mapper/KNNVectorFieldMapper.java
  src/main/java/org/opensearch/knn/index/query/KNNQueryBuilder.java
  src/main/java/org/opensearch/knn/indices/Model.java
  src/main/java/org/opensearch/knn/indices/ModelGraveyard.java
  src/main/java/org/opensearch/knn/indices/ModelMetadata.java
  src/main/java/org/opensearch/knn/plugin/KNNPlugin.java
  src/main/java/org/opensearch/knn/plugin/rest/RestTrainModelHandler.java
  src/main/java/org/opensearch/knn/plugin/transport/DeleteModelResponse.java
  src/main/java/org/opensearch/knn/plugin/transport/GetModelResponse.java
  src/main/java/org/opensearch/knn/plugin/transport/KNNStatsNodeResponse.java
  src/main/java/org/opensearch/knn/plugin/transport/KNNStatsResponse.java
  src/main/java/org/opensearch/knn/plugin/transport/KNNWarmupResponse.java
  src/main/java/org/opensearch/knn/plugin/transport/TrainingJobRouteDecisionInfoNodeResponse.java
  src/main/java/org/opensearch/knn/plugin/transport/TrainingJobRouteDecisionInfoResponse.java
  src/main/java/org/opensearch/knn/plugin/transport/TrainingModelResponse.java
  src/test/java/org/opensearch/knn/KNNSingleNodeTestCase.java
  src/test/java/org/opensearch/knn/KNNTestCase.java
  src/test/java/org/opensearch/knn/index/FaissIT.java
  src/test/java/org/opensearch/knn/index/KNNMethodContextTests.java
  src/test/java/org/opensearch/knn/index/KNNMethodTests.java
  src/test/java/org/opensearch/knn/index/LuceneEngineIT.java
  src/test/java/org/opensearch/knn/index/MethodComponentContextTests.java
  src/test/java/org/opensearch/knn/index/MethodComponentTests.java
  src/test/java/org/opensearch/knn/index/NmslibIT.java
  src/test/java/org/opensearch/knn/index/OpenSearchIT.java
  src/test/java/org/opensearch/knn/index/mapper/KNNVectorFieldMapperTests.java
  src/test/java/org/opensearch/knn/index/query/KNNQueryBuilderTests.java
  src/test/java/org/opensearch/knn/index/util/AbstractKNNLibraryTests.java
  src/test/java/org/opensearch/knn/index/util/FaissTests.java
  src/test/java/org/opensearch/knn/index/util/LuceneTests.java
  src/test/java/org/opensearch/knn/indices/ModelDaoTests.java
  src/test/java/org/opensearch/knn/indices/ModelGraveyardTests.java
  src/test/java/org/opensearch/knn/plugin/action/RestDeleteModelHandlerIT.java
  src/test/java/org/opensearch/knn/plugin/action/RestKNNStatsHandlerIT.java
  src/test/java/org/opensearch/knn/plugin/action/RestSearchModelHandlerIT.java
  src/test/java/org/opensearch/knn/plugin/action/RestTrainModelHandlerIT.java
  src/test/java/org/opensearch/knn/plugin/script/KNNScriptScoringIT.java
  src/test/java/org/opensearch/knn/plugin/script/PainlessScriptIT.java
  src/test/java/org/opensearch/knn/plugin/transport/DeleteModelResponseTests.java
  src/test/java/org/opensearch/knn/plugin/transport/GetModelResponseTests.java
  src/test/java/org/opensearch/knn/plugin/transport/TrainingJobRouteDecisionInfoNodeResponseTests.java
  src/test/java/org/opensearch/knn/plugin/transport/TrainingJobRouteDecisionInfoResponseTests.java
  src/test/java/org/opensearch/knn/plugin/transport/TrainingModelResponseTests.java
  src/test/java/org/opensearch/knn/plugin/transport/TrainingModelTransportActionTests.java
  src/testFixtures/java/org/opensearch/knn/KNNRestTestCase.java
  src/testFixtures/java/org/opensearch/knn/ODFERestTestCase.java
  src/testFixtures/java/org/opensearch/knn/TestUtils.java
Labels: Refactoring, v3.0.0
