Repository opensearch-project/k-NN, pull requests merged in 2023-08, with the labels that each got.

#1014 Fixed XContent, MediaTypeRegistry, CircuitBreaker, ByteSizeValue etc breaking changes coming from core.
  qa/restart-upgrade/src/test/java/org/opensearch/knn/bwc/ModelIT.java
  src/main/java/org/opensearch/knn/index/KNNSettings.java
  src/main/java/org/opensearch/knn/index/KNNVectorIndexFieldData.java
  src/main/java/org/opensearch/knn/index/codec/KNN80Codec/KNN80DocValuesConsumer.java
  src/test/java/org/opensearch/knn/index/KNNSettingsTests.java
  src/test/java/org/opensearch/knn/index/query/KNNWeightTests.java
  src/test/java/org/opensearch/knn/plugin/action/RestDeleteModelHandlerIT.java
  src/test/java/org/opensearch/knn/plugin/action/RestGetModelHandlerIT.java
  src/test/java/org/opensearch/knn/plugin/action/RestKNNStatsHandlerIT.java
  src/test/java/org/opensearch/knn/plugin/action/RestSearchModelHandlerIT.java
  src/test/java/org/opensearch/knn/plugin/action/RestTrainModelHandlerIT.java
  src/test/java/org/opensearch/knn/plugin/script/KNNScriptScoringIT.java
  src/test/java/org/opensearch/knn/plugin/transport/DeleteModelResponseTests.java
  src/test/java/org/opensearch/knn/plugin/transport/GetModelResponseTests.java
  src/testFixtures/java/org/opensearch/knn/KNNRestTestCase.java
  src/testFixtures/java/org/opensearch/knn/ODFERestTestCase.java
  src/testFixtures/java/org/opensearch/knn/TestUtils.java
Labels: Maintenance, skip-changelog

#1016 Enabled the IVF algorithm to work with Filters of K-NN Query. (#1013)
  CHANGELOG.md
  src/main/java/org/opensearch/knn/index/query/KNNWeight.java
  src/test/java/org/opensearch/knn/index/FaissIT.java
  src/testFixtures/java/org/opensearch/knn/KNNRestTestCase.java
Labels: Features, v2.10.0

#1020 Fix TransportAddress Refactoring Changes in Core
  CHANGELOG.md
  src/test/java/org/opensearch/knn/plugin/transport/TrainingJobRouteDecisionInfoNodeResponseTests.java
  src/test/java/org/opensearch/knn/plugin/transport/TrainingJobRouteDecisionInfoResponseTests.java
Labels: Refactoring, backport 2.x

#1019 Update Guava Version to 32.0.1
  CHANGELOG.md
  build.gradle
Labels: backport 1.3, backport 2.x, backport 2.9

#1027 Remove k-NN gcc requirements ceiling and not equals 8.3.1 version
  scripts/build.sh
Labels: bug, release, backport 2.x, skip-changelog

#1029 Fixing compilation errors from mediatype refactoring changes
  src/main/java/org/opensearch/knn/index/KNNSettings.java
  src/main/java/org/opensearch/knn/index/KNNVectorIndexFieldData.java
  src/main/java/org/opensearch/knn/index/codec/KNN80Codec/KNN80DocValuesConsumer.java
  src/test/java/org/opensearch/knn/index/KNNSettingsTests.java
  src/test/java/org/opensearch/knn/index/query/KNNWeightTests.java
  src/test/java/org/opensearch/knn/plugin/transport/DeleteModelResponseTests.java
  src/test/java/org/opensearch/knn/plugin/transport/GetModelResponseTests.java
  src/test/java/org/opensearch/knn/plugin/transport/TrainingJobRouteDecisionInfoNodeResponseTests.java
  src/test/java/org/opensearch/knn/plugin/transport/TrainingJobRouteDecisionInfoResponseTests.java
  src/testFixtures/java/org/opensearch/knn/KNNRestTestCase.java
  src/testFixtures/java/org/opensearch/knn/ODFERestTestCase.java
  src/testFixtures/java/org/opensearch/knn/TestUtils.java
Labels: skip-changelog

#1031 Fixed compilation errors after recent changes in core
  qa/restart-upgrade/src/test/java/org/opensearch/knn/bwc/IndexingIT.java
  qa/restart-upgrade/src/test/java/org/opensearch/knn/bwc/ModelIT.java
  src/main/java/org/opensearch/knn/index/mapper/MethodFieldMapper.java
  src/test/java/org/opensearch/knn/index/FaissIT.java
  src/test/java/org/opensearch/knn/index/KNNCreateIndexFromModelTests.java
  src/test/java/org/opensearch/knn/index/LuceneEngineIT.java
  src/test/java/org/opensearch/knn/index/NmslibIT.java
  src/test/java/org/opensearch/knn/index/OpenSearchIT.java
  src/test/java/org/opensearch/knn/index/VectorDataTypeIT.java
  src/test/java/org/opensearch/knn/index/codec/KNN80Codec/KNN80DocValuesConsumerTests.java
  src/test/java/org/opensearch/knn/plugin/action/RestKNNStatsHandlerIT.java
  src/test/java/org/opensearch/knn/plugin/script/KNNScriptScoringIT.java
  src/test/java/org/opensearch/knn/plugin/script/PainlessScriptIT.java
  src/test/java/org/opensearch/knn/plugin/transport/DeleteModelResponseTests.java
  src/test/java/org/opensearch/knn/plugin/transport/GetModelResponseTests.java
  src/test/resources/lang-painless/lang-painless-1.3.0-SNAPSHOT.zip
  src/testFixtures/java/org/opensearch/knn/KNNRestTestCase.java
  src/testFixtures/java/org/opensearch/knn/ODFERestTestCase.java
Labels: Maintenance, backport 2.x, skip-changelog

#1038 Fixed compilation errors after refactoring in core foundation classes
  src/main/java/org/opensearch/knn/index/KNNSettings.java
  src/main/java/org/opensearch/knn/index/memory/NativeMemoryLoadStrategy.java
  src/main/java/org/opensearch/knn/indices/ModelDao.java
  src/main/java/org/opensearch/knn/plugin/KNNPlugin.java
  src/main/java/org/opensearch/knn/plugin/transport/DeleteModelResponse.java
  src/main/java/org/opensearch/knn/plugin/transport/DeleteModelTransportAction.java
  src/main/java/org/opensearch/knn/plugin/transport/GetModelResponse.java
  src/main/java/org/opensearch/knn/plugin/transport/GetModelTransportAction.java
  src/main/java/org/opensearch/knn/plugin/transport/SearchModelTransportAction.java
  src/main/java/org/opensearch/knn/plugin/transport/TrainingJobRouterTransportAction.java
  src/main/java/org/opensearch/knn/plugin/transport/TrainingModelResponse.java
  src/main/java/org/opensearch/knn/plugin/transport/TrainingModelTransportAction.java
  src/main/java/org/opensearch/knn/plugin/transport/UpdateModelGraveyardTransportAction.java
  src/main/java/org/opensearch/knn/plugin/transport/UpdateModelMetadataTransportAction.java
  src/main/java/org/opensearch/knn/training/TrainingJobRunner.java
  src/main/java/org/opensearch/knn/training/VectorReader.java
  src/test/java/org/opensearch/knn/index/KNNCreateIndexFromModelTests.java
  src/test/java/org/opensearch/knn/index/memory/NativeMemoryLoadStrategyTests.java
  src/test/java/org/opensearch/knn/indices/ModelDaoTests.java
  src/test/java/org/opensearch/knn/plugin/transport/TrainingJobRouteDecisionInfoTransportActionTests.java
  src/test/java/org/opensearch/knn/plugin/transport/TrainingJobRouterTransportActionTests.java
  src/test/java/org/opensearch/knn/plugin/transport/TrainingModelTransportActionTests.java
  src/test/java/org/opensearch/knn/plugin/transport/UpdateModelGraveyardTransportActionTests.java
  src/test/java/org/opensearch/knn/plugin/transport/UpdateModelMetadataTransportActionTests.java
  src/test/java/org/opensearch/knn/training/TrainingJobRunnerTests.java
  src/test/java/org/opensearch/knn/training/VectorReaderTests.java
Labels: Maintenance, skip-changelog

#1044 Fix OnDiskInvertedLists file path for windows patching
  scripts/windowsScript.ps1
Labels: Infrastructure, backport 2.x, skip-changelog

#1048 [Backport 2.x] Fixed compilation errors after refactoring in core foundation classes (#1038)
  src/main/java/org/opensearch/knn/index/KNNSettings.java
  src/main/java/org/opensearch/knn/index/memory/NativeMemoryLoadStrategy.java
  src/main/java/org/opensearch/knn/indices/ModelDao.java
  src/main/java/org/opensearch/knn/plugin/KNNPlugin.java
  src/main/java/org/opensearch/knn/plugin/transport/DeleteModelResponse.java
  src/main/java/org/opensearch/knn/plugin/transport/DeleteModelTransportAction.java
  src/main/java/org/opensearch/knn/plugin/transport/GetModelResponse.java
  src/main/java/org/opensearch/knn/plugin/transport/GetModelTransportAction.java
  src/main/java/org/opensearch/knn/plugin/transport/SearchModelTransportAction.java
  src/main/java/org/opensearch/knn/plugin/transport/TrainingJobRouterTransportAction.java
  src/main/java/org/opensearch/knn/plugin/transport/TrainingModelResponse.java
  src/main/java/org/opensearch/knn/plugin/transport/TrainingModelTransportAction.java
  src/main/java/org/opensearch/knn/plugin/transport/UpdateModelGraveyardTransportAction.java
  src/main/java/org/opensearch/knn/plugin/transport/UpdateModelMetadataTransportAction.java
  src/main/java/org/opensearch/knn/training/TrainingJobRunner.java
  src/main/java/org/opensearch/knn/training/VectorReader.java
  src/test/java/org/opensearch/knn/index/KNNCreateIndexFromModelTests.java
  src/test/java/org/opensearch/knn/index/KNNSettingsTests.java
  src/test/java/org/opensearch/knn/index/memory/NativeMemoryLoadStrategyTests.java
  src/test/java/org/opensearch/knn/indices/ModelDaoTests.java
  src/test/java/org/opensearch/knn/plugin/transport/TrainingJobRouteDecisionInfoTransportActionTests.java
  src/test/java/org/opensearch/knn/plugin/transport/TrainingJobRouterTransportActionTests.java
  src/test/java/org/opensearch/knn/plugin/transport/TrainingModelTransportActionTests.java
  src/test/java/org/opensearch/knn/plugin/transport/UpdateModelGraveyardTransportActionTests.java
  src/test/java/org/opensearch/knn/plugin/transport/UpdateModelMetadataTransportActionTests.java
  src/test/java/org/opensearch/knn/training/TrainingJobRunnerTests.java
  src/test/java/org/opensearch/knn/training/VectorReaderTests.java
Labels: skip-changelog

#740 [k-NN] Add Clear Cache API
  CHANGELOG.md
  qa/restart-upgrade/src/test/java/org/opensearch/knn/bwc/ClearCacheIT.java
  qa/rolling-upgrade/src/test/java/org/opensearch/knn/bwc/ClearCacheIT.java
  src/main/java/org/opensearch/knn/common/KNNConstants.java
  src/main/java/org/opensearch/knn/index/KNNIndexShard.java
  src/main/java/org/opensearch/knn/index/memory/NativeMemoryCacheManager.java
  src/main/java/org/opensearch/knn/plugin/KNNPlugin.java
  src/main/java/org/opensearch/knn/plugin/rest/RestClearCacheHandler.java
  src/main/java/org/opensearch/knn/plugin/transport/ClearCacheAction.java
  src/main/java/org/opensearch/knn/plugin/transport/ClearCacheRequest.java
  src/main/java/org/opensearch/knn/plugin/transport/ClearCacheResponse.java
  src/main/java/org/opensearch/knn/plugin/transport/ClearCacheTransportAction.java
  src/test/java/org/opensearch/knn/KNNSingleNodeTestCase.java
  src/test/java/org/opensearch/knn/index/KNNIndexShardTests.java
  src/test/java/org/opensearch/knn/plugin/action/RestClearCacheHandlerIT.java
  src/test/java/org/opensearch/knn/plugin/transport/ClearCacheTransportActionTests.java
  src/testFixtures/java/org/opensearch/knn/KNNRestTestCase.java
Labels: Features, backport 2.x

#1056 Fixing the backward incompatible changes coming from core in ScoreScript class and index.store.hybrid.mmap.extensions settings
  src/main/java/org/opensearch/knn/plugin/script/KNNScoreScript.java
  src/main/java/org/opensearch/knn/plugin/script/KNNScoreScriptFactory.java
  src/main/java/org/opensearch/knn/plugin/script/KNNScoringSpace.java
  src/test/java/org/opensearch/knn/index/KNNSettingsTests.java
Labels: skip-changelog

#1059 Improved the logic to switch to exact search for restrictive filters search.
  CHANGELOG.md
  src/main/java/org/opensearch/knn/index/KNNSettings.java
  src/main/java/org/opensearch/knn/index/query/KNNWeight.java
  src/test/java/org/opensearch/knn/index/KNNSettingsTests.java
  src/test/java/org/opensearch/knn/index/query/KNNWeightTests.java
Labels: Features, enhancement, backport 2.x

#1063 [Backport 2.x] Fixing the backward incompatible changes coming from core in ScoreScriptipt class(#1056)
  src/main/java/org/opensearch/knn/plugin/script/KNNScoreScript.java
  src/main/java/org/opensearch/knn/plugin/script/KNNScoreScriptFactory.java
  src/main/java/org/opensearch/knn/plugin/script/KNNScoringSpace.java
  src/test/java/org/opensearch/knn/index/KNNSettingsTests.java
  src/test/java/org/opensearch/knn/index/query/KNNWeightTests.java
Labels: skip-changelog, v2.10.0

#1066 Added max distance computation logic to enhance the switch to exact search in filtered Nearest Neighbor Search.
  CHANGELOG.md
  src/main/java/org/opensearch/knn/common/KNNConstants.java
  src/main/java/org/opensearch/knn/index/KNNSettings.java
  src/main/java/org/opensearch/knn/index/query/KNNWeight.java
  src/test/java/org/opensearch/knn/index/KNNSettingsTests.java
  src/test/java/org/opensearch/knn/index/query/KNNWeightTests.java
Labels: enhancement, backport 2.x, v2.10.0, backport 2.10

#1069 Fixed the github actions to use the image used by OpenSearch-build repo for building the distribution
  .github/workflows/CI.yml
Labels: Enhancements, backport 2.x, skip-changelog, backport 2.10

#1074 Update Faiss engine to allow PQ and HNSW
  CHANGELOG.md
  src/main/java/org/opensearch/knn/index/util/Faiss.java
  src/test/java/org/opensearch/knn/index/FaissIT.java
  src/test/java/org/opensearch/knn/index/KNNMethodContextTests.java
  src/test/java/org/opensearch/knn/index/util/FaissTests.java
  src/test/java/org/opensearch/knn/jni/JNIServiceTests.java
  src/testFixtures/java/org/opensearch/knn/KNNRestTestCase.java
Labels: Bug Fixes, backport 2.x, backport 2.10

#1082 Fix locale in FaissTests
  src/test/java/org/opensearch/knn/index/util/FaissTests.java
Labels: skip-changelog

#1083 Fixing the check for max distance computation happening to switch to exact search
  src/main/java/org/opensearch/knn/index/query/KNNQueryFactory.java
  src/main/java/org/opensearch/knn/index/query/KNNWeight.java
  src/test/java/org/opensearch/knn/index/query/KNNWeightTests.java
Labels: backport 2.x, skip-changelog, backport 2.10
