Repository opensearch-project/k-NN, pull requests merged in 2023-01, with the labels that each got.

#700 Add Lucene 9.5 codec and make it new default
  DEVELOPER_GUIDE.md
  src/main/java/org/opensearch/knn/index/codec/KNN950Codec/KNN950Codec.java
  src/main/java/org/opensearch/knn/index/codec/KNN950Codec/KNN950PerFieldKnnVectorsFormat.java
  src/main/java/org/opensearch/knn/index/codec/KNNCodecVersion.java
  src/main/resources/META-INF/services/org.apache.lucene.codecs.Codec
  src/test/java/org/opensearch/knn/index/codec/KNN950Codec/KNN950CodecTests.java
  src/test/java/org/opensearch/knn/index/codec/KNNCodecFactoryTests.java
Labels: Maintenance

#701 Update backwards compatibility versions
  .github/workflows/backwards_compatibility_tests_workflow.yml
Labels: Infrastructure

#703 Update backwards compatibility versions
  .github/workflows/backwards_compatibility_tests_workflow.yml
Labels: Infrastructure

#706 Update backwards compatibility versions
  .github/workflows/backwards_compatibility_tests_workflow.yml
Labels: Infrastructure

#705 Update backwards compatibility versions
  .github/workflows/backwards_compatibility_tests_workflow.yml
Labels: Infrastructure

#704 Update backwards compatibility versions
  .github/workflows/backwards_compatibility_tests_workflow.yml
Labels: Infrastructure

#707 Fixed flaky test
  src/test/java/org/opensearch/knn/index/codec/KNNCodecTestCase.java
Labels: Infrastructure, v2.5.0

#702 Update backwards compatibility versions
  .github/workflows/backwards_compatibility_tests_workflow.yml
  qa/rolling-upgrade/src/test/java/org/opensearch/knn/bwc/LuceneFilteringIT.java
Labels: Infrastructure

#710 Update tests for backwards codecs
  src/test/java/org/opensearch/knn/index/codec/KNN940Codec/KNN940CodecTests.java
  src/test/java/org/opensearch/knn/index/codec/KNN950Codec/KNN950CodecTests.java
Labels: Infrastructure, backport 2.x, v2.5.0

#709 Updated MAINTAINERS.md format.
  MAINTAINERS.md
Labels: Documentation

#691 Making version of lucene k-nn engine match lucene current version
  src/main/java/org/opensearch/knn/index/util/Lucene.java
  src/test/java/org/opensearch/knn/index/util/KNNEngineTests.java
  src/test/java/org/opensearch/knn/index/util/LuceneTests.java
Labels: Maintenance, backport 2.x, v2.5.0

#714 Add 2.5 release notes
  release-notes/opensearch-knn.release-notes-2.5.0.0.md
Labels: Documentation, backport 2.x, backport 2.5

#718 Fix typo in release notes
  release-notes/opensearch-knn.release-notes-2.5.0.0.md
Labels: Documentation, backport 2.x, backport 2.5

#721 Add Lucene specific file extensions to core HybridFS
  release-notes/opensearch-knn.release-notes-2.5.0.0.md
  src/main/java/org/opensearch/knn/index/util/KNNEngine.java
  src/main/java/org/opensearch/knn/index/util/KNNLibrary.java
  src/main/java/org/opensearch/knn/index/util/Lucene.java
  src/main/java/org/opensearch/knn/plugin/KNNPlugin.java
  src/test/java/org/opensearch/knn/index/util/KNNEngineTests.java
  src/test/java/org/opensearch/knn/index/util/LuceneTests.java
Labels: Features, backport 2.x, v2.5.0

#722 Upgrade to 2.6.0-SNAPSHOT
  .github/workflows/backwards_compatibility_tests_workflow.yml
  build.gradle
  qa/build.gradle
  qa/restart-upgrade/build.gradle
  qa/rolling-upgrade/build.gradle
Labels: Maintenance

#723 Update bwc to 2.6.0-SNAPSHOT
  .github/workflows/backwards_compatibility_tests_workflow.yml
Labels: Infrastructure

#729 Remove lucene 95 upgrade from release notes
  release-notes/opensearch-knn.release-notes-2.5.0.0.md
Labels: Documentation, backport 2.x, backport 2.5

#726 Add Windows Support to BWC Tests
  .github/workflows/backwards_compatibility_tests_workflow.yml
  qa/build.gradle
  qa/restart-upgrade/build.gradle
  qa/rolling-upgrade/build.gradle
Labels: Infrastructure, windows, backport 2.x, backport 2.4

#727 Remove latestSettings cache from KNNSettings
  src/main/java/org/opensearch/knn/index/KNNSettings.java
  src/main/java/org/opensearch/knn/index/memory/NativeMemoryCacheManager.java
  src/main/java/org/opensearch/knn/index/memory/NativeMemoryCacheManagerDto.java
  src/test/java/org/opensearch/knn/KNNTestCase.java
  src/test/java/org/opensearch/knn/index/KNNSettingsTests.java
  src/test/java/org/opensearch/knn/index/codec/KNNCodecTestCase.java
Labels: Bug Fixes, backport 2.x

#736 Refactor structure of stats module
  qa/rolling-upgrade/src/test/java/org/opensearch/knn/bwc/StatsIT.java
  src/main/java/org/opensearch/knn/index/KNNCircuitBreaker.java
  src/main/java/org/opensearch/knn/plugin/KNNPlugin.java
  src/main/java/org/opensearch/knn/plugin/rest/RestKNNStatsHandler.java
  src/main/java/org/opensearch/knn/plugin/stats/KNNStats.java
  src/main/java/org/opensearch/knn/plugin/stats/KNNStatsConfig.java
  src/main/java/org/opensearch/knn/plugin/transport/KNNStatsRequest.java
  src/test/java/org/opensearch/knn/plugin/action/RestKNNStatsHandlerIT.java
  src/test/java/org/opensearch/knn/plugin/action/RestLegacyKNNStatsHandlerIT.java
Labels: Refactoring, backport 2.x

#742 Update certifi dependency version
  benchmarks/osb/requirements.txt
  benchmarks/perf-tool/requirements.txt
Labels: security vulnerability, backport 2.x

#739 Adding p99.9, p100 and num_of_segments metrics to perf-tool
  benchmarks/perf-tool/README.md
  benchmarks/perf-tool/okpt/test/steps/factory.py
  benchmarks/perf-tool/okpt/test/steps/steps.py
  benchmarks/perf-tool/okpt/test/test.py
Labels: Enhancements, backport 2.x, v2.6.0
