Repository opensearch-project/k-NN, pull requests merged in 2023-03, with the labels that each got.

#793 Update bwc version to next release
  .github/workflows/backwards_compatibility_tests_workflow.yml
Labels: Infrastructure

#792 Adding filter type to filtering release configs
  benchmarks/perf-tool/release-configs/lucene-hnsw/filtering/relaxed-filter/relaxed-filter-test.yml
  benchmarks/perf-tool/release-configs/lucene-hnsw/filtering/restrictive-filter/restrictive-filter-test.yml
Labels: Infrastructure, backport 2.x, v2.7.0

#800 Add CHANGELOG
  .github/workflows/changelog_verifier.yml
  CHANGELOG.md
  CONTRIBUTING.md
Labels: backport 2.x

#802 Add Release Notes for 1.3.9
  release-notes/opensearch-knn.release-notes-1.3.9.0.md
Labels: Infrastructure, backport 1.x, backport 1.3, skip-changelog, v1.3.9

#804 Bump byte-buddy version from 1.12.22 to 1.14.2
  CHANGELOG.md
  build.gradle
Labels: Infrastructure, backport 2.x

#813 Update BWC Version with OpenSearch Version Bump
  CHANGELOG.md
  build.gradle
Labels: Infrastructure

#819 Disable BWC Tests on Windows OS
  .github/workflows/backwards_compatibility_tests_workflow.yml
Labels: Infrastructure, skip-changelog

#817 Update Certifi version to 2022.12.7
  CHANGELOG.md
  benchmarks/perf-tool/requirements.txt
Labels: security fix, backport 1.3

#824 [Backport 2.x] Fixing the imports failures happening due to changes in OpenSearch Core.
  qa/restart-upgrade/src/test/java/org/opensearch/knn/bwc/ModelIT.java
  src/main/java/org/opensearch/knn/index/KNNMethodContext.java
  src/main/java/org/opensearch/knn/index/MethodComponentContext.java
  src/main/java/org/opensearch/knn/index/codec/KNN80Codec/KNN80DocValuesConsumer.java
  src/main/java/org/opensearch/knn/index/mapper/KNNVectorFieldMapper.java
  src/main/java/org/opensearch/knn/index/query/KNNQueryBuilder.java
  src/main/java/org/opensearch/knn/indices/Model.java
  src/main/java/org/opensearch/knn/indices/ModelGraveyard.java
  src/main/java/org/opensearch/knn/indices/ModelMetadata.java
  src/main/java/org/opensearch/knn/plugin/KNNPlugin.java
  src/main/java/org/opensearch/knn/plugin/rest/RestTrainModelHandler.java
  src/main/java/org/opensearch/knn/plugin/transport/DeleteModelResponse.java
  src/main/java/org/opensearch/knn/plugin/transport/GetModelResponse.java
  src/main/java/org/opensearch/knn/plugin/transport/KNNStatsNodeResponse.java
  src/main/java/org/opensearch/knn/plugin/transport/KNNStatsResponse.java
  src/main/java/org/opensearch/knn/plugin/transport/KNNWarmupResponse.java
  src/main/java/org/opensearch/knn/plugin/transport/TrainingJobRouteDecisionInfoNodeResponse.java
  src/main/java/org/opensearch/knn/plugin/transport/TrainingJobRouteDecisionInfoResponse.java
  src/main/java/org/opensearch/knn/plugin/transport/TrainingModelResponse.java
  src/test/java/org/opensearch/knn/KNNSingleNodeTestCase.java
  src/test/java/org/opensearch/knn/KNNTestCase.java
  src/test/java/org/opensearch/knn/index/FaissIT.java
  src/test/java/org/opensearch/knn/index/KNNMethodContextTests.java
  src/test/java/org/opensearch/knn/index/KNNMethodTests.java
  src/test/java/org/opensearch/knn/index/LuceneEngineIT.java
  src/test/java/org/opensearch/knn/index/MethodComponentContextTests.java
  src/test/java/org/opensearch/knn/index/MethodComponentTests.java
  src/test/java/org/opensearch/knn/index/NmslibIT.java
  src/test/java/org/opensearch/knn/index/OpenSearchIT.java
  src/test/java/org/opensearch/knn/index/mapper/KNNVectorFieldMapperTests.java
  src/test/java/org/opensearch/knn/index/query/KNNQueryBuilderTests.java
  src/test/java/org/opensearch/knn/index/util/AbstractKNNLibraryTests.java
  src/test/java/org/opensearch/knn/index/util/FaissTests.java
  src/test/java/org/opensearch/knn/index/util/LuceneTests.java
  src/test/java/org/opensearch/knn/indices/ModelDaoTests.java
  src/test/java/org/opensearch/knn/indices/ModelGraveyardTests.java
  src/test/java/org/opensearch/knn/plugin/action/RestDeleteModelHandlerIT.java
  src/test/java/org/opensearch/knn/plugin/action/RestKNNStatsHandlerIT.java
  src/test/java/org/opensearch/knn/plugin/action/RestSearchModelHandlerIT.java
  src/test/java/org/opensearch/knn/plugin/action/RestTrainModelHandlerIT.java
  src/test/java/org/opensearch/knn/plugin/script/KNNScriptScoringIT.java
  src/test/java/org/opensearch/knn/plugin/script/PainlessScriptIT.java
  src/test/java/org/opensearch/knn/plugin/transport/DeleteModelResponseTests.java
  src/test/java/org/opensearch/knn/plugin/transport/GetModelResponseTests.java
  src/test/java/org/opensearch/knn/plugin/transport/TrainingJobRouteDecisionInfoNodeResponseTests.java
  src/test/java/org/opensearch/knn/plugin/transport/TrainingJobRouteDecisionInfoResponseTests.java
  src/test/java/org/opensearch/knn/plugin/transport/TrainingModelResponseTests.java
  src/test/java/org/opensearch/knn/plugin/transport/TrainingModelTransportActionTests.java
  src/testFixtures/java/org/opensearch/knn/KNNRestTestCase.java
  src/testFixtures/java/org/opensearch/knn/ODFERestTestCase.java
  src/testFixtures/java/org/opensearch/knn/TestUtils.java
Labels: skip-changelog
