Repository opensearch-project/k-NN, pull requests merged in 2024-09, with the labels that each got.

#2018 Adds graph build time metrics in NativeEngines990KnnVectorsWriter
  src/main/java/org/opensearch/knn/index/codec/KNN990Codec/NativeEngines990KnnVectorsWriter.java
  src/test/java/org/opensearch/knn/index/codec/KNN990Codec/NativeEngines990KnnVectorsFormatTests.java
Labels: backport 2.x, skip-changelog, v2.17.0

#2021 [Backport 2.x] Makes NativeEngines990KnnVectorFormat as default for index version (#…
  src/main/java/org/opensearch/knn/index/KNNSettings.java
  src/main/java/org/opensearch/knn/index/codec/BasePerFieldKnnVectorsFormat.java
  src/main/java/org/opensearch/knn/index/mapper/KNNVectorFieldMapperUtil.java
  src/test/java/org/opensearch/knn/index/mapper/KNNVectorFieldMapperUtilTests.java
Labels: skip-changelog

#2025 Fixing the format name for NativeEngines990KnnVectorsFormat
  src/main/java/org/opensearch/knn/index/codec/KNN990Codec/NativeEngines990KnnVectorsFormat.java
  src/test/java/org/opensearch/knn/index/codec/KNN990Codec/NativeEngines990KnnVectorsFormatTests.java
Labels: backport 2.x, skip-changelog, backport 2.17

#2024 Fixes the build for 2.x
  src/test/java/org/opensearch/knn/index/mapper/KNNVectorFieldMapperUtilTests.java
Labels: skip-changelog, backport 2.17

#2019 Introduce compression and mode mapping parms
  src/main/java/org/opensearch/knn/common/KNNConstants.java
  src/main/java/org/opensearch/knn/index/engine/KNNMethodConfigContext.java
  src/main/java/org/opensearch/knn/index/mapper/CompressionLevel.java
  src/main/java/org/opensearch/knn/index/mapper/FlatVectorFieldMapper.java
  src/main/java/org/opensearch/knn/index/mapper/KNNVectorFieldMapper.java
  src/main/java/org/opensearch/knn/index/mapper/LuceneFieldMapper.java
  src/main/java/org/opensearch/knn/index/mapper/MethodFieldMapper.java
  src/main/java/org/opensearch/knn/index/mapper/Mode.java
  src/main/java/org/opensearch/knn/index/mapper/ModelFieldMapper.java
  src/main/java/org/opensearch/knn/index/mapper/OriginalMappingParameters.java
  src/main/java/org/opensearch/knn/index/util/IndexUtil.java
  src/main/java/org/opensearch/knn/indices/ModelDao.java
  src/main/java/org/opensearch/knn/indices/ModelMetadata.java
  src/main/java/org/opensearch/knn/plugin/rest/RestTrainModelHandler.java
  src/main/java/org/opensearch/knn/plugin/transport/TrainingModelRequest.java
  src/main/java/org/opensearch/knn/plugin/transport/TrainingModelTransportAction.java
  src/main/java/org/opensearch/knn/training/TrainingJob.java
  src/main/resources/mappings/model-index.json
  src/test/java/org/opensearch/knn/index/KNNCreateIndexFromModelTests.java
  src/test/java/org/opensearch/knn/index/codec/KNN80Codec/KNN80DocValuesConsumerTests.java
  src/test/java/org/opensearch/knn/index/codec/KNNCodecTestCase.java
  src/test/java/org/opensearch/knn/index/mapper/CompressionLevelTests.java
  src/test/java/org/opensearch/knn/index/mapper/KNNVectorFieldMapperTests.java
  src/test/java/org/opensearch/knn/index/mapper/ModeTests.java
  src/test/java/org/opensearch/knn/index/mapper/OriginalMappingParametersTests.java
  src/test/java/org/opensearch/knn/indices/ModelCacheTests.java
  src/test/java/org/opensearch/knn/indices/ModelDaoTests.java
  src/test/java/org/opensearch/knn/indices/ModelMetadataTests.java
  src/test/java/org/opensearch/knn/indices/ModelTests.java
  src/test/java/org/opensearch/knn/integ/ModeAndCompressionIT.java
  src/test/java/org/opensearch/knn/plugin/transport/GetModelResponseTests.java
  src/test/java/org/opensearch/knn/plugin/transport/RemoveModelFromCacheTransportActionTests.java
  src/test/java/org/opensearch/knn/plugin/transport/TrainingJobRouterTransportActionTests.java
  src/test/java/org/opensearch/knn/plugin/transport/TrainingModelRequestTests.java
  src/test/java/org/opensearch/knn/plugin/transport/TrainingModelTransportActionTests.java
  src/test/java/org/opensearch/knn/plugin/transport/UpdateModelGraveyardTransportActionTests.java
  src/test/java/org/opensearch/knn/plugin/transport/UpdateModelMetadataRequestTests.java
  src/test/java/org/opensearch/knn/plugin/transport/UpdateModelMetadataTransportActionTests.java
  src/test/java/org/opensearch/knn/training/TrainingJobTests.java
Labels: backport 2.x, skip-changelog, backport 2.17

#2015 Fix memory overflow caused by cache behavior
  CHANGELOG.md
  src/main/java/org/opensearch/knn/common/featureflags/KNNFeatureFlags.java
  src/main/java/org/opensearch/knn/index/KNNSettings.java
  src/main/java/org/opensearch/knn/index/memory/NativeMemoryAllocation.java
  src/main/java/org/opensearch/knn/index/memory/NativeMemoryCacheManager.java
  src/test/java/org/opensearch/knn/common/featureflags/KNNFeatureFlagsTests.java
  src/test/java/org/opensearch/knn/index/memory/NativeMemoryAllocationTests.java
Labels: Enhancements, search-improvements, v2.17.0

#2037 Add release notes for 2.17
  CHANGELOG.md
  release-notes/opensearch-knn.release-notes-2.17.0.0.md
Labels: backport 2.x, skip-changelog, backport 2.17

#1997 Add quantization state reader and writer
  CHANGELOG.md
  release-notes/opensearch-knn.release-notes-2.17.0.0.md
  src/main/java/org/opensearch/knn/common/KNNConstants.java
  src/main/java/org/opensearch/knn/index/KNNSettings.java
  src/main/java/org/opensearch/knn/index/codec/KNN990Codec/KNN990QuantizationStateReader.java
  src/main/java/org/opensearch/knn/index/codec/KNN990Codec/KNN990QuantizationStateWriter.java
  src/main/java/org/opensearch/knn/index/codec/KNN990Codec/NativeEngines990KnnVectorsReader.java
  src/main/java/org/opensearch/knn/index/codec/KNN990Codec/NativeEngines990KnnVectorsWriter.java
  src/main/java/org/opensearch/knn/index/codec/KNN990Codec/QuantizationConfigKNNCollector.java
  src/main/java/org/opensearch/knn/index/query/KNNWeight.java
  src/main/java/org/opensearch/knn/quantization/models/quantizationState/QuantizationStateCache.java
  src/main/java/org/opensearch/knn/quantization/models/quantizationState/QuantizationStateCacheManager.java
  src/main/java/org/opensearch/knn/quantization/models/quantizationState/QuantizationStateReadConfig.java
  src/test/java/org/opensearch/knn/index/codec/KNN990Codec/KNN990QuantizationStateReaderTests.java
  src/test/java/org/opensearch/knn/index/codec/KNN990Codec/KNN990QuantizationStateWriterTests.java
  src/test/java/org/opensearch/knn/index/codec/KNN990Codec/NativeEngines990KnnVectorsFormatTests.java
  src/test/java/org/opensearch/knn/index/query/KNNWeightTests.java
  src/test/java/org/opensearch/knn/quantization/models/quantizationState/QuantizationStateCacheManagerTests.java
Labels: backport 2.x, skip-changelog, v2.17.0

#2039 [Backport 2.x] Add release notes for 2.17
  CHANGELOG.md
  release-notes/opensearch-knn.release-notes-2.17.0.0.md
Labels: skip-changelog

#2038 [Backport 2.17] Add release notes for 2.17
  CHANGELOG.md
  release-notes/opensearch-knn.release-notes-2.17.0.0.md
Labels: skip-changelog

#2034 Introduce mode and compression param resolution
  release-notes/opensearch-knn.release-notes-2.17.0.0.md
  src/main/java/org/opensearch/knn/index/KNNIndexShard.java
  src/main/java/org/opensearch/knn/index/codec/KNN990Codec/KNN990QuantizationStateReader.java
  src/main/java/org/opensearch/knn/index/codec/KNN990Codec/NativeEngines990KnnVectorsReader.java
  src/main/java/org/opensearch/knn/index/codec/nativeindex/NativeIndexWriter.java
  src/main/java/org/opensearch/knn/index/engine/KNNMethodConfigContext.java
  src/main/java/org/opensearch/knn/index/mapper/CompressionLevel.java
  src/main/java/org/opensearch/knn/index/mapper/KNNMappingConfig.java
  src/main/java/org/opensearch/knn/index/mapper/KNNVectorFieldMapper.java
  src/main/java/org/opensearch/knn/index/mapper/KNNVectorFieldType.java
  src/main/java/org/opensearch/knn/index/mapper/MethodFieldMapper.java
  src/main/java/org/opensearch/knn/index/mapper/Mode.java
  src/main/java/org/opensearch/knn/index/mapper/ModeBasedResolver.java
  src/main/java/org/opensearch/knn/index/mapper/ModelFieldMapper.java
  src/main/java/org/opensearch/knn/index/query/KNNQueryBuilder.java
  src/main/java/org/opensearch/knn/plugin/rest/RestTrainModelHandler.java
  src/main/java/org/opensearch/knn/plugin/transport/TrainingModelRequest.java
  src/main/java/org/opensearch/knn/training/TrainingJob.java
  src/test/java/org/opensearch/knn/index/codec/KNN990Codec/KNN990QuantizationStateReaderTests.java
  src/test/java/org/opensearch/knn/index/codec/KNN990Codec/NativeEngines990KnnVectorsFormatTests.java
  src/test/java/org/opensearch/knn/index/engine/KNNMethodContextTests.java
  src/test/java/org/opensearch/knn/index/mapper/KNNVectorFieldMapperTests.java
  src/test/java/org/opensearch/knn/integ/ModeAndCompressionIT.java
  src/test/java/org/opensearch/knn/integ/QFrameworkIT.java
  src/test/java/org/opensearch/knn/plugin/transport/TrainingModelRequestTests.java
Labels: backport 2.x, skip-changelog, backport 2.17

#2045 Fix tests related to quantization state
  src/main/java/org/opensearch/knn/index/codec/KNN990Codec/KNN990QuantizationStateReader.java
  src/main/java/org/opensearch/knn/index/codec/KNN990Codec/NativeEngines990KnnVectorsReader.java
  src/test/java/org/opensearch/knn/index/codec/KNN990Codec/KNN990QuantizationStateReaderTests.java
  src/test/java/org/opensearch/knn/index/codec/KNN990Codec/NativeEngines990KnnVectorsFormatTests.java
Labels: backport 2.x, skip-changelog, backport 2.17

#2044 Add spaceType as a top level parameter while creating vector field.
  release-notes/opensearch-knn.release-notes-2.17.0.0.md
  src/main/java/org/opensearch/knn/common/KNNConstants.java
  src/main/java/org/opensearch/knn/index/SpaceType.java
  src/main/java/org/opensearch/knn/index/mapper/KNNVectorFieldMapper.java
  src/main/java/org/opensearch/knn/index/mapper/KNNVectorFieldMapperUtil.java
  src/main/java/org/opensearch/knn/index/mapper/ModeBasedResolver.java
  src/main/java/org/opensearch/knn/index/mapper/OriginalMappingParameters.java
  src/main/java/org/opensearch/knn/index/util/IndexUtil.java
  src/main/java/org/opensearch/knn/plugin/rest/RestTrainModelHandler.java
  src/main/java/org/opensearch/knn/plugin/transport/TrainingModelRequest.java
  src/test/java/org/opensearch/knn/index/mapper/KNNVectorFieldMapperTests.java
  src/test/java/org/opensearch/knn/index/mapper/OriginalMappingParametersTests.java
Labels: backport 2.x, skip-changelog, backport 2.17

#2046 Fix the force merge with Quantization failures when a segment has deleted docs in it
  src/main/java/org/opensearch/knn/index/codec/KNN80Codec/KNN80DocValuesConsumer.java
  src/main/java/org/opensearch/knn/index/codec/KNN990Codec/NativeEngines990KnnVectorsWriter.java
  src/main/java/org/opensearch/knn/index/codec/nativeindex/DefaultIndexBuildStrategy.java
  src/main/java/org/opensearch/knn/index/codec/nativeindex/MemOptimizedNativeIndexBuildStrategy.java
  src/main/java/org/opensearch/knn/index/codec/nativeindex/NativeIndexBuildStrategy.java
  src/main/java/org/opensearch/knn/index/codec/nativeindex/NativeIndexWriter.java
  src/main/java/org/opensearch/knn/index/codec/nativeindex/model/BuildIndexParams.java
  src/main/java/org/opensearch/knn/index/quantizationservice/KNNVectorQuantizationTrainingRequest.java
  src/main/java/org/opensearch/knn/index/quantizationservice/QuantizationService.java
  src/main/java/org/opensearch/knn/index/vectorvalues/KNNVectorValues.java
  src/test/java/org/opensearch/knn/index/codec/nativeindex/DefaultIndexBuildStrategyTests.java
  src/test/java/org/opensearch/knn/index/codec/nativeindex/MemOptimizedNativeIndexBuildStrategyTests.java
  src/test/java/org/opensearch/knn/index/quantizationservice/QuantizationServiceTests.java
  src/test/java/org/opensearch/knn/integ/ModeAndCompressionIT.java
Labels: backport 2.x, skip-changelog, v2.17.0, backport 2.17

#2005 Add model version to model metadata and change model metadata reads to be from cluster metadata
  release-notes/opensearch-knn.release-notes-2.17.0.0.md
  src/main/java/org/opensearch/knn/common/KNNConstants.java
  src/main/java/org/opensearch/knn/index/mapper/ModelFieldMapper.java
  src/main/java/org/opensearch/knn/index/util/IndexUtil.java
  src/main/java/org/opensearch/knn/indices/ModelDao.java
  src/main/java/org/opensearch/knn/indices/ModelMetadata.java
  src/main/java/org/opensearch/knn/indices/ModelUtil.java
  src/main/java/org/opensearch/knn/training/TrainingJob.java
  src/main/java/org/opensearch/knn/training/TrainingJobRunner.java
  src/main/resources/mappings/model-index.json
  src/test/java/org/opensearch/knn/index/KNNCreateIndexFromModelTests.java
  src/test/java/org/opensearch/knn/index/codec/KNN80Codec/KNN80DocValuesConsumerTests.java
  src/test/java/org/opensearch/knn/index/codec/KNNCodecTestCase.java
  src/test/java/org/opensearch/knn/index/mapper/KNNVectorFieldMapperTests.java
  src/test/java/org/opensearch/knn/indices/ModelCacheTests.java
  src/test/java/org/opensearch/knn/indices/ModelDaoTests.java
  src/test/java/org/opensearch/knn/indices/ModelMetadataTests.java
  src/test/java/org/opensearch/knn/indices/ModelTests.java
  src/test/java/org/opensearch/knn/indices/ModelUtilTests.java
  src/test/java/org/opensearch/knn/plugin/transport/GetModelResponseTests.java
  src/test/java/org/opensearch/knn/plugin/transport/RemoveModelFromCacheTransportActionTests.java
  src/test/java/org/opensearch/knn/plugin/transport/TrainingModelRequestTests.java
  src/test/java/org/opensearch/knn/plugin/transport/UpdateModelGraveyardTransportActionTests.java
  src/test/java/org/opensearch/knn/plugin/transport/UpdateModelMetadataRequestTests.java
  src/test/java/org/opensearch/knn/plugin/transport/UpdateModelMetadataTransportActionTests.java
  src/test/java/org/opensearch/knn/training/TrainingJobRunnerTests.java
  src/test/java/org/opensearch/knn/training/TrainingJobTests.java
Labels: backport 2.x, skip-changelog, v2.17.0, backport 2.17

#2058 Add tests for top level spaceType parameter with different combinations
  src/test/java/org/opensearch/knn/index/mapper/KNNVectorFieldMapperTests.java
  src/test/java/org/opensearch/knn/integ/TopLevelSpaceTypeParameterIT.java
Labels: backport 2.x, skip-changelog, backport 2.17

#2064 [Backport 2.17] Fix expected string for get model response tests
  src/test/java/org/opensearch/knn/plugin/transport/GetModelResponseTests.java
Labels: skip-changelog

#2055 Throws and exception for radial search when mapping is for on-disk mode
  src/main/java/org/opensearch/knn/index/mapper/KNNMappingConfig.java
  src/main/java/org/opensearch/knn/index/mapper/KNNVectorFieldMapper.java
  src/main/java/org/opensearch/knn/index/mapper/MethodFieldMapper.java
  src/main/java/org/opensearch/knn/index/mapper/ModelFieldMapper.java
  src/main/java/org/opensearch/knn/index/query/KNNQueryBuilder.java
  src/main/java/org/opensearch/knn/index/query/nativelib/NativeEngineKnnVectorQuery.java
  src/test/java/org/opensearch/knn/index/mapper/KNNVectorFieldMapperTests.java
  src/test/java/org/opensearch/knn/index/query/KNNQueryBuilderTests.java
Labels: backport 2.x, skip-changelog, backport 2.17

#2070 Bounds the transferLimit in OffheapVectorTransfer
  src/main/java/org/opensearch/knn/index/codec/nativeindex/DefaultIndexBuildStrategy.java
  src/main/java/org/opensearch/knn/index/codec/nativeindex/MemOptimizedNativeIndexBuildStrategy.java
  src/main/java/org/opensearch/knn/index/codec/transfer/OffHeapBinaryVectorTransfer.java
  src/main/java/org/opensearch/knn/index/codec/transfer/OffHeapByteVectorTransfer.java
  src/main/java/org/opensearch/knn/index/codec/transfer/OffHeapFloatVectorTransfer.java
  src/main/java/org/opensearch/knn/index/codec/transfer/OffHeapVectorTransfer.java
  src/main/java/org/opensearch/knn/index/codec/transfer/OffHeapVectorTransferFactory.java
  src/test/java/org/opensearch/knn/index/codec/nativeindex/DefaultIndexBuildStrategyTests.java
  src/test/java/org/opensearch/knn/index/codec/nativeindex/MemOptimizedNativeIndexBuildStrategyTests.java
  src/test/java/org/opensearch/knn/index/codec/transfer/OffHeapVectorTransferFactoryTests.java
  src/test/java/org/opensearch/knn/index/codec/transfer/OffHeapVectorTransferTests.java
Labels: backport 2.x, skip-changelog, backport 2.17

#2072 [BugFix] Fixing KNNMethodContext resolution when documents are ingested and a flaky test
  src/main/java/org/opensearch/knn/index/mapper/KNNVectorFieldMapper.java
  src/test/java/org/opensearch/knn/index/mapper/KNNVectorFieldMapperTests.java
  src/test/java/org/opensearch/knn/integ/ModeAndCompressionIT.java
Labels: backport 2.x, skip-changelog, backport 2.17

#2075 [Backport 2.x] [BugFix] Fixing KNNMethodContext resolution when documents are ingested and a flaky test (#2072)
  src/main/java/org/opensearch/knn/index/mapper/KNNVectorFieldMapper.java
  src/test/java/org/opensearch/knn/index/mapper/KNNVectorFieldMapperTests.java
  src/test/java/org/opensearch/knn/integ/ModeAndCompressionIT.java
Labels: skip-changelog, backport 2.17

#2071 Re-Call Issue Fix with Binary Quantized Vectors
  src/main/java/org/opensearch/knn/index/codec/nativeindex/QuantizationIndexUtils.java
  src/main/java/org/opensearch/knn/quantization/models/quantizationOutput/BinaryQuantizationOutput.java
  src/main/java/org/opensearch/knn/quantization/models/quantizationOutput/QuantizationOutput.java
  src/main/java/org/opensearch/knn/quantization/quantizer/MultiBitScalarQuantizer.java
  src/main/java/org/opensearch/knn/quantization/quantizer/OneBitScalarQuantizer.java
  src/test/java/org/opensearch/knn/index/codec/nativeindex/DefaultIndexBuildStrategyTests.java
  src/test/java/org/opensearch/knn/index/codec/nativeindex/MemOptimizedNativeIndexBuildStrategyTests.java
  src/test/java/org/opensearch/knn/quantization/output/BinaryQuantizationOutputTests.java
Labels: backport 2.x, skip-changelog, backport 2.17

#2063 [Backport 2.x] Add model version to model metadata and change model metadata reads to be from cluster metadata
  release-notes/opensearch-knn.release-notes-2.17.0.0.md
  src/main/java/org/opensearch/knn/common/KNNConstants.java
  src/main/java/org/opensearch/knn/index/mapper/ModelFieldMapper.java
  src/main/java/org/opensearch/knn/index/util/IndexUtil.java
  src/main/java/org/opensearch/knn/indices/ModelDao.java
  src/main/java/org/opensearch/knn/indices/ModelMetadata.java
  src/main/java/org/opensearch/knn/indices/ModelUtil.java
  src/main/java/org/opensearch/knn/training/TrainingJob.java
  src/main/java/org/opensearch/knn/training/TrainingJobRunner.java
  src/main/resources/mappings/model-index.json
  src/test/java/org/opensearch/knn/index/KNNCreateIndexFromModelTests.java
  src/test/java/org/opensearch/knn/index/codec/KNN80Codec/KNN80DocValuesConsumerTests.java
  src/test/java/org/opensearch/knn/index/codec/KNNCodecTestCase.java
  src/test/java/org/opensearch/knn/index/mapper/KNNVectorFieldMapperTests.java
  src/test/java/org/opensearch/knn/indices/ModelCacheTests.java
  src/test/java/org/opensearch/knn/indices/ModelDaoTests.java
  src/test/java/org/opensearch/knn/indices/ModelMetadataTests.java
  src/test/java/org/opensearch/knn/indices/ModelTests.java
  src/test/java/org/opensearch/knn/indices/ModelUtilTests.java
  src/test/java/org/opensearch/knn/plugin/transport/GetModelResponseTests.java
  src/test/java/org/opensearch/knn/plugin/transport/RemoveModelFromCacheTransportActionTests.java
  src/test/java/org/opensearch/knn/plugin/transport/TrainingModelRequestTests.java
  src/test/java/org/opensearch/knn/plugin/transport/UpdateModelGraveyardTransportActionTests.java
  src/test/java/org/opensearch/knn/plugin/transport/UpdateModelMetadataRequestTests.java
  src/test/java/org/opensearch/knn/plugin/transport/UpdateModelMetadataTransportActionTests.java
  src/test/java/org/opensearch/knn/training/TrainingJobRunnerTests.java
  src/test/java/org/opensearch/knn/training/TrainingJobTests.java
Labels: skip-changelog

#2076 [Bug-Fix] Fix efficient filtering of vector search when quantization is used
  src/main/java/org/opensearch/knn/index/query/ExactSearcher.java
  src/main/java/org/opensearch/knn/index/query/KNNWeight.java
  src/main/java/org/opensearch/knn/index/query/SegmentLevelQuantizationInfo.java
  src/main/java/org/opensearch/knn/index/query/SegmentLevelQuantizationUtil.java
  src/main/java/org/opensearch/knn/index/query/filtered/FilteredIdsKNNIterator.java
  src/main/java/org/opensearch/knn/index/query/filtered/NestedFilteredIdsKNNIterator.java
  src/main/java/org/opensearch/knn/index/query/nativelib/NativeEngineKnnVectorQuery.java
  src/test/java/org/opensearch/knn/index/query/KNNWeightTests.java
  src/test/java/org/opensearch/knn/index/query/nativelib/NativeEngineKNNVectorQueryTests.java
Labels: backport 2.x, skip-changelog, backport 2.17

#2083 Fix mode/comp params so parameter overrides work
  src/main/java/org/opensearch/knn/index/engine/AbstractMethodResolver.java
  src/main/java/org/opensearch/knn/index/engine/Encoder.java
  src/main/java/org/opensearch/knn/index/engine/EngineResolver.java
  src/main/java/org/opensearch/knn/index/engine/KNNEngine.java
  src/main/java/org/opensearch/knn/index/engine/KNNLibrary.java
  src/main/java/org/opensearch/knn/index/engine/KNNMethodContext.java
  src/main/java/org/opensearch/knn/index/engine/MethodComponent.java
  src/main/java/org/opensearch/knn/index/engine/MethodComponentContext.java
  src/main/java/org/opensearch/knn/index/engine/MethodResolver.java
  src/main/java/org/opensearch/knn/index/engine/ResolvedMethodContext.java
  src/main/java/org/opensearch/knn/index/engine/SpaceTypeResolver.java
  src/main/java/org/opensearch/knn/index/engine/faiss/Faiss.java
  src/main/java/org/opensearch/knn/index/engine/faiss/FaissFlatEncoder.java
  src/main/java/org/opensearch/knn/index/engine/faiss/FaissHNSWMethod.java
  src/main/java/org/opensearch/knn/index/engine/faiss/FaissHNSWPQEncoder.java
  src/main/java/org/opensearch/knn/index/engine/faiss/FaissIVFMethod.java
  src/main/java/org/opensearch/knn/index/engine/faiss/FaissIVFPQEncoder.java
  src/main/java/org/opensearch/knn/index/engine/faiss/FaissMethodResolver.java
  src/main/java/org/opensearch/knn/index/engine/faiss/FaissSQEncoder.java
  src/main/java/org/opensearch/knn/index/engine/faiss/QFrameBitEncoder.java
  src/main/java/org/opensearch/knn/index/engine/lucene/Lucene.java
  src/main/java/org/opensearch/knn/index/engine/lucene/LuceneHNSWMethod.java
  src/main/java/org/opensearch/knn/index/engine/lucene/LuceneMethodResolver.java
  src/main/java/org/opensearch/knn/index/engine/lucene/LuceneSQEncoder.java
  src/main/java/org/opensearch/knn/index/engine/nmslib/Nmslib.java
  src/main/java/org/opensearch/knn/index/engine/nmslib/NmslibHNSWMethod.java
  src/main/java/org/opensearch/knn/index/engine/nmslib/NmslibMethodResolver.java
  src/main/java/org/opensearch/knn/index/mapper/CompressionLevel.java
  src/main/java/org/opensearch/knn/index/mapper/KNNVectorFieldMapper.java
  src/main/java/org/opensearch/knn/index/mapper/KNNVectorFieldType.java
  src/main/java/org/opensearch/knn/index/mapper/LuceneFieldMapper.java
  src/main/java/org/opensearch/knn/index/mapper/MethodFieldMapper.java
  src/main/java/org/opensearch/knn/index/mapper/ModeBasedResolver.java
  src/main/java/org/opensearch/knn/index/mapper/OriginalMappingParameters.java
  src/main/java/org/opensearch/knn/index/util/IndexUtil.java
  src/main/java/org/opensearch/knn/plugin/rest/RestTrainModelHandler.java
  src/main/java/org/opensearch/knn/plugin/transport/TrainingModelRequest.java
  src/test/java/org/opensearch/knn/KNNTestCase.java
  src/test/java/org/opensearch/knn/index/engine/AbstractKNNLibraryTests.java
  src/test/java/org/opensearch/knn/index/engine/AbstractMethodResolverTests.java
  src/test/java/org/opensearch/knn/index/engine/EngineResolverTests.java
  src/test/java/org/opensearch/knn/index/engine/NativeLibraryTests.java
  src/test/java/org/opensearch/knn/index/engine/SpaceTypeResolverTests.java
  src/test/java/org/opensearch/knn/index/engine/faiss/FaissHNSWPQEncoderTests.java
  src/test/java/org/opensearch/knn/index/engine/faiss/FaissIVFPQEncoderTests.java
  src/test/java/org/opensearch/knn/index/engine/faiss/FaissMethodResolverTests.java
  src/test/java/org/opensearch/knn/index/engine/faiss/FaissSQEncoderTests.java
  src/test/java/org/opensearch/knn/index/engine/faiss/QFrameBitEncoderTests.java
  src/test/java/org/opensearch/knn/index/engine/lucene/LuceneMethodResolverTests.java
  src/test/java/org/opensearch/knn/index/engine/lucene/LuceneSQEncoderTests.java
  src/test/java/org/opensearch/knn/index/engine/nmslib/NmslibMethodResolverTests.java
  src/test/java/org/opensearch/knn/index/mapper/KNNVectorFieldMapperTests.java
  src/test/java/org/opensearch/knn/integ/ModeAndCompressionIT.java
  src/test/java/org/opensearch/knn/plugin/stats/suppliers/LibraryInitializedSupplierTests.java
  src/test/java/org/opensearch/knn/plugin/transport/TrainingJobRouterTransportActionTests.java
  src/test/java/org/opensearch/knn/plugin/transport/TrainingModelRequestTests.java
Labels: backport 2.x, skip-changelog, backport 2.17

#2086 Use correct type for binary vector in ivf training
  jni/src/faiss_wrapper.cpp
  release-notes/opensearch-knn.release-notes-2.17.0.0.md
Labels: Bug Fixes, backport 2.x, skip-changelog, backport 2.17

#2090 Switch MINGW32 to MINGW64
  release-notes/opensearch-knn.release-notes-2.17.0.0.md
  scripts/windowsScript.ps1
Labels: backport 2.x, skip-changelog, backport 2.17

#2035 Adds index and query BWC tests for missing engines
  qa/restart-upgrade/build.gradle
  qa/restart-upgrade/src/test/java/org/opensearch/knn/bwc/IndexingIT.java
  qa/restart-upgrade/src/test/java/org/opensearch/knn/bwc/QueryANNIT.java
Labels: backport 2.x, skip-changelog

#2087 Improving Defaults Hyper Parameter for Binary Quantization Indexes
  src/main/java/org/opensearch/knn/index/engine/MethodComponent.java
  src/main/java/org/opensearch/knn/index/engine/faiss/FaissMethodResolver.java
  src/main/java/org/opensearch/knn/index/mapper/CompressionLevel.java
  src/main/java/org/opensearch/knn/index/query/rescore/RescoreContext.java
  src/main/java/org/opensearch/knn/index/util/IndexHyperParametersUtil.java
  src/test/java/org/opensearch/knn/index/engine/MethodComponentTests.java
  src/test/java/org/opensearch/knn/index/engine/faiss/FaissMethodResolverTests.java
  src/test/java/org/opensearch/knn/index/mapper/CompressionLevelTests.java
  src/test/java/org/opensearch/knn/index/query/rescore/RescoreContextTests.java
  src/test/java/org/opensearch/knn/index/util/IndexHyperParametersUtilTests.java
Labels: backport 2.x, skip-changelog, backport 2.17

#2098 Fixes spotless for restart upgrade
  qa/restart-upgrade/src/test/java/org/opensearch/knn/bwc/IndexingIT.java
Labels: skip-changelog

#2100 Fix bug where quantization framework does not work with training
  jni/src/faiss_wrapper.cpp
  src/main/java/org/opensearch/knn/index/mapper/CompressionLevel.java
  src/main/java/org/opensearch/knn/index/memory/NativeMemoryAllocation.java
  src/main/java/org/opensearch/knn/index/memory/NativeMemoryEntryContext.java
  src/main/java/org/opensearch/knn/index/memory/NativeMemoryLoadStrategy.java
  src/main/java/org/opensearch/knn/plugin/transport/TrainingModelTransportAction.java
  src/main/java/org/opensearch/knn/training/FloatTrainingDataConsumer.java
  src/test/java/org/opensearch/knn/index/memory/NativeMemoryEntryContextTests.java
  src/test/java/org/opensearch/knn/index/memory/NativeMemoryLoadStrategyTests.java
  src/test/java/org/opensearch/knn/integ/ModeAndCompressionIT.java
  src/test/java/org/opensearch/knn/training/FloatTrainingDataConsumerTests.java
Labels: backport 2.x, skip-changelog, backport 2.17

#2096 [Backport 2.x] Adds index and query BWC tests for missing engines (#2035)
  qa/restart-upgrade/build.gradle
  qa/restart-upgrade/src/test/java/org/opensearch/knn/bwc/IndexingIT.java
  qa/restart-upgrade/src/test/java/org/opensearch/knn/bwc/QueryANNIT.java
Labels: skip-changelog

#2059 Add short circuit if no live docs are in segments
  CHANGELOG.md
  src/main/java/org/opensearch/knn/index/codec/KNN990Codec/NativeEngines990KnnVectorsWriter.java
Labels: backport 2.x

#2097 Adds Unit tests for NativeEngines990KnnVectorsWriter
  src/main/java/org/opensearch/knn/index/codec/KNN990Codec/NativeEngines990KnnVectorsWriter.java
  src/test/java/org/opensearch/knn/index/codec/KNN990Codec/NativeEngines990KnnVectorsWriterFlushTests.java
  src/test/java/org/opensearch/knn/index/codec/KNN990Codec/NativeEngines990KnnVectorsWriterMergeTests.java
  src/test/java/org/opensearch/knn/index/vectorvalues/TestVectorValues.java
Labels: skip-changelog

#2103 Fix native engine vector format test
  src/test/java/org/opensearch/knn/index/codec/KNN990Codec/NativeEngines990KnnVectorsFormatTests.java
Labels: backport 2.x, skip-changelog

#1946 Add DocValuesProducers for releasing memory when close index
  CHANGELOG.md
  src/main/java/org/opensearch/knn/index/codec/KNN80Codec/KNN80CompoundDirectory.java
  src/main/java/org/opensearch/knn/index/codec/KNN80Codec/KNN80CompoundFormat.java
  src/main/java/org/opensearch/knn/index/codec/KNN80Codec/KNN80DocValuesFormat.java
  src/main/java/org/opensearch/knn/index/codec/KNN80Codec/KNN80DocValuesProducer.java
  src/main/java/org/opensearch/knn/index/codec/util/KNNCodecUtil.java
  src/main/java/org/opensearch/knn/index/memory/NativeMemoryAllocation.java
  src/main/java/org/opensearch/knn/index/query/KNNWeight.java
  src/test/java/org/opensearch/knn/index/OpenSearchIT.java
  src/test/java/org/opensearch/knn/index/codec/KNN80Codec/KNN80CompoundFormatTests.java
  src/test/java/org/opensearch/knn/index/codec/KNN80Codec/KNN80DocValuesProducerTests.java
  src/test/java/org/opensearch/knn/index/codec/util/KNNCodecUtilTests.java
  src/test/java/org/opensearch/knn/index/query/KNNWeightTests.java
  src/testFixtures/java/org/opensearch/knn/KNNRestTestCase.java
Labels: Bug Fixes, backport 2.x

#2116 Remove outdated comment in integration tests
  src/test/java/org/opensearch/knn/integ/ModeAndCompressionIT.java
Labels: backport 2.x, skip-changelog

#2117 Change min oversample to 1
  src/main/java/org/opensearch/knn/index/query/rescore/RescoreContext.java
Labels: Bug Fixes, backport 2.x, skip-changelog

#2120 Add log message for quantization state cache eviction due to full cache
  src/main/java/org/opensearch/knn/quantization/models/quantizationState/QuantizationStateCache.java
Labels: backport 2.x, skip-changelog, backport 2.17

#2111 Integrates KNN plugin with ConcurrentSearchRequestDecider interface
  CHANGELOG.md
  src/main/java/org/opensearch/knn/plugin/KNNPlugin.java
  src/main/java/org/opensearch/knn/plugin/search/KNNConcurrentSearchRequestDecider.java
  src/test/java/org/opensearch/knn/integ/search/ConcurrentSegmentSearchIT.java
  src/test/java/org/opensearch/knn/plugin/search/KNNConcurrentSearchRequestDeciderTests.java
  src/testFixtures/java/org/opensearch/knn/KNNJsonIndexMappingsBuilder.java
Labels: Enhancements, backport 2.x

#2124 Fix BWC CI for 2.18
  .github/workflows/backwards_compatibility_tests_workflow.yml
Labels: skip-changelog

#2110 Add changes for AVX-512 support in k-NN.
  .github/workflows/CI.yml
  .github/workflows/backwards_compatibility_tests_workflow.yml
  .github/workflows/test_security.yml
  CHANGELOG.md
  DEVELOPER_GUIDE.md
  build.gradle
  jni/cmake/init-faiss.cmake
  scripts/build.sh
  src/main/java/org/opensearch/knn/common/KNNConstants.java
  src/main/java/org/opensearch/knn/index/KNNSettings.java
  src/main/java/org/opensearch/knn/jni/FaissService.java
  src/main/java/org/opensearch/knn/jni/PlatformUtils.java
  src/main/plugin-metadata/plugin-security.policy
  src/test/java/org/opensearch/knn/jni/PlatformUtilTests.java
Labels: Features, backport 2.x

#2141 Add space_type as acceptable field in train API
  src/main/java/org/opensearch/knn/plugin/rest/RestTrainModelHandler.java
Labels: backport 2.x, skip-changelog

#2147 KNN80DocValues should only be considered for BinaryDocValues fields
  CHANGELOG.md
  src/main/java/org/opensearch/knn/index/codec/KNN80Codec/KNN80DocValuesProducer.java
  src/test/java/org/opensearch/knn/index/OpenSearchIT.java
  src/test/java/org/opensearch/knn/index/codec/KNN80Codec/KNN80DocValuesProducerTests.java
Labels: Bug Fixes, backport 2.x

#2154 Add Release Notes for 2.17.1.0
  CHANGELOG.md
  release-notes/opensearch-knn.release-notes-2.17.1.0.md
Labels: backport 2.x, skip-changelog, backport 2.17

#2140 [Backport 2.17] Makes sure KNNVectorValues aren't recreated unnecessarily when quantization isn't needed (#2133)
  release-notes/opensearch-knn.release-notes-2.17.0.0.md
  src/main/java/org/opensearch/knn/index/codec/KNN990Codec/NativeEngines990KnnVectorsWriter.java
  src/test/java/org/opensearch/knn/index/codec/KNN990Codec/NativeEngines990KnnVectorsWriterFlushTests.java
  src/test/java/org/opensearch/knn/index/codec/KNN990Codec/NativeEngines990KnnVectorsWriterMergeTests.java
  src/test/java/org/opensearch/knn/index/vectorvalues/TestVectorValues.java
Labels: skip-changelog

#2158 Update release notes 2.17.1
  release-notes/opensearch-knn.release-notes-2.17.1.0.md
Labels: backport 2.x, backport main, skip-changelog

#2144 Added NMSLIB patched allowing load/write APIs with a stream object.
  jni/cmake/init-nmslib.cmake
  jni/patches/nmslib/0003-Adding-two-apis-using-stream-to-load-save-in-Hnsw.patch
Labels: backport 2.x, skip-changelog

#2161 Revert "Makes sure KNNVectorValues aren't recreated unnecessarily when quantization isn't needed"
  release-notes/opensearch-knn.release-notes-2.17.0.0.md
  src/main/java/org/opensearch/knn/index/codec/KNN990Codec/NativeEngines990KnnVectorsWriter.java
  src/test/java/org/opensearch/knn/index/codec/KNN990Codec/NativeEngines990KnnVectorsWriterFlushTests.java
  src/test/java/org/opensearch/knn/index/codec/KNN990Codec/NativeEngines990KnnVectorsWriterMergeTests.java
  src/test/java/org/opensearch/knn/index/vectorvalues/TestVectorValues.java
Labels: skip-changelog

#2146 Optimize reduceToTopK in ResultUtil by removing pre-filling and reducing peek calls
  CHANGELOG.md
  src/main/java/org/opensearch/knn/index/query/ResultUtil.java
Labels: enhancement

#2155 KNNIterators should support with and without filters
  CHANGELOG.md
  src/main/java/org/opensearch/knn/index/query/ExactSearcher.java
  src/main/java/org/opensearch/knn/index/query/iterators/ByteVectorIdsKNNIterator.java
  src/main/java/org/opensearch/knn/index/query/iterators/KNNIterator.java
  src/main/java/org/opensearch/knn/index/query/iterators/NestedByteVectorIdsKNNIterator.java
  src/main/java/org/opensearch/knn/index/query/iterators/NestedVectorIdsKNNIterator.java
  src/main/java/org/opensearch/knn/index/query/iterators/VectorIdsKNNIterator.java
  src/test/java/org/opensearch/knn/index/query/filtered/FilteredIdsKNNByteIteratorTests.java
  src/test/java/org/opensearch/knn/index/query/filtered/FilteredIdsKNNIteratorTests.java
  src/test/java/org/opensearch/knn/index/query/iterators/ByteVectorIdsKNNIteratorTests.java
  src/test/java/org/opensearch/knn/index/query/iterators/NestedByteVectorIdsKNNIteratorTests.java
  src/test/java/org/opensearch/knn/index/query/iterators/NestedVectorIdsKNNIteratorTests.java
  src/test/java/org/opensearch/knn/index/query/iterators/VectorIdsKNNIteratorTests.java
Labels: backport 2.x
