Repository opensearch-project/k-NN, pull requests merged in 2024-06, with the labels that each got.

#1738 Add 2.15.0 release notes
  CHANGELOG.md
  release-notes/opensearch-knn.release-notes-2.15.0.0.md
Labels: backport 2.x, skip-changelog

#1722 Block delete model requests if an index uses the model
  release-notes/opensearch-knn.release-notes-2.15.0.0.md
  src/main/java/org/opensearch/knn/common/KNNConstants.java
  src/main/java/org/opensearch/knn/common/exception/DeleteModelException.java
  src/main/java/org/opensearch/knn/indices/ModelDao.java
  src/main/java/org/opensearch/knn/plugin/transport/UpdateModelGraveyardTransportAction.java
  src/test/java/org/opensearch/knn/KNNSingleNodeTestCase.java
  src/test/java/org/opensearch/knn/index/FaissIT.java
  src/test/java/org/opensearch/knn/indices/ModelDaoTests.java
  src/test/java/org/opensearch/knn/plugin/transport/UpdateModelGraveyardTransportActionTests.java
  src/test/java/org/opensearch/knn/recall/RecallTestsIT.java
Labels: backport 2.x, skip-changelog, v2.15.0

#1750 Bump jinja2 from 2.11.3 to 3.1.3
  benchmarks/osb/requirements.txt
Labels: backport 2.x, skip-changelog, backport 2.15

#1732 Introduces query parameter ef_search for NMSLIB
  jni/CMakeLists.txt
  jni/cmake/init-nmslib.cmake
  jni/include/commons.h
  jni/include/nmslib_wrapper.h
  jni/include/org_opensearch_knn_jni_NmslibService.h
  jni/patches/nmslib/0002-Adds-ability-to-pass-ef-parameter-in-the-query-for-h.patch
  jni/src/commons.cpp
  jni/src/faiss_wrapper.cpp
  jni/src/nmslib_wrapper.cpp
  jni/src/org_opensearch_knn_jni_NmslibService.cpp
  jni/tests/commons_test.cpp
  jni/tests/nmslib_wrapper_test.cpp
  jni/tests/nmslib_wrapper_unit_test.cpp
  src/main/java/org/opensearch/knn/index/util/Nmslib.java
  src/main/java/org/opensearch/knn/jni/JNIService.java
  src/main/java/org/opensearch/knn/jni/NmslibService.java
  src/test/java/org/opensearch/knn/index/NmslibIT.java
  src/test/java/org/opensearch/knn/index/query/KNNQueryBuilderTests.java
Labels: skip-changelog

#1748 Adds ef_search support for Lucene kNN queries
  src/main/java/org/opensearch/knn/index/query/KNNQueryFactory.java
  src/main/java/org/opensearch/knn/index/query/parser/MethodParametersParser.java
  src/main/java/org/opensearch/knn/index/util/Lucene.java
  src/test/java/org/opensearch/knn/index/LuceneEngineIT.java
  src/test/java/org/opensearch/knn/index/query/KNNQueryBuilderTests.java
  src/test/java/org/opensearch/knn/index/query/KNNQueryFactoryTests.java
  src/testFixtures/java/org/opensearch/knn/KNNRestTestCase.java
Labels: skip-changelog

#1754 Support ef_search parameter in radial search Faiss engine
  jni/include/faiss_wrapper.h
  jni/include/org_opensearch_knn_jni_FaissService.h
  jni/src/faiss_wrapper.cpp
  jni/src/org_opensearch_knn_jni_FaissService.cpp
  jni/tests/faiss_wrapper_test.cpp
  jni/tests/faiss_wrapper_unit_test.cpp
  src/main/java/org/opensearch/knn/index/query/KNNQuery.java
  src/main/java/org/opensearch/knn/index/query/KNNQueryBuilder.java
  src/main/java/org/opensearch/knn/index/query/KNNWeight.java
  src/main/java/org/opensearch/knn/index/query/RNNQueryFactory.java
  src/main/java/org/opensearch/knn/jni/FaissService.java
  src/main/java/org/opensearch/knn/jni/JNIService.java
  src/test/java/org/opensearch/knn/index/FaissIT.java
  src/test/java/org/opensearch/knn/index/query/KNNQueryBuilderTests.java
  src/test/java/org/opensearch/knn/index/query/KNNWeightTests.java
  src/test/java/org/opensearch/knn/index/query/RNNQueryFactoryTests.java
Labels: Features, feature branch, skip-changelog

#1757 Optimize logic and tests for blocking model deletion when in use
  src/main/java/org/opensearch/knn/plugin/transport/UpdateModelGraveyardTransportAction.java
  src/test/java/org/opensearch/knn/KNNSingleNodeTestCase.java
  src/test/java/org/opensearch/knn/indices/ModelDaoTests.java
  src/test/java/org/opensearch/knn/plugin/transport/UpdateModelGraveyardTransportActionTests.java
Labels: backport 2.x, skip-changelog, backport 2.15

#1758 Adds Nprobe as a method parameter in knn query
  jni/src/faiss_wrapper.cpp
  jni/tests/faiss_wrapper_unit_test.cpp
  src/main/java/org/opensearch/knn/index/query/KNNQueryBuilder.java
  src/main/java/org/opensearch/knn/index/query/parser/MethodParametersParser.java
  src/main/java/org/opensearch/knn/index/query/request/MethodParameter.java
  src/main/java/org/opensearch/knn/index/util/DefaultIVFContext.java
  src/main/java/org/opensearch/knn/index/util/Faiss.java
  src/test/java/org/opensearch/knn/index/FaissIT.java
  src/test/java/org/opensearch/knn/index/LuceneEngineIT.java
  src/test/java/org/opensearch/knn/index/query/KNNQueryBuilderTests.java
  src/testFixtures/java/org/opensearch/knn/KNNRestTestCase.java
Labels: feature branch, skip-changelog

#1747 Add jni interface to use a binary hnsw index with faiss
  jni/CMakeLists.txt
  jni/include/commons.h
  jni/include/faiss_index_service.h
  jni/include/faiss_methods.h
  jni/include/faiss_wrapper.h
  jni/include/jni_util.h
  jni/include/org_opensearch_knn_jni_FaissService.h
  jni/include/org_opensearch_knn_jni_JNICommons.h
  jni/src/commons.cpp
  jni/src/faiss_index_service.cpp
  jni/src/faiss_methods.cpp
  jni/src/faiss_wrapper.cpp
  jni/src/jni_util.cpp
  jni/src/org_opensearch_knn_jni_FaissService.cpp
  jni/src/org_opensearch_knn_jni_JNICommons.cpp
  jni/tests/faiss_index_service_test.cpp
  jni/tests/faiss_wrapper_test.cpp
  jni/tests/mocks/faiss_index_mock.h
  jni/tests/mocks/faiss_index_service_mock.h
  jni/tests/mocks/faiss_methods_mock.h
  jni/tests/test_util.cpp
  jni/tests/test_util.h
  src/main/java/org/opensearch/knn/index/IndexUtil.java
  src/main/java/org/opensearch/knn/index/KNNIndexShard.java
  src/main/java/org/opensearch/knn/index/query/KNNWeight.java
  src/main/java/org/opensearch/knn/index/util/FieldInfoExtractor.java
  src/main/java/org/opensearch/knn/jni/FaissService.java
  src/main/java/org/opensearch/knn/jni/JNICommons.java
  src/main/java/org/opensearch/knn/jni/JNIService.java
  src/test/java/org/opensearch/knn/index/IndexUtilTests.java
  src/test/java/org/opensearch/knn/index/KNNIndexShardTests.java
  src/test/java/org/opensearch/knn/index/query/KNNWeightTests.java
  src/test/java/org/opensearch/knn/index/util/FieldInfoExtractorTests.java
  src/test/java/org/opensearch/knn/jni/JNIServiceTests.java
  src/testFixtures/java/org/opensearch/knn/TestUtils.java
Labels: skip-changelog

#1776 Fix memory leak on test code
  jni/tests/faiss_wrapper_test.cpp
Labels: skip-changelog
