Repository opensearch-project/k-NN, pull requests merged in 2024-11, with the labels that each got.

#2244 Added 'j' option to use multiple cpus to build JNI library.
  scripts/build.sh
Labels: backport 2.x, skip-changelog

#2254 Fix backport branch deletion on merge
  .github/workflows/delete_backport_branch.yml
Labels: skip-changelog

#2221 Update default engine to FAISS
  qa/restart-upgrade/src/test/java/org/opensearch/knn/bwc/IndexingIT.java
  release-notes/opensearch-knn.release-notes-2.18.0.0.md
  src/main/java/org/opensearch/knn/index/engine/EngineResolver.java
  src/main/java/org/opensearch/knn/index/engine/KNNEngine.java
  src/main/java/org/opensearch/knn/index/mapper/KNNVectorFieldMapper.java
  src/main/java/org/opensearch/knn/index/query/KNNWeight.java
  src/test/java/org/opensearch/knn/KNNSingleNodeTestCase.java
  src/test/java/org/opensearch/knn/index/KNNIndexShardTests.java
  src/test/java/org/opensearch/knn/index/NmslibIT.java
  src/test/java/org/opensearch/knn/index/VectorDataTypeIT.java
  src/test/java/org/opensearch/knn/index/codec/KNN80Codec/KNN80DocValuesConsumerTests.java
  src/test/java/org/opensearch/knn/index/codec/KNNCodecTestCase.java
  src/test/java/org/opensearch/knn/index/engine/EngineResolverTests.java
  src/test/java/org/opensearch/knn/index/engine/KNNEngineTests.java
  src/test/java/org/opensearch/knn/index/mapper/KNNVectorFieldMapperTests.java
  src/test/java/org/opensearch/knn/index/query/KNNWeightTests.java
  src/test/java/org/opensearch/knn/jni/JNIServiceTests.java
  src/test/java/org/opensearch/knn/plugin/transport/GetModelResponseTests.java
  src/test/java/org/opensearch/knn/plugin/transport/TrainingModelRequestTests.java
Labels: backport 2.x, skip-changelog

#2260 Fixing the BWC and rolling upgrade test after 2.18 release
  .github/workflows/backwards_compatibility_tests_workflow.yml
Labels: Maintenance, skip-changelog

#2259 Bump up C++ version in JNI from c++11 to c++17.
  CHANGELOG.md
  jni/CMakeLists.txt
  src/test/java/org/opensearch/knn/index/memory/NativeMemoryCacheManagerTests.java
Labels: Infrastructure, backport 2.x

#2279 Upgrade bytebuddy and objenesis version to match OpenSearch core and, update github ci runner for macos
  .github/workflows/CI.yml
  CHANGELOG.md
  build.gradle
Labels: backport 2.x

#2278 Added null checks for fieldInfo in ExactSearcher to avoid NPE while running exact search for segments with no vector field
  CHANGELOG.md
  src/main/java/org/opensearch/knn/common/FieldInfoExtractor.java
  src/main/java/org/opensearch/knn/index/KNNVectorDVLeafFieldData.java
  src/main/java/org/opensearch/knn/index/query/ExactSearcher.java
  src/main/java/org/opensearch/knn/index/query/KNNWeight.java
  src/test/java/org/opensearch/knn/common/FieldInfoExtractorTests.java
  src/test/java/org/opensearch/knn/index/query/ExactSearcherTests.java
Labels: Bug Fixes, backport 2.x

#2287 Add simple IntelliJ debugger config
  .idea/runConfigurations/Debug_OpenSearch.xml
  DEVELOPER_GUIDE.md
Labels: backport 2.x, skip-changelog
