Repository opensearch-project/k-NN, pull requests merged in 2024-02, with the labels that each got.

#1444 Pass correct value on IDSelectorBitmap initialization
  CHANGELOG.md
  jni/src/faiss_wrapper.cpp
  jni/tests/faiss_wrapper_test.cpp
Labels: Bug Fixes, backport 2.x, v2.12.0

#1451 Update Build Script to build libraries with SIMD
  scripts/build.sh
Labels: backport 2.x, skip-changelog

#1450 Update spotless and eclipse dependencies
  CHANGELOG.md
  build.gradle
Labels: backport 2.x, v2.12.0

#1455 [Backport 2.x] Set Default value for SIMD_ENABLED in CMakeList
  jni/CMakeLists.txt
Labels: skip-changelog

#1457 Change eclipse version to latest
  build.gradle
Labels: backport 2.x, skip-changelog, v2.12.0

#1460 Revert "Update Build Script to build libraries with SIMD"
  scripts/build.sh
Labels: skip-changelog

#1463 Add release notes for 2.12.0 release
  CHANGELOG.md
  release-notes/opensearch-knn.release-notes-2.12.0.0.md
Labels: backport 2.x, v2.12.0, backport 2.12

#1442 Disable warning checks in k-NN test case
  src/test/java/org/opensearch/knn/KNNTestCase.java
  src/test/java/org/opensearch/knn/index/KNNSettingsTests.java
Labels: backport 2.x, skip-changelog

#1474 Use valid data for sqfp16 test
  src/test/java/org/opensearch/knn/jni/JNIServiceTests.java
Labels: backport 2.x, skip-changelog

#1477 Fix a bug on sqfp16 test
  src/test/java/org/opensearch/knn/jni/JNIServiceTests.java
Labels: backport 2.x, skip-changelog

#1485 Remove unnecessary dataset
  benchmarks/perf-tool/dataset/sift-128-euclidean-nested.hdf5
Labels: backport 2.x, skip-changelog

#1490 Fix FieldInfo Parameters Mismatch
  CHANGELOG.md
  src/test/java/org/opensearch/knn/index/codec/KNNCodecTestUtil.java
Labels: backport 2.x

#1488 Update performance test with nested field
  benchmarks/perf-tool/add-parent-doc-id-to-dataset.py
  benchmarks/perf-tool/okpt/test/steps/steps.py
  benchmarks/perf-tool/release-configs/faiss-hnsw/nested/simple/index.json
  benchmarks/perf-tool/release-configs/lucene-hnsw/nested/simple/index.json
  benchmarks/perf-tool/release-configs/lucene-hnsw/nested/simple/simple-nested-test.yml
  benchmarks/perf-tool/release-configs/run_all_tests.sh
Labels: backport 2.x, skip-changelog
