Repository opensearch-project/k-NN, pull requests merged in 2024-07, with the labels that each got.

#1782 Adds integration test for invalid method parameters
  src/main/java/org/opensearch/knn/index/util/DefaultIVFContext.java
  src/test/java/org/opensearch/knn/index/query/InvalidSearchQueryIT.java
  src/test/java/org/opensearch/knn/index/query/parser/MethodParametersParserTests.java
Labels: feature branch, skip-changelog

#1778 Add jni interface to use a binary hnsw index with faiss
  jni/CMakeLists.txt
  jni/include/commons.h
  jni/include/faiss_index_service.h
  jni/include/faiss_methods.h
  jni/include/faiss_wrapper.h
  jni/include/jni_util.h
  jni/include/org_opensearch_knn_jni_FaissService.h
  jni/include/org_opensearch_knn_jni_JNICommons.h
  jni/src/commons.cpp
  jni/src/faiss_index_service.cpp
  jni/src/faiss_methods.cpp
  jni/src/faiss_wrapper.cpp
  jni/src/jni_util.cpp
  jni/src/org_opensearch_knn_jni_FaissService.cpp
  jni/src/org_opensearch_knn_jni_JNICommons.cpp
  jni/tests/faiss_index_service_test.cpp
  jni/tests/faiss_wrapper_test.cpp
  jni/tests/faiss_wrapper_unit_test.cpp
  jni/tests/mocks/faiss_index_mock.h
  jni/tests/mocks/faiss_index_service_mock.h
  jni/tests/mocks/faiss_methods_mock.h
  jni/tests/test_util.cpp
  jni/tests/test_util.h
  src/main/java/org/opensearch/knn/index/IndexUtil.java
  src/main/java/org/opensearch/knn/index/KNNIndexShard.java
  src/main/java/org/opensearch/knn/index/query/KNNWeight.java
  src/main/java/org/opensearch/knn/index/util/FieldInfoExtractor.java
  src/main/java/org/opensearch/knn/jni/FaissService.java
  src/main/java/org/opensearch/knn/jni/JNICommons.java
  src/main/java/org/opensearch/knn/jni/JNIService.java
  src/test/java/org/opensearch/knn/index/IndexUtilTests.java
  src/test/java/org/opensearch/knn/index/KNNIndexShardTests.java
  src/test/java/org/opensearch/knn/index/query/KNNWeightTests.java
  src/test/java/org/opensearch/knn/index/util/FieldInfoExtractorTests.java
  src/test/java/org/opensearch/knn/jni/JNIServiceTests.java
  src/testFixtures/java/org/opensearch/knn/TestUtils.java
Labels: backport 2.x, skip-changelog

#1795 Fix linux build CI error due to action runner env upgrade node 20
  .github/workflows/CI.yml
  .github/workflows/test_security.yml
Labels: Infrastructure, backport 2.x, skip-changelog

#1804 Fixing the arithmetic to find the number of vectors to stream from java to jni layer.
  CHANGELOG.md
  src/main/java/org/opensearch/knn/index/codec/util/KNNCodecUtil.java
Labels: Bug Fixes, backport 2.x

#1812 Setting locale to Locale.ROOT while using String.format to ensure that UTs doesn't fail when validating the exception messages
  src/main/java/org/opensearch/knn/index/query/KNNQueryBuilder.java
Labels: backport 2.x, skip-changelog, flaky-test

#1813 [Backport 2.x] Setting locale to Locale.ROOT while using String.format to ensure that UTs doesn't fail when validating the exception messages (#1812)
  src/main/java/org/opensearch/knn/index/query/KNNQueryBuilder.java
Labels: skip-changelog

#1811 Fixing BWC tests as 2.15.0 is already launched
  .github/workflows/backwards_compatibility_tests_workflow.yml
Labels: skip-changelog

#1819 Avoid conflict of mock class name to fix test failure
  jni/tests/faiss_wrapper_unit_test.cpp
Labels: skip-changelog

#1820 Release memory properly for an array type
  CHANGELOG.md
  jni/patches/faiss/0001-Custom-patch-to-support-multi-vector.patch
Labels: backport 2.x

#1802 [BUG] FIX Same Suffix Cause Recall Drop to zero
  CHANGELOG.md
  src/main/java/org/opensearch/knn/index/query/KNNWeight.java
  src/test/java/org/opensearch/knn/index/query/KNNWeightTests.java
Labels: Bug Fixes, backport 2.x

#1825 Switch from byte stream to byte ref for serde
  CHANGELOG.md
  src/main/java/org/opensearch/knn/index/VectorDataType.java
  src/main/java/org/opensearch/knn/index/codec/transfer/VectorTransfer.java
  src/main/java/org/opensearch/knn/index/codec/transfer/VectorTransferByte.java
  src/main/java/org/opensearch/knn/index/codec/transfer/VectorTransferFloat.java
  src/main/java/org/opensearch/knn/index/codec/util/KNNCodecUtil.java
  src/main/java/org/opensearch/knn/index/codec/util/KNNVectorAsArraySerializer.java
  src/main/java/org/opensearch/knn/index/codec/util/KNNVectorAsCollectionOfFloatsSerializer.java
  src/main/java/org/opensearch/knn/index/codec/util/KNNVectorSerializer.java
  src/main/java/org/opensearch/knn/index/codec/util/KNNVectorSerializerFactory.java
  src/main/java/org/opensearch/knn/index/query/filtered/FilteredIdsKNNIterator.java
  src/test/java/org/opensearch/knn/index/codec/transfer/VectorTransferByteTests.java
  src/test/java/org/opensearch/knn/index/codec/transfer/VectorTransferFloatTests.java
  src/test/java/org/opensearch/knn/index/codec/util/KNNCodecUtilTests.java
  src/test/java/org/opensearch/knn/index/codec/util/KNNVectorSerializerTests.java
  src/test/java/org/opensearch/knn/index/mapper/KNNVectorFieldMapperUtilTests.java
Labels: Enhancements, backport 2.x

#1808 Fixed LeafReaders casting errors to SegmentReaders when segment repli…
  CHANGELOG.md
  src/main/java/org/opensearch/knn/index/KNNIndexShard.java
  src/main/java/org/opensearch/knn/index/query/KNNWeight.java
  src/test/java/org/opensearch/knn/index/SegmentReplicationIT.java
  src/testFixtures/java/org/opensearch/knn/KNNRestTestCase.java
Labels: Bug Fixes, backport 2.x

#1826 Add script scoring support for knn field with binary data type
  CHANGELOG.md
  src/main/java/org/opensearch/knn/index/VectorDataType.java
  src/main/java/org/opensearch/knn/index/mapper/KNNVectorFieldMapperUtil.java
  src/main/java/org/opensearch/knn/plugin/script/KNNScoringSpace.java
  src/main/java/org/opensearch/knn/plugin/script/KNNScoringSpaceUtil.java
  src/main/java/org/opensearch/knn/plugin/script/KNNScoringUtil.java
  src/test/java/org/opensearch/knn/index/VectorDataTypeTests.java
  src/test/java/org/opensearch/knn/index/mapper/KNNVectorFieldMapperUtilTests.java
  src/test/java/org/opensearch/knn/plugin/script/KNNScoringSpaceTests.java
  src/test/java/org/opensearch/knn/plugin/script/KNNScoringSpaceUtilTests.java
Labels: backport 2.x

#1833 Apply custom patch only once by comparing the patch-id of the last commit
  .github/workflows/CI.yml
  .github/workflows/test_security.yml
  CHANGELOG.md
  jni/cmake/init-faiss.cmake
  jni/cmake/init-nmslib.cmake
Labels: Infrastructure, backport 2.x

#1801 Update PULL_REQUEST_TEMPLATE to include an API spec change in the checklist.
  .github/PULL_REQUEST_TEMPLATE.md
Labels: skip-changelog

#1839 Add painless script support for hamming with binary vector data type
  CHANGELOG.md
  src/main/java/org/opensearch/knn/plugin/script/KNNScoringUtil.java
  src/main/resources/org/opensearch/knn/plugin/script/knn_allowlist.txt
  src/test/java/org/opensearch/knn/common/KNNValidationUtilTests.java
  src/test/java/org/opensearch/knn/plugin/script/KNNScoringUtilTests.java
Labels: backport 2.x

#1851 Fix build failure due to patch conflict
  .gitignore
  build.gradle
  jni/cmake/init-faiss.cmake
  jni/cmake/init-nmslib.cmake
  scripts/build.sh
Labels: backport 2.x, skip-changelog

#1850 Fix few bugs on binary index with Faiss HNSW
  src/main/java/org/opensearch/knn/index/IndexUtil.java
  src/main/java/org/opensearch/knn/index/KNNMethod.java
  src/main/java/org/opensearch/knn/index/KNNSettings.java
  src/main/java/org/opensearch/knn/index/mapper/KNNVectorFieldMapper.java
  src/main/java/org/opensearch/knn/index/mapper/LegacyFieldMapper.java
  src/main/java/org/opensearch/knn/index/query/KNNQueryBuilder.java
  src/main/java/org/opensearch/knn/index/query/KNNWeight.java
  src/test/java/org/opensearch/knn/index/IndexUtilTests.java
  src/test/java/org/opensearch/knn/index/mapper/KNNVectorFieldMapperTests.java
  src/test/java/org/opensearch/knn/index/query/KNNQueryBuilderTests.java
  src/test/java/org/opensearch/knn/index/query/KNNWeightTests.java
Labels: backport 2.x, skip-changelog

#1854 Switch space type name from hammingbit to hamming for binary index
  jni/include/jni_util.h
  jni/src/faiss_wrapper.cpp
  jni/src/jni_util.cpp
  jni/tests/faiss_wrapper_test.cpp
  src/main/java/org/opensearch/knn/index/KNNSettings.java
  src/main/java/org/opensearch/knn/index/SpaceType.java
  src/main/java/org/opensearch/knn/index/util/Faiss.java
  src/main/java/org/opensearch/knn/plugin/script/KNNScoringSpace.java
  src/main/java/org/opensearch/knn/plugin/script/KNNScoringSpaceFactory.java
  src/test/java/org/opensearch/knn/index/SpaceTypeTests.java
  src/test/java/org/opensearch/knn/index/codec/KNN80Codec/KNN80DocValuesConsumerTests.java
  src/test/java/org/opensearch/knn/index/mapper/KNNVectorFieldMapperTests.java
  src/test/java/org/opensearch/knn/index/mapper/MethodFieldMapperTests.java
  src/test/java/org/opensearch/knn/index/memory/NativeMemoryAllocationTests.java
  src/test/java/org/opensearch/knn/index/memory/NativeMemoryLoadStrategyTests.java
  src/test/java/org/opensearch/knn/index/query/KNNQueryBuilderTests.java
  src/test/java/org/opensearch/knn/index/query/KNNWeightTests.java
  src/test/java/org/opensearch/knn/index/query/filtered/FilteredIdsKNNByteIteratorTests.java
  src/test/java/org/opensearch/knn/index/query/filtered/NestedFilteredIdsKNNByteIteratorTests.java
  src/test/java/org/opensearch/knn/jni/JNIServiceTests.java
  src/test/java/org/opensearch/knn/plugin/script/KNNScoringSpaceFactoryTests.java
  src/test/java/org/opensearch/knn/plugin/script/KNNScoringSpaceTests.java
  src/test/java/org/opensearch/knn/plugin/script/KNNScriptScoringIT.java
Labels: backport 2.x, skip-changelog

#1868 Block PQ support when data type is binary format
  src/main/java/org/opensearch/knn/index/IndexUtil.java
  src/main/java/org/opensearch/knn/plugin/transport/TrainingModelRequest.java
  src/main/java/org/opensearch/knn/training/VectorReader.java
  src/test/java/org/opensearch/knn/index/FaissIT.java
  src/test/java/org/opensearch/knn/index/IndexUtilTests.java
  src/test/java/org/opensearch/knn/plugin/transport/TrainingModelRequestTests.java
Labels: backport 2.x, skip-changelog, v2.16.0, backport 2.16

#1848 Add support for Lucene inbuilt Scalar Quantizer
  release-notes/opensearch-knn.release-notes-2.16.0.0.md
  src/main/java/org/opensearch/knn/common/KNNConstants.java
  src/main/java/org/opensearch/knn/index/Parameter.java
  src/main/java/org/opensearch/knn/index/codec/BasePerFieldKnnVectorsFormat.java
  src/main/java/org/opensearch/knn/index/codec/KNN920Codec/KNN920PerFieldKnnVectorsFormat.java
  src/main/java/org/opensearch/knn/index/codec/KNN940Codec/KNN940PerFieldKnnVectorsFormat.java
  src/main/java/org/opensearch/knn/index/codec/KNN950Codec/KNN950PerFieldKnnVectorsFormat.java
  src/main/java/org/opensearch/knn/index/codec/KNN990Codec/KNN990PerFieldKnnVectorsFormat.java
  src/main/java/org/opensearch/knn/index/codec/params/KNNScalarQuantizedVectorsFormatParams.java
  src/main/java/org/opensearch/knn/index/codec/params/KNNVectorsFormatParams.java
  src/main/java/org/opensearch/knn/index/mapper/KNNVectorFieldMapper.java
  src/main/java/org/opensearch/knn/index/util/Lucene.java
  src/test/java/org/opensearch/knn/index/LuceneEngineIT.java
  src/test/java/org/opensearch/knn/index/ParameterTests.java
  src/test/java/org/opensearch/knn/index/codec/params/KNNScalarQuantizedVectorsFormatParamsTests.java
  src/test/java/org/opensearch/knn/index/codec/params/KNNVectorsFormatParamsTests.java
Labels: Features, backport 2.x, skip-changelog, v2.16.0, backport 2.16

#1855 Introduce NativeEngineKNNVectorsFormat as a KNNVectorsFormat for Native engines
  src/main/java/org/opensearch/knn/index/codec/KNN990Codec/NativeEngineFieldVectorsWriter.java
  src/main/java/org/opensearch/knn/index/codec/KNN990Codec/NativeEngines990KnnVectorsFormat.java
  src/main/java/org/opensearch/knn/index/codec/KNN990Codec/NativeEngines990KnnVectorsReader.java
  src/main/java/org/opensearch/knn/index/codec/KNN990Codec/NativeEngines990KnnVectorsWriter.java
  src/main/java/org/opensearch/knn/index/codec/KNN990Codec/UnitTestCodec.java
  src/main/resources/META-INF/services/org.apache.lucene.codecs.Codec
  src/main/resources/META-INF/services/org.apache.lucene.codecs.KnnVectorsFormat
  src/test/java/org/opensearch/knn/index/codec/KNN990Codec/NativeEngineFieldVectorsWriterTests.java
  src/test/java/org/opensearch/knn/index/codec/KNN990Codec/NativeEngines990KnnVectorsFormatTests.java
Labels: Enhancements, skip-changelog

#1874 Corrected search logic for scenario with non-existent fields in filter
  CHANGELOG.md
  src/main/java/org/opensearch/knn/index/query/KNNQueryBuilder.java
  src/test/java/org/opensearch/knn/index/FaissIT.java
  src/test/java/org/opensearch/knn/index/LuceneEngineIT.java
  src/test/java/org/opensearch/knn/index/query/KNNQueryBuilderTests.java
Labels: Bug Fixes, backport 2.x

#1880 Apply https://github.com/opensearch-project/k-NN/pull/1804
  src/main/java/org/opensearch/knn/index/codec/transfer/VectorTransferByte.java
  src/main/java/org/opensearch/knn/index/codec/transfer/VectorTransferFloat.java
  src/test/java/org/opensearch/knn/index/codec/transfer/VectorTransferByteTests.java
  src/test/java/org/opensearch/knn/index/codec/transfer/VectorTransferFloatTests.java
Labels: bug, skip-changelog

#1824 Refactor parsing logic of the Query Builder (second try)
  .idea/copyright/SPDX_ALv2.xml
  CHANGELOG.md
  micro-benchmarks/src/main/java/org/opensearch/knn/QueryParsingBenchmarks.java
  src/main/java/org/opensearch/knn/index/query/KNNQueryBuilder.java
  src/main/java/org/opensearch/knn/index/query/parser/KNNQueryBuilderParser.java
  src/main/java/org/opensearch/knn/plugin/KNNPlugin.java
  src/test/java/org/opensearch/knn/index/VectorDataTypeIT.java
  src/test/java/org/opensearch/knn/index/query/KNNQueryBuilderTests.java
  src/test/java/org/opensearch/knn/index/query/parser/KNNQueryParserTests.java
Labels: Refactoring, backport 2.x

#1896 Remove additionalSettings in KNN plugin
  src/main/java/org/opensearch/knn/plugin/KNNPlugin.java
Labels: v3.0.0, skip-changelog

#1899 Fix idea xml file
  .idea/copyright/SPDX_ALv2.xml
  src/main/java/org/opensearch/knn/index/query/parser/KNNQueryBuilderParser.java
  src/test/java/org/opensearch/knn/index/query/parser/KNNQueryBuilderParserTests.java
Labels: backport 2.x, skip-changelog

#1888 Add triage.md based off of security
  TRIAGING.md
Labels: backport 2.x, skip-changelog

#1901 Limit tests run based on changed path
  .github/workflows/CI.yml
  .github/workflows/backwards_compatibility_tests_workflow.yml
  .github/workflows/test_security.yml
Labels: Infrastructure, backport 2.x, skip-changelog

#1876 Adding integration tests for binary index
  src/main/java/org/opensearch/knn/index/query/KNNQueryBuilder.java
  src/main/java/org/opensearch/knn/plugin/script/KNNScoringSpace.java
  src/test/java/org/opensearch/knn/integ/BinaryIndexIT.java
  src/test/java/org/opensearch/knn/integ/BinaryIndexInvalidMappingIT.java
  src/test/java/org/opensearch/knn/integ/FilteredSearchBinaryIT.java
  src/test/java/org/opensearch/knn/integ/KNNScriptScoringIT.java
  src/test/java/org/opensearch/knn/integ/NestedSearchBinaryIT.java
  src/test/java/org/opensearch/knn/integ/NestedSearchIT.java
  src/test/java/org/opensearch/knn/integ/PainlessScriptIT.java
  src/test/java/org/opensearch/knn/plugin/script/KNNScoringSpaceTests.java
  src/test/resources/data/README.md
  src/test/resources/data/test_queries_binary_100x128.csv
  src/test/resources/data/test_vectors_binary_1000x128.json
  src/testFixtures/java/org/opensearch/knn/KNNJsonIndexMappingsBuilder.java
  src/testFixtures/java/org/opensearch/knn/KNNJsonQueryBuilder.java
  src/testFixtures/java/org/opensearch/knn/KNNRestTestCase.java
  src/testFixtures/java/org/opensearch/knn/TestUtils.java
Labels: backport 2.x, skip-changelog
