Repository opensearch-project/k-NN, pull requests merged in 2024-08, with the labels that each got.

#1897 Introduce KNNVectorValues interface to iterate on different types of Vector values during indexing and search
  CHANGELOG.md
  src/main/java/org/opensearch/knn/index/codec/KNN990Codec/NativeEngineFieldVectorsWriter.java
  src/main/java/org/opensearch/knn/index/codec/util/KNNCodecUtil.java
  src/main/java/org/opensearch/knn/index/vectorvalues/KNNBinaryVectorValues.java
  src/main/java/org/opensearch/knn/index/vectorvalues/KNNByteVectorValues.java
  src/main/java/org/opensearch/knn/index/vectorvalues/KNNFloatVectorValues.java
  src/main/java/org/opensearch/knn/index/vectorvalues/KNNVectorValues.java
  src/main/java/org/opensearch/knn/index/vectorvalues/KNNVectorValuesFactory.java
  src/main/java/org/opensearch/knn/index/vectorvalues/KNNVectorValuesIterator.java
  src/main/java/org/opensearch/knn/index/vectorvalues/VectorValueExtractorStrategy.java
  src/test/java/org/opensearch/knn/index/codec/KNN80Codec/KNN80BinaryDocValuesTests.java
  src/test/java/org/opensearch/knn/index/codec/KNN80Codec/KNN80DocValuesConsumerTests.java
  src/test/java/org/opensearch/knn/index/codec/KNN990Codec/NativeEngineFieldVectorsWriterTests.java
  src/test/java/org/opensearch/knn/index/codec/KNNCodecTestUtil.java
  src/test/java/org/opensearch/knn/index/codec/util/BinaryDocValuesSubTests.java
  src/test/java/org/opensearch/knn/index/vectorvalues/KNNVectorValuesFactoryTests.java
  src/test/java/org/opensearch/knn/index/vectorvalues/KNNVectorValuesTests.java
  src/test/java/org/opensearch/knn/index/vectorvalues/TestVectorValues.java
  src/test/java/org/opensearch/knn/index/vectorvalues/VectorValueExtractorStrategyTests.java
Labels: Enhancements, Features, Refactoring, memory-reduction

#1919 [Backport 2.x] Introduced KNNVectorValues interface to iterate on different types of Vector values during indexing and search (#1897)
  CHANGELOG.md
  src/main/java/org/opensearch/knn/index/codec/KNN990Codec/NativeEngineFieldVectorsWriter.java
  src/main/java/org/opensearch/knn/index/codec/util/KNNCodecUtil.java
  src/main/java/org/opensearch/knn/index/vectorvalues/KNNBinaryVectorValues.java
  src/main/java/org/opensearch/knn/index/vectorvalues/KNNByteVectorValues.java
  src/main/java/org/opensearch/knn/index/vectorvalues/KNNFloatVectorValues.java
  src/main/java/org/opensearch/knn/index/vectorvalues/KNNVectorValues.java
  src/main/java/org/opensearch/knn/index/vectorvalues/KNNVectorValuesFactory.java
  src/main/java/org/opensearch/knn/index/vectorvalues/KNNVectorValuesIterator.java
  src/main/java/org/opensearch/knn/index/vectorvalues/VectorValueExtractorStrategy.java
  src/test/java/org/opensearch/knn/index/codec/KNN80Codec/KNN80BinaryDocValuesTests.java
  src/test/java/org/opensearch/knn/index/codec/KNN80Codec/KNN80DocValuesConsumerTests.java
  src/test/java/org/opensearch/knn/index/codec/KNN990Codec/NativeEngineFieldVectorsWriterTests.java
  src/test/java/org/opensearch/knn/index/codec/KNNCodecTestUtil.java
  src/test/java/org/opensearch/knn/index/codec/util/BinaryDocValuesSubTests.java
  src/test/java/org/opensearch/knn/index/vectorvalues/KNNVectorValuesFactoryTests.java
  src/test/java/org/opensearch/knn/index/vectorvalues/KNNVectorValuesTests.java
  src/test/java/org/opensearch/knn/index/vectorvalues/TestVectorValues.java
  src/test/java/org/opensearch/knn/index/vectorvalues/VectorValueExtractorStrategyTests.java
Labels: Enhancements, Refactoring, memory-reduction, v2.17.0

#1920 Refactor method structure and definitions
  CHANGELOG.md
  qa/restart-upgrade/src/test/java/org/opensearch/knn/bwc/FaissSQIT.java
  src/main/java/org/opensearch/knn/index/engine/AbstractKNNLibrary.java
  src/main/java/org/opensearch/knn/index/engine/AbstractKNNMethod.java
  src/main/java/org/opensearch/knn/index/engine/Encoder.java
  src/main/java/org/opensearch/knn/index/engine/JVMLibrary.java
  src/main/java/org/opensearch/knn/index/engine/KNNEngine.java
  src/main/java/org/opensearch/knn/index/engine/KNNLibrary.java
  src/main/java/org/opensearch/knn/index/engine/KNNMethod.java
  src/main/java/org/opensearch/knn/index/engine/NativeLibrary.java
  src/main/java/org/opensearch/knn/index/engine/faiss/Faiss.java
  src/main/java/org/opensearch/knn/index/engine/faiss/FaissFlatEncoder.java
  src/main/java/org/opensearch/knn/index/engine/faiss/FaissHNSWMethod.java
  src/main/java/org/opensearch/knn/index/engine/faiss/FaissHNSWPQEncoder.java
  src/main/java/org/opensearch/knn/index/engine/faiss/FaissIVFMethod.java
  src/main/java/org/opensearch/knn/index/engine/faiss/FaissIVFPQEncoder.java
  src/main/java/org/opensearch/knn/index/engine/faiss/FaissSQEncoder.java
  src/main/java/org/opensearch/knn/index/engine/faiss/MethodAsMapBuilder.java
  src/main/java/org/opensearch/knn/index/engine/lucene/Lucene.java
  src/main/java/org/opensearch/knn/index/engine/lucene/LuceneHNSWMethod.java
  src/main/java/org/opensearch/knn/index/engine/lucene/LuceneSQEncoder.java
  src/main/java/org/opensearch/knn/index/engine/nmslib/Nmslib.java
  src/main/java/org/opensearch/knn/index/engine/nmslib/NmslibHNSWMethod.java
  src/test/java/org/opensearch/knn/KNNTestCase.java
  src/test/java/org/opensearch/knn/index/FaissHNSWFlatE2EIT.java
  src/test/java/org/opensearch/knn/index/FaissIT.java
  src/test/java/org/opensearch/knn/index/LuceneEngineIT.java
  src/test/java/org/opensearch/knn/index/NmslibIT.java
  src/test/java/org/opensearch/knn/index/OpenSearchIT.java
  src/test/java/org/opensearch/knn/index/engine/AbstractKNNLibraryTests.java
  src/test/java/org/opensearch/knn/index/engine/AbstractKNNMethodTests.java
  src/test/java/org/opensearch/knn/index/engine/NativeLibraryTests.java
  src/test/java/org/opensearch/knn/index/engine/faiss/FaissTests.java
  src/test/java/org/opensearch/knn/index/engine/lucene/LuceneTests.java
  src/test/java/org/opensearch/knn/jni/JNIServiceTests.java
  src/test/java/org/opensearch/knn/plugin/stats/suppliers/LibraryInitializedSupplierTests.java
Labels: Refactoring, backport 2.x

#1921 Removed JDK 11 and 17 version from CI runs
  .github/workflows/CI.yml
  .github/workflows/backwards_compatibility_tests_workflow.yml
  .github/workflows/maven-publish.yml
  CHANGELOG.md
Labels: Maintenance

#1924 Fix a flaky unit test:testMultiFieldsKnnIndex, which was failing due to inconsistent merge behaviors
  CHANGELOG.md
  src/test/java/org/opensearch/knn/index/codec/KNNCodecTestCase.java
Labels: Infrastructure, backport 2.x, flaky-test, v2.17.0

#1925 Generalize lib interface to return context objects
  CHANGELOG.md
  src/main/java/org/opensearch/knn/index/engine/AbstractKNNLibrary.java
  src/main/java/org/opensearch/knn/index/engine/AbstractKNNMethod.java
  src/main/java/org/opensearch/knn/index/engine/DefaultHnswSearchContext.java
  src/main/java/org/opensearch/knn/index/engine/DefaultIVFSearchContext.java
  src/main/java/org/opensearch/knn/index/engine/EngineSpecificMethodContext.java
  src/main/java/org/opensearch/knn/index/engine/KNNEngine.java
  src/main/java/org/opensearch/knn/index/engine/KNNLibrary.java
  src/main/java/org/opensearch/knn/index/engine/KNNLibraryIndexingContext.java
  src/main/java/org/opensearch/knn/index/engine/KNNLibraryIndexingContextImpl.java
  src/main/java/org/opensearch/knn/index/engine/KNNLibrarySearchContext.java
  src/main/java/org/opensearch/knn/index/engine/KNNMethod.java
  src/main/java/org/opensearch/knn/index/engine/faiss/FaissHNSWMethod.java
  src/main/java/org/opensearch/knn/index/engine/faiss/FaissIVFMethod.java
  src/main/java/org/opensearch/knn/index/engine/lucene/LuceneHNSWMethod.java
  src/main/java/org/opensearch/knn/index/engine/lucene/LuceneHNSWSearchContext.java
  src/main/java/org/opensearch/knn/index/engine/nmslib/NmslibHNSWMethod.java
  src/main/java/org/opensearch/knn/index/mapper/MethodFieldMapper.java
  src/main/java/org/opensearch/knn/index/query/KNNQueryBuilder.java
  src/main/java/org/opensearch/knn/training/TrainingJob.java
  src/test/java/org/opensearch/knn/KNNTestCase.java
  src/test/java/org/opensearch/knn/index/codec/KNN80Codec/KNN80DocValuesConsumerTests.java
  src/test/java/org/opensearch/knn/index/engine/AbstractKNNLibraryTests.java
  src/test/java/org/opensearch/knn/index/engine/AbstractKNNMethodTests.java
  src/test/java/org/opensearch/knn/index/engine/faiss/FaissTests.java
  src/test/java/org/opensearch/knn/jni/JNIServiceTests.java
  src/test/java/org/opensearch/knn/plugin/stats/suppliers/LibraryInitializedSupplierTests.java
Labels: Refactoring, backport 2.x

#1840 Iterative Vector Insertion
  CHANGELOG.md
  jni/include/faiss_index_service.h
  jni/include/faiss_wrapper.h
  jni/include/org_opensearch_knn_jni_FaissService.h
  jni/src/faiss_index_service.cpp
  jni/src/faiss_wrapper.cpp
  jni/src/org_opensearch_knn_jni_FaissService.cpp
  jni/tests/commons_test.cpp
  jni/tests/faiss_index_service_test.cpp
  jni/tests/faiss_wrapper_test.cpp
  jni/tests/mocks/faiss_index_service_mock.h
  src/main/java/org/opensearch/knn/index/codec/KNN80Codec/KNN80DocValuesConsumer.java
  src/main/java/org/opensearch/knn/index/codec/nativeindex/NativeIndexWriter.java
  src/main/java/org/opensearch/knn/index/codec/nativeindex/NativeIndexWriterScratch.java
  src/main/java/org/opensearch/knn/index/codec/nativeindex/NativeIndexWriterScratchIter.java
  src/main/java/org/opensearch/knn/index/codec/nativeindex/NativeIndexWriterTemplate.java
  src/main/java/org/opensearch/knn/index/codec/transfer/VectorTransfer.java
  src/main/java/org/opensearch/knn/index/codec/transfer/VectorTransferByte.java
  src/main/java/org/opensearch/knn/index/codec/transfer/VectorTransferFloat.java
  src/main/java/org/opensearch/knn/index/codec/util/KNNCodecUtil.java
  src/main/java/org/opensearch/knn/jni/FaissService.java
  src/main/java/org/opensearch/knn/jni/JNIService.java
  src/test/java/org/opensearch/knn/index/codec/KNNCodecTestUtil.java
  src/test/java/org/opensearch/knn/index/codec/util/KNNCodecUtilTests.java
  src/test/java/org/opensearch/knn/index/memory/NativeMemoryAllocationTests.java
  src/test/java/org/opensearch/knn/index/memory/NativeMemoryLoadStrategyTests.java
  src/test/java/org/opensearch/knn/jni/JNIServiceTests.java
  src/testFixtures/java/org/opensearch/knn/TestUtils.java
Labels: Enhancements, v2.17.0

#1917 Add script_fields context to KNNAllowlist
  CHANGELOG.md
  src/main/java/org/opensearch/knn/plugin/script/KNNAllowlistExtension.java
  src/test/java/org/opensearch/knn/integ/PainlessScriptFieldsIT.java
  src/test/java/org/opensearch/knn/integ/PainlessScriptHelper.java
  src/test/java/org/opensearch/knn/integ/PainlessScriptScoreIT.java
  src/testFixtures/java/org/opensearch/knn/KNNRestTestCase.java
Labels: backport 2.x

#1931 Refactor KNNVectorFieldType from KNNVectorFieldMapper to a separate class for better readability.
  CHANGELOG.md
  src/main/java/org/opensearch/knn/index/codec/BasePerFieldKnnVectorsFormat.java
  src/main/java/org/opensearch/knn/index/mapper/KNNVectorFieldMapper.java
  src/main/java/org/opensearch/knn/index/mapper/KNNVectorFieldMapperUtil.java
  src/main/java/org/opensearch/knn/index/mapper/KNNVectorFieldType.java
  src/main/java/org/opensearch/knn/index/query/KNNQueryBuilder.java
  src/main/java/org/opensearch/knn/plugin/script/KNNScoringSpace.java
  src/main/java/org/opensearch/knn/plugin/script/KNNScoringSpaceUtil.java
  src/test/java/org/opensearch/knn/index/codec/KNNCodecTestCase.java
  src/test/java/org/opensearch/knn/index/mapper/KNNVectorFieldMapperTests.java
  src/test/java/org/opensearch/knn/index/mapper/KNNVectorFieldMapperUtilTests.java
  src/test/java/org/opensearch/knn/index/mapper/MethodFieldMapperTests.java
  src/test/java/org/opensearch/knn/index/query/KNNQueryBuilderTests.java
  src/test/java/org/opensearch/knn/integ/KNNScriptScoringIT.java
  src/test/java/org/opensearch/knn/plugin/script/KNNScoringSpaceFactoryTests.java
  src/test/java/org/opensearch/knn/plugin/script/KNNScoringSpaceTests.java
  src/test/java/org/opensearch/knn/plugin/script/KNNScoringSpaceUtilTests.java
Labels: Refactoring, backport 2.x, v2.17.0

#1844 Fix graph merge stats size calculation
  CHANGELOG.md
  src/main/java/org/opensearch/knn/index/codec/KNN80Codec/KNN80DocValuesConsumer.java
  src/main/java/org/opensearch/knn/index/codec/util/KNNCodecUtil.java
  src/test/java/org/opensearch/knn/index/codec/util/KNNCodecUtilTests.java
Labels: backport 2.x, v2.17.0

#1940 Update CI for 2.17
  .github/workflows/backwards_compatibility_tests_workflow.yml
Labels: Maintenance, skip-changelog

#1933 Index Initialization Alloc Method
  CHANGELOG.md
  jni/include/faiss_index_service.h
  jni/src/faiss_index_service.cpp
Labels: Enhancements, indexing-improvements, v2.17.0

#1941 [Backport 2.x] Fix graph merge stats size calculation
  CHANGELOG.md
  src/main/java/org/opensearch/knn/index/codec/KNN80Codec/KNN80DocValuesConsumer.java
  src/main/java/org/opensearch/knn/index/codec/util/KNNCodecUtil.java
  src/test/java/org/opensearch/knn/index/codec/util/KNNCodecUtilTests.java
Labels: v2.17.0

#1939 Refactor Around Mapper and Mapping
  CHANGELOG.md
  qa/restart-upgrade/src/test/java/org/opensearch/knn/bwc/IndexingIT.java
  src/main/java/org/opensearch/knn/index/codec/BasePerFieldKnnVectorsFormat.java
  src/main/java/org/opensearch/knn/index/codec/KNN80Codec/KNN80DocValuesConsumer.java
  src/main/java/org/opensearch/knn/index/engine/KNNMethodContext.java
  src/main/java/org/opensearch/knn/index/mapper/FlatVectorFieldMapper.java
  src/main/java/org/opensearch/knn/index/mapper/KNNMappingConfig.java
  src/main/java/org/opensearch/knn/index/mapper/KNNVectorFieldMapper.java
  src/main/java/org/opensearch/knn/index/mapper/KNNVectorFieldMapperUtil.java
  src/main/java/org/opensearch/knn/index/mapper/KNNVectorFieldType.java
  src/main/java/org/opensearch/knn/index/mapper/LegacyFieldMapper.java
  src/main/java/org/opensearch/knn/index/mapper/LuceneFieldMapper.java
  src/main/java/org/opensearch/knn/index/mapper/MethodFieldMapper.java
  src/main/java/org/opensearch/knn/index/mapper/ModelFieldMapper.java
  src/main/java/org/opensearch/knn/index/mapper/PerDimensionProcessor.java
  src/main/java/org/opensearch/knn/index/mapper/PerDimensionValidator.java
  src/main/java/org/opensearch/knn/index/mapper/SpaceVectorValidator.java
  src/main/java/org/opensearch/knn/index/mapper/VectorValidator.java
  src/main/java/org/opensearch/knn/index/query/KNNQueryBuilder.java
  src/main/java/org/opensearch/knn/plugin/KNNPlugin.java
  src/test/java/org/opensearch/knn/KNNTestCase.java
  src/test/java/org/opensearch/knn/index/KNNMethodContextTests.java
  src/test/java/org/opensearch/knn/index/codec/KNN80Codec/KNN80DocValuesConsumerTests.java
  src/test/java/org/opensearch/knn/index/codec/KNNCodecTestCase.java
  src/test/java/org/opensearch/knn/index/mapper/KNNVectorFieldMapperTests.java
  src/test/java/org/opensearch/knn/index/mapper/KNNVectorFieldMapperUtilTests.java
  src/test/java/org/opensearch/knn/index/mapper/MethodFieldMapperTests.java
  src/test/java/org/opensearch/knn/index/query/KNNQueryBuilderTests.java
  src/test/java/org/opensearch/knn/integ/KNNScriptScoringIT.java
  src/test/java/org/opensearch/knn/plugin/script/KNNScoringSpaceFactoryTests.java
  src/test/java/org/opensearch/knn/plugin/script/KNNScoringSpaceTests.java
  src/test/java/org/opensearch/knn/plugin/script/KNNScoringSpaceUtilTests.java
  src/test/java/org/opensearch/knn/plugin/transport/TrainingJobRouterTransportActionTests.java
  src/test/java/org/opensearch/knn/plugin/transport/TrainingModelRequestTests.java
Labels: Refactoring, backport 2.x

#1945 Integrate Lucene Vector field with native engines to use KNNVectorFormat during segment creation
  CHANGELOG.md
  src/main/java/org/opensearch/knn/index/KNNSettings.java
  src/main/java/org/opensearch/knn/index/mapper/FlatVectorFieldMapper.java
  src/main/java/org/opensearch/knn/index/mapper/KNNVectorFieldMapper.java
  src/main/java/org/opensearch/knn/index/mapper/KNNVectorFieldMapperUtil.java
  src/main/java/org/opensearch/knn/index/mapper/LuceneFieldMapper.java
  src/main/java/org/opensearch/knn/index/mapper/MethodFieldMapper.java
  src/main/java/org/opensearch/knn/index/mapper/ModelFieldMapper.java
  src/test/java/org/opensearch/knn/index/codec/KNNCodecTestCase.java
  src/test/java/org/opensearch/knn/index/mapper/KNNVectorFieldMapperTests.java
  src/test/java/org/opensearch/knn/index/mapper/KNNVectorFieldMapperUtilTests.java
Labels: Features, backport 2.x, memory-reduction

#1936 Disallow invalid characters for physical file name to be included within vector field name.
  CHANGELOG.md
  src/main/java/org/opensearch/knn/index/mapper/KNNVectorFieldMapper.java
  src/test/java/org/opensearch/knn/index/mapper/KNNVectorFieldMapperTests.java
Labels: backport 2.x

#1929 Quantization Framework Implementation with 1bit and MultiBit Binary Quantizer
  CHANGELOG.md
  src/main/java/org/opensearch/knn/quantization/enums/ScalarQuantizationType.java
  src/main/java/org/opensearch/knn/quantization/factory/QuantizerFactory.java
  src/main/java/org/opensearch/knn/quantization/factory/QuantizerRegistrar.java
  src/main/java/org/opensearch/knn/quantization/factory/QuantizerRegistry.java
  src/main/java/org/opensearch/knn/quantization/models/quantizationOutput/BinaryQuantizationOutput.java
  src/main/java/org/opensearch/knn/quantization/models/quantizationOutput/QuantizationOutput.java
  src/main/java/org/opensearch/knn/quantization/models/quantizationParams/QuantizationParams.java
  src/main/java/org/opensearch/knn/quantization/models/quantizationParams/ScalarQuantizationParams.java
  src/main/java/org/opensearch/knn/quantization/models/quantizationState/DefaultQuantizationState.java
  src/main/java/org/opensearch/knn/quantization/models/quantizationState/MultiBitScalarQuantizationState.java
  src/main/java/org/opensearch/knn/quantization/models/quantizationState/OneBitScalarQuantizationState.java
  src/main/java/org/opensearch/knn/quantization/models/quantizationState/QuantizationState.java
  src/main/java/org/opensearch/knn/quantization/models/quantizationState/QuantizationStateSerializer.java
  src/main/java/org/opensearch/knn/quantization/models/requests/TrainingRequest.java
  src/main/java/org/opensearch/knn/quantization/quantizer/BitPacker.java
  src/main/java/org/opensearch/knn/quantization/quantizer/MultiBitScalarQuantizer.java
  src/main/java/org/opensearch/knn/quantization/quantizer/OneBitScalarQuantizer.java
  src/main/java/org/opensearch/knn/quantization/quantizer/Quantizer.java
  src/main/java/org/opensearch/knn/quantization/quantizer/QuantizerHelper.java
  src/main/java/org/opensearch/knn/quantization/sampler/ReservoirSampler.java
  src/main/java/org/opensearch/knn/quantization/sampler/Sampler.java
  src/main/java/org/opensearch/knn/quantization/sampler/SamplerType.java
  src/main/java/org/opensearch/knn/quantization/sampler/SamplingFactory.java
  src/test/java/org/opensearch/knn/quantization/enums/ScalarQuantizationTypeTests.java
  src/test/java/org/opensearch/knn/quantization/factory/QuantizerFactoryTests.java
  src/test/java/org/opensearch/knn/quantization/factory/QuantizerRegistryTests.java
  src/test/java/org/opensearch/knn/quantization/quantizationState/QuantizationStateSerializerTests.java
  src/test/java/org/opensearch/knn/quantization/quantizationState/QuantizationStateTests.java
  src/test/java/org/opensearch/knn/quantization/quantizer/MultiBitScalarQuantizerTests.java
  src/test/java/org/opensearch/knn/quantization/quantizer/OneBitScalarQuantizerTests.java
  src/test/java/org/opensearch/knn/quantization/sampler/ReservoirSamplerTests.java
  src/test/java/org/opensearch/knn/quantization/sampler/SamplingFactoryTests.java
Labels: backport 2.x, v2.17.0

#1952 Integrate KNNVectorValues with vector ANN Search flow
  CHANGELOG.md
  src/main/java/org/opensearch/knn/common/FieldInfoExtractor.java
  src/main/java/org/opensearch/knn/index/query/KNNWeight.java
  src/main/java/org/opensearch/knn/index/query/filtered/FilteredIdsKNNByteIterator.java
  src/main/java/org/opensearch/knn/index/query/filtered/FilteredIdsKNNIterator.java
  src/main/java/org/opensearch/knn/index/query/filtered/NestedFilteredIdsKNNByteIterator.java
  src/main/java/org/opensearch/knn/index/query/filtered/NestedFilteredIdsKNNIterator.java
  src/main/java/org/opensearch/knn/index/vectorvalues/KNNVectorValuesFactory.java
  src/main/java/org/opensearch/knn/indices/ModelUtil.java
  src/test/java/org/opensearch/knn/common/FieldInfoExtractorTests.java
  src/test/java/org/opensearch/knn/index/query/KNNWeightTests.java
  src/test/java/org/opensearch/knn/index/query/filtered/FilteredIdsKNNByteIteratorTests.java
  src/test/java/org/opensearch/knn/index/query/filtered/FilteredIdsKNNIteratorTests.java
  src/test/java/org/opensearch/knn/index/query/filtered/NestedFilteredIdsKNNByteIteratorTests.java
  src/test/java/org/opensearch/knn/index/query/filtered/NestedFilteredIdsKNNIteratorTests.java
  src/test/java/org/opensearch/knn/index/vectorvalues/KNNVectorValuesFactoryTests.java
  src/test/java/org/opensearch/knn/indices/ModelUtilTests.java
Labels: Features, backport 2.x, v2.17.0

#1959 BackPort Java Doc Fix with Code Improvements
  src/main/java/org/opensearch/knn/quantization/factory/QuantizerFactory.java
  src/main/java/org/opensearch/knn/quantization/factory/QuantizerRegistry.java
  src/main/java/org/opensearch/knn/quantization/models/quantizationParams/ScalarQuantizationParams.java
  src/main/java/org/opensearch/knn/quantization/models/quantizationState/MultiBitScalarQuantizationState.java
  src/test/java/org/opensearch/knn/quantization/factory/QuantizerFactoryTests.java
  src/test/java/org/opensearch/knn/quantization/factory/QuantizerRegistryTests.java
Labels: backport 2.x, skip-changelog

#1958 [Backport 2.x] Integrate KNNVectorValues with vector ANN Search flow #1952
  CHANGELOG.md
  src/main/java/org/opensearch/knn/common/FieldInfoExtractor.java
  src/main/java/org/opensearch/knn/index/query/KNNWeight.java
  src/main/java/org/opensearch/knn/index/query/filtered/FilteredIdsKNNByteIterator.java
  src/main/java/org/opensearch/knn/index/query/filtered/FilteredIdsKNNIterator.java
  src/main/java/org/opensearch/knn/index/query/filtered/NestedFilteredIdsKNNByteIterator.java
  src/main/java/org/opensearch/knn/index/query/filtered/NestedFilteredIdsKNNIterator.java
  src/main/java/org/opensearch/knn/index/vectorvalues/KNNVectorValuesFactory.java
  src/main/java/org/opensearch/knn/indices/ModelUtil.java
  src/test/java/org/opensearch/knn/common/FieldInfoExtractorTests.java
  src/test/java/org/opensearch/knn/index/query/KNNWeightTests.java
  src/test/java/org/opensearch/knn/index/query/filtered/FilteredIdsKNNByteIteratorTests.java
  src/test/java/org/opensearch/knn/index/query/filtered/FilteredIdsKNNIteratorTests.java
  src/test/java/org/opensearch/knn/index/query/filtered/NestedFilteredIdsKNNByteIteratorTests.java
  src/test/java/org/opensearch/knn/index/query/filtered/NestedFilteredIdsKNNIteratorTests.java
  src/test/java/org/opensearch/knn/index/vectorvalues/KNNVectorValuesFactoryTests.java
  src/test/java/org/opensearch/knn/indices/ModelUtilTests.java
Labels: v2.17.0

#1967 Quantization Framework Code Structure Improvement
  src/main/java/org/opensearch/knn/quantization/models/quantizationOutput/BinaryQuantizationOutput.java
  src/main/java/org/opensearch/knn/quantization/models/quantizationOutput/QuantizationOutput.java
  src/main/java/org/opensearch/knn/quantization/quantizer/MultiBitScalarQuantizer.java
  src/main/java/org/opensearch/knn/quantization/quantizer/OneBitScalarQuantizer.java
  src/test/java/org/opensearch/knn/quantization/quantizer/MultiBitScalarQuantizerTests.java
  src/test/java/org/opensearch/knn/quantization/quantizer/OneBitScalarQuantizerTests.java
Labels: backport 2.x, skip-changelog

#1969 Adds rescore parameter to KNNQuery
  src/main/java/org/opensearch/knn/index/query/KNNQueryBuilder.java
  src/main/java/org/opensearch/knn/index/query/parser/KNNQueryBuilderParser.java
  src/main/java/org/opensearch/knn/index/query/parser/RescoreParser.java
  src/main/java/org/opensearch/knn/index/query/rescore/RescoreContext.java
  src/main/java/org/opensearch/knn/index/util/IndexUtil.java
  src/test/java/org/opensearch/knn/index/query/KNNQueryBuilderInvalidParamsTests.java
  src/test/java/org/opensearch/knn/index/query/KNNQueryBuilderTests.java
  src/test/java/org/opensearch/knn/index/query/KNNQueryBuilderValidParamsTests.java
  src/test/java/org/opensearch/knn/index/query/parser/KNNQueryBuilderParserTests.java
  src/test/java/org/opensearch/knn/index/query/parser/RescoreParserTests.java
  src/test/java/org/opensearch/knn/index/query/parser/RescoreValidationTests.java
  src/test/java/org/opensearch/knn/integ/QueryParseIT.java
Labels: backport 2.x, skip-changelog

#1975 Fixes bwc change for rescore query
  src/main/java/org/opensearch/knn/index/util/IndexUtil.java
Labels: skip-changelog

#1982 [Backport 2.x] Block a vector field to have invalid characters for a physical file n…
  src/main/java/org/opensearch/knn/index/mapper/KNNVectorFieldMapper.java
  src/test/java/org/opensearch/knn/index/mapper/KNNVectorFieldMapperTests.java
Labels: skip-changelog

#1980 Fixing the dimension for the vector when using Lucene field in ModelFieldMapper
  src/main/java/org/opensearch/knn/index/mapper/ModelFieldMapper.java
  src/test/java/org/opensearch/knn/KNNTestCase.java
  src/test/java/org/opensearch/knn/common/FieldInfoExtractorTests.java
  src/test/java/org/opensearch/knn/index/mapper/KNNVectorFieldMapperTests.java
  src/test/java/org/opensearch/knn/index/query/KNNWeightTests.java
Labels: backport 2.x, skip-changelog, v2.17.0

#1987 Disables rewrite code path to debug latency issues
  src/main/java/org/opensearch/knn/common/featureflags/KNNFeatureFlags.java
Labels: backport 2.x, skip-changelog

#1960 Add quantization state cache
  CHANGELOG.md
  src/main/java/org/opensearch/knn/index/KNNSettings.java
  src/main/java/org/opensearch/knn/quantization/models/quantizationState/QuantizationStateCache.java
  src/test/java/org/opensearch/knn/quantization/models/quantizationState/QuantizationStateCacheTests.java
Labels: backport 2.x, v2.17.0

#1950 Integrates FAISS iterative builds with NativeEngines990KnnVectorsFormat
  CHANGELOG.md
  jni/include/commons.h
  jni/include/faiss_index_service.h
  jni/include/faiss_wrapper.h
  jni/include/org_opensearch_knn_jni_FaissService.h
  jni/include/org_opensearch_knn_jni_JNICommons.h
  jni/src/commons.cpp
  jni/src/faiss_index_service.cpp
  jni/src/faiss_wrapper.cpp
  jni/src/org_opensearch_knn_jni_FaissService.cpp
  jni/src/org_opensearch_knn_jni_JNICommons.cpp
  jni/tests/commons_test.cpp
  jni/tests/faiss_index_service_test.cpp
  jni/tests/faiss_wrapper_test.cpp
  jni/tests/mocks/faiss_index_service_mock.h
  src/main/java/org/opensearch/knn/common/FieldInfoExtractor.java
  src/main/java/org/opensearch/knn/common/KNNVectorUtil.java
  src/main/java/org/opensearch/knn/index/codec/BasePerFieldKnnVectorsFormat.java
  src/main/java/org/opensearch/knn/index/codec/KNN80Codec/KNN80DocValuesConsumer.java
  src/main/java/org/opensearch/knn/index/codec/KNN990Codec/NativeEngineFieldVectorsWriter.java
  src/main/java/org/opensearch/knn/index/codec/KNN990Codec/NativeEngines990KnnVectorsWriter.java
  src/main/java/org/opensearch/knn/index/codec/nativeindex/DefaultIndexBuildStrategy.java
  src/main/java/org/opensearch/knn/index/codec/nativeindex/MemOptimizedNativeIndexBuildStrategy.java
  src/main/java/org/opensearch/knn/index/codec/nativeindex/NativeIndexBuildStrategy.java
  src/main/java/org/opensearch/knn/index/codec/nativeindex/NativeIndexWriter.java
  src/main/java/org/opensearch/knn/index/codec/nativeindex/model/BuildIndexParams.java
  src/main/java/org/opensearch/knn/index/codec/transfer/OffHeapBinaryVectorTransfer.java
  src/main/java/org/opensearch/knn/index/codec/transfer/OffHeapByteVectorTransfer.java
  src/main/java/org/opensearch/knn/index/codec/transfer/OffHeapFloatVectorTransfer.java
  src/main/java/org/opensearch/knn/index/codec/transfer/OffHeapVectorTransfer.java
  src/main/java/org/opensearch/knn/index/codec/transfer/OffHeapVectorTransferFactory.java
  src/main/java/org/opensearch/knn/index/codec/transfer/VectorTransfer.java
  src/main/java/org/opensearch/knn/index/codec/transfer/VectorTransferByte.java
  src/main/java/org/opensearch/knn/index/codec/transfer/VectorTransferFloat.java
  src/main/java/org/opensearch/knn/index/codec/util/KNNCodecUtil.java
  src/main/java/org/opensearch/knn/index/vectorvalues/KNNBinaryVectorValues.java
  src/main/java/org/opensearch/knn/index/vectorvalues/KNNByteVectorValues.java
  src/main/java/org/opensearch/knn/index/vectorvalues/KNNFloatVectorValues.java
  src/main/java/org/opensearch/knn/index/vectorvalues/KNNVectorValues.java
  src/main/java/org/opensearch/knn/indices/ModelUtil.java
  src/main/java/org/opensearch/knn/jni/FaissService.java
  src/main/java/org/opensearch/knn/jni/JNICommons.java
  src/main/java/org/opensearch/knn/jni/JNIService.java
  src/test/java/org/opensearch/knn/common/FieldInfoExtractorTests.java
  src/test/java/org/opensearch/knn/common/KNNVectorUtilTests.java
  src/test/java/org/opensearch/knn/index/codec/KNN80Codec/KNN80DocValuesConsumerTests.java
  src/test/java/org/opensearch/knn/index/codec/KNN990Codec/NativeEngines990KnnVectorsFormatTests.java
  src/test/java/org/opensearch/knn/index/codec/nativeindex/DefaultIndexBuildStrategyTests.java
  src/test/java/org/opensearch/knn/index/codec/nativeindex/MemOptimizedNativeIndexBuildStrategyTests.java
  src/test/java/org/opensearch/knn/index/codec/transfer/OffHeapVectorTransferFactoryTests.java
  src/test/java/org/opensearch/knn/index/codec/transfer/OffHeapVectorTransferTests.java
  src/test/java/org/opensearch/knn/index/codec/transfer/VectorTransferByteTests.java
  src/test/java/org/opensearch/knn/index/codec/transfer/VectorTransferFloatTests.java
  src/test/java/org/opensearch/knn/index/codec/util/KNNCodecUtilTests.java
  src/test/java/org/opensearch/knn/index/memory/NativeMemoryAllocationTests.java
  src/test/java/org/opensearch/knn/index/memory/NativeMemoryLoadStrategyTests.java
  src/test/java/org/opensearch/knn/index/vectorvalues/KNNVectorValuesTests.java
  src/test/java/org/opensearch/knn/jni/JNIServiceTests.java
  src/testFixtures/java/org/opensearch/knn/TestUtils.java
Labels: backport 2.x, v2.17.0

#1994 Add support for qframework from interface
  src/main/java/org/opensearch/knn/common/FieldInfoExtractor.java
  src/main/java/org/opensearch/knn/common/KNNConstants.java
  src/main/java/org/opensearch/knn/index/engine/AbstractKNNMethod.java
  src/main/java/org/opensearch/knn/index/engine/KNNLibraryIndexingContext.java
  src/main/java/org/opensearch/knn/index/engine/KNNLibraryIndexingContextImpl.java
  src/main/java/org/opensearch/knn/index/engine/MethodComponent.java
  src/main/java/org/opensearch/knn/index/engine/faiss/AbstractFaissMethod.java
  src/main/java/org/opensearch/knn/index/engine/faiss/FaissFlatEncoder.java
  src/main/java/org/opensearch/knn/index/engine/faiss/FaissHNSWMethod.java
  src/main/java/org/opensearch/knn/index/engine/faiss/FaissHNSWPQEncoder.java
  src/main/java/org/opensearch/knn/index/engine/faiss/FaissIVFMethod.java
  src/main/java/org/opensearch/knn/index/engine/faiss/FaissIVFPQEncoder.java
  src/main/java/org/opensearch/knn/index/engine/faiss/FaissSQEncoder.java
  src/main/java/org/opensearch/knn/index/engine/faiss/MethodAsMapBuilder.java
  src/main/java/org/opensearch/knn/index/engine/faiss/QFrameBitEncoder.java
  src/main/java/org/opensearch/knn/index/engine/qframe/QuantizationConfig.java
  src/main/java/org/opensearch/knn/index/engine/qframe/QuantizationConfigParser.java
  src/main/java/org/opensearch/knn/index/mapper/MethodFieldMapper.java
  src/main/java/org/opensearch/knn/index/mapper/ModelFieldMapper.java
  src/main/java/org/opensearch/knn/index/query/KNNWeight.java
  src/test/java/org/opensearch/knn/index/engine/AbstractKNNLibraryTests.java
  src/test/java/org/opensearch/knn/index/engine/AbstractKNNMethodTests.java
  src/test/java/org/opensearch/knn/index/engine/MethodComponentTests.java
  src/test/java/org/opensearch/knn/index/engine/faiss/FaissTests.java
  src/test/java/org/opensearch/knn/index/engine/faiss/QFrameBitEncoderTests.java
  src/test/java/org/opensearch/knn/index/engine/qframe/QuantizationConfigParserTests.java
  src/test/java/org/opensearch/knn/integ/QFrameworkIT.java
Labels: backport 2.x, skip-changelog

#1998 [Backport 2.x] Add support for qframework from interface
  src/main/java/org/opensearch/knn/common/FieldInfoExtractor.java
  src/main/java/org/opensearch/knn/common/KNNConstants.java
  src/main/java/org/opensearch/knn/index/engine/AbstractKNNMethod.java
  src/main/java/org/opensearch/knn/index/engine/KNNLibraryIndexingContext.java
  src/main/java/org/opensearch/knn/index/engine/KNNLibraryIndexingContextImpl.java
  src/main/java/org/opensearch/knn/index/engine/MethodComponent.java
  src/main/java/org/opensearch/knn/index/engine/faiss/AbstractFaissMethod.java
  src/main/java/org/opensearch/knn/index/engine/faiss/FaissFlatEncoder.java
  src/main/java/org/opensearch/knn/index/engine/faiss/FaissHNSWMethod.java
  src/main/java/org/opensearch/knn/index/engine/faiss/FaissHNSWPQEncoder.java
  src/main/java/org/opensearch/knn/index/engine/faiss/FaissIVFMethod.java
  src/main/java/org/opensearch/knn/index/engine/faiss/FaissIVFPQEncoder.java
  src/main/java/org/opensearch/knn/index/engine/faiss/FaissSQEncoder.java
  src/main/java/org/opensearch/knn/index/engine/faiss/MethodAsMapBuilder.java
  src/main/java/org/opensearch/knn/index/engine/faiss/QFrameBitEncoder.java
  src/main/java/org/opensearch/knn/index/engine/qframe/QuantizationConfig.java
  src/main/java/org/opensearch/knn/index/engine/qframe/QuantizationConfigParser.java
  src/main/java/org/opensearch/knn/index/mapper/MethodFieldMapper.java
  src/main/java/org/opensearch/knn/index/mapper/ModelFieldMapper.java
  src/main/java/org/opensearch/knn/index/query/KNNWeight.java
  src/test/java/org/opensearch/knn/index/engine/AbstractKNNLibraryTests.java
  src/test/java/org/opensearch/knn/index/engine/AbstractKNNMethodTests.java
  src/test/java/org/opensearch/knn/index/engine/MethodComponentTests.java
  src/test/java/org/opensearch/knn/index/engine/faiss/FaissTests.java
  src/test/java/org/opensearch/knn/index/engine/faiss/QFrameBitEncoderTests.java
  src/test/java/org/opensearch/knn/index/engine/qframe/QuantizationConfigParserTests.java
  src/test/java/org/opensearch/knn/integ/QFrameworkIT.java
Labels: skip-changelog

#1999 Fix string for qframe parser key to not use String.format
  src/main/java/org/opensearch/knn/index/engine/qframe/QuantizationConfigParser.java
  src/test/java/org/opensearch/knn/index/engine/faiss/FaissTests.java
  src/test/java/org/opensearch/knn/index/engine/qframe/QuantizationConfigParserTests.java
Labels: backport 2.x, skip-changelog

#1984 k-NN query rescore support for native engines
  CHANGELOG.md
  src/main/java/org/opensearch/knn/common/FieldInfoExtractor.java
  src/main/java/org/opensearch/knn/index/query/BaseQueryFactory.java
  src/main/java/org/opensearch/knn/index/query/ExactSearcher.java
  src/main/java/org/opensearch/knn/index/query/KNNQuery.java
  src/main/java/org/opensearch/knn/index/query/KNNQueryBuilder.java
  src/main/java/org/opensearch/knn/index/query/KNNQueryFactory.java
  src/main/java/org/opensearch/knn/index/query/KNNWeight.java
  src/main/java/org/opensearch/knn/index/query/ResultUtil.java
  src/main/java/org/opensearch/knn/index/query/nativelib/NativeEngineKnnVectorQuery.java
  src/main/java/org/opensearch/knn/index/query/rescore/RescoreContext.java
  src/test/java/org/opensearch/knn/index/codec/KNNCodecTestCase.java
  src/test/java/org/opensearch/knn/index/query/KNNQueryFactoryTests.java
  src/test/java/org/opensearch/knn/index/query/KNNWeightTests.java
  src/test/java/org/opensearch/knn/index/query/ResultUtilTests.java
  src/test/java/org/opensearch/knn/index/query/nativelib/NativeEngineKNNVectorQueryTests.java
  src/test/java/org/opensearch/knn/index/query/rescore/RescoreContextTests.java
  src/test/java/org/opensearch/knn/integ/NestedSearchIT.java
Labels: Features, backport 2.x

#1823 Add HNSW changes to support Faiss byte vector
  CHANGELOG.md
  jni/include/commons.h
  jni/include/faiss_index_service.h
  jni/include/jni_util.h
  jni/include/org_opensearch_knn_jni_FaissService.h
  jni/include/org_opensearch_knn_jni_JNICommons.h
  jni/src/commons.cpp
  jni/src/faiss_index_service.cpp
  jni/src/jni_util.cpp
  jni/src/org_opensearch_knn_jni_FaissService.cpp
  jni/src/org_opensearch_knn_jni_JNICommons.cpp
  jni/tests/faiss_index_service_test.cpp
  jni/tests/test_util.cpp
  jni/tests/test_util.h
  src/main/java/org/opensearch/knn/common/KNNConstants.java
  src/main/java/org/opensearch/knn/index/codec/transfer/OffHeapBinaryVectorTransfer.java
  src/main/java/org/opensearch/knn/index/codec/transfer/OffHeapVectorTransferFactory.java
  src/main/java/org/opensearch/knn/index/engine/faiss/AbstractFaissMethod.java
  src/main/java/org/opensearch/knn/index/engine/faiss/FaissHNSWMethod.java
  src/main/java/org/opensearch/knn/index/engine/faiss/FaissIVFMethod.java
  src/main/java/org/opensearch/knn/index/mapper/KNNVectorFieldMapperUtil.java
  src/main/java/org/opensearch/knn/index/memory/NativeMemoryAllocation.java
  src/main/java/org/opensearch/knn/index/query/KNNQueryBuilder.java
  src/main/java/org/opensearch/knn/index/util/IndexUtil.java
  src/main/java/org/opensearch/knn/jni/FaissService.java
  src/main/java/org/opensearch/knn/jni/JNICommons.java
  src/main/java/org/opensearch/knn/jni/JNIService.java
  src/main/java/org/opensearch/knn/training/ByteTrainingDataConsumer.java
  src/test/java/org/opensearch/knn/index/VectorDataTypeIT.java
  src/test/java/org/opensearch/knn/index/codec/transfer/OffHeapVectorTransferFactoryTests.java
  src/test/java/org/opensearch/knn/index/engine/KNNMethodContextTests.java
  src/test/java/org/opensearch/knn/index/memory/NativeMemoryAllocationTests.java
  src/test/java/org/opensearch/knn/index/memory/NativeMemoryLoadStrategyTests.java
  src/test/java/org/opensearch/knn/index/query/KNNQueryBuilderTests.java
  src/testFixtures/java/org/opensearch/knn/TestUtils.java
Labels: Features, backport 2.x, v2.17.0

#2006 Parallelize make to reduce build time
  .github/workflows/CI.yml
  .github/workflows/test_security.yml
  CHANGELOG.md
  DEVELOPER_GUIDE.md
  build.gradle
Labels: Infrastructure, backport 2.x

#2010 Align dimensions to the nearest multiple of 8 in QuantizationState
  src/main/java/org/opensearch/knn/index/codec/KNN990Codec/NativeEngines990KnnVectorsWriter.java
  src/main/java/org/opensearch/knn/index/codec/nativeindex/NativeIndexWriter.java
  src/main/java/org/opensearch/knn/index/codec/nativeindex/QuantizationIndexUtils.java
  src/main/java/org/opensearch/knn/index/quantizationservice/KNNVectorQuantizationTrainingRequest.java
  src/main/java/org/opensearch/knn/index/quantizationservice/QuantizationService.java
  src/main/java/org/opensearch/knn/quantization/models/quantizationState/MultiBitScalarQuantizationState.java
  src/main/java/org/opensearch/knn/quantization/models/quantizationState/OneBitScalarQuantizationState.java
  src/test/java/org/opensearch/knn/index/codec/nativeindex/DefaultIndexBuildStrategyTests.java
  src/test/java/org/opensearch/knn/index/codec/nativeindex/MemOptimizedNativeIndexBuildStrategyTests.java
  src/test/java/org/opensearch/knn/index/codec/nativeindex/QuantizationIndexUtilsTests.java
  src/test/java/org/opensearch/knn/index/quantizationservice/QuantizationServiceTests.java
  src/test/java/org/opensearch/knn/quantization/quantizationState/QuantizationStateTests.java
Labels: skip-changelog
