Repository opensearch-project/k-NN, pull requests merged in 2024-12, with the labels that each got.

#2303 Fixing the CI actions failures due to AL2 with older glibc
  .github/workflows/CI.yml
  .github/workflows/test_security.yml
Labels: Infrastructure, Maintenance, backport 2.x, skip-changelog

#2290 Allow method parameter override for training based indices (solves issue #2246)
  CHANGELOG.md
  src/main/java/org/opensearch/knn/plugin/rest/RestTrainModelHandler.java
  src/test/java/org/opensearch/knn/integ/ModeAndCompressionIT.java
  src/test/java/org/opensearch/knn/plugin/action/RestTrainModelHandlerIT.java
Labels: backport 2.x

#2283 Add Support for Multi Values in innerHit for Nested k-NN Fields in Lucene and FAISS
  CHANGELOG.md
  build.gradle
  src/main/java/org/opensearch/knn/common/KNNConstants.java
  src/main/java/org/opensearch/knn/index/engine/KNNEngine.java
  src/main/java/org/opensearch/knn/index/query/BaseQueryFactory.java
  src/main/java/org/opensearch/knn/index/query/ExactSearcher.java
  src/main/java/org/opensearch/knn/index/query/KNNQuery.java
  src/main/java/org/opensearch/knn/index/query/KNNQueryBuilder.java
  src/main/java/org/opensearch/knn/index/query/KNNQueryFactory.java
  src/main/java/org/opensearch/knn/index/query/KNNWeight.java
  src/main/java/org/opensearch/knn/index/query/PerLeafResult.java
  src/main/java/org/opensearch/knn/index/query/ResultUtil.java
  src/main/java/org/opensearch/knn/index/query/common/DocAndScoreQuery.java
  src/main/java/org/opensearch/knn/index/query/common/QueryUtils.java
  src/main/java/org/opensearch/knn/index/query/iterators/BinaryVectorIdsKNNIterator.java
  src/main/java/org/opensearch/knn/index/query/iterators/ByteVectorIdsKNNIterator.java
  src/main/java/org/opensearch/knn/index/query/iterators/GroupedNestedDocIdSetIterator.java
  src/main/java/org/opensearch/knn/index/query/iterators/NestedBinaryVectorIdsKNNIterator.java
  src/main/java/org/opensearch/knn/index/query/iterators/NestedByteVectorIdsKNNIterator.java
  src/main/java/org/opensearch/knn/index/query/iterators/NestedVectorIdsKNNIterator.java
  src/main/java/org/opensearch/knn/index/query/iterators/VectorIdsKNNIterator.java
  src/main/java/org/opensearch/knn/index/query/lucenelib/ExpandNestedDocsQuery.java
  src/main/java/org/opensearch/knn/index/query/lucenelib/InternalNestedKnnByteVectoryQuery.java
  src/main/java/org/opensearch/knn/index/query/lucenelib/InternalNestedKnnFloatVectoryQuery.java
  src/main/java/org/opensearch/knn/index/query/lucenelib/InternalNestedKnnVectorQuery.java
  src/main/java/org/opensearch/knn/index/query/lucenelib/NestedKnnVectorQueryFactory.java
  src/main/java/org/opensearch/knn/index/query/nativelib/NativeEngineKnnVectorQuery.java
  src/main/java/org/opensearch/knn/index/query/parser/KNNQueryBuilderParser.java
  src/main/java/org/opensearch/knn/index/util/IndexUtil.java
  src/test/java/org/opensearch/knn/index/query/KNNQueryFactoryTests.java
  src/test/java/org/opensearch/knn/index/query/ResultUtilTests.java
  src/test/java/org/opensearch/knn/index/query/common/DocAndScoreQueryTests.java
  src/test/java/org/opensearch/knn/index/query/common/QueryUtilsTests.java
  src/test/java/org/opensearch/knn/index/query/iterators/BinaryVectorIdsKNNIteratorTests.java
  src/test/java/org/opensearch/knn/index/query/iterators/ByteVectorIdsKNNIteratorTests.java
  src/test/java/org/opensearch/knn/index/query/iterators/GroupedNestedDocIdSetIteratorTests.java
  src/test/java/org/opensearch/knn/index/query/iterators/NestedBinaryVectorIdsKNNIteratorTests.java
  src/test/java/org/opensearch/knn/index/query/iterators/NestedByteVectorIdsKNNIteratorTests.java
  src/test/java/org/opensearch/knn/index/query/iterators/NestedVectorIdsKNNIteratorTests.java
  src/test/java/org/opensearch/knn/index/query/iterators/VectorIdsKNNIteratorTests.java
  src/test/java/org/opensearch/knn/index/query/lucenelib/ExpandNestedEDocsQueryTests.java
  src/test/java/org/opensearch/knn/index/query/lucenelib/NestedKnnVectorQueryFactoryTests.java
  src/test/java/org/opensearch/knn/index/query/nativelib/NativeEngineKNNVectorQueryTests.java
  src/test/java/org/opensearch/knn/integ/ExpandNestedDocsIT.java
  src/testFixtures/java/org/opensearch/knn/KNNRestTestCase.java
Labels: backport 2.x, v2.19.0

#2325 Upgrade jsonpath from 2.8.0 to 2.9.0
  CHANGELOG.md
  build.gradle
Labels: Maintenance, backport 2.x

#2305 Adds in lazy execution for Lucene kNN queries
  CHANGELOG.md
  src/main/java/org/opensearch/knn/index/query/KNNQueryFactory.java
  src/main/java/org/opensearch/knn/index/query/lucene/LuceneEngineKnnVectorQuery.java
  src/test/java/org/opensearch/knn/index/query/KNNQueryBuilderTests.java
  src/test/java/org/opensearch/knn/index/query/KNNQueryFactoryTests.java
  src/test/java/org/opensearch/knn/index/query/lucene/LuceneEngineKnnVectorQueryTests.java
Labels: Enhancements, backport 2.x, search-improvements, v2.19.0

#2333 Switch type of expandNested from boolean to Boolean
  src/main/java/org/opensearch/knn/index/query/BaseQueryFactory.java
  src/main/java/org/opensearch/knn/index/query/KNNQueryBuilder.java
  src/main/java/org/opensearch/knn/index/query/KNNQueryFactory.java
  src/main/java/org/opensearch/knn/index/query/parser/KNNQueryBuilderParser.java
Labels: backport 2.x, skip-changelog

#2337 Removing micro-benchmarks module due to JMH using GPL
  .github/workflows/CI.yml
  micro-benchmarks/README.md
  micro-benchmarks/build.gradle
  micro-benchmarks/src/main/java/org/opensearch/knn/QueryParsingBenchmarks.java
  micro-benchmarks/src/main/java/org/opensearch/knn/TransferVectorsBenchmarks.java
  micro-benchmarks/src/main/resources/log4j2.properties
  settings.gradle
Labels: Infrastructure, backport 2.x, skip-changelog, v2.19.0

#2313 Add BWC tests for Lucene Engine
  CHANGELOG.md
  qa/restart-upgrade/build.gradle
  qa/restart-upgrade/src/test/java/org/opensearch/knn/bwc/IndexingIT.java
  qa/rolling-upgrade/src/test/java/org/opensearch/knn/bwc/IndexingIT.java
Labels: backport 2.x

#2315 Allow validation for non knn index only after 2.17.0
  CHANGELOG.md
  qa/restart-upgrade/build.gradle
  qa/restart-upgrade/src/test/java/org/opensearch/knn/bwc/AbstractRestartUpgradeTestCase.java
  qa/restart-upgrade/src/test/java/org/opensearch/knn/bwc/ModelIT.java
  qa/restart-upgrade/src/test/java/org/opensearch/knn/bwc/PainlessScriptScoringIT.java
  qa/restart-upgrade/src/test/java/org/opensearch/knn/bwc/ScriptScoringIT.java
  src/main/java/org/opensearch/knn/index/mapper/KNNVectorFieldMapper.java
  src/test/java/org/opensearch/knn/index/OpenSearchIT.java
  src/testFixtures/java/org/opensearch/knn/KNNRestTestCase.java
Labels: backport 2.x

#2332 Update knn index default to always do approximate search in test
  qa/restart-upgrade/src/test/java/org/opensearch/knn/bwc/AbstractRestartUpgradeTestCase.java
  qa/rolling-upgrade/src/test/java/org/opensearch/knn/bwc/AbstractRollingUpgradeTestCase.java
  qa/rolling-upgrade/src/test/java/org/opensearch/knn/bwc/IndexingIT.java
  src/test/java/org/opensearch/knn/KNNSingleNodeTestCase.java
  src/test/java/org/opensearch/knn/index/KNNESSettingsTestIT.java
  src/test/java/org/opensearch/knn/index/OpenSearchIT.java
  src/test/java/org/opensearch/knn/integ/ExpandNestedDocsIT.java
  src/test/java/org/opensearch/knn/integ/KNNScriptScoringIT.java
  src/test/java/org/opensearch/knn/integ/PainlessScriptScoreIT.java
  src/test/java/org/opensearch/knn/plugin/action/RestKNNStatsHandlerIT.java
  src/test/java/org/opensearch/knn/plugin/action/RestLegacyKNNStatsHandlerIT.java
  src/test/java/org/opensearch/knn/recall/RecallTestsIT.java
  src/testFixtures/java/org/opensearch/knn/KNNRestTestCase.java
Labels: backport 2.x, skip-changelog

#2346 Release query vector memory after execution
  CHANGELOG.md
  jni/src/faiss_wrapper.cpp
Labels: backport 2.x

#2350 [Backport 2.x] Update knn index default to always do approximate search in test (#2332)
  qa/restart-upgrade/src/test/java/org/opensearch/knn/bwc/AbstractRestartUpgradeTestCase.java
  qa/rolling-upgrade/src/test/java/org/opensearch/knn/bwc/AbstractRollingUpgradeTestCase.java
  qa/rolling-upgrade/src/test/java/org/opensearch/knn/bwc/IndexingIT.java
  src/test/java/org/opensearch/knn/KNNSingleNodeTestCase.java
  src/test/java/org/opensearch/knn/index/KNNESSettingsTestIT.java
  src/test/java/org/opensearch/knn/index/OpenSearchIT.java
  src/test/java/org/opensearch/knn/integ/ExpandNestedDocsIT.java
  src/test/java/org/opensearch/knn/integ/KNNScriptScoringIT.java
  src/test/java/org/opensearch/knn/integ/PainlessScriptScoreIT.java
  src/test/java/org/opensearch/knn/plugin/action/RestKNNStatsHandlerIT.java
  src/test/java/org/opensearch/knn/plugin/action/RestLegacyKNNStatsHandlerIT.java
  src/test/java/org/opensearch/knn/recall/RecallTestsIT.java
  src/testFixtures/java/org/opensearch/knn/KNNRestTestCase.java
Labels: skip-changelog

#2352 Fix shard level rescoring disabled setting flag
  CHANGELOG.md
  src/main/java/org/opensearch/knn/index/KNNSettings.java
  src/main/java/org/opensearch/knn/index/query/nativelib/NativeEngineKnnVectorQuery.java
  src/main/java/org/opensearch/knn/index/query/rescore/RescoreContext.java
  src/test/java/org/opensearch/knn/index/KNNSettingsTests.java
  src/test/java/org/opensearch/knn/index/query/nativelib/NativeEngineKNNVectorQueryTests.java
  src/test/java/org/opensearch/knn/index/query/rescore/RescoreContextTests.java
Labels: Bug Fixes, backport 2.x
