Repository opensearch-project/k-NN, pull requests merged in 2024-04, with the labels that each got.

#1586 Add the interface for streaming the vectors from java to jni layer with initial capacity
  jni/CMakeLists.txt
  jni/include/commons.h
  jni/include/jni_util.h
  jni/include/org_opensearch_knn_jni_FaissService.h
  jni/include/org_opensearch_knn_jni_JNICommons.h
  jni/src/commons.cpp
  jni/src/jni_util.cpp
  jni/src/org_opensearch_knn_jni_FaissService.cpp
  jni/src/org_opensearch_knn_jni_JNICommons.cpp
  jni/tests/commons_test.cpp
  jni/tests/test_util.cpp
  jni/tests/test_util.h
  micro-benchmarks/src/main/java/org/opensearch/knn/TransferVectorsBenchmarks.java
  src/main/java/org/opensearch/knn/common/KNNConstants.java
  src/main/java/org/opensearch/knn/jni/FaissService.java
  src/main/java/org/opensearch/knn/jni/JNICommons.java
  src/main/java/org/opensearch/knn/jni/JNIService.java
  src/main/plugin-metadata/plugin-security.policy
  src/test/java/org/opensearch/knn/jni/JNICommonsTest.java
Labels: Enhancements, skip-changelog, v2.14.0

#1588 Integrating storeVectors interfaces with createIndex and createIndexTemplate functions.
  jni/include/faiss_wrapper.h
  jni/include/nmslib_wrapper.h
  jni/include/org_opensearch_knn_jni_FaissService.h
  jni/include/org_opensearch_knn_jni_NmslibService.h
  jni/src/faiss_wrapper.cpp
  jni/src/nmslib_wrapper.cpp
  jni/src/org_opensearch_knn_jni_FaissService.cpp
  jni/src/org_opensearch_knn_jni_NmslibService.cpp
  jni/tests/faiss_wrapper_test.cpp
  jni/tests/nmslib_wrapper_test.cpp
  src/main/java/org/opensearch/knn/index/codec/KNN80Codec/KNN80DocValuesConsumer.java
  src/main/java/org/opensearch/knn/index/codec/util/KNNCodecUtil.java
  src/main/java/org/opensearch/knn/index/memory/NativeMemoryAllocation.java
  src/main/java/org/opensearch/knn/jni/FaissService.java
  src/main/java/org/opensearch/knn/jni/JNIService.java
  src/main/java/org/opensearch/knn/jni/NmslibService.java
  src/test/java/org/opensearch/knn/index/codec/KNN80Codec/KNN80DocValuesConsumerTests.java
  src/test/java/org/opensearch/knn/index/memory/NativeMemoryAllocationTests.java
  src/test/java/org/opensearch/knn/index/memory/NativeMemoryLoadStrategyTests.java
  src/test/java/org/opensearch/knn/jni/JNIServiceTests.java
  src/test/java/org/opensearch/knn/training/TrainingJobTests.java
  src/testFixtures/java/org/opensearch/knn/TestUtils.java
Labels: Enhancements, skip-changelog, v2.14.0

#1592 Fix script to pick up correct zip
  scripts/build.sh
Labels: Infrastructure, backport 2.x, skip-changelog

#1605 Update BWC CI to 2.14 version as 2.13 is released
  .github/workflows/backwards_compatibility_tests_workflow.yml
Labels: Maintenance, ci, skip-changelog

#1604 Implemented the Streaming Feature to stream vectors from Java to JNI layer to enable creation of larger segments for vector indices
  CHANGELOG.md
  jni/CMakeLists.txt
  jni/include/commons.h
  jni/include/faiss_wrapper.h
  jni/include/jni_util.h
  jni/include/nmslib_wrapper.h
  jni/include/org_opensearch_knn_jni_FaissService.h
  jni/include/org_opensearch_knn_jni_JNICommons.h
  jni/include/org_opensearch_knn_jni_NmslibService.h
  jni/src/commons.cpp
  jni/src/faiss_wrapper.cpp
  jni/src/jni_util.cpp
  jni/src/nmslib_wrapper.cpp
  jni/src/org_opensearch_knn_jni_FaissService.cpp
  jni/src/org_opensearch_knn_jni_JNICommons.cpp
  jni/src/org_opensearch_knn_jni_NmslibService.cpp
  jni/tests/commons_test.cpp
  jni/tests/faiss_wrapper_test.cpp
  jni/tests/nmslib_wrapper_test.cpp
  jni/tests/test_util.cpp
  jni/tests/test_util.h
  micro-benchmarks/src/main/java/org/opensearch/knn/TransferVectorsBenchmarks.java
  src/main/java/org/opensearch/knn/common/KNNConstants.java
  src/main/java/org/opensearch/knn/index/KNNSettings.java
  src/main/java/org/opensearch/knn/index/codec/KNN80Codec/KNN80BinaryDocValues.java
  src/main/java/org/opensearch/knn/index/codec/KNN80Codec/KNN80DocValuesConsumer.java
  src/main/java/org/opensearch/knn/index/codec/KNN80Codec/KNN80DocValuesReader.java
  src/main/java/org/opensearch/knn/index/codec/util/KNNCodecUtil.java
  src/main/java/org/opensearch/knn/index/memory/NativeMemoryAllocation.java
  src/main/java/org/opensearch/knn/jni/FaissService.java
  src/main/java/org/opensearch/knn/jni/JNICommons.java
  src/main/java/org/opensearch/knn/jni/JNIService.java
  src/main/java/org/opensearch/knn/jni/NmslibService.java
  src/main/plugin-metadata/plugin-security.policy
  src/test/java/org/opensearch/knn/index/FaissIT.java
  src/test/java/org/opensearch/knn/index/codec/KNN80Codec/KNN80DocValuesConsumerTests.java
  src/test/java/org/opensearch/knn/index/memory/NativeMemoryAllocationTests.java
  src/test/java/org/opensearch/knn/index/memory/NativeMemoryLoadStrategyTests.java
  src/test/java/org/opensearch/knn/jni/JNICommonsTest.java
  src/test/java/org/opensearch/knn/jni/JNIServiceTests.java
  src/test/java/org/opensearch/knn/training/TrainingJobTests.java
  src/testFixtures/java/org/opensearch/knn/TestUtils.java
Labels: Enhancements, backport 2.x, v2.14.0

#1608 [Backport 2.x] Implemented the Streaming Feature to stream vectors from Java to JNI layer to enable creation of larger segments for vector indices (#1604)
  CHANGELOG.md
  jni/CMakeLists.txt
  jni/include/commons.h
  jni/include/faiss_wrapper.h
  jni/include/jni_util.h
  jni/include/nmslib_wrapper.h
  jni/include/org_opensearch_knn_jni_FaissService.h
  jni/include/org_opensearch_knn_jni_JNICommons.h
  jni/include/org_opensearch_knn_jni_NmslibService.h
  jni/src/commons.cpp
  jni/src/faiss_wrapper.cpp
  jni/src/jni_util.cpp
  jni/src/nmslib_wrapper.cpp
  jni/src/org_opensearch_knn_jni_FaissService.cpp
  jni/src/org_opensearch_knn_jni_JNICommons.cpp
  jni/src/org_opensearch_knn_jni_NmslibService.cpp
  jni/tests/commons_test.cpp
  jni/tests/faiss_wrapper_test.cpp
  jni/tests/nmslib_wrapper_test.cpp
  jni/tests/test_util.cpp
  jni/tests/test_util.h
  micro-benchmarks/src/main/java/org/opensearch/knn/TransferVectorsBenchmarks.java
  src/main/java/org/opensearch/knn/common/KNNConstants.java
  src/main/java/org/opensearch/knn/index/KNNSettings.java
  src/main/java/org/opensearch/knn/index/codec/KNN80Codec/KNN80BinaryDocValues.java
  src/main/java/org/opensearch/knn/index/codec/KNN80Codec/KNN80DocValuesConsumer.java
  src/main/java/org/opensearch/knn/index/codec/KNN80Codec/KNN80DocValuesReader.java
  src/main/java/org/opensearch/knn/index/codec/util/KNNCodecUtil.java
  src/main/java/org/opensearch/knn/index/memory/NativeMemoryAllocation.java
  src/main/java/org/opensearch/knn/jni/FaissService.java
  src/main/java/org/opensearch/knn/jni/JNICommons.java
  src/main/java/org/opensearch/knn/jni/JNIService.java
  src/main/java/org/opensearch/knn/jni/NmslibService.java
  src/main/plugin-metadata/plugin-security.policy
  src/test/java/org/opensearch/knn/index/FaissIT.java
  src/test/java/org/opensearch/knn/index/codec/KNN80Codec/KNN80DocValuesConsumerTests.java
  src/test/java/org/opensearch/knn/index/memory/NativeMemoryAllocationTests.java
  src/test/java/org/opensearch/knn/index/memory/NativeMemoryLoadStrategyTests.java
  src/test/java/org/opensearch/knn/jni/JNICommonsTest.java
  src/test/java/org/opensearch/knn/jni/JNIServiceTests.java
  src/test/java/org/opensearch/knn/training/TrainingJobTests.java
  src/testFixtures/java/org/opensearch/knn/TestUtils.java
Labels: Enhancements

#1609 Rename radial search parameters score and distance to min_score and max_distance
  src/main/java/org/opensearch/knn/index/query/KNNQueryBuilder.java
  src/test/java/org/opensearch/knn/index/FaissIT.java
  src/test/java/org/opensearch/knn/index/LuceneEngineIT.java
  src/test/java/org/opensearch/knn/index/query/KNNQueryBuilderTests.java
Labels: feature branch, skip-changelog, v2.14.0

#1617 Add radial search feature to main branch
  CHANGELOG.md
  jni/include/faiss_wrapper.h
  jni/include/org_opensearch_knn_jni_FaissService.h
  jni/src/faiss_wrapper.cpp
  jni/src/org_opensearch_knn_jni_FaissService.cpp
  jni/tests/faiss_wrapper_test.cpp
  src/main/java/org/opensearch/knn/common/KNNConstants.java
  src/main/java/org/opensearch/knn/index/IndexUtil.java
  src/main/java/org/opensearch/knn/index/SpaceType.java
  src/main/java/org/opensearch/knn/index/query/BaseQueryFactory.java
  src/main/java/org/opensearch/knn/index/query/KNNQuery.java
  src/main/java/org/opensearch/knn/index/query/KNNQueryBuilder.java
  src/main/java/org/opensearch/knn/index/query/KNNQueryFactory.java
  src/main/java/org/opensearch/knn/index/query/KNNWeight.java
  src/main/java/org/opensearch/knn/index/query/RNNQueryFactory.java
  src/main/java/org/opensearch/knn/index/util/Faiss.java
  src/main/java/org/opensearch/knn/index/util/KNNEngine.java
  src/main/java/org/opensearch/knn/index/util/KNNLibrary.java
  src/main/java/org/opensearch/knn/index/util/Lucene.java
  src/main/java/org/opensearch/knn/index/util/Nmslib.java
  src/main/java/org/opensearch/knn/jni/FaissService.java
  src/main/java/org/opensearch/knn/jni/JNIService.java
  src/test/java/org/opensearch/knn/index/FaissIT.java
  src/test/java/org/opensearch/knn/index/LuceneEngineIT.java
  src/test/java/org/opensearch/knn/index/query/KNNQueryBuilderTests.java
  src/test/java/org/opensearch/knn/index/query/KNNWeightTests.java
  src/test/java/org/opensearch/knn/index/query/RNNQueryFactoryTests.java
  src/test/java/org/opensearch/knn/index/util/AbstractKNNLibraryTests.java
  src/test/java/org/opensearch/knn/index/util/LuceneTests.java
  src/test/java/org/opensearch/knn/index/util/NativeLibraryTests.java
  src/test/java/org/opensearch/knn/plugin/stats/suppliers/LibraryInitializedSupplierTests.java
  src/testFixtures/java/org/opensearch/knn/KNNRestTestCase.java
Labels: Features, backport 2.x, v2.14.0

#1619 Use 0.95 as default ratio for lucene radial search traversal similarity
  src/main/java/org/opensearch/knn/common/KNNConstants.java
  src/main/java/org/opensearch/knn/index/query/RNNQueryFactory.java
  src/test/java/org/opensearch/knn/index/query/KNNQueryBuilderTests.java
Labels: skip-changelog, v2.14.0

#1620 Separate common lib jni and non-jni into 2 libs
  build.gradle
  jni/CMakeLists.txt
Labels: Infrastructure, backport 2.x, skip-changelog

#1627 [backport 2.x] Support radial search in k-NN
  CHANGELOG.md
  jni/include/faiss_wrapper.h
  jni/include/org_opensearch_knn_jni_FaissService.h
  jni/src/faiss_wrapper.cpp
  jni/src/org_opensearch_knn_jni_FaissService.cpp
  jni/tests/faiss_wrapper_test.cpp
  src/main/java/org/opensearch/knn/common/KNNConstants.java
  src/main/java/org/opensearch/knn/index/IndexUtil.java
  src/main/java/org/opensearch/knn/index/SpaceType.java
  src/main/java/org/opensearch/knn/index/query/BaseQueryFactory.java
  src/main/java/org/opensearch/knn/index/query/KNNQuery.java
  src/main/java/org/opensearch/knn/index/query/KNNQueryBuilder.java
  src/main/java/org/opensearch/knn/index/query/KNNQueryFactory.java
  src/main/java/org/opensearch/knn/index/query/KNNWeight.java
  src/main/java/org/opensearch/knn/index/query/RNNQueryFactory.java
  src/main/java/org/opensearch/knn/index/util/Faiss.java
  src/main/java/org/opensearch/knn/index/util/KNNEngine.java
  src/main/java/org/opensearch/knn/index/util/KNNLibrary.java
  src/main/java/org/opensearch/knn/index/util/Lucene.java
  src/main/java/org/opensearch/knn/index/util/Nmslib.java
  src/main/java/org/opensearch/knn/jni/FaissService.java
  src/main/java/org/opensearch/knn/jni/JNIService.java
  src/test/java/org/opensearch/knn/index/FaissIT.java
  src/test/java/org/opensearch/knn/index/LuceneEngineIT.java
  src/test/java/org/opensearch/knn/index/query/KNNQueryBuilderTests.java
  src/test/java/org/opensearch/knn/index/query/KNNWeightTests.java
  src/test/java/org/opensearch/knn/index/query/RNNQueryFactoryTests.java
  src/test/java/org/opensearch/knn/index/util/AbstractKNNLibraryTests.java
  src/test/java/org/opensearch/knn/index/util/LuceneTests.java
  src/test/java/org/opensearch/knn/index/util/NativeLibraryTests.java
  src/test/java/org/opensearch/knn/plugin/stats/suppliers/LibraryInitializedSupplierTests.java
  src/testFixtures/java/org/opensearch/knn/KNNRestTestCase.java
Labels: v2.14.0

#1635 Fix flaky faiss integration tests
  src/test/java/org/opensearch/knn/index/FaissIT.java
Labels: backport 2.x, skip-changelog

#1634 Update gcc restrictions to version 12.0.0
  scripts/build.sh
Labels: Enhancements, release, skip-changelog, v2.14.0

#1630 Add stored fields for knn_vector type
  CHANGELOG.md
  src/main/java/org/opensearch/knn/index/KNNVectorScriptDocValues.java
  src/main/java/org/opensearch/knn/index/VectorDataType.java
  src/main/java/org/opensearch/knn/index/mapper/KNNVectorFieldMapper.java
  src/main/java/org/opensearch/knn/index/mapper/KNNVectorFieldMapperUtil.java
  src/main/java/org/opensearch/knn/index/mapper/LuceneFieldMapper.java
  src/test/java/org/opensearch/knn/index/AdvancedFilteringUseCasesIT.java
  src/test/java/org/opensearch/knn/index/KNNMapperSearcherIT.java
  src/test/java/org/opensearch/knn/index/mapper/KNNVectorFieldMapperUtilTests.java
  src/testFixtures/java/org/opensearch/knn/KNNRestTestCase.java
Labels: Bug Fixes, backport 2.x, backport 2.13

#1640 [Backport 2.x] Add stored fields for knn_vector type (#1630)
  CHANGELOG.md
  src/main/java/org/opensearch/knn/index/KNNVectorScriptDocValues.java
  src/main/java/org/opensearch/knn/index/VectorDataType.java
  src/main/java/org/opensearch/knn/index/mapper/KNNVectorFieldMapper.java
  src/main/java/org/opensearch/knn/index/mapper/KNNVectorFieldMapperUtil.java
  src/main/java/org/opensearch/knn/index/mapper/LuceneFieldMapper.java
  src/test/java/org/opensearch/knn/index/AdvancedFilteringUseCasesIT.java
  src/test/java/org/opensearch/knn/index/KNNMapperSearcherIT.java
  src/test/java/org/opensearch/knn/index/mapper/KNNVectorFieldMapperUtilTests.java
  src/testFixtures/java/org/opensearch/knn/KNNRestTestCase.java
Labels: Bug Fixes, skip-changelog

#1636 Skip rebuild from scratch after cmake is ran
  .github/workflows/CI.yml
  .github/workflows/backwards_compatibility_tests_workflow.yml
  .github/workflows/test_security.yml
  .gitignore
  CHANGELOG.md
  jni/CMakeLists.txt
  jni/cmake/init-faiss.cmake
  jni/cmake/init-nmslib.cmake
  jni/cmake/macros.cmake
Labels: Infrastructure, backport 2.x

#1653 Add flag for whether patches should be committed
  .github/workflows/dco.yml
  DEVELOPER_GUIDE.md
  build.gradle
  jni/CMakeLists.txt
  jni/cmake/init-faiss.cmake
  jni/cmake/init-nmslib.cmake
  scripts/build.sh
Labels: skip-changelog

#1654 [Backport 2.13] Add stored fields for knn_vector type
  CHANGELOG.md
  src/main/java/org/opensearch/knn/index/KNNVectorScriptDocValues.java
  src/main/java/org/opensearch/knn/index/VectorDataType.java
  src/main/java/org/opensearch/knn/index/mapper/KNNVectorFieldMapper.java
  src/main/java/org/opensearch/knn/index/mapper/KNNVectorFieldMapperUtil.java
  src/main/java/org/opensearch/knn/index/mapper/LuceneFieldMapper.java
  src/test/java/org/opensearch/knn/index/AdvancedFilteringUseCasesIT.java
  src/test/java/org/opensearch/knn/index/KNNMapperSearcherIT.java
  src/test/java/org/opensearch/knn/index/mapper/KNNVectorFieldMapperUtilTests.java
  src/testFixtures/java/org/opensearch/knn/KNNRestTestCase.java
Labels: Bug Fixes

#1642 Updates Developer guide
  DEVELOPER_GUIDE.md
Labels: Documentation, backport 2.x, skip-changelog

#1652 Support filter and nested field in faiss engine radial search
  CHANGELOG.md
  jni/CMakeLists.txt
  jni/cmake/init-faiss.cmake
  jni/include/faiss_wrapper.h
  jni/include/org_opensearch_knn_jni_FaissService.h
  jni/patches/faiss/0003-Custom-patch-to-support-range-search-params.patch
  jni/src/faiss_wrapper.cpp
  jni/src/org_opensearch_knn_jni_FaissService.cpp
  jni/tests/faiss_wrapper_test.cpp
  src/main/java/org/opensearch/knn/common/KNNConstants.java
  src/main/java/org/opensearch/knn/index/query/KNNQueryBuilder.java
  src/main/java/org/opensearch/knn/index/query/KNNWeight.java
  src/main/java/org/opensearch/knn/jni/FaissService.java
  src/main/java/org/opensearch/knn/jni/JNIService.java
  src/test/java/org/opensearch/knn/index/FaissIT.java
  src/test/java/org/opensearch/knn/index/LuceneEngineIT.java
  src/test/java/org/opensearch/knn/index/NestedSearchIT.java
  src/test/java/org/opensearch/knn/index/query/KNNWeightTests.java
Labels: Features, backport 2.x, v2.14.0

#1649 Enable script score to work with model based indices
  CHANGELOG.md
  src/main/java/org/opensearch/knn/index/mapper/KNNVectorFieldMapperUtil.java
  src/main/java/org/opensearch/knn/plugin/KNNPlugin.java
  src/main/java/org/opensearch/knn/plugin/script/KNNScoringSpace.java
  src/main/java/org/opensearch/knn/plugin/script/KNNScoringSpaceUtil.java
  src/test/java/org/opensearch/knn/index/mapper/KNNVectorFieldMapperUtilTests.java
  src/test/java/org/opensearch/knn/plugin/script/KNNScriptScoringIT.java
Labels: backport 2.x, v2.14.0

#1662 Revert 'Support script score when doc value is disabled'
  CHANGELOG.md
  src/main/java/org/opensearch/knn/index/KNNVectorDVLeafFieldData.java
  src/main/java/org/opensearch/knn/index/KNNVectorScriptDocValues.java
  src/test/java/org/opensearch/knn/index/KNNVectorScriptDocValuesTests.java
  src/test/java/org/opensearch/knn/index/VectorDataTypeTests.java
  src/test/java/org/opensearch/knn/plugin/script/KNNScoringUtilTests.java
  src/test/java/org/opensearch/knn/plugin/script/KNNScriptScoringIT.java
  src/test/java/org/opensearch/knn/plugin/script/PainlessScriptIT.java
Labels: backport 2.x, v2.14.0

#1665 Ensure blas is statically linked
  jni/cmake/init-faiss.cmake
Labels: Infrastructure, backport 2.x, skip-changelog

#1664 Ensure gcc is newer >= 11.2.1 < 12.0.0 when building knn lib
  scripts/build.sh
Labels: Enhancements, release, backport 2.x, skip-changelog, v2.14.0

#1670 Add 2.14 release notes
  CHANGELOG.md
  release-notes/opensearch-knn.release-notes-2.14.0.0.md
Labels: backport 2.x, skip-changelog

#1674 Revert #1634 #1664 to switch back to CentOS7
  scripts/build.sh
Labels: release, backport 2.x, skip-changelog, v2.14.0

#1675 [Backport 2.x] Add 2.14 release notes
  CHANGELOG.md
  release-notes/opensearch-knn.release-notes-2.14.0.0.md
Labels: skip-changelog
