Repository opensearch-project/k-NN, pull requests merged in 2024-05, with the labels that each got.

#1679 Update 2.14 release notes
  release-notes/opensearch-knn.release-notes-2.14.0.0.md
Labels: backport 2.x, skip-changelog, backport 2.14

#1682 Update DEVELOPER_GUIDE.md for M Chip Mac
  DEVELOPER_GUIDE.md
Labels: backport 2.x, skip-changelog

#1628 Add Yuncheng Lu as maintainer
  .github/CODEOWNERS
  MAINTAINERS.md
Labels: skip-changelog

#1685 Fix build CI failure on MacOS
  .github/workflows/CI.yml
Labels: Infrastructure, skip-changelog

#1692 Block commas in model description
  CHANGELOG.md
  src/main/java/org/opensearch/knn/indices/ModelMetadata.java
  src/main/java/org/opensearch/knn/indices/ModelUtil.java
  src/main/java/org/opensearch/knn/plugin/rest/RestTrainModelHandler.java
  src/test/java/org/opensearch/knn/indices/ModelMetadataTests.java
  src/test/java/org/opensearch/knn/plugin/action/RestTrainModelHandlerIT.java
Labels: backport 2.x, v2.15.0

#1684 Add stats for radial search
  CHANGELOG.md
  src/main/java/org/opensearch/knn/index/VectorQueryType.java
  src/main/java/org/opensearch/knn/index/query/KNNQueryBuilder.java
  src/main/java/org/opensearch/knn/plugin/stats/KNNCounter.java
  src/main/java/org/opensearch/knn/plugin/stats/KNNStats.java
  src/main/java/org/opensearch/knn/plugin/stats/StatNames.java
  src/test/java/org/opensearch/knn/index/VectorQueryTypeTests.java
  src/test/java/org/opensearch/knn/plugin/action/RestKNNStatsHandlerIT.java
Labels: enhancement, backport 2.x, v2.15.0

#1700 Updating security reachout email
  SECURITY.md
Labels: backport 2.x, skip-changelog

#1705 Fix flaky test in FAISS JNI range search
  jni/tests/faiss_wrapper_test.cpp
Labels: backport 2.x, skip-changelog, flaky-test

#1704 Add luyuncheng as maintainer (#1628)
  .github/CODEOWNERS
  MAINTAINERS.md
Labels: skip-changelog

#1715 Update threshold value after new result is added
  CHANGELOG.md
  jni/patches/faiss/0001-Custom-patch-to-support-multi-vector.patch
  src/test/java/org/opensearch/knn/index/NestedSearchIT.java
Labels: backport 2.x

#1713 Add validation for pq m parameter before training starts
  CHANGELOG.md
  src/main/java/org/opensearch/knn/index/KNNMethod.java
  src/main/java/org/opensearch/knn/index/KNNMethodContext.java
  src/main/java/org/opensearch/knn/index/MethodComponent.java
  src/main/java/org/opensearch/knn/index/Parameter.java
  src/main/java/org/opensearch/knn/index/util/AbstractKNNLibrary.java
  src/main/java/org/opensearch/knn/index/util/Faiss.java
  src/main/java/org/opensearch/knn/index/util/KNNEngine.java
  src/main/java/org/opensearch/knn/index/util/KNNLibrary.java
  src/main/java/org/opensearch/knn/plugin/transport/TrainingModelRequest.java
  src/main/java/org/opensearch/knn/training/VectorSpaceInfo.java
  src/test/java/org/opensearch/knn/index/FaissIT.java
  src/test/java/org/opensearch/knn/index/KNNMethodTests.java
  src/test/java/org/opensearch/knn/index/ParameterTests.java
  src/test/java/org/opensearch/knn/plugin/stats/suppliers/LibraryInitializedSupplierTests.java
  src/testFixtures/java/org/opensearch/knn/KNNRestTestCase.java
Labels: backport 2.x, v2.15.0

#1724 Updating the BWC test config after 2.14 release
  .github/workflows/backwards_compatibility_tests_workflow.yml
Labels: skip-changelog

#1726 Refactor createParseField function in mappers for code reusability
  src/main/java/org/opensearch/knn/index/mapper/KNNVectorFieldMapper.java
  src/main/java/org/opensearch/knn/index/mapper/LuceneFieldMapper.java
Labels: backport 2.x, skip-changelog, v2.15.0
