Repository opensearch-project/k-NN, pull requests merged in 2024-01, with the labels that each got.

#1307 Install security plugin from individual artifacts
  .github/workflows/CI.yml
  .github/workflows/test_security.yml
  CHANGELOG.md
  DEVELOPER_GUIDE.md
  build.gradle
  qa/restart-upgrade/src/test/java/org/opensearch/knn/bwc/ModelIT.java
  src/test/resources/security/sample.pem
  src/test/resources/security/test-kirk.jks
  src/testFixtures/java/org/opensearch/knn/KNNRestTestCase.java
  src/testFixtures/java/org/opensearch/knn/ODFERestTestCase.java
Labels: Infrastructure, backport 2.x

#1355 Fix flaky tests
  qa/restart-upgrade/src/test/java/org/opensearch/knn/bwc/ModelIT.java
  src/test/java/org/opensearch/knn/plugin/transport/GetModelResponseTests.java
Labels: backport 2.x, skip-changelog

#1370 [Backport 2.x] Fix flaky tests
  qa/restart-upgrade/src/test/java/org/opensearch/knn/bwc/ModelIT.java
  src/test/java/org/opensearch/knn/plugin/transport/GetModelResponseTests.java
Labels: skip-changelog, v2.12.0

#1367 Fix script score queries not getting cached
  CHANGELOG.md
  qa/restart-upgrade/src/test/java/org/opensearch/knn/bwc/ScriptScoringIT.java
  src/main/java/org/opensearch/knn/plugin/script/KNNScoreScriptFactory.java
  src/main/java/org/opensearch/knn/plugin/script/KNNScoreScriptLeafFactory.java
  src/main/java/org/opensearch/knn/plugin/script/KNNScoringScriptEngine.java
  src/test/java/org/opensearch/knn/index/VectorDataTypeIT.java
  src/test/java/org/opensearch/knn/plugin/script/KNNScriptScoringIT.java
  src/test/java/org/opensearch/knn/plugin/script/PainlessScriptIT.java
  src/testFixtures/java/org/opensearch/knn/KNNRestTestCase.java
Labels: bug, backport 2.x, v2.12.0

#1373 [Backport 2.x] Fix script score queries not getting cached
  CHANGELOG.md
  qa/restart-upgrade/src/test/java/org/opensearch/knn/bwc/ScriptScoringIT.java
  src/main/java/org/opensearch/knn/plugin/script/KNNScoreScriptFactory.java
  src/main/java/org/opensearch/knn/plugin/script/KNNScoreScriptLeafFactory.java
  src/main/java/org/opensearch/knn/plugin/script/KNNScoringScriptEngine.java
  src/test/java/org/opensearch/knn/index/VectorDataTypeIT.java
  src/test/java/org/opensearch/knn/plugin/script/KNNScriptScoringIT.java
  src/test/java/org/opensearch/knn/plugin/script/PainlessScriptIT.java
  src/testFixtures/java/org/opensearch/knn/KNNRestTestCase.java
Labels: bug, v2.12.0

#1374 Refactor TrainingJobRouteDecisionInfo test to use KNNTestCase
  src/test/java/org/opensearch/knn/plugin/transport/TrainingJobRouteDecisionInfoTransportActionTests.java
Labels: backport 2.x, skip-changelog

#1372 Enabled Filtering on Nested Vector fields with top level filters
  CHANGELOG.md
  src/main/java/org/opensearch/knn/index/query/KNNQueryFactory.java
  src/test/java/org/opensearch/knn/index/AdvancedFilteringUseCasesIT.java
  src/test/java/org/opensearch/knn/index/NestedSearchIT.java
  src/test/java/org/opensearch/knn/index/query/KNNQueryFactoryTests.java
  src/testFixtures/java/org/opensearch/knn/KNNRestTestCase.java
  src/testFixtures/java/org/opensearch/knn/NestedKnnDocBuilder.java
Labels: Enhancements, backport 2.x, v2.12.0

#1371 Multi vector support for Faiss HNSW - approximate search only
  .github/workflows/test_security.yml
  jni/include/knn_extension/faiss/utils/BitSet.h
  jni/include/knn_extension/faiss/utils/Heap.h
  jni/src/knn_extension/faiss/utils/BitSet.cpp
  src/main/java/org/opensearch/knn/index/query/KNNQuery.java
  src/main/java/org/opensearch/knn/index/query/KNNQueryFactory.java
  src/main/java/org/opensearch/knn/index/query/KNNWeight.java
  src/main/java/org/opensearch/knn/jni/JNIService.java
  src/test/java/org/opensearch/knn/index/NestedSearchIT.java
  src/test/java/org/opensearch/knn/index/codec/KNNCodecTestCase.java
  src/test/java/org/opensearch/knn/index/codec/KNNCodecTestUtil.java
  src/test/java/org/opensearch/knn/index/memory/NativeMemoryLoadStrategyTests.java
  src/test/java/org/opensearch/knn/index/query/KNNQueryFactoryTests.java
  src/test/java/org/opensearch/knn/index/query/KNNWeightTests.java
  src/test/java/org/opensearch/knn/jni/JNIServiceTests.java
  src/test/resources/data/README.md
  src/test/resources/data/test_vectors_nested_1000x128.json
Labels: skip-changelog

#1380 Throw proper exception to invalid k-NN query
  CHANGELOG.md
  src/main/java/org/opensearch/knn/index/query/KNNQueryBuilder.java
  src/test/java/org/opensearch/knn/index/VectorDataTypeIT.java
  src/test/java/org/opensearch/knn/index/query/KNNQueryBuilderTests.java
Labels: Enhancements, backport 2.x, v2.12.0

#1388 Add data generation script for nested field
  benchmarks/perf-tool/README.md
  benchmarks/perf-tool/add-parent-doc-id-to-dataset.py
  src/test/java/org/opensearch/knn/index/query/KNNWeightTests.java
Labels: backport 2.x, skip-changelog

#1394 Add perf test for nested field
  benchmarks/perf-tool/README.md
  benchmarks/perf-tool/add-parent-doc-id-to-dataset.py
  benchmarks/perf-tool/dataset/data-nested.hdf5
  benchmarks/perf-tool/dataset/sift-128-euclidean-nested.hdf5
  benchmarks/perf-tool/okpt/test/steps/factory.py
  benchmarks/perf-tool/okpt/test/steps/steps.py
  benchmarks/perf-tool/release-configs/faiss-hnsw/nested/simple/index.json
  benchmarks/perf-tool/release-configs/faiss-hnsw/nested/simple/simple-nested-test.yml
  benchmarks/perf-tool/release-configs/lucene-hnsw/nested/simple/index.json
  benchmarks/perf-tool/release-configs/lucene-hnsw/nested/simple/simple-nested-test.yml
Labels: skip-changelog

#1399 Handle multi-vector in exact search scenario
  src/main/java/org/opensearch/knn/index/query/KNNWeight.java
  src/main/java/org/opensearch/knn/index/query/filtered/FilteredIdsKNNIterator.java
  src/main/java/org/opensearch/knn/index/query/filtered/NestedFilteredIdsKNNIterator.java
  src/test/java/org/opensearch/knn/common/Constants.java
  src/test/java/org/opensearch/knn/index/NestedSearchIT.java
  src/test/java/org/opensearch/knn/index/query/KNNWeightTests.java
  src/test/java/org/opensearch/knn/index/query/filtered/FilteredIdsKNNIteratorTests.java
  src/test/java/org/opensearch/knn/index/query/filtered/NestedFilteredIdsKNNIteratorTests.java
  src/testFixtures/java/org/opensearch/knn/KNNRestTestCase.java
Labels: backport 2.x, skip-changelog

#1395 Few changes in integration test
  src/test/java/org/opensearch/knn/index/AdvancedFilteringUseCasesIT.java
  src/test/java/org/opensearch/knn/index/NestedSearchIT.java
Labels: backport 2.x, skip-changelog

#1403 Fix KNNScorer to apply boost
  CHANGELOG.md
  src/main/java/org/opensearch/knn/index/query/KNNScorer.java
  src/test/java/org/opensearch/knn/index/query/KNNWeightTests.java
Labels: backport 2.x

#1397 Fix equals and hashCode methods for KNNQuery and KNNQueryBuilder
  CHANGELOG.md
  src/main/java/org/opensearch/knn/index/query/KNNQuery.java
  src/main/java/org/opensearch/knn/index/query/KNNQueryBuilder.java
  src/test/java/org/opensearch/knn/index/query/KNNQueryBuilderTests.java
Labels: Bug Fixes, backport 2.x

#1415 Remove default admin credential references in DEVELOPER_GUIDE
  DEVELOPER_GUIDE.md
  build.gradle
Labels: backport 2.x, skip-changelog

#1419 Skip delete .plugins-ml-config system index during integ test
  src/testFixtures/java/org/opensearch/knn/ODFERestTestCase.java
  src/testFixtures/java/org/opensearch/knn/TestUtils.java
Labels: Maintenance, backport 2.x, skip-changelog

#1426 Fix markdown formatting in developer guide
  DEVELOPER_GUIDE.md
Labels: backport 2.x, skip-changelog

#1423 Refactor integ tests that access model index
  CHANGELOG.md
  src/test/java/org/opensearch/knn/plugin/action/RestDeleteModelHandlerIT.java
  src/test/java/org/opensearch/knn/plugin/action/RestGetModelHandlerIT.java
  src/test/java/org/opensearch/knn/plugin/action/RestKNNStatsHandlerIT.java
  src/test/java/org/opensearch/knn/plugin/action/RestSearchModelHandlerIT.java
  src/testFixtures/java/org/opensearch/knn/KNNRestTestCase.java
Labels: backport 2.x, integ-test-failure

#1429 Fix flaky model tests
  CHANGELOG.md
  src/test/java/org/opensearch/knn/indices/ModelDaoTests.java
Labels: backport 2.x, v2.12.0
