Repository opensearch-project/k-NN, pull requests merged in 2024-03, with the labels that each got.

#1402 Optimize Faiss Query With Filters: Reduce iteration and memory for id filter
  CHANGELOG.md
  jni/include/faiss_wrapper.h
  jni/include/jni_util.h
  jni/include/org_opensearch_knn_jni_FaissService.h
  jni/src/faiss_wrapper.cpp
  jni/src/jni_util.cpp
  jni/src/org_opensearch_knn_jni_FaissService.cpp
  jni/tests/faiss_wrapper_test.cpp
  jni/tests/test_util.cpp
  jni/tests/test_util.h
  src/main/java/org/opensearch/knn/index/query/FilterIdsSelector.java
  src/main/java/org/opensearch/knn/index/query/KNNWeight.java
  src/main/java/org/opensearch/knn/index/query/filtered/FilteredIdsKNNIterator.java
  src/main/java/org/opensearch/knn/index/query/filtered/NestedFilteredIdsKNNIterator.java
  src/main/java/org/opensearch/knn/jni/FaissService.java
  src/main/java/org/opensearch/knn/jni/JNIService.java
  src/test/java/org/opensearch/knn/index/codec/KNNCodecTestUtil.java
  src/test/java/org/opensearch/knn/index/memory/NativeMemoryLoadStrategyTests.java
  src/test/java/org/opensearch/knn/index/query/FilterIdsSelectorTests.java
  src/test/java/org/opensearch/knn/index/query/KNNWeightTests.java
  src/test/java/org/opensearch/knn/index/query/filtered/FilteredIdsKNNIteratorTests.java
  src/test/java/org/opensearch/knn/index/query/filtered/NestedFilteredIdsKNNIteratorTests.java
  src/test/java/org/opensearch/knn/jni/JNIServiceTests.java
Labels: Enhancements, backport 2.x

#1505 Increment 2.12.0-SNAPSHOT to 2.13.0-SNAPSHOT in BWC workflow
  .github/workflows/backwards_compatibility_tests_workflow.yml
Labels: backport 2.x, skip-changelog

#1513 Manually install zlib for win CI
  .github/workflows/CI.yml
  CHANGELOG.md
Labels: Infrastructure, backport 2.x

#1518 Disable sdc table for HNSWPQ read-only indices
  CHANGELOG.md
  jni/src/faiss_wrapper.cpp
  jni/tests/faiss_wrapper_test.cpp
  jni/tests/test_util.cpp
  jni/tests/test_util.h
Labels: Bug Fixes, backport 2.x

#1520 Introduce faiss patch to share ivfpq precomp table
  .github/workflows/CI.yml
  .github/workflows/test_security.yml
  jni/CMakeLists.txt
  jni/patches/faiss/0003-Enable-precomp-table-to-be-shared-ivfpq.patch
Labels: skip-changelog

#1517 Raise gcc version requirement to 9.0.0 for SIMD Neon support on ARM64
  scripts/build.sh
Labels: Enhancements, enhancement, backport 2.x, skip-changelog

#1503 Detect AVX2 Dynamically on the System
  .github/workflows/CI.yml
  CHANGELOG.md
  DEVELOPER_GUIDE.md
  build.gradle
  jni/CMakeLists.txt
  scripts/build.sh
  src/main/java/org/opensearch/knn/common/KNNConstants.java
  src/main/java/org/opensearch/knn/index/KNNSettings.java
  src/main/java/org/opensearch/knn/jni/FaissService.java
  src/main/java/org/opensearch/knn/jni/PlatformUtils.java
  src/main/plugin-metadata/plugin-security.policy
  src/test/java/org/opensearch/knn/index/KNNSettingsTests.java
  src/test/java/org/opensearch/knn/jni/PlatformUtilTests.java
Labels: Enhancements, backport 2.x

#1532 Switch spacetype similarity function to MAXIMUM_INNER_PRODUCT
  CHANGELOG.md
  src/main/java/org/opensearch/knn/index/SpaceType.java
  src/test/java/org/opensearch/knn/index/FaissIT.java
  src/test/java/org/opensearch/knn/index/SpaceTypeTests.java
Labels: Bug Fixes, backport 2.x

#1533 [Backport 2.x] Switch spacetype similarity function to MAXIMUM_INNER_PRODUCT
  CHANGELOG.md
  src/main/java/org/opensearch/knn/index/SpaceType.java
  src/test/java/org/opensearch/knn/index/FaissIT.java
  src/test/java/org/opensearch/knn/index/SpaceTypeTests.java
Labels: Bug Fixes

#1535 Bump jinja2 dependency from 2.11.3 to 3.1.3
  benchmarks/osb/requirements.txt
Labels: backport 2.x, skip-changelog

#1501 Validate zero vector when using cosine metric
  CHANGELOG.md
  src/main/java/org/opensearch/knn/common/KNNValidationUtil.java
  src/main/java/org/opensearch/knn/common/KNNVectorUtil.java
  src/main/java/org/opensearch/knn/index/SpaceType.java
  src/main/java/org/opensearch/knn/index/mapper/KNNVectorFieldMapper.java
  src/main/java/org/opensearch/knn/index/mapper/KNNVectorFieldMapperUtil.java
  src/main/java/org/opensearch/knn/index/mapper/LuceneFieldMapper.java
  src/main/java/org/opensearch/knn/index/mapper/ModelFieldMapper.java
  src/main/java/org/opensearch/knn/index/query/KNNQueryBuilder.java
  src/main/java/org/opensearch/knn/plugin/script/KNNScoringSpace.java
  src/main/java/org/opensearch/knn/plugin/script/KNNScoringSpaceUtil.java
  src/main/java/org/opensearch/knn/plugin/script/KNNScoringUtil.java
  src/test/java/org/opensearch/knn/common/KNNVectorUtilTests.java
  src/test/java/org/opensearch/knn/index/OpenSearchIT.java
  src/test/java/org/opensearch/knn/index/mapper/KNNVectorFieldMapperTests.java
  src/test/java/org/opensearch/knn/index/query/KNNQueryBuilderTests.java
  src/test/java/org/opensearch/knn/plugin/script/KNNScoringSpaceFactoryTests.java
  src/test/java/org/opensearch/knn/plugin/script/KNNScoringSpaceTests.java
  src/test/java/org/opensearch/knn/plugin/script/KNNScoringUtilTests.java
  src/testFixtures/java/org/opensearch/knn/KNNRestTestCase.java
Labels: Enhancements, backport 2.x

#1528 Fix AppSec Findings CWE-22 and CWE-476
  qa/rolling-upgrade/src/test/java/org/opensearch/knn/bwc/AbstractRollingUpgradeTestCase.java
  src/main/java/org/opensearch/knn/indices/ModelDao.java
  src/test/java/org/opensearch/knn/index/FaissIT.java
  src/test/java/org/opensearch/knn/index/NmslibIT.java
  src/test/java/org/opensearch/knn/index/OpenSearchIT.java
  src/test/java/org/opensearch/knn/jni/JNIServiceTests.java
  src/testFixtures/java/org/opensearch/knn/KNNRestTestCase.java
Labels: backport 2.x, skip-changelog

#1538 [Backport 2.x] Validate zero vector when using cosine metric
  CHANGELOG.md
  src/main/java/org/opensearch/knn/common/KNNValidationUtil.java
  src/main/java/org/opensearch/knn/common/KNNVectorUtil.java
  src/main/java/org/opensearch/knn/index/SpaceType.java
  src/main/java/org/opensearch/knn/index/mapper/KNNVectorFieldMapper.java
  src/main/java/org/opensearch/knn/index/mapper/KNNVectorFieldMapperUtil.java
  src/main/java/org/opensearch/knn/index/mapper/LuceneFieldMapper.java
  src/main/java/org/opensearch/knn/index/mapper/ModelFieldMapper.java
  src/main/java/org/opensearch/knn/index/query/KNNQueryBuilder.java
  src/main/java/org/opensearch/knn/plugin/script/KNNScoringSpace.java
  src/main/java/org/opensearch/knn/plugin/script/KNNScoringSpaceUtil.java
  src/main/java/org/opensearch/knn/plugin/script/KNNScoringUtil.java
  src/test/java/org/opensearch/knn/common/KNNVectorUtilTests.java
  src/test/java/org/opensearch/knn/index/OpenSearchIT.java
  src/test/java/org/opensearch/knn/index/mapper/KNNVectorFieldMapperTests.java
  src/test/java/org/opensearch/knn/index/query/KNNQueryBuilderTests.java
  src/test/java/org/opensearch/knn/plugin/script/KNNScoringSpaceFactoryTests.java
  src/test/java/org/opensearch/knn/plugin/script/KNNScoringSpaceTests.java
  src/test/java/org/opensearch/knn/plugin/script/KNNScoringUtilTests.java
  src/testFixtures/java/org/opensearch/knn/KNNRestTestCase.java
Labels: Enhancements

#1541 Add patch to fix arm segfault in nmslib during ingestion
  .github/workflows/CI.yml
  .github/workflows/test_security.yml
  CHANGELOG.md
  jni/CMakeLists.txt
  jni/patches/nmslib/0001-Initialize-maxlevel-during-add-from-enterpoint-level.patch
Labels: Bug Fixes, backport 2.x

#1529 Add ability to share IVFPQ-l2 state in JNI
  jni/include/faiss_wrapper.h
  jni/include/org_opensearch_knn_jni_FaissService.h
  jni/src/faiss_wrapper.cpp
  jni/src/org_opensearch_knn_jni_FaissService.cpp
  jni/tests/faiss_wrapper_test.cpp
  src/main/java/org/opensearch/knn/index/codec/KNN80Codec/KNN80DocValuesConsumer.java
  src/main/java/org/opensearch/knn/index/memory/NativeMemoryAllocation.java
  src/main/java/org/opensearch/knn/index/memory/NativeMemoryLoadStrategy.java
  src/main/java/org/opensearch/knn/index/query/KNNWeight.java
  src/main/java/org/opensearch/knn/jni/FaissService.java
  src/main/java/org/opensearch/knn/jni/JNIService.java
  src/main/java/org/opensearch/knn/training/TrainingJob.java
  src/test/java/org/opensearch/knn/index/KNNCreateIndexFromModelTests.java
  src/test/java/org/opensearch/knn/index/codec/KNN80Codec/KNN80DocValuesConsumerTests.java
  src/test/java/org/opensearch/knn/index/codec/KNNCodecTestCase.java
  src/test/java/org/opensearch/knn/index/codec/KNNCodecTestUtil.java
  src/test/java/org/opensearch/knn/index/memory/NativeMemoryAllocationTests.java
  src/test/java/org/opensearch/knn/index/memory/NativeMemoryLoadStrategyTests.java
  src/test/java/org/opensearch/knn/index/query/KNNWeightTests.java
  src/test/java/org/opensearch/knn/jni/JNIServiceTests.java
  src/test/java/org/opensearch/knn/training/TrainingJobTests.java
Labels: skip-changelog

#1543 Update k-NN build artifact script to enable SIMD on ARM for Faiss
  CHANGELOG.md
  scripts/build.sh
Labels: Infrastructure, backport 2.x

#1551 Enabled Inner Product Space Type support for Lucene Engine
  CHANGELOG.md
  src/main/java/org/opensearch/knn/index/util/Lucene.java
  src/test/java/org/opensearch/knn/index/LuceneEngineIT.java
  src/test/java/org/opensearch/knn/index/mapper/KNNVectorFieldMapperTests.java
  src/test/java/org/opensearch/knn/index/util/LuceneTests.java
Labels: Features, backport 2.x

#1545 Integrate index state sharing into mem management
  src/main/java/org/opensearch/knn/index/IndexUtil.java
  src/main/java/org/opensearch/knn/index/KNNIndexShard.java
  src/main/java/org/opensearch/knn/index/memory/NativeMemoryAllocation.java
  src/main/java/org/opensearch/knn/index/memory/NativeMemoryEntryContext.java
  src/main/java/org/opensearch/knn/index/memory/NativeMemoryLoadStrategy.java
  src/main/java/org/opensearch/knn/index/memory/SharedIndexState.java
  src/main/java/org/opensearch/knn/index/memory/SharedIndexStateManager.java
  src/main/java/org/opensearch/knn/index/query/KNNWeight.java
  src/test/java/org/opensearch/knn/index/FaissIT.java
  src/test/java/org/opensearch/knn/index/IndexUtilTests.java
  src/test/java/org/opensearch/knn/index/KNNIndexShardTests.java
  src/test/java/org/opensearch/knn/index/memory/SharedIndexStateManagerTests.java
  src/test/java/org/opensearch/knn/index/memory/SharedIndexStateTests.java
  src/test/java/org/opensearch/knn/recall/RecallTestsIT.java
  src/testFixtures/java/org/opensearch/knn/KNNRestTestCase.java
  src/testFixtures/java/org/opensearch/knn/TestUtils.java
Labels: skip-changelog

#1560 Remove Faiss AVX2 CI patch
  .github/workflows/CI.yml
  .github/workflows/test_security.yml
  jni/CMakeLists.txt
  jni/patches/faiss/0002-Custom-patch-to-support-AVX2-Linux-CI.patch
  jni/patches/faiss/0002-Enable-precomp-table-to-be-shared-ivfpq.patch
Labels: backport 2.x, skip-changelog

#1562 Faiss SQFP16 Range Validation and Clipping
  CHANGELOG.md
  qa/restart-upgrade/src/test/java/org/opensearch/knn/bwc/FaissSQIT.java
  src/main/java/org/opensearch/knn/common/KNNConstants.java
  src/main/java/org/opensearch/knn/index/Parameter.java
  src/main/java/org/opensearch/knn/index/mapper/KNNVectorFieldMapper.java
  src/main/java/org/opensearch/knn/index/mapper/KNNVectorFieldMapperUtil.java
  src/main/java/org/opensearch/knn/index/mapper/LuceneFieldMapper.java
  src/main/java/org/opensearch/knn/index/mapper/ModelFieldMapper.java
  src/main/java/org/opensearch/knn/index/util/Faiss.java
  src/test/java/org/opensearch/knn/index/FaissIT.java
  src/test/java/org/opensearch/knn/index/mapper/KNNVectorFieldMapperTests.java
Labels: backport 2.x

#1564 Add release notes for 2.13.0 release
  CHANGELOG.md
  release-notes/opensearch-knn.release-notes-2.13.0.0.md
Labels: backport 2.x

#1567 Upgrade byte-buddy version to 1.14.9
  build.gradle
Labels: backport 2.x, skip-changelog, v2.13.0, backport 2.13

#1578 Add no new development notice to perf tool
  benchmarks/osb/README.md
  benchmarks/perf-tool/README.md
Labels: backport 2.x, skip-changelog

#1583 Add micro-benchmark module in k-NN plugin for benchmark streaming vectors to JNI layer functionality.
  CHANGELOG.md
  jni/include/org_opensearch_knn_jni_FaissService.h
  jni/src/org_opensearch_knn_jni_FaissService.cpp
  micro-benchmarks/README.md
  micro-benchmarks/build.gradle
  micro-benchmarks/src/main/java/org/opensearch/knn/TransferVectorsBenchmarks.java
  micro-benchmarks/src/main/resources/log4j2.properties
  settings.gradle
  src/main/java/org/opensearch/knn/index/KNNSettings.java
  src/main/java/org/opensearch/knn/jni/FaissService.java
  src/main/java/org/opensearch/knn/jni/JNIService.java
Labels: backport 2.x, benchmarking, v2.14.0
