Repository opensearch-project/k-NN, pull requests merged in 2024-10, with the labels that each got.

#2142 Add integration test for binary vector values
  src/test/java/org/opensearch/knn/integ/BinaryIndexIT.java
Labels: skip-changelog

#2136 Add exact search if no native engine files are available
  CHANGELOG.md
  src/main/java/org/opensearch/knn/index/query/KNNWeight.java
  src/test/java/org/opensearch/knn/index/OpenSearchIT.java
  src/test/java/org/opensearch/knn/index/codec/KNN990Codec/NativeEngineFieldVectorsWriterTests.java
  src/test/java/org/opensearch/knn/index/query/KNNWeightTests.java
  src/test/java/org/opensearch/knn/integ/BinaryIndexIT.java
Labels: skip-changelog

#2174 Add support for radial search in exact search
  src/main/java/org/opensearch/knn/index/query/ExactSearcher.java
  src/main/java/org/opensearch/knn/index/query/KNNWeight.java
  src/main/java/org/opensearch/knn/index/query/RNNQueryFactory.java
  src/test/java/org/opensearch/knn/index/FaissIT.java
  src/test/java/org/opensearch/knn/index/OpenSearchIT.java
  src/test/java/org/opensearch/knn/index/query/ExactSearcherTests.java
  src/test/java/org/opensearch/knn/index/query/KNNWeightTests.java
  src/test/java/org/opensearch/knn/integ/BinaryIndexIT.java
Labels: skip-changelog

#2183 Score Fix for Binary Quantized Vector and Setting Default value in case of shard level rescoring is disabled for oversampling factor
  CHANGELOG.md
  src/main/java/org/opensearch/knn/index/KNNSettings.java
  src/main/java/org/opensearch/knn/index/mapper/CompressionLevel.java
  src/main/java/org/opensearch/knn/index/query/KNNWeight.java
  src/main/java/org/opensearch/knn/index/query/nativelib/NativeEngineKnnVectorQuery.java
  src/main/java/org/opensearch/knn/index/query/rescore/RescoreContext.java
  src/test/java/org/opensearch/knn/index/KNNSettingsTests.java
  src/test/java/org/opensearch/knn/index/mapper/CompressionLevelTests.java
  src/test/java/org/opensearch/knn/index/query/KNNQueryBuilderTests.java
  src/test/java/org/opensearch/knn/index/query/KNNWeightTests.java
  src/test/java/org/opensearch/knn/index/query/nativelib/NativeEngineKNNVectorQueryTests.java
  src/test/java/org/opensearch/knn/index/query/rescore/RescoreContextTests.java
Labels: backport 2.x

#2195 Fix lucene codec after lucene version bumped to 9.12
  CHANGELOG.md
  src/main/java/org/opensearch/knn/index/codec/KNN9120Codec/KNN9120Codec.java
  src/main/java/org/opensearch/knn/index/codec/KNN990Codec/NativeEngineFieldVectorsWriter.java
  src/main/java/org/opensearch/knn/index/codec/KNN990Codec/NativeEngines990KnnVectorsWriter.java
  src/main/java/org/opensearch/knn/index/codec/KNNCodecVersion.java
  src/main/java/org/opensearch/knn/index/codec/params/KNNScalarQuantizedVectorsFormatParams.java
  src/main/resources/META-INF/services/org.apache.lucene.codecs.Codec
  src/test/java/org/opensearch/knn/index/codec/KNN990Codec/NativeEngineFieldVectorsWriterTests.java
  src/test/java/org/opensearch/knn/index/codec/KNN990Codec/NativeEngines990KnnVectorsWriterFlushTests.java
  src/test/java/org/opensearch/knn/index/codec/KNN990Codec/NativeEngines990KnnVectorsWriterMergeTests.java
  src/test/java/org/opensearch/knn/index/codec/params/KNNScalarQuantizedVectorsFormatParamsTests.java
Labels: Maintenance

#2198 Fix changelog so changes for 2.x are in 2.x
  CHANGELOG.md
Labels: Infrastructure, backport 2.x, skip-changelog

#2188 Add support to build vector data structures greedily and perform exact search when there are no engine files
  CHANGELOG.md
  src/main/java/org/opensearch/knn/index/KNNSettings.java
  src/main/java/org/opensearch/knn/index/codec/BasePerFieldKnnVectorsFormat.java
  src/main/java/org/opensearch/knn/index/codec/KNN990Codec/NativeEngines990KnnVectorsFormat.java
  src/main/java/org/opensearch/knn/index/codec/KNN990Codec/NativeEngines990KnnVectorsWriter.java
  src/main/java/org/opensearch/knn/index/query/ExactSearcher.java
  src/main/java/org/opensearch/knn/index/query/KNNWeight.java
  src/main/java/org/opensearch/knn/index/query/RNNQueryFactory.java
  src/main/java/org/opensearch/knn/index/query/nativelib/NativeEngineKnnVectorQuery.java
  src/test/java/org/opensearch/knn/index/FaissIT.java
  src/test/java/org/opensearch/knn/index/OpenSearchIT.java
  src/test/java/org/opensearch/knn/index/codec/KNN990Codec/NativeEngineFieldVectorsWriterTests.java
  src/test/java/org/opensearch/knn/index/codec/KNN990Codec/NativeEngines990KnnVectorsWriterFlushTests.java
  src/test/java/org/opensearch/knn/index/codec/KNN990Codec/NativeEngines990KnnVectorsWriterMergeTests.java
  src/test/java/org/opensearch/knn/index/query/ExactSearcherTests.java
  src/test/java/org/opensearch/knn/index/query/KNNWeightTests.java
  src/test/java/org/opensearch/knn/integ/BinaryIndexIT.java
  src/testFixtures/java/org/opensearch/knn/KNNRestTestCase.java
Labels: Enhancements, backport 2.x, v2.18.0

#2204 Bump byte-buddy to 1.15.4
  build.gradle
Labels: backport 2.x, skip-changelog

#2202 Adding shatejas as the maintainer
  .github/CODEOWNERS
  MAINTAINERS.md
Labels: backport 2.x, skip-changelog

#2206 Minor code fixes to remove code inconsistencies.
  src/main/java/org/opensearch/knn/index/query/KNNQuery.java
  src/main/java/org/opensearch/knn/index/query/nativelib/NativeEngineKnnVectorQuery.java
  src/test/java/org/opensearch/knn/index/query/nativelib/NativeEngineKNNVectorQueryTests.java
Labels: skip-changelog

#2185 Introduce a loading layer in NMSLIB.
  jni/CMakeLists.txt
  jni/cmake/init-nmslib.cmake
  jni/include/faiss_stream_support.h
  jni/include/jni_util.h
  jni/include/native_engines_stream_support.h
  jni/include/nmslib_stream_support.h
  jni/include/nmslib_wrapper.h
  jni/include/org_opensearch_knn_jni_NmslibService.h
  jni/patches/nmslib/0003-Added-streaming-apis-for-vector-index-loading-in-Hnsw.patch
  jni/patches/nmslib/0003-Adding-two-apis-using-stream-to-load-save-in-Hnsw.patch
  jni/src/jni_util.cpp
  jni/src/nmslib_wrapper.cpp
  jni/src/org_opensearch_knn_jni_NmslibService.cpp
  jni/tests/faiss_stream_support_test.cpp
  jni/tests/native_stream_support_util.h
  jni/tests/nmslib_stream_support_test.cpp
  jni/tests/test_util.h
  src/main/java/org/opensearch/knn/index/memory/NativeMemoryAllocation.java
  src/main/java/org/opensearch/knn/index/memory/NativeMemoryLoadStrategy.java
  src/main/java/org/opensearch/knn/index/store/IndexInputWithBuffer.java
  src/main/java/org/opensearch/knn/jni/JNIService.java
  src/main/java/org/opensearch/knn/jni/NmslibService.java
  src/test/java/org/opensearch/knn/index/KNNCircuitBreakerIT.java
  src/test/java/org/opensearch/knn/jni/JNIServiceTests.java
Labels: backport 2.x, skip-changelog

#2200 Add CompressionLevel Calculation for PQ
  CHANGELOG.md
  src/main/java/org/opensearch/knn/index/engine/faiss/AbstractFaissPQEncoder.java
  src/main/java/org/opensearch/knn/index/engine/faiss/FaissHNSWPQEncoder.java
  src/main/java/org/opensearch/knn/index/engine/faiss/FaissIVFPQEncoder.java
  src/main/java/org/opensearch/knn/index/mapper/CompressionLevel.java
  src/main/java/org/opensearch/knn/index/mapper/KNNVectorFieldMapper.java
  src/test/java/org/opensearch/knn/index/FaissIT.java
  src/test/java/org/opensearch/knn/index/engine/faiss/AbstractFaissPQEncoderTests.java
  src/test/java/org/opensearch/knn/index/engine/faiss/FaissHNSWPQEncoderTests.java
  src/test/java/org/opensearch/knn/index/engine/faiss/FaissIVFPQEncoderTests.java
  src/test/java/org/opensearch/knn/integ/ModeAndCompressionIT.java
Labels: Enhancements, backport 2.x

#2228 [Backport 2.x] Add Release Notes for 2.18.0.0 (#2227)
  CHANGELOG.md
  release-notes/opensearch-knn.release-notes-2.18.0.0.md
Labels: skip-changelog

#2229 Update approximate_threshold to 15K documents
  qa/restart-upgrade/src/test/java/org/opensearch/knn/bwc/ClearCacheIT.java
  qa/restart-upgrade/src/test/java/org/opensearch/knn/bwc/IndexingIT.java
  qa/restart-upgrade/src/test/java/org/opensearch/knn/bwc/WarmupIT.java
  qa/rolling-upgrade/src/test/java/org/opensearch/knn/bwc/ClearCacheIT.java
  qa/rolling-upgrade/src/test/java/org/opensearch/knn/bwc/WarmupIT.java
  release-notes/opensearch-knn.release-notes-2.18.0.0.md
  src/main/java/org/opensearch/knn/index/KNNSettings.java
  src/main/java/org/opensearch/knn/index/codec/KNN990Codec/NativeEngines990KnnVectorsFormat.java
  src/main/java/org/opensearch/knn/index/codec/KNN990Codec/UnitTestCodec.java
  src/test/java/org/opensearch/knn/KNNSingleNodeTestCase.java
  src/test/java/org/opensearch/knn/index/KNNCircuitBreakerIT.java
  src/test/java/org/opensearch/knn/index/KNNESSettingsTestIT.java
  src/test/java/org/opensearch/knn/index/KNNIndexShardTests.java
  src/test/java/org/opensearch/knn/index/NmslibIT.java
  src/test/java/org/opensearch/knn/index/OpenSearchIT.java
  src/test/java/org/opensearch/knn/plugin/action/RestClearCacheHandlerIT.java
  src/test/java/org/opensearch/knn/plugin/action/RestKNNStatsHandlerIT.java
  src/test/java/org/opensearch/knn/plugin/action/RestKNNWarmupHandlerIT.java
  src/test/java/org/opensearch/knn/plugin/action/RestLegacyKNNStatsHandlerIT.java
  src/test/java/org/opensearch/knn/plugin/action/RestLegacyKNNWarmupHandlerIT.java
  src/test/java/org/opensearch/knn/plugin/transport/ClearCacheTransportActionTests.java
  src/test/java/org/opensearch/knn/plugin/transport/KNNWarmupTransportActionTests.java
  src/testFixtures/java/org/opensearch/knn/KNNRestTestCase.java
Labels: backport 2.x, skip-changelog

#2231 [Backport 2.x] Update approximate_threshold to 15K documents (#2229)
  qa/restart-upgrade/src/test/java/org/opensearch/knn/bwc/ClearCacheIT.java
  qa/restart-upgrade/src/test/java/org/opensearch/knn/bwc/IndexingIT.java
  qa/restart-upgrade/src/test/java/org/opensearch/knn/bwc/WarmupIT.java
  qa/rolling-upgrade/src/test/java/org/opensearch/knn/bwc/ClearCacheIT.java
  qa/rolling-upgrade/src/test/java/org/opensearch/knn/bwc/WarmupIT.java
  release-notes/opensearch-knn.release-notes-2.18.0.0.md
  src/main/java/org/opensearch/knn/index/KNNSettings.java
  src/main/java/org/opensearch/knn/index/codec/KNN990Codec/NativeEngines990KnnVectorsFormat.java
  src/main/java/org/opensearch/knn/index/codec/KNN990Codec/UnitTestCodec.java
  src/test/java/org/opensearch/knn/KNNSingleNodeTestCase.java
  src/test/java/org/opensearch/knn/index/KNNCircuitBreakerIT.java
  src/test/java/org/opensearch/knn/index/KNNESSettingsTestIT.java
  src/test/java/org/opensearch/knn/index/KNNIndexShardTests.java
  src/test/java/org/opensearch/knn/index/NmslibIT.java
  src/test/java/org/opensearch/knn/index/OpenSearchIT.java
  src/test/java/org/opensearch/knn/plugin/action/RestClearCacheHandlerIT.java
  src/test/java/org/opensearch/knn/plugin/action/RestKNNStatsHandlerIT.java
  src/test/java/org/opensearch/knn/plugin/action/RestKNNWarmupHandlerIT.java
  src/test/java/org/opensearch/knn/plugin/action/RestLegacyKNNStatsHandlerIT.java
  src/test/java/org/opensearch/knn/plugin/action/RestLegacyKNNWarmupHandlerIT.java
  src/test/java/org/opensearch/knn/plugin/transport/ClearCacheTransportActionTests.java
  src/test/java/org/opensearch/knn/plugin/transport/KNNWarmupTransportActionTests.java
  src/testFixtures/java/org/opensearch/knn/KNNRestTestCase.java
Labels: skip-changelog

#2232 update warmup rolling upgrade scenario
  qa/rolling-upgrade/src/test/java/org/opensearch/knn/bwc/WarmupIT.java
Labels: skip-changelog

#2235 Update default engine to FAISS
  qa/restart-upgrade/src/test/java/org/opensearch/knn/bwc/IndexingIT.java
  release-notes/opensearch-knn.release-notes-2.18.0.0.md
  src/main/java/org/opensearch/knn/index/engine/EngineResolver.java
  src/main/java/org/opensearch/knn/index/engine/KNNEngine.java
  src/main/java/org/opensearch/knn/index/mapper/KNNVectorFieldMapper.java
  src/main/java/org/opensearch/knn/index/query/KNNWeight.java
  src/test/java/org/opensearch/knn/KNNSingleNodeTestCase.java
  src/test/java/org/opensearch/knn/index/KNNIndexShardTests.java
  src/test/java/org/opensearch/knn/index/NmslibIT.java
  src/test/java/org/opensearch/knn/index/VectorDataTypeIT.java
  src/test/java/org/opensearch/knn/index/codec/KNN80Codec/KNN80DocValuesConsumerTests.java
  src/test/java/org/opensearch/knn/index/codec/KNNCodecTestCase.java
  src/test/java/org/opensearch/knn/index/engine/EngineResolverTests.java
  src/test/java/org/opensearch/knn/index/engine/KNNEngineTests.java
  src/test/java/org/opensearch/knn/index/mapper/KNNVectorFieldMapperTests.java
  src/test/java/org/opensearch/knn/index/query/KNNWeightTests.java
  src/test/java/org/opensearch/knn/jni/JNIServiceTests.java
  src/test/java/org/opensearch/knn/plugin/transport/GetModelResponseTests.java
  src/test/java/org/opensearch/knn/plugin/transport/TrainingModelRequestTests.java
Labels: skip-changelog

#2236 Select index settings based on cluster version
  CHANGELOG.md
  qa/restart-upgrade/src/test/java/org/opensearch/knn/bwc/ClearCacheIT.java
  qa/restart-upgrade/src/test/java/org/opensearch/knn/bwc/IndexingIT.java
  qa/restart-upgrade/src/test/java/org/opensearch/knn/bwc/WarmupIT.java
  qa/rolling-upgrade/src/test/java/org/opensearch/knn/bwc/ClearCacheIT.java
  qa/rolling-upgrade/src/test/java/org/opensearch/knn/bwc/WarmupIT.java
  src/testFixtures/java/org/opensearch/knn/KNNRestTestCase.java
Labels: backport 2.x
