Repository opensearch-project/k-NN, pull requests merged in 2025-08, with the labels that each got.

#2835 Deduplicating Vectors for Space Optimization
  src/main/java/org/opensearch/knn/index/KNNIndexShard.java
  src/main/java/org/opensearch/knn/index/codec/KNN990Codec/NativeEngines990KnnVectorsReader.java
  src/main/java/org/opensearch/knn/index/memory/NativeMemoryEntryContext.java
  src/main/java/org/opensearch/knn/index/memory/NativeMemoryLoadStrategy.java
  src/main/java/org/opensearch/knn/index/query/DefaultKNNWeight.java
  src/main/java/org/opensearch/knn/index/store/IndexInputWithBuffer.java
  src/main/java/org/opensearch/knn/index/store/VectorReader.java
  src/main/java/org/opensearch/knn/memoryoptsearch/FlatVectorsReaderWithFieldName.java
  src/main/java/org/opensearch/knn/memoryoptsearch/VectorSearcherFactory.java
  src/main/java/org/opensearch/knn/memoryoptsearch/faiss/FaissHNSWIndex.java
  src/main/java/org/opensearch/knn/memoryoptsearch/faiss/FaissIdMapIndex.java
  src/main/java/org/opensearch/knn/memoryoptsearch/faiss/FaissIndex.java
  src/main/java/org/opensearch/knn/memoryoptsearch/faiss/FaissIndexFloatFlat.java
  src/main/java/org/opensearch/knn/memoryoptsearch/faiss/FaissIndexLoadUtils.java
  src/main/java/org/opensearch/knn/memoryoptsearch/faiss/FaissIndexScalarQuantizedFlat.java
  src/main/java/org/opensearch/knn/memoryoptsearch/faiss/FaissMemoryOptimizedSearcher.java
  src/main/java/org/opensearch/knn/memoryoptsearch/faiss/FaissMemoryOptimizedSearcherFactory.java
  src/main/java/org/opensearch/knn/memoryoptsearch/faiss/binary/FaissBinaryHnswIndex.java
  src/main/java/org/opensearch/knn/memoryoptsearch/faiss/binary/FaissIndexBinaryFlat.java
  src/main/java/org/opensearch/knn/memoryoptsearch/faiss/cagra/FaissHNSWCagraBinaryIndex.java
  src/main/java/org/opensearch/knn/memoryoptsearch/faiss/cagra/FaissHNSWCagraIndex.java
  src/test/java/org/opensearch/knn/index/codec/KNN990Codec/NativeEngines990KnnVectorsReaderTests.java
  src/test/java/org/opensearch/knn/index/memory/NativeMemoryCacheManagerTests.java
  src/test/java/org/opensearch/knn/index/memory/NativeMemoryEntryContextTests.java
  src/test/java/org/opensearch/knn/index/memory/NativeMemoryLoadStrategyTests.java
  src/test/java/org/opensearch/knn/index/query/ExplainTests.java
  src/test/java/org/opensearch/knn/index/query/KNNWeightTests.java
  src/test/java/org/opensearch/knn/memoryoptsearch/AbstractFaissCagraHnswIndexTests.java
  src/test/java/org/opensearch/knn/memoryoptsearch/FaissBinaryHnswIndexTests.java
  src/test/java/org/opensearch/knn/memoryoptsearch/FaissByteIndexTests.java
  src/test/java/org/opensearch/knn/memoryoptsearch/FaissCagraHnswIndexTests.java
  src/test/java/org/opensearch/knn/memoryoptsearch/FaissIdMapIndexTests.java
  src/test/java/org/opensearch/knn/memoryoptsearch/FaissIndexBinaryFlatTests.java
  src/test/java/org/opensearch/knn/memoryoptsearch/FaissIndexFloatFlatTests.java
Labels: skip-changelog

#2817 [GRPC] Extend transport-grpc module to support GRPC KNN queries
  build.gradle
  qa/build.gradle
  qa/restart-upgrade/build.gradle
  qa/rolling-upgrade/build.gradle
  release-notes/opensearch-k-NN.release-notes-3.2.0.0.md
  src/main/java/org/opensearch/knn/grpc/proto/request/search/query/KNNQueryBuilderProtoConverter.java
  src/main/java/org/opensearch/knn/grpc/proto/request/search/query/KNNQueryBuilderProtoUtils.java
  src/main/resources/META-INF/services/org.opensearch.transport.grpc.proto.request.search.query.QueryBuilderProtoConverter
  src/test/java/org/opensearch/knn/grpc/proto/request/search/query/KNNQueryBuilderProtoConverterTests.java
  src/test/java/org/opensearch/knn/grpc/proto/request/search/query/KNNQueryBuilderProtoUtilsTests.java
Labels: skip-changelog, backport 3.2

#2736 Add engine as a top level mapping parameter
  CHANGELOG.md
  src/main/java/org/opensearch/knn/common/KNNConstants.java
  src/main/java/org/opensearch/knn/index/engine/EngineResolver.java
  src/main/java/org/opensearch/knn/index/engine/KNNEngine.java
  src/main/java/org/opensearch/knn/index/engine/KNNMethodContext.java
  src/main/java/org/opensearch/knn/index/mapper/KNNVectorFieldMapper.java
  src/main/java/org/opensearch/knn/index/mapper/OriginalMappingParameters.java
  src/main/java/org/opensearch/knn/index/util/IndexUtil.java
  src/main/java/org/opensearch/knn/plugin/rest/RestTrainModelHandler.java
  src/main/java/org/opensearch/knn/plugin/transport/TrainingModelRequest.java
  src/test/java/org/opensearch/knn/index/engine/EngineResolverTests.java
  src/test/java/org/opensearch/knn/index/engine/KNNEngineTests.java
  src/test/java/org/opensearch/knn/index/engine/KNNMethodContextTests.java
  src/test/java/org/opensearch/knn/index/mapper/KNNVectorFieldMapperTests.java
  src/test/java/org/opensearch/knn/index/mapper/OriginalMappingParametersTests.java
  src/test/java/org/opensearch/knn/index/query/KNNQueryBuilderTests.java
  src/test/java/org/opensearch/knn/integ/TopLevelEngineParameterIT.java
Labels: Enhancements
