Repository opensearch-project/k-NN, pull requests merged in 2025-04, with the labels that each got.

#2634 Add checks to block derived source feature
  src/main/java/org/opensearch/knn/index/DerivedKnnByteVectorField.java
  src/main/java/org/opensearch/knn/index/DerivedKnnFloatVectorField.java
  src/main/java/org/opensearch/knn/index/codec/KNN10010Codec/KNN10010DerivedSourceStoredFieldsFormat.java
  src/main/java/org/opensearch/knn/index/codec/derivedsource/DerivedSourceIndexOperationListener.java
  src/main/java/org/opensearch/knn/index/mapper/KNNVectorFieldMapper.java
  src/main/java/org/opensearch/knn/index/mapper/LuceneFieldMapper.java
  src/main/java/org/opensearch/knn/index/util/IndexUtil.java
  src/test/java/org/opensearch/knn/index/codec/derivedsource/DerivedSourceIndexOperationListenerTests.java
  src/test/java/org/opensearch/knn/index/mapper/KNNVectorFieldMapperTests.java
  src/test/java/org/opensearch/knn/integ/DerivedSourceIT.java
  src/testFixtures/java/org/opensearch/knn/DerivedSourceTestCase.java
  src/testFixtures/java/org/opensearch/knn/DerivedSourceUtils.java
Labels: v3.0.0, skip-changelog

#2637 Optimize first child lookup for nested docs
  qa/restart-upgrade/src/test/java/org/opensearch/knn/bwc/DerivedSourceBWCRestartIT.java
  src/main/java/org/opensearch/knn/index/codec/derivedsource/DerivedSourceLuceneHelper.java
  src/test/java/org/opensearch/knn/index/codec/derivedsource/DerivedSourceLuceneHelperTests.java
  src/test/java/org/opensearch/knn/integ/DerivedSourceIT.java
  src/testFixtures/java/org/opensearch/knn/DerivedSourceTestCase.java
  src/testFixtures/java/org/opensearch/knn/DerivedSourceUtils.java
Labels: v3.0.0, skip-changelog

#2648 Enhance derived source integ tests
  build.gradle
  src/test/java/org/opensearch/knn/integ/DerivedSourceIT.java
  src/testFixtures/java/org/opensearch/knn/DerivedSourceTestCase.java
  src/testFixtures/java/org/opensearch/knn/KNNRestTestCase.java
Labels: v3.0.0, skip-changelog

#2498 Update engine for version 2.19 or above
  src/main/java/org/opensearch/knn/index/engine/EngineResolver.java
  src/main/java/org/opensearch/knn/index/mapper/KNNVectorFieldMapper.java
  src/main/java/org/opensearch/knn/plugin/transport/TrainingModelRequest.java
  src/test/java/org/opensearch/knn/index/engine/EngineResolverTests.java
  src/test/java/org/opensearch/knn/index/mapper/KNNVectorFieldMapperTests.java
Labels: skip-changelog

#2647 Add multi-vector-support faiss patch to IndexHNSW::search_level_0
  CHANGELOG.md
  jni/cmake/init-faiss.cmake
  jni/patches/faiss/0005-Custom-patch-to-support-multi-vector-IndexHNSW-search_level_0.patch
  jni/tests/faiss_wrapper_test.cpp
  src/test/java/org/opensearch/knn/jni/JNIServiceTests.java
  src/test/resources/data/remoteindexbuild/faiss_hnsw_cagra_nested_float_1000_vectors_128_dims.bin
Labels: v3.0.0

#2657 Fix build due to phasing off SecurityManager usage in favor of Java Agent
  build.gradle
  remote-index-build-client/build.gradle
  src/main/java/org/opensearch/knn/jni/PlatformUtils.java
  src/main/java/org/opensearch/knn/plugin/KNNPlugin.java
  src/test/java/org/opensearch/knn/KNNSingleNodeTestCase.java
  src/test/java/org/opensearch/knn/jni/PlatformUtilTests.java
Labels: skip-changelog

#2652 Prevent derived source from open reader per transform
  src/main/java/org/opensearch/knn/index/codec/KNN10010Codec/KNN10010DerivedSourceStoredFieldsFormat.java
  src/main/java/org/opensearch/knn/index/codec/KNN10010Codec/KNN10010DerivedSourceStoredFieldsReader.java
  src/main/java/org/opensearch/knn/index/codec/backward_codecs/KNN9120Codec/DerivedSourceVectorInjector.java
  src/main/java/org/opensearch/knn/index/codec/backward_codecs/KNN9120Codec/KNN9120DerivedSourceReaders.java
  src/main/java/org/opensearch/knn/index/codec/backward_codecs/KNN9120Codec/KNN9120DerivedSourceStoredFieldsFormat.java
  src/main/java/org/opensearch/knn/index/codec/backward_codecs/KNN9120Codec/KNN9120DerivedSourceStoredFieldsReader.java
  src/main/java/org/opensearch/knn/index/codec/derivedsource/DerivedSourceReaders.java
  src/main/java/org/opensearch/knn/index/codec/derivedsource/DerivedSourceVectorTransformer.java
  src/test/java/org/opensearch/knn/index/codec/backward_codecs/KNN9120Codec/DerivedSourceVectorInjectorTests.java
  src/test/java/org/opensearch/knn/index/codec/derivedsource/DerivedSourceReadersTests.java
Labels: Bug Fixes, v3.0.0, skip-changelog

#2403 Explain API for Exact/ANN/Radial/Disk based KNN search on Faiss
  release-notes/opensearch-knn.release-notes-3.0.0.0-beta1.md
  src/main/java/org/opensearch/knn/common/KNNConstants.java
  src/main/java/org/opensearch/knn/index/SpaceType.java
  src/main/java/org/opensearch/knn/index/query/KNNQuery.java
  src/main/java/org/opensearch/knn/index/query/KNNWeight.java
  src/main/java/org/opensearch/knn/index/query/common/DocAndScoreQuery.java
  src/main/java/org/opensearch/knn/index/query/common/QueryUtils.java
  src/main/java/org/opensearch/knn/index/query/explain/KnnExplanation.java
  src/main/java/org/opensearch/knn/index/query/nativelib/NativeEngineKnnVectorQuery.java
  src/test/java/org/opensearch/knn/index/ExplainIT.java
  src/test/java/org/opensearch/knn/index/query/ExplainTests.java
  src/test/java/org/opensearch/knn/index/query/KNNWeightTestCase.java
  src/test/java/org/opensearch/knn/index/query/KNNWeightTests.java
  src/test/java/org/opensearch/knn/index/query/common/DocAndScoreQueryTests.java
  src/test/java/org/opensearch/knn/index/query/nativelib/NativeEngineKNNVectorQueryTests.java
Labels: skip-changelog

#2650 [Bug fix LuceneOnFaiss] Having field info to have a corresponding Lucene vector similarity function.
  src/main/java/org/opensearch/knn/index/mapper/EngineFieldMapper.java
  src/test/java/org/opensearch/knn/index/mapper/KNNVectorFieldMapperTests.java
Labels: skip-changelog

#2663 Fix concurrency bug to share non-thread safe graph structure.
  src/main/java/org/opensearch/knn/memoryoptsearch/faiss/FaissMemoryOptimizedSearcher.java
Labels: skip-changelog

#2664 Switch derived to default and fix bug in byte derived
  qa/restart-upgrade/src/test/java/org/opensearch/knn/bwc/DerivedSourceBWCRestartIT.java
  src/main/java/org/opensearch/knn/common/FieldInfoExtractor.java
  src/main/java/org/opensearch/knn/index/KNNSettings.java
  src/main/java/org/opensearch/knn/plugin/KNNPlugin.java
  src/test/java/org/opensearch/knn/integ/DerivedSourceIT.java
  src/testFixtures/java/org/opensearch/knn/DerivedSourceTestCase.java
Labels: skip-changelog

#2639 Change skip building vector data structure log to debug level
  src/main/java/org/opensearch/knn/index/codec/KNN990Codec/NativeEngines990KnnVectorsWriter.java
Labels: Maintenance, skip-changelog

#2668 Fix build.gradle AVX settings to not to use default value.
  build.gradle
Labels: skip-changelog

#2669 Minor code refactoring for explain
  src/main/java/org/opensearch/knn/index/query/KNNWeight.java
  src/test/java/org/opensearch/knn/index/ExplainIT.java
Labels: Maintenance, skip-changelog

#2683 Remove beta1 qualifier
  build.gradle
Labels: release, v3.0.0, backport main, skip-changelog

#2685 [Backport 2.19] [Bug-fix] Enables rescoring by default when dimensions > 1024. (#2671)
  release-notes/opensearch-knn.release-notes-2.19.2.0.md
  src/main/java/org/opensearch/knn/index/mapper/CompressionLevel.java
  src/test/java/org/opensearch/knn/index/mapper/CompressionLevelTests.java
  src/test/java/org/opensearch/knn/integ/ModeAndCompressionIT.java
  src/testFixtures/java/org/opensearch/knn/KNNRestTestCase.java
Labels: Bug Fixes, skip-changelog
