Repository opensearch-project/k-NN, pull requests merged in 2025-03, with the labels that each got.

#2571 Update gradle to 8.13 to fix command exec on java 21
  CHANGELOG.md
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  qa/restart-upgrade/build.gradle
  qa/rolling-upgrade/build.gradle
  scripts/build.sh
Labels: Maintenance, v3.0.0

#2574 Add fix for nmslib pragma on arm
  CHANGELOG.md
  DEVELOPER_GUIDE.md
  jni/cmake/init-nmslib.cmake
  jni/patches/nmslib/0005-Add-util-include-to-fix-pragma-error.patch
Labels: Maintenance

#2560 [Remote Vector Index Build] Introduce RemoteIndexClient skeleton and Build Request construction
  CHANGELOG.md
  build.gradle
  src/main/java/org/opensearch/knn/index/KNNSettings.java
  src/main/java/org/opensearch/knn/index/codec/nativeindex/remote/DefaultVectorRepositoryAccessor.java
  src/main/java/org/opensearch/knn/index/codec/nativeindex/remote/RemoteIndexBuildStrategy.java
  src/main/java/org/opensearch/knn/index/engine/KNNEngine.java
  src/main/java/org/opensearch/knn/index/engine/KNNLibrary.java
  src/main/java/org/opensearch/knn/index/engine/faiss/Faiss.java
  src/main/java/org/opensearch/knn/index/engine/faiss/FaissHNSWMethod.java
  src/main/java/org/opensearch/knn/index/remote/KNNRemoteConstants.java
  src/main/java/org/opensearch/knn/index/remote/RemoteBuildRequest.java
  src/main/java/org/opensearch/knn/index/remote/RemoteBuildResponse.java
  src/main/java/org/opensearch/knn/index/remote/RemoteFaissHNSWIndexParameters.java
  src/main/java/org/opensearch/knn/index/remote/RemoteIndexClient.java
  src/main/java/org/opensearch/knn/index/remote/RemoteIndexClientFactory.java
  src/main/java/org/opensearch/knn/index/remote/RemoteIndexHTTPClient.java
  src/main/java/org/opensearch/knn/index/remote/RemoteIndexHTTPClientRetryStrategy.java
  src/main/java/org/opensearch/knn/index/remote/RemoteIndexParameters.java
  src/main/java/org/opensearch/knn/index/remote/RemoteStatusResponse.java
  src/main/java/org/opensearch/knn/plugin/KNNPlugin.java
  src/test/java/org/opensearch/knn/index/codec/nativeindex/remote/DefaultVectorRepositoryAccessorTests.java
  src/test/java/org/opensearch/knn/index/remote/RemoteBuildRequestTests.java
  src/test/java/org/opensearch/knn/index/remote/RemoteBuildResponseTests.java
  src/test/java/org/opensearch/knn/index/remote/RemoteFaissHNSWIndexParametersTests.java
  src/test/java/org/opensearch/knn/index/remote/RemoteIndexHTTPClientTests.java
  src/test/java/org/opensearch/knn/index/remote/RemoteIndexParametersTests.java
Labels: v3.0.0

#2575 Improve Streaming Compatibility Issue for MethodComponetContext and Remove OpenDistro URL
  CHANGELOG.md
  src/main/java/org/opensearch/knn/index/engine/MethodComponentContext.java
  src/main/java/org/opensearch/knn/plugin/rest/RestKNNStatsHandler.java
  src/main/java/org/opensearch/knn/plugin/rest/RestKNNWarmupHandler.java
  src/test/java/org/opensearch/knn/index/engine/KNNMethodContextTests.java
  src/test/java/org/opensearch/knn/plugin/action/RestLegacyKNNStatsHandlerIT.java
  src/test/java/org/opensearch/knn/plugin/action/RestLegacyKNNWarmupHandlerIT.java
Labels: v3.0.0

#2578 Remove integrity checking TODO and leave up to the vendor implementation
  src/main/java/org/opensearch/knn/index/codec/nativeindex/remote/DefaultVectorRepositoryAccessor.java
  src/main/java/org/opensearch/knn/index/codec/nativeindex/remote/DocIdInputStream.java
  src/main/java/org/opensearch/knn/index/codec/nativeindex/remote/VectorValuesInputStream.java
  src/test/java/org/opensearch/knn/index/codec/nativeindex/remote/DefaultVectorRepositoryAccessorTests.java
  src/test/java/org/opensearch/knn/index/codec/nativeindex/remote/RemoteIndexBuildTests.java
Labels: v3.0.0, skip-changelog

#2587 Removes Array based vector serialization
  CHANGELOG.md
  src/main/java/org/opensearch/knn/index/VectorDataType.java
  src/main/java/org/opensearch/knn/index/VectorField.java
  src/main/java/org/opensearch/knn/index/codec/util/KNNVectorAsArraySerializer.java
  src/main/java/org/opensearch/knn/index/codec/util/KNNVectorAsCollectionOfFloatsSerializer.java
  src/main/java/org/opensearch/knn/index/codec/util/KNNVectorSerializerFactory.java
  src/main/java/org/opensearch/knn/index/codec/util/SerializationMode.java
  src/main/java/org/opensearch/knn/index/mapper/KNNVectorFieldMapperUtil.java
  src/main/java/org/opensearch/knn/index/vectorvalues/VectorValueExtractorStrategy.java
  src/test/java/org/opensearch/knn/index/KNNVectorDVLeafFieldDataTests.java
  src/test/java/org/opensearch/knn/index/KNNVectorScriptDocValuesTests.java
  src/test/java/org/opensearch/knn/index/VectorDataTypeTests.java
  src/test/java/org/opensearch/knn/index/codec/util/KNNVectorSerializerTests.java
  src/test/java/org/opensearch/knn/index/mapper/KNNVectorFieldMapperTests.java
  src/test/java/org/opensearch/knn/index/mapper/KNNVectorFieldMapperUtilTests.java
  src/test/java/org/opensearch/knn/index/query/KNNWeightTests.java
  src/test/java/org/opensearch/knn/index/vectorvalues/TestVectorValues.java
  src/test/java/org/opensearch/knn/plugin/script/KNNScoringUtilTests.java
  src/testFixtures/java/org/opensearch/knn/TestUtils.java
Labels: Maintenance, v3.0.0

#2581 [LuceneOnFaiss - Part1] Added building blocks for memory optimized search.
  src/main/java/org/opensearch/knn/index/codec/KNN990Codec/NativeEngines990KnnVectorsReader.java
  src/main/java/org/opensearch/knn/index/engine/KNNEngine.java
  src/main/java/org/opensearch/knn/index/engine/KNNLibrary.java
  src/main/java/org/opensearch/knn/index/engine/faiss/Faiss.java
  src/main/java/org/opensearch/knn/memoryoptsearch/VectorSearcher.java
  src/main/java/org/opensearch/knn/memoryoptsearch/VectorSearcherFactory.java
  src/main/java/org/opensearch/knn/memoryoptsearch/faiss/FaissMemoryOptimizedSearcher.java
  src/main/java/org/opensearch/knn/memoryoptsearch/faiss/FaissMemoryOptimizedSearcherFactory.java
  src/test/java/org/opensearch/knn/index/codec/KNN990Codec/NativeEngines990KnnVectorsReaderTests.java
  src/test/java/org/opensearch/knn/memoryoptsearch/FaissEngineTests.java
Labels: skip-changelog

#2596 Use latest json-smart lib to fix CVE-2024-57699
  build.gradle
Labels: skip-changelog

#2594 [LuceneOnFaiss - Part3] Added FaissHNSW graph.
  src/main/java/org/opensearch/knn/memoryoptsearch/faiss/FaissHNSW.java
  src/main/java/org/opensearch/knn/memoryoptsearch/faiss/FaissHNSWFlatIndex.java
  src/main/java/org/opensearch/knn/memoryoptsearch/faiss/FaissHNSWIndex.java
  src/main/java/org/opensearch/knn/memoryoptsearch/faiss/FaissHnswGraph.java
  src/main/java/org/opensearch/knn/memoryoptsearch/faiss/FaissIdMapIndex.java
  src/main/java/org/opensearch/knn/memoryoptsearch/faiss/FaissSection.java
  src/main/java/org/opensearch/knn/memoryoptsearch/faiss/IndexTypeToFaissIndexMapping.java
  src/test/java/org/opensearch/knn/memoryoptsearch/FaissHNSWTests.java
  src/test/java/org/opensearch/knn/memoryoptsearch/FaissHnswGraphTests.java
  src/test/java/org/opensearch/knn/memoryoptsearch/FaissIdMapIndexTests.java
  src/test/resources/data/memoryoptsearch/faiss_flat_float_50_vectors_128_dim.bin
  src/test/resources/data/memoryoptsearch/faiss_hnsw_100_vectors.bin
  src/test/resources/data/memoryoptsearch/faiss_hnsw_one_vector.bin
Labels: skip-changelog

#2597 Fix flaky test in RemoteIndexBuildStrategyTests.java
  src/test/java/org/opensearch/knn/index/codec/nativeindex/remote/RemoteIndexBuildStrategyTests.java
Labels: skip-changelog

#2601 NMSLib Build Issue due to GCC upgrade
  scripts/build.sh
Labels: skip-changelog

#2598 [LuceneOnFaiss - Part4] Added FAISS float flat index.
  src/main/java/org/opensearch/knn/memoryoptsearch/faiss/FaissIndexFloatFlat.java
  src/main/java/org/opensearch/knn/memoryoptsearch/faiss/IndexTypeToFaissIndexMapping.java
  src/test/java/org/opensearch/knn/memoryoptsearch/FaissIndexFloatFlatTests.java
Labels: skip-changelog

#2599 Add filter function to KNNQueryBuilder with unit tests and integration tests
  CHANGELOG.md
  src/main/java/org/opensearch/knn/index/query/KNNQueryBuilder.java
  src/test/java/org/opensearch/knn/index/FaissIT.java
  src/test/java/org/opensearch/knn/index/query/KNNQueryBuilderTests.java
Labels: Features

#2604 [LuceneOnFaiss - Part5] Added FAISS byte index deserializer - FaissIndexScalarQuantizedFlat
  src/main/java/org/opensearch/knn/memoryoptsearch/faiss/FaissIndexFloatFlat.java
  src/main/java/org/opensearch/knn/memoryoptsearch/faiss/FaissIndexScalarQuantizedFlat.java
  src/main/java/org/opensearch/knn/memoryoptsearch/faiss/IndexTypeToFaissIndexMapping.java
  src/test/java/org/opensearch/knn/memoryoptsearch/FaissByteIndexTests.java
  src/test/resources/data/memoryoptsearch/faiss_flat_byte_100_vectors_8_dim.bin
Labels: skip-changelog

#2606 Switch derived source from field attributes to segment attribute
  CHANGELOG.md
  qa/restart-upgrade/build.gradle
  qa/restart-upgrade/src/test/java/org/opensearch/knn/bwc/DerivedSourceBWCRestartIT.java
  src/main/java/org/opensearch/knn/common/KNNConstants.java
  src/main/java/org/opensearch/knn/index/codec/KNN10010Codec/KNN10010Codec.java
  src/main/java/org/opensearch/knn/index/codec/KNN10010Codec/KNN10010DerivedSourceStoredFieldsFormat.java
  src/main/java/org/opensearch/knn/index/codec/KNN10010Codec/KNN10010DerivedSourceStoredFieldsWriter.java
  src/main/java/org/opensearch/knn/index/codec/KNN9120Codec/KNN9120DerivedSourceStoredFieldsReader.java
  src/main/java/org/opensearch/knn/index/codec/backward_codecs/KNN9120Codec/KNN9120Codec.java
  src/main/java/org/opensearch/knn/index/codec/backward_codecs/KNN9120Codec/KNN9120DerivedSourceStoredFieldsFormat.java
  src/main/java/org/opensearch/knn/index/codec/derivedsource/DerivedSourceSegmentAttributeParser.java
  src/main/java/org/opensearch/knn/index/mapper/FlatVectorFieldMapper.java
  src/main/java/org/opensearch/knn/index/mapper/KNNVectorFieldMapper.java
  src/main/java/org/opensearch/knn/index/mapper/LuceneFieldMapper.java
  src/main/java/org/opensearch/knn/index/mapper/MethodFieldMapper.java
  src/main/java/org/opensearch/knn/index/mapper/ModelFieldMapper.java
  src/test/java/org/opensearch/knn/index/codec/KNN9120Codec/DerivedSourceStoredFieldsWriterTests.java
  src/test/java/org/opensearch/knn/index/codec/derivedsource/DerivedSourceSegmentAttributeParserTests.java
  src/test/java/org/opensearch/knn/index/mapper/KNNVectorFieldMapperTests.java
  src/test/java/org/opensearch/knn/integ/DerivedSourceIT.java
  src/testFixtures/java/org/opensearch/knn/DerivedSourceTestCase.java
Labels: Refactoring

#2607 Adding Breaking Changes Section in Release Note for 3.0.0
  release-notes/opensearch-knn.release-notes-3.0.0.0-alpha1.md
Labels: skip-changelog

#2610 Add VectorDataType check to NativeIndexBuildStrategy
  src/main/java/org/opensearch/knn/index/codec/nativeindex/NativeIndexBuildStrategyFactory.java
  src/main/java/org/opensearch/knn/index/engine/KNNEngine.java
  src/main/java/org/opensearch/knn/index/engine/KNNLibrary.java
  src/main/java/org/opensearch/knn/index/engine/faiss/Faiss.java
  src/main/java/org/opensearch/knn/index/engine/faiss/FaissHNSWMethod.java
  src/test/java/org/opensearch/knn/index/engine/KNNEngineTests.java
Labels: skip-changelog

#2608 [LuceneOnFaiss Part-7] Enable memory optimized searching in VectorReader for FAISS engine.
  src/main/java/org/opensearch/knn/index/codec/KNN990Codec/NativeEngines990KnnVectorsReader.java
  src/main/java/org/opensearch/knn/index/codec/util/KNNCodecUtil.java
  src/main/java/org/opensearch/knn/jni/JNIService.java
  src/main/java/org/opensearch/knn/memoryoptsearch/VectorSearcherFactory.java
  src/main/java/org/opensearch/knn/memoryoptsearch/faiss/FaissHnswGraph.java
  src/main/java/org/opensearch/knn/memoryoptsearch/faiss/FaissIndexScalarQuantizedFlat.java
  src/main/java/org/opensearch/knn/memoryoptsearch/faiss/FaissMemoryOptimizedSearcher.java
  src/main/java/org/opensearch/knn/memoryoptsearch/faiss/FaissMemoryOptimizedSearcherFactory.java
  src/test/java/org/opensearch/knn/index/codec/KNN990Codec/NativeEngines990KnnVectorsFormatTests.java
  src/test/java/org/opensearch/knn/index/codec/KNN990Codec/NativeEngines990KnnVectorsReaderTests.java
  src/test/java/org/opensearch/knn/index/codec/nativeindex/MemoryOptimizedSearchIndexingSupport.java
  src/test/java/org/opensearch/knn/memoryoptsearch/FaissEngineTests.java
  src/test/java/org/opensearch/knn/memoryoptsearch/FaissHnswGraphTests.java
  src/test/java/org/opensearch/knn/memoryoptsearch/FaissMemoryOptimizedSearcherTests.java
Labels: skip-changelog

#2621 [LuceneOnFaiss CAGRA] Added CAGRA index partial loading logic.
  src/main/java/org/opensearch/knn/memoryoptsearch/faiss/AbstractFaissHNSWIndex.java
  src/main/java/org/opensearch/knn/memoryoptsearch/faiss/FaissHNSW.java
  src/main/java/org/opensearch/knn/memoryoptsearch/faiss/FaissHNSWIndex.java
  src/main/java/org/opensearch/knn/memoryoptsearch/faiss/FaissIdMapIndex.java
  src/main/java/org/opensearch/knn/memoryoptsearch/faiss/IndexTypeToFaissIndexMapping.java
  src/main/java/org/opensearch/knn/memoryoptsearch/faiss/cagra/FaissCagraHNSW.java
  src/main/java/org/opensearch/knn/memoryoptsearch/faiss/cagra/FaissHNSWCagraIndex.java
  src/test/java/org/opensearch/knn/memoryoptsearch/FaissCagraHnswIndexTests.java
  src/test/resources/data/memoryoptsearch/faiss_cagra_flat_float_300_vectors_768_dims.bin
Labels: skip-changelog

#2616 [LuceneOnFaiss Part-8] Added `index.knn.memory_optimized_search` index setting.
  src/main/java/org/opensearch/knn/index/KNNSettings.java
  src/main/java/org/opensearch/knn/index/codec/BasePerFieldKnnVectorsFormat.java
  src/main/java/org/opensearch/knn/index/codec/KNN990Codec/NativeEngines990KnnVectorsFormat.java
  src/main/java/org/opensearch/knn/index/codec/KNN990Codec/NativeEngines990KnnVectorsReader.java
  src/main/java/org/opensearch/knn/index/engine/MemoryOptimizedSearchSupportSpec.java
  src/main/java/org/opensearch/knn/index/mapper/KNNVectorFieldType.java
  src/main/java/org/opensearch/knn/index/query/BaseQueryFactory.java
  src/main/java/org/opensearch/knn/index/query/KNNQueryBuilder.java
  src/main/java/org/opensearch/knn/index/query/KNNQueryFactory.java
  src/test/java/org/opensearch/knn/index/codec/KNN990Codec/NativeEngines990KnnVectorsReaderTests.java
  src/test/java/org/opensearch/knn/index/codec/nativeindex/MemoryOptimizedSearchFlagInFormatTests.java
  src/test/java/org/opensearch/knn/index/query/KNNQueryBuilderTests.java
  src/test/java/org/opensearch/knn/memoryoptsearch/MemoryOptimizedSearchSupportSpecTests.java
Labels: skip-changelog

#2609 [LuceneOnFaiss] Apply monotonic increasing integer encoding to FAISS HNSW and IdMapIndex.
  src/main/java/org/opensearch/knn/memoryoptsearch/faiss/FaissHNSW.java
  src/main/java/org/opensearch/knn/memoryoptsearch/faiss/FaissHnswGraph.java
  src/main/java/org/opensearch/knn/memoryoptsearch/faiss/FaissIdMapIndex.java
  src/main/java/org/opensearch/knn/memoryoptsearch/faiss/MonotonicIntegerSequenceEncoder.java
  src/test/java/org/opensearch/knn/memoryoptsearch/FaissHNSWTests.java
  src/test/java/org/opensearch/knn/memoryoptsearch/FaissIdMapIndexTests.java
  src/test/java/org/opensearch/knn/memoryoptsearch/MonotonicIntegerSequenceEncoderTests.java
Labels: skip-changelog

#2618 [LuceneOnFaiss Part-6] Adding byte index, FP16 index decoding.
  src/main/java/org/opensearch/knn/memoryoptsearch/faiss/FaissHNSWIndex.java
  src/main/java/org/opensearch/knn/memoryoptsearch/faiss/FaissIndexScalarQuantizedFlat.java
  src/main/java/org/opensearch/knn/memoryoptsearch/faiss/reconstruct/Faiss8BitsDirectSignedReconstructor.java
  src/main/java/org/opensearch/knn/memoryoptsearch/faiss/reconstruct/FaissFP16Reconstructor.java
  src/main/java/org/opensearch/knn/memoryoptsearch/faiss/reconstruct/FaissQuantizedValueReconstructor.java
  src/main/java/org/opensearch/knn/memoryoptsearch/faiss/reconstruct/FaissQuantizedValueReconstructorFactory.java
  src/main/java/org/opensearch/knn/memoryoptsearch/faiss/reconstruct/FaissQuantizerType.java
  src/test/java/org/opensearch/knn/memoryoptsearch/FaissByteIndexTests.java
  src/test/java/org/opensearch/knn/memoryoptsearch/FaissMemoryOptimizedSearcherTests.java
  src/test/java/org/opensearch/knn/memoryoptsearch/QuantizedValueReconstructorTests.java
Labels: skip-changelog

#2629 Add index operation listener to update translog source
  .github/workflows/backwards_compatibility_tests_workflow.yml
  CHANGELOG.md
  qa/restart-upgrade/build.gradle
  qa/restart-upgrade/src/test/java/org/opensearch/knn/bwc/DerivedSourceBWCRestartIT.java
  src/main/java/org/opensearch/knn/index/codec/KNN10010Codec/KNN10010DerivedSourceStoredFieldsWriter.java
  src/main/java/org/opensearch/knn/index/codec/derivedsource/DerivedSourceIndexOperationListener.java
  src/main/java/org/opensearch/knn/index/codec/derivedsource/DerivedSourceVectorTransformer.java
  src/main/java/org/opensearch/knn/plugin/KNNPlugin.java
  src/test/java/org/opensearch/knn/index/codec/derivedsource/DerivedSourceIndexOperationListenerTests.java
  src/test/java/org/opensearch/knn/integ/DerivedSourceIT.java
  src/testFixtures/java/org/opensearch/knn/DerivedSourceTestCase.java
  src/testFixtures/java/org/opensearch/knn/DerivedSourceUtils.java
  src/testFixtures/java/org/opensearch/knn/KNNRestTestCase.java
  src/testFixtures/java/org/opensearch/knn/Pair.java
Labels: Bug Fixes, v3.0.0

#2632 Update jna and bytebuddy version to match OpenSearch core
  build.gradle
Labels: skip-changelog
