Repository opensearch-project/k-NN, pull requests merged in 2025-09, with the labels that each got.

#2902 Increase the health check timeout for local stack to 30sec
  .github/workflows/remote_index_build.yml
Labels: Maintenance, skip-changelog

#2894 Remove dependency of common lang from all the modules
  qa/build.gradle
  remote-index-build-client/build.gradle
  remote-index-build-client/src/main/java/org/opensearch/remoteindexbuild/client/RemoteIndexHTTPClient.java
  src/main/java/org/opensearch/knn/common/FieldInfoExtractor.java
  src/main/java/org/opensearch/knn/index/codec/derivedsource/DerivedSourceSegmentAttributeParser.java
  src/main/java/org/opensearch/knn/index/codec/nativeindex/remote/DefaultVectorRepositoryAccessor.java
  src/main/java/org/opensearch/knn/index/engine/KNNMethodContext.java
  src/main/java/org/opensearch/knn/index/engine/MethodComponentContext.java
  src/main/java/org/opensearch/knn/index/engine/faiss/AbstractFaissMethod.java
  src/main/java/org/opensearch/knn/index/memory/NativeMemoryCacheManager.java
  src/main/java/org/opensearch/knn/index/remote/RemoteIndexPoller.java
  src/main/java/org/opensearch/knn/index/util/IndexUtil.java
  src/main/java/org/opensearch/knn/indices/ModelMetadata.java
  src/main/java/org/opensearch/knn/indices/ModelUtil.java
  src/main/java/org/opensearch/knn/jni/JNIService.java
  src/main/java/org/opensearch/knn/jni/PlatformUtils.java
  src/main/java/org/opensearch/knn/plugin/rest/RestGetModelHandler.java
  src/main/java/org/opensearch/knn/plugin/rest/RestKNNStatsHandler.java
  src/main/java/org/opensearch/knn/plugin/rest/RestKNNWarmupHandler.java
  src/main/java/org/opensearch/knn/plugin/transport/DeleteModelRequest.java
  src/main/java/org/opensearch/knn/plugin/transport/TrainingJobRouterTransportAction.java
  src/main/java/org/opensearch/knn/training/FloatTrainingDataConsumer.java
  src/main/java/org/opensearch/knn/training/TrainingJob.java
  src/test/java/org/opensearch/knn/index/LuceneEngineIT.java
  src/test/java/org/opensearch/knn/integ/BinaryIndexIT.java
  src/test/java/org/opensearch/knn/integ/IndexIT.java
  src/testFixtures/java/org/opensearch/knn/KNNRestTestCase.java
Labels: Maintenance, skip-changelog

#2903 Fixes integer overflow for efficient filtering
  CHANGELOG.md
  src/main/java/org/opensearch/knn/index/query/KNNQuery.java
  src/main/java/org/opensearch/knn/index/query/KNNWeight.java
  src/test/java/org/opensearch/knn/index/query/ExplainTests.java
  src/test/java/org/opensearch/knn/index/query/KNNQueryTests.java
  src/test/java/org/opensearch/knn/index/query/KNNWeightTests.java
Labels: backport 2.19, backport 3.1

#2904 [BulkSimd PR1] Added MMapByteVectorValues for FP16 in LuceneOnFaiss.
  build.gradle
  src/main/java/org/opensearch/knn/memoryoptsearch/MemorySegmentAddressExtractor.java
  src/main/java/org/opensearch/knn/memoryoptsearch/MemorySegmentAddressExtractorJDK21.java
  src/main/java/org/opensearch/knn/memoryoptsearch/MemorySegmentAddressExtractorJDK22.java
  src/main/java/org/opensearch/knn/memoryoptsearch/MemorySegmentAddressExtractorUtil.java
  src/main/java/org/opensearch/knn/memoryoptsearch/faiss/FaissIndexScalarQuantizedFlat.java
  src/main/java/org/opensearch/knn/memoryoptsearch/faiss/FaissMemoryOptimizedSearcher.java
  src/main/java/org/opensearch/knn/memoryoptsearch/faiss/MMapByteVectorValues.java
  src/main/java/org/opensearch/knn/memoryoptsearch/faiss/MMapFloatVectorValues.java
  src/test/java/org/opensearch/knn/memoryoptsearch/MMapByteVectorValuesTests.java
  src/test/java/org/opensearch/knn/memoryoptsearch/MMapFloatVectorValuesTests.java
  src/test/java/org/opensearch/knn/memoryoptsearch/MemorySegmentAddressExtractorTests.java
Labels: skip-changelog

#2912 Fix AVX2 detection on other platforms
  CHANGELOG.md
  src/main/java/org/opensearch/knn/jni/PlatformUtils.java
  src/test/java/org/opensearch/knn/jni/PlatformUtilTests.java
Labels: Bug Fixes, v3.3.0
