Repository opensearch-project/k-NN, pull requests merged in 2025-06, with the labels that each got.

#2677 [LuceneOnFaiss M2, PR3] Make FaissIdMapIndex support binary format in Faiss index.
  src/main/java/org/opensearch/knn/memoryoptsearch/faiss/AbstractFaissHNSWIndex.java
  src/main/java/org/opensearch/knn/memoryoptsearch/faiss/FaissHNSW.java
  src/main/java/org/opensearch/knn/memoryoptsearch/faiss/FaissHNSWIndex.java
  src/main/java/org/opensearch/knn/memoryoptsearch/faiss/FaissHnswGraph.java
  src/main/java/org/opensearch/knn/memoryoptsearch/faiss/FaissIdMapIndex.java
  src/main/java/org/opensearch/knn/memoryoptsearch/faiss/FaissMemoryOptimizedSearcher.java
  src/main/java/org/opensearch/knn/memoryoptsearch/faiss/IndexTypeToFaissIndexMapping.java
  src/main/java/org/opensearch/knn/memoryoptsearch/faiss/binary/FaissBinaryHnswIndex.java
  src/main/java/org/opensearch/knn/memoryoptsearch/faiss/binary/FaissBinaryIndex.java
  src/main/java/org/opensearch/knn/memoryoptsearch/faiss/binary/FaissIndexBinaryFlat.java
  src/main/java/org/opensearch/knn/memoryoptsearch/faiss/cagra/FaissHNSWCagraIndex.java
  src/test/java/org/opensearch/knn/jni/JNIServiceTests.java
  src/test/java/org/opensearch/knn/memoryoptsearch/FaissHNSWTests.java
  src/test/java/org/opensearch/knn/memoryoptsearch/FaissHnswGraphTests.java
  src/test/java/org/opensearch/knn/memoryoptsearch/FaissIdMapIndexTests.java
  src/test/java/org/opensearch/knn/memoryoptsearch/FaissIndexTestUtils.java
Labels: skip-changelog

#2734 Add upper bound setting for remote vector index build + GA settings changes
  CHANGELOG.md
  build.gradle
  src/main/java/org/opensearch/knn/common/featureflags/KNNFeatureFlags.java
  src/main/java/org/opensearch/knn/index/KNNSettings.java
  src/main/java/org/opensearch/knn/index/codec/nativeindex/NativeIndexBuildStrategyFactory.java
  src/main/java/org/opensearch/knn/index/codec/nativeindex/remote/RemoteIndexBuildStrategy.java
  src/main/java/org/opensearch/knn/plugin/KNNPlugin.java
  src/main/java/org/opensearch/knn/plugin/transport/KNNStatsRequest.java
  src/test/java/org/opensearch/knn/index/codec/nativeindex/remote/RemoteIndexBuildStrategyTests.java
  src/test/java/org/opensearch/knn/index/codec/nativeindex/remote/RemoteIndexBuildTests.java
  src/test/java/org/opensearch/knn/plugin/action/RestKNNStatsHandlerIT.java
  src/testFixtures/java/org/opensearch/knn/KNNRestTestCase.java
Labels: v3.1.0

#2722 Block mode and compression for indices created before version 2.17.0
  CHANGELOG.md
  qa/restart-upgrade/build.gradle
  qa/restart-upgrade/src/test/java/org/opensearch/knn/bwc/IndexingIT.java
  src/main/java/org/opensearch/knn/index/mapper/KNNVectorFieldMapper.java
Labels: Bug Fixes, backport 2.19, v3.1.0

#2728 [BUGFIX] Fix RefCount and ClearCache in some race conditions
  CHANGELOG.md
  src/main/java/org/opensearch/knn/index/query/KNNWeight.java
Labels: Bug Fixes

#2749 Update TRIAGING.md
  TRIAGING.md
Labels: Maintenance, skip-changelog

#2709 [Feature] Add rescore to Lucene Vector Search Query
  CHANGELOG.md
  release-notes/opensearch-knn.release-notes-3.1.0.0.md
  src/main/java/org/opensearch/knn/common/FieldInfoExtractor.java
  src/main/java/org/opensearch/knn/index/SpaceType.java
  src/main/java/org/opensearch/knn/index/query/ExactSearcher.java
  src/main/java/org/opensearch/knn/index/query/KNNQueryFactory.java
  src/main/java/org/opensearch/knn/index/query/KNNWeight.java
  src/main/java/org/opensearch/knn/index/query/RescoreKNNVectorQuery.java
  src/main/java/org/opensearch/knn/index/query/common/QueryUtils.java
  src/main/java/org/opensearch/knn/index/query/lucenelib/NestedKnnVectorQueryFactory.java
  src/main/java/org/opensearch/knn/index/query/nativelib/NativeEngineKnnVectorQuery.java
  src/test/java/org/opensearch/knn/index/SpaceTypeTests.java
  src/test/java/org/opensearch/knn/index/query/ExactSearcherTests.java
  src/test/java/org/opensearch/knn/index/query/ExplainTests.java
  src/test/java/org/opensearch/knn/index/query/KNNWeightTests.java
  src/test/java/org/opensearch/knn/index/query/RescoreKnnVectorQueryTests.java
  src/test/java/org/opensearch/knn/index/query/common/QueryUtilsTests.java
  src/test/java/org/opensearch/knn/index/query/nativelib/NativeEngineKNNVectorQueryTests.java
Labels: backport 3.1

#2751 [Bug Fix] Warm-up and support on_disk + 1x compression.
  src/main/java/org/opensearch/knn/index/KNNIndexShard.java
  src/main/java/org/opensearch/knn/index/KNNSettings.java
  src/main/java/org/opensearch/knn/index/codec/BasePerFieldKnnVectorsFormat.java
  src/main/java/org/opensearch/knn/index/codec/KNN990Codec/NativeEngines990KnnVectorsFormat.java
  src/main/java/org/opensearch/knn/index/codec/KNN990Codec/NativeEngines990KnnVectorsReader.java
  src/main/java/org/opensearch/knn/index/engine/MemoryOptimizedSearchSupportSpec.java
  src/main/java/org/opensearch/knn/index/engine/faiss/FaissMethodResolver.java
  src/main/java/org/opensearch/knn/index/mapper/KNNVectorFieldType.java
  src/main/java/org/opensearch/knn/index/query/BaseQueryFactory.java
  src/main/java/org/opensearch/knn/index/query/KNNQueryBuilder.java
  src/main/java/org/opensearch/knn/index/query/KNNQueryFactory.java
  src/main/java/org/opensearch/knn/index/query/RNNQueryFactory.java
  src/test/java/org/opensearch/knn/KNNSingleNodeTestCase.java
  src/test/java/org/opensearch/knn/index/KNNIndexShardTests.java
  src/test/java/org/opensearch/knn/index/codec/KNN990Codec/NativeEngines990KnnVectorsReaderTests.java
  src/test/java/org/opensearch/knn/index/codec/nativeindex/MemoryOptimizedSearchFlagInFormatTests.java
  src/test/java/org/opensearch/knn/index/engine/faiss/FaissMethodResolverTests.java
  src/test/java/org/opensearch/knn/index/query/KNNQueryBuilderTests.java
  src/test/java/org/opensearch/knn/memoryoptsearch/AbstractMemoryOptimizedKnnSearchIT.java
  src/test/java/org/opensearch/knn/memoryoptsearch/DiskMode1xCompressionSupportedIT.java
  src/test/java/org/opensearch/knn/memoryoptsearch/MOSFaissFP16IndexIT.java
  src/test/java/org/opensearch/knn/memoryoptsearch/MOSFaissFloatIndexIT.java
  src/test/java/org/opensearch/knn/memoryoptsearch/MemoryOptimizedSearchSupportSpecTests.java
Labels: skip-changelog, backport 3.1

#2757 Add -Dbuild.snapshot=$SNAPSHOT in build script for libs
  scripts/build.sh
Labels: Infrastructure, skip-changelog

#2756 [Backport 3.1] [Bug Fix] Bug fix warm-up and support on_disk + 1x compression. (#2751)
  src/main/java/org/opensearch/knn/index/KNNIndexShard.java
  src/main/java/org/opensearch/knn/index/KNNSettings.java
  src/main/java/org/opensearch/knn/index/codec/BasePerFieldKnnVectorsFormat.java
  src/main/java/org/opensearch/knn/index/codec/KNN990Codec/NativeEngines990KnnVectorsFormat.java
  src/main/java/org/opensearch/knn/index/codec/KNN990Codec/NativeEngines990KnnVectorsReader.java
  src/main/java/org/opensearch/knn/index/engine/MemoryOptimizedSearchSupportSpec.java
  src/main/java/org/opensearch/knn/index/engine/faiss/FaissMethodResolver.java
  src/main/java/org/opensearch/knn/index/mapper/KNNVectorFieldType.java
  src/main/java/org/opensearch/knn/index/query/BaseQueryFactory.java
  src/main/java/org/opensearch/knn/index/query/KNNQueryBuilder.java
  src/main/java/org/opensearch/knn/index/query/KNNQueryFactory.java
  src/main/java/org/opensearch/knn/index/query/RNNQueryFactory.java
  src/test/java/org/opensearch/knn/KNNSingleNodeTestCase.java
  src/test/java/org/opensearch/knn/index/KNNIndexShardTests.java
  src/test/java/org/opensearch/knn/index/codec/KNN990Codec/NativeEngines990KnnVectorsReaderTests.java
  src/test/java/org/opensearch/knn/index/codec/nativeindex/MemoryOptimizedSearchFlagInFormatTests.java
  src/test/java/org/opensearch/knn/index/engine/faiss/FaissMethodResolverTests.java
  src/test/java/org/opensearch/knn/index/query/KNNQueryBuilderTests.java
  src/test/java/org/opensearch/knn/memoryoptsearch/AbstractMemoryOptimizedKnnSearchIT.java
  src/test/java/org/opensearch/knn/memoryoptsearch/DiskMode1xCompressionSupportedIT.java
  src/test/java/org/opensearch/knn/memoryoptsearch/MOSFaissFP16IndexIT.java
  src/test/java/org/opensearch/knn/memoryoptsearch/MOSFaissFloatIndexIT.java
  src/test/java/org/opensearch/knn/memoryoptsearch/MemoryOptimizedSearchSupportSpecTests.java
Labels: skip-changelog

#2750 Update rescore context for 4X Compression
  release-notes/opensearch-knn.release-notes-3.1.0.0.md
  src/main/java/org/opensearch/knn/index/mapper/CompressionLevel.java
  src/main/java/org/opensearch/knn/index/mapper/KNNVectorFieldType.java
  src/test/java/org/opensearch/knn/index/mapper/CompressionLevelTests.java
  src/test/java/org/opensearch/knn/integ/ModeAndCompressionIT.java
Labels: skip-changelog, backport 3.1

#2760 [Fix] Log error responseBody on submitVectorBuild failure
  remote-index-build-client/src/main/java/org/opensearch/remoteindexbuild/client/RemoteIndexHTTPClient.java
Labels: skip-changelog, backport 3.1

#2765 [Backport 3.1] [Bug Fix] Fix Cagra HNSW graph populates random entry points at the beginning of search.
  src/main/java/org/opensearch/knn/memoryoptsearch/faiss/FaissMemoryOptimizedSearcher.java
  src/main/java/org/opensearch/knn/memoryoptsearch/faiss/cagra/FaissCagraHNSW.java
  src/main/java/org/opensearch/knn/memoryoptsearch/faiss/cagra/FaissHNSWCagraIndex.java
  src/test/java/org/opensearch/knn/memoryoptsearch/faiss/RandomEntryPointsKnnSearchStrategyTests.java
Labels: skip-changelog

#2773 Don't fall back to CPU on terminal exceptions
  CHANGELOG.md
  src/main/java/org/opensearch/knn/common/exception/TerminalIOException.java
  src/main/java/org/opensearch/knn/index/codec/nativeindex/remote/RemoteIndexBuildStrategy.java
  src/main/java/org/opensearch/knn/index/store/IndexOutputWithBuffer.java
  src/main/java/org/opensearch/knn/plugin/stats/KNNRemoteIndexBuildValue.java
  src/test/java/org/opensearch/knn/index/codec/nativeindex/remote/RemoteIndexBuildStrategyTests.java
  src/test/java/org/opensearch/knn/index/codec/nativeindex/remote/RemoteIndexBuildTests.java
Labels: v3.2.0

#2767 Update the maven snapshot publish endpoint and credential
  .github/workflows/maven-publish.yml
  build-tools/repositories.gradle
  build.gradle
  remote-index-build-client/build.gradle
Labels: skip-changelog
