Repository opensearch-project/k-NN, pull requests merged in 2025-05, with the labels that each got.

#2689 Allow maven to publish to all versions
  .github/workflows/maven-publish.yml
Labels: enhancement, release, skip-changelog, backport 3.0

#2692 Makes sure slice count is honored for non-quantization case
  CHANGELOG.md
  src/main/java/org/opensearch/knn/index/engine/KNNEngine.java
  src/main/java/org/opensearch/knn/index/query/BaseQueryFactory.java
  src/main/java/org/opensearch/knn/index/query/KNNQueryBuilder.java
  src/main/java/org/opensearch/knn/index/query/KNNQueryFactory.java
  src/test/java/org/opensearch/knn/index/query/KNNQueryBuilderTests.java
  src/test/java/org/opensearch/knn/index/query/KNNQueryFactoryTests.java
Labels: backport 2.19

#2693 [Remote Vector Index Build] fix: end remote build metrics before falling back to CPU, log exceptions
  CHANGELOG.md
  src/main/java/org/opensearch/knn/index/codec/nativeindex/remote/RemoteIndexBuildMetrics.java
  src/main/java/org/opensearch/knn/index/codec/nativeindex/remote/RemoteIndexBuildStrategy.java
Labels: Bug Fixes, backport main

#2702 [BUGFIX] Block derived source enable if index.knn is false
  CHANGELOG.md
  src/main/java/org/opensearch/knn/index/KNNSettings.java
  src/test/java/org/opensearch/knn/integ/DerivedSourceIT.java
Labels: Bug Fixes, backport 3.0

#2704 Apply mask operation in preindex to optimize derived source
  CHANGELOG.md
  src/main/java/org/opensearch/knn/index/codec/KNN10010Codec/KNN10010DerivedSourceStoredFieldsWriter.java
  src/main/java/org/opensearch/knn/index/codec/derivedsource/DerivedSourceIndexOperationListener.java
  src/test/java/org/opensearch/knn/index/codec/derivedsource/DerivedSourceIndexOperationListenerTests.java
Labels: Enhancements, backport 3.0

#2676 [LuceneOnFaiss M2, PR2] Added binary HNSW graph support in Faiss index for memory optimized search
  src/main/java/org/opensearch/knn/memoryoptsearch/faiss/FaissHNSWProvider.java
  src/main/java/org/opensearch/knn/memoryoptsearch/faiss/FaissIndex.java
  src/main/java/org/opensearch/knn/memoryoptsearch/faiss/FaissIndexLoadUtils.java
  src/main/java/org/opensearch/knn/memoryoptsearch/faiss/IndexTypeToFaissIndexMapping.java
  src/main/java/org/opensearch/knn/memoryoptsearch/faiss/binary/FaissBinaryHnswIndex.java
  src/main/java/org/opensearch/knn/memoryoptsearch/faiss/binary/FaissBinaryIndex.java
  src/main/java/org/opensearch/knn/memoryoptsearch/faiss/binary/FaissIndexBinaryFlat.java
  src/test/java/org/opensearch/knn/memoryoptsearch/FaissBinaryHnswIndexTests.java
Labels: skip-changelog

#2721 Fix compatibility with Lucene 10.2.1
  .github/workflows/remote_index_build.yml
  src/main/java/org/opensearch/knn/index/codec/KNN10010Codec/KNN10010DerivedSourceStoredFieldsWriter.java
  src/main/java/org/opensearch/knn/index/codec/KNN9120Codec/KNN9120BinaryVectorScorer.java
  src/main/java/org/opensearch/knn/index/codec/KNN990Codec/QuantizationConfigKNNCollector.java
  src/main/java/org/opensearch/knn/index/query/KNNScorer.java
  src/main/java/org/opensearch/knn/index/query/KNNWeight.java
  src/main/java/org/opensearch/knn/index/query/ResultUtil.java
  src/main/java/org/opensearch/knn/memoryoptsearch/faiss/FaissHnswGraph.java
  src/test/java/org/opensearch/knn/index/codec/backward_codecs/KNN9120Codec/KNN9120DerivedSourceStoredFieldVisitorTests.java
  src/test/java/org/opensearch/knn/index/query/KNNWeightTests.java
Labels: skip-changelog

#2719 Avoid opening of graph file if graph is already loaded in memory
  CHANGELOG.md
  src/main/java/org/opensearch/knn/index/memory/NativeMemoryCacheManager.java
  src/test/java/org/opensearch/knn/index/memory/NativeMemoryCacheManagerTests.java
Labels: Bug Fixes, performance, backport 2.19, v3.1.0

#2723 [Backport: 2.19] Avoid opening of graph file if graph is already loaded in memory
  CHANGELOG.md
  src/main/java/org/opensearch/knn/index/memory/NativeMemoryCacheManager.java
  src/test/java/org/opensearch/knn/index/memory/NativeMemoryCacheManagerTests.java
Labels: Bug Fixes
