Repository opensearch-project/k-NN, pull requests merged in 2025-01, with the labels that each got.

#2320 Add check to directly use ANN Search when filters match all docs.
  CHANGELOG.md
  src/main/java/org/opensearch/knn/index/query/FilterIdsSelector.java
  src/main/java/org/opensearch/knn/index/query/KNNWeight.java
  src/test/java/org/opensearch/knn/index/query/KNNWeightTests.java
  src/test/java/org/opensearch/knn/integ/FilteredSearchANNSearchIT.java
Labels: backport 2.x

#2365 Added the fix for NPE happening during merges when all vector fields docs are deleted in the segments getting merged
  CHANGELOG.md
  src/main/java/org/opensearch/knn/common/KNNVectorUtil.java
  src/main/java/org/opensearch/knn/index/codec/nativeindex/DefaultIndexBuildStrategy.java
  src/main/java/org/opensearch/knn/index/codec/nativeindex/MemOptimizedNativeIndexBuildStrategy.java
  src/main/java/org/opensearch/knn/index/codec/nativeindex/NativeIndexWriter.java
  src/main/java/org/opensearch/knn/index/codec/util/KNNCodecUtil.java
  src/test/java/org/opensearch/knn/common/KNNVectorUtilTests.java
  src/test/java/org/opensearch/knn/index/codec/util/KNNCodecUtilTests.java
Labels: Bug Fixes, backport 2.x

#2364 Adding @0ctopus13prime as the maintainer for the k-NN repo
  .github/CODEOWNERS
  MAINTAINERS.md
Labels: backport 2.x, skip-changelog

#2372 Adding @0ctopus13prime as the maintainer for the k-NN repo (#2364)
  .github/CODEOWNERS
  MAINTAINERS.md
Labels: skip-changelog

#2388 Remove debugging println from source
  src/testFixtures/java/org/opensearch/knn/KNNRestTestCase.java
Labels: skip-changelog

#2387 Fix sequence of NativeMemory/QuantizationState cache test setup/teardown
  src/test/java/org/opensearch/knn/index/memory/NativeMemoryCacheManagerTests.java
  src/test/java/org/opensearch/knn/quantization/models/quantizationState/QuantizationStateCacheTests.java
Labels: skip-changelog

#2389 [Backport 2.x] Fixed a bug that does not get a space type from index setting when it…
  CHANGELOG.md
  qa/restart-upgrade/src/test/java/org/opensearch/knn/bwc/IndexingIT.java
  qa/restart-upgrade/src/test/java/org/opensearch/knn/bwc/ScriptScoringIT.java
  qa/restart-upgrade/src/test/java/org/opensearch/knn/bwc/WarmupIT.java
  src/main/java/org/opensearch/knn/index/engine/SpaceTypeResolver.java
  src/main/java/org/opensearch/knn/index/mapper/KNNVectorFieldMapper.java
  src/main/java/org/opensearch/knn/index/mapper/KNNVectorFieldMapperUtil.java
  src/main/java/org/opensearch/knn/plugin/rest/RestTrainModelHandler.java
  src/test/java/org/opensearch/knn/index/KNNESSettingsTestIT.java
  src/test/java/org/opensearch/knn/index/engine/SpaceTypeResolverTests.java
  src/test/java/org/opensearch/knn/index/mapper/KNNVectorFieldMapperTests.java
Labels: backlog

#2398 Add WithFieldName implementation to KNNQueryBuilder
  CHANGELOG.md
  src/main/java/org/opensearch/knn/index/query/KNNQueryBuilder.java
Labels: backport 2.x

#2397 Fix build for macos
  CHANGELOG.md
  DEVELOPER_GUIDE.md
  build.gradle
  jni/cmake/init-faiss.cmake
Labels: Infrastructure, backport 2.x

#2376 Add cosine similarity support for faiss engine
  CHANGELOG.md
  src/main/java/org/opensearch/knn/index/engine/AbstractKNNMethod.java
  src/main/java/org/opensearch/knn/index/engine/KNNLibraryIndexingContext.java
  src/main/java/org/opensearch/knn/index/engine/KNNLibraryIndexingContextImpl.java
  src/main/java/org/opensearch/knn/index/engine/faiss/AbstractFaissMethod.java
  src/main/java/org/opensearch/knn/index/engine/faiss/Faiss.java
  src/main/java/org/opensearch/knn/index/engine/faiss/FaissHNSWMethod.java
  src/main/java/org/opensearch/knn/index/engine/faiss/FaissIVFMethod.java
  src/main/java/org/opensearch/knn/index/mapper/FlatVectorFieldMapper.java
  src/main/java/org/opensearch/knn/index/mapper/KNNVectorFieldMapper.java
  src/main/java/org/opensearch/knn/index/mapper/KNNVectorFieldType.java
  src/main/java/org/opensearch/knn/index/mapper/MethodFieldMapper.java
  src/main/java/org/opensearch/knn/index/mapper/ModelFieldMapper.java
  src/main/java/org/opensearch/knn/index/mapper/NormalizeVectorTransformer.java
  src/main/java/org/opensearch/knn/index/mapper/VectorTransformer.java
  src/main/java/org/opensearch/knn/index/mapper/VectorTransformerFactory.java
  src/main/java/org/opensearch/knn/index/query/KNNQueryBuilder.java
  src/test/java/org/opensearch/knn/index/FaissIT.java
  src/test/java/org/opensearch/knn/index/mapper/NormalizeVectorTransformerTests.java
  src/test/java/org/opensearch/knn/index/mapper/VectorTransformerFactoryTests.java
  src/test/java/org/opensearch/knn/recall/RecallTestsIT.java
  src/testFixtures/java/org/opensearch/knn/KNNRestTestCase.java
Labels: backport 2.x, v2.19.0

#2416 Mute testKNNWarmupCustomLegacyFieldMapping
  qa/restart-upgrade/src/test/java/org/opensearch/knn/bwc/WarmupIT.java
Labels: backport 2.x, skip-changelog

#2408 Remove DocsWithFieldSet reference from NativeEngineFieldVectorsWriter
  CHANGELOG.md
  src/main/java/org/opensearch/knn/index/codec/KNN990Codec/NativeEngineFieldVectorsWriter.java
  src/main/java/org/opensearch/knn/index/codec/KNN990Codec/NativeEngines990KnnVectorsWriter.java
  src/test/java/org/opensearch/knn/index/codec/KNN990Codec/NativeEngineFieldVectorsWriterTests.java
  src/test/java/org/opensearch/knn/index/codec/KNN990Codec/NativeEngines990KnnVectorsWriterFlushTests.java
  src/test/java/org/opensearch/knn/index/codec/KNN990Codec/NativeEngines990KnnVectorsWriterMergeTests.java
Labels: backport 2.x

#2426 [Manual backport 2.x]Remove DocsWithFieldSet reference from NativeEngineFieldVectorsWriter
  CHANGELOG.md
  src/main/java/org/opensearch/knn/index/codec/KNN990Codec/NativeEngineFieldVectorsWriter.java
  src/main/java/org/opensearch/knn/index/codec/KNN990Codec/NativeEngines990KnnVectorsWriter.java
  src/test/java/org/opensearch/knn/index/codec/KNN990Codec/NativeEngineFieldVectorsWriterTests.java
  src/test/java/org/opensearch/knn/index/codec/KNN990Codec/NativeEngines990KnnVectorsWriterFlushTests.java
  src/test/java/org/opensearch/knn/index/codec/KNN990Codec/NativeEngines990KnnVectorsWriterMergeTests.java
Labels: v2.19.0

#2404 Add a FAISS_OPT_LEVEL=avx512_spr build mode.
  .github/workflows/CI.yml
  .github/workflows/backwards_compatibility_tests_workflow.yml
  .github/workflows/test_security.yml
  CHANGELOG.md
  DEVELOPER_GUIDE.md
  build.gradle
  jni/cmake/init-faiss.cmake
  scripts/build.sh
  src/main/java/org/opensearch/knn/common/KNNConstants.java
  src/main/java/org/opensearch/knn/index/KNNSettings.java
  src/main/java/org/opensearch/knn/jni/FaissService.java
  src/main/java/org/opensearch/knn/jni/PlatformUtils.java
  src/main/plugin-metadata/plugin-security.policy
  src/test/java/org/opensearch/knn/jni/PlatformUtilTests.java
Labels: Features, backport 2.x, v2.19.0

#2378 Added more detailed error messages for KNN model training
  CHANGELOG.md
  qa/restart-upgrade/src/test/java/org/opensearch/knn/bwc/FaissSQIT.java
  src/main/java/org/opensearch/knn/index/engine/AbstractKNNMethod.java
  src/main/java/org/opensearch/knn/index/engine/KNNLibraryIndexingContext.java
  src/main/java/org/opensearch/knn/index/engine/KNNLibraryIndexingContextImpl.java
  src/main/java/org/opensearch/knn/index/engine/TrainingConfigValidationInput.java
  src/main/java/org/opensearch/knn/index/engine/TrainingConfigValidationOutput.java
  src/main/java/org/opensearch/knn/plugin/transport/TrainingJobRouterTransportAction.java
  src/main/java/org/opensearch/knn/plugin/transport/TrainingModelRequest.java
  src/main/java/org/opensearch/knn/training/TrainingJob.java
  src/test/java/org/opensearch/knn/index/FaissIT.java
  src/test/java/org/opensearch/knn/index/VectorDataTypeIT.java
  src/test/java/org/opensearch/knn/integ/KNNScriptScoringIT.java
  src/test/java/org/opensearch/knn/integ/ModeAndCompressionIT.java
  src/test/java/org/opensearch/knn/plugin/action/RestKNNStatsHandlerIT.java
  src/test/java/org/opensearch/knn/plugin/action/RestTrainModelHandlerIT.java
  src/test/java/org/opensearch/knn/plugin/transport/TrainingJobRouterTransportActionTests.java
  src/test/java/org/opensearch/knn/plugin/transport/TrainingModelRequestTests.java
  src/test/java/org/opensearch/knn/recall/RecallTestsIT.java
  src/test/java/org/opensearch/knn/training/TrainingJobTests.java
Labels: backport main

#2410 Fixing bug where mapping accepts both dimension and model-id
  CHANGELOG.md
  src/main/java/org/opensearch/knn/index/mapper/KNNVectorFieldMapper.java
  src/test/java/org/opensearch/knn/index/mapper/KNNVectorFieldMapperTests.java
Labels: backport 2.x

#2441 Concurrency optimization for graph native loading update
  CHANGELOG.md
  src/main/java/org/opensearch/knn/index/memory/NativeMemoryCacheManager.java
  src/main/java/org/opensearch/knn/index/memory/NativeMemoryEntryContext.java
  src/main/java/org/opensearch/knn/index/memory/NativeMemoryLoadStrategy.java
  src/test/java/org/opensearch/knn/index/memory/NativeMemoryCacheManagerTests.java
  src/test/java/org/opensearch/knn/index/memory/NativeMemoryEntryContextTests.java
  src/test/java/org/opensearch/knn/index/memory/NativeMemoryLoadStrategyTests.java
Labels: backport main

#2445 Add UnmodifiableOnRestore property to index.knn setting
  CHANGELOG.md
  src/main/java/org/opensearch/knn/index/KNNSettings.java
  src/test/java/org/opensearch/knn/index/RestoreSnapshotIT.java
  src/testFixtures/java/org/opensearch/knn/KNNRestTestCase.java
Labels: Features

#2453 Add mirror repository for spotless
  CHANGELOG.md
  gradle/formatting.gradle
Labels: backport main

#2457 Properly set gcc version lock on x64 and arm64 for avx512_spr support
  scripts/build.sh
Labels: Enhancements, Bug Fixes, release, backport 2.x, skip-changelog, v2.19.0

#2448 Fix Faiss byte vector efficient filter bug
  CHANGELOG.md
  src/main/java/org/opensearch/knn/index/query/KNNWeight.java
  src/test/java/org/opensearch/knn/index/VectorDataTypeIT.java
  src/testFixtures/java/org/opensearch/knn/KNNRestTestCase.java
Labels: Bug Fixes, backport main, v2.19.0

#2444 Fix rolling upgrade bwc workflow avx512spr
  .github/workflows/backwards_compatibility_tests_workflow.yml
  scripts/build.sh
Labels: Infrastructure, skip-changelog

#2452 Update default to 0 to always build graph as default behavior
  CHANGELOG.md
  src/main/java/org/opensearch/knn/index/KNNSettings.java
Labels: backport main

#2461 Add path.repo for registering snapshot repository in integ tests
  build.gradle
  src/testFixtures/java/org/opensearch/knn/KNNRestTestCase.java
Labels: backport main, skip-changelog

#2449 Introduce derived vector source via stored fields
  CHANGELOG.md
  build.gradle
  src/main/java/org/opensearch/knn/common/KNNConstants.java
  src/main/java/org/opensearch/knn/index/KNNSettings.java
  src/main/java/org/opensearch/knn/index/codec/KNN9120Codec/DerivedSourceStoredFieldsFormat.java
  src/main/java/org/opensearch/knn/index/codec/KNN9120Codec/DerivedSourceStoredFieldsReader.java
  src/main/java/org/opensearch/knn/index/codec/KNN9120Codec/DerivedSourceStoredFieldsWriter.java
  src/main/java/org/opensearch/knn/index/codec/KNN9120Codec/KNN9120Codec.java
  src/main/java/org/opensearch/knn/index/codec/KNNCodecVersion.java
  src/main/java/org/opensearch/knn/index/codec/derivedsource/DerivedSourceReaderSupplier.java
  src/main/java/org/opensearch/knn/index/codec/derivedsource/DerivedSourceReaders.java
  src/main/java/org/opensearch/knn/index/codec/derivedsource/DerivedSourceReadersSupplier.java
  src/main/java/org/opensearch/knn/index/codec/derivedsource/DerivedSourceStoredFieldVisitor.java
  src/main/java/org/opensearch/knn/index/codec/derivedsource/DerivedSourceVectorInjector.java
  src/main/java/org/opensearch/knn/index/codec/derivedsource/NestedPerFieldDerivedVectorInjector.java
  src/main/java/org/opensearch/knn/index/codec/derivedsource/NestedPerFieldParentToDocIdIterator.java
  src/main/java/org/opensearch/knn/index/codec/derivedsource/ParentChildHelper.java
  src/main/java/org/opensearch/knn/index/codec/derivedsource/PerFieldDerivedVectorInjector.java
  src/main/java/org/opensearch/knn/index/codec/derivedsource/PerFieldDerivedVectorInjectorFactory.java
  src/main/java/org/opensearch/knn/index/codec/derivedsource/RootPerFieldDerivedVectorInjector.java
  src/main/java/org/opensearch/knn/index/mapper/FlatVectorFieldMapper.java
  src/main/java/org/opensearch/knn/index/mapper/KNNVectorFieldMapper.java
  src/main/java/org/opensearch/knn/index/mapper/LuceneFieldMapper.java
  src/main/java/org/opensearch/knn/index/mapper/MethodFieldMapper.java
  src/main/java/org/opensearch/knn/index/mapper/ModelFieldMapper.java
  src/main/java/org/opensearch/knn/index/vectorvalues/KNNVectorValuesFactory.java
  src/test/java/org/opensearch/knn/index/mapper/KNNVectorFieldMapperTests.java
  src/test/java/org/opensearch/knn/integ/DerivedSourceIT.java
  src/testFixtures/java/org/opensearch/knn/KNNRestTestCase.java
Labels: Features, backport main

#2466 Adds debug logs for KNNQuery and KNNWeight
  src/main/java/org/opensearch/knn/index/query/KNNQuery.java
  src/main/java/org/opensearch/knn/index/query/KNNQueryFactory.java
  src/main/java/org/opensearch/knn/index/query/KNNWeight.java
Labels: backport main, skip-changelog, backport 2.19

#2472 Switch away from getMergeInstance for derived source
  src/main/java/org/opensearch/knn/index/codec/KNN9120Codec/DerivedSourceStoredFieldsReader.java
  src/main/java/org/opensearch/knn/index/codec/KNN9120Codec/DerivedSourceStoredFieldsWriter.java
Labels: Bug Fixes, backport 2.x, backport main, skip-changelog

#2460 [Release 3.0] Update gradle to 8.10.2 to support JDK23
  .github/workflows/CI.yml
  build-tools/knnplugin-coverage.gradle
  gradle/wrapper/gradle-wrapper.properties
Labels: Enhancements, release, v3.0.0, skip-changelog

#2477 Add version check for full field name validation
  CHANGELOG.md
  src/main/java/org/opensearch/knn/index/mapper/KNNVectorFieldMapper.java
  src/main/java/org/opensearch/knn/index/mapper/KNNVectorFieldMapperUtil.java
  src/test/java/org/opensearch/knn/index/mapper/KNNVectorFieldMapperTests.java
  src/test/java/org/opensearch/knn/index/mapper/KNNVectorFieldMapperUtilTests.java
Labels: backport main, backport 2.19
