Repository opensearch-project/k-NN, pull requests merged in 2025-02, with the labels that each got.

#2482 Adding Vikasht34 as maintainer for k-NN repo
  .github/CODEOWNERS
  MAINTAINERS.md
Labels: backport 2.x, skip-changelog

#2487 Adding Vikasht34 as maintainer for k-NN repo (#2482)
  .github/CODEOWNERS
  MAINTAINERS.md
Labels: skip-changelog

#2480 Enabled concurrent graph creation for Lucene engine with index thread qty settings
  CHANGELOG.md
  src/main/java/org/opensearch/knn/index/KNNSettings.java
  src/main/java/org/opensearch/knn/index/codec/KNN9120Codec/KNN9120PerFieldKnnVectorsFormat.java
  src/main/java/org/opensearch/knn/index/codec/nativeindex/NativeIndexWriter.java
  src/main/java/org/opensearch/knn/training/TrainingJob.java
  src/test/java/org/opensearch/knn/index/KNNSettingsTests.java
Labels: Enhancements, backport main, indexing-improvements, backport 2.19

#2495 Fix warn logs for engine deprecation
  src/main/java/org/opensearch/knn/index/engine/EngineResolver.java
  src/main/java/org/opensearch/knn/index/engine/KNNEngine.java
  src/main/java/org/opensearch/knn/index/engine/nmslib/NmslibMethodResolver.java
  src/main/java/org/opensearch/knn/jni/JNIService.java
Labels: backport main, skip-changelog, backport 2.19

#2494 Fix bytes offset bug and duplicate readers and add uTs for derived source
  src/main/java/org/opensearch/knn/index/codec/KNN9120Codec/DerivedSourceStoredFieldsFormat.java
  src/main/java/org/opensearch/knn/index/codec/KNN9120Codec/DerivedSourceStoredFieldsReader.java
  src/main/java/org/opensearch/knn/index/codec/KNN9120Codec/DerivedSourceStoredFieldsWriter.java
  src/main/java/org/opensearch/knn/index/codec/KNN9120Codec/KNN9120Codec.java
  src/main/java/org/opensearch/knn/index/codec/derivedsource/DerivedSourceReaders.java
  src/main/java/org/opensearch/knn/index/codec/derivedsource/DerivedSourceReadersSupplier.java
  src/main/java/org/opensearch/knn/index/codec/derivedsource/DerivedSourceVectorInjector.java
  src/main/java/org/opensearch/knn/index/codec/derivedsource/ParentChildHelper.java
  src/main/java/org/opensearch/knn/index/vectorvalues/VectorValueExtractorStrategy.java
  src/test/java/org/opensearch/knn/index/codec/KNN9120Codec/DerivedSourceStoredFieldsWriterTests.java
  src/test/java/org/opensearch/knn/index/codec/derivedsource/DerivedSourceStoredFieldVisitorTests.java
  src/test/java/org/opensearch/knn/index/codec/derivedsource/DerivedSourceVectorInjectorTests.java
  src/test/java/org/opensearch/knn/index/codec/derivedsource/ParentChildHelperTests.java
  src/test/java/org/opensearch/knn/index/codec/derivedsource/PerFieldDerivedVectorInjectorFactoryTests.java
  src/test/java/org/opensearch/knn/index/codec/derivedsource/RootPerFieldDerivedVectorInjectorTests.java
Labels: Bug Fixes, backport 2.x, backport main, skip-changelog

#2473 Changes to publish jar to maven
  .github/workflows/maven-publish.yml
Labels: backport main, skip-changelog

#2493 [Backport main] Enabled concurrent graph creation for Lucene engine with index thread qty settings (#2480)
  CHANGELOG.md
  src/main/java/org/opensearch/knn/index/KNNSettings.java
  src/main/java/org/opensearch/knn/index/codec/KNN9120Codec/KNN9120PerFieldKnnVectorsFormat.java
  src/main/java/org/opensearch/knn/index/codec/nativeindex/NativeIndexWriter.java
  src/main/java/org/opensearch/knn/training/TrainingJob.java
  src/test/java/org/opensearch/knn/index/KNNSettingsTests.java
Labels: Enhancements, indexing-improvements

#2501 Update engine for version 2.19 or above
  release-notes/opensearch-knn.release-notes-2.19.0.0.md
  src/main/java/org/opensearch/knn/index/engine/EngineResolver.java
  src/main/java/org/opensearch/knn/index/mapper/KNNVectorFieldMapper.java
  src/main/java/org/opensearch/knn/plugin/transport/TrainingModelRequest.java
  src/test/java/org/opensearch/knn/index/engine/EngineResolverTests.java
  src/test/java/org/opensearch/knn/index/mapper/KNNVectorFieldMapperTests.java
Labels: skip-changelog

#2506 Update build.gradle and build.sh to separate x64 linux nmslib build with different gcc versions
  .github/workflows/CI.yml
  .github/workflows/test_security.yml
  build.gradle
  qa/restart-upgrade/build.gradle
  qa/rolling-upgrade/build.gradle
  scripts/build.sh
Labels: backport 2.x, skip-changelog

#2516 Clean JNI artifacts with ./gradlew clean
  .gitignore
  CHANGELOG.md
  build.gradle
  jni/cmake/macros.cmake
  qa/restart-upgrade/build.gradle
  qa/rolling-upgrade/build.gradle
Labels: Maintenance, skip-changelog

#2523 Increment version to 2.20.0-SNAPSHOT
  .github/workflows/backwards_compatibility_tests_workflow.yml
  build.gradle
  qa/restart-upgrade/src/test/java/org/opensearch/knn/bwc/ModelIT.java
Labels: skip-changelog

#2526 Fix main knnlib dir in build script based on #2442
  scripts/build.sh
Labels: release, v3.0.0, skip-changelog

#2528 Minor performance improvments in KNNQueryBuilder
  src/main/java/org/opensearch/knn/index/query/KNNQueryBuilder.java
  src/main/java/org/opensearch/knn/index/query/KNNQueryFactory.java
Labels: backport 2.x, skip-changelog

#2533 Fix derived source for binary and byte vectors
  CHANGELOG.md
  src/main/java/org/opensearch/knn/index/codec/derivedsource/AbstractPerFieldDerivedVectorInjector.java
  src/main/java/org/opensearch/knn/index/codec/derivedsource/NestedPerFieldDerivedVectorInjector.java
  src/main/java/org/opensearch/knn/index/codec/derivedsource/RootPerFieldDerivedVectorInjector.java
  src/main/java/org/opensearch/knn/index/mapper/KNNVectorFieldMapperUtil.java
  src/test/java/org/opensearch/knn/index/mapper/KNNVectorFieldMapperUtilTests.java
  src/test/java/org/opensearch/knn/integ/DerivedSourceIT.java
  src/testFixtures/java/org/opensearch/knn/KNNRestTestCase.java
  src/testFixtures/java/org/opensearch/knn/TestUtils.java
Labels: Bug Fixes, backport 2.x

#2542 Fix the put mapping issue for already created index with flat mapper
  CHANGELOG.md
  src/main/java/org/opensearch/knn/index/mapper/KNNVectorFieldMapper.java
  src/test/java/org/opensearch/knn/index/KNNMapperSearcherIT.java
Labels: Bug Fixes, backport 2.x

#2525 [Remote Vector Index Build] Introduce RemoteNativeIndexBuildStrategy skeleton
  qa/restart-upgrade/src/test/java/org/opensearch/knn/bwc/AbstractRestartUpgradeTestCase.java
  qa/rolling-upgrade/src/test/java/org/opensearch/knn/bwc/AbstractRollingUpgradeTestCase.java
  src/main/java/org/opensearch/knn/common/featureflags/KNNFeatureFlags.java
  src/main/java/org/opensearch/knn/index/KNNSettings.java
  src/main/java/org/opensearch/knn/index/codec/BasePerFieldKnnVectorsFormat.java
  src/main/java/org/opensearch/knn/index/codec/KNN80Codec/KNN80DocValuesConsumer.java
  src/main/java/org/opensearch/knn/index/codec/KNN9120Codec/KNN9120PerFieldKnnVectorsFormat.java
  src/main/java/org/opensearch/knn/index/codec/KNN990Codec/NativeEngines990KnnVectorsFormat.java
  src/main/java/org/opensearch/knn/index/codec/KNN990Codec/NativeEngines990KnnVectorsWriter.java
  src/main/java/org/opensearch/knn/index/codec/KNNCodecService.java
  src/main/java/org/opensearch/knn/index/codec/KNNCodecVersion.java
  src/main/java/org/opensearch/knn/index/codec/nativeindex/DefaultIndexBuildStrategy.java
  src/main/java/org/opensearch/knn/index/codec/nativeindex/MemOptimizedNativeIndexBuildStrategy.java
  src/main/java/org/opensearch/knn/index/codec/nativeindex/NativeIndexBuildStrategyFactory.java
  src/main/java/org/opensearch/knn/index/codec/nativeindex/NativeIndexWriter.java
  src/main/java/org/opensearch/knn/index/codec/nativeindex/model/BuildIndexParams.java
  src/main/java/org/opensearch/knn/index/codec/nativeindex/remote/RemoteIndexBuildStrategy.java
  src/main/java/org/opensearch/knn/index/engine/KNNEngine.java
  src/main/java/org/opensearch/knn/index/engine/KNNLibrary.java
  src/main/java/org/opensearch/knn/index/engine/faiss/Faiss.java
  src/main/java/org/opensearch/knn/index/vectorvalues/KNNVectorValuesFactory.java
  src/main/java/org/opensearch/knn/plugin/KNNPlugin.java
  src/test/java/org/opensearch/knn/index/codec/KNN990Codec/NativeEngines990KnnVectorsFormatTests.java
  src/test/java/org/opensearch/knn/index/codec/KNN990Codec/NativeEngines990KnnVectorsWriterFlushTests.java
  src/test/java/org/opensearch/knn/index/codec/KNN990Codec/NativeEngines990KnnVectorsWriterMergeTests.java
  src/test/java/org/opensearch/knn/index/codec/KNNCodecServiceTests.java
  src/test/java/org/opensearch/knn/index/codec/nativeindex/DefaultIndexBuildStrategyTests.java
  src/test/java/org/opensearch/knn/index/codec/nativeindex/MemOptimizedNativeIndexBuildStrategyTests.java
  src/test/java/org/opensearch/knn/index/codec/nativeindex/remote/RemoteIndexBuildStrategyTests.java
  src/testFixtures/java/org/opensearch/knn/KNNRestTestCase.java
Labels: v3.0.0, skip-changelog

#2546 Refactor codec to leverage backwards_codecs
  CHANGELOG.md
  src/main/java/org/opensearch/knn/index/codec/KNN10010Codec/KNN10010Codec.java
  src/main/java/org/opensearch/knn/index/codec/KNN80Codec/KNN80Codec.java
  src/main/java/org/opensearch/knn/index/codec/KNN84Codec/KNN84Codec.java
  src/main/java/org/opensearch/knn/index/codec/KNN86Codec/KNN86Codec.java
  src/main/java/org/opensearch/knn/index/codec/KNN87Codec/KNN87Codec.java
  src/main/java/org/opensearch/knn/index/codec/KNN910Codec/KNN910Codec.java
  src/main/java/org/opensearch/knn/index/codec/KNNCodecService.java
  src/main/java/org/opensearch/knn/index/codec/KNNCodecVersion.java
  src/main/java/org/opensearch/knn/index/codec/KNNFormatFacade.java
  src/main/java/org/opensearch/knn/index/codec/backward_codecs/KNN910Codec/KNN910Codec.java
  src/main/java/org/opensearch/knn/index/codec/backward_codecs/KNN9120Codec/KNN9120Codec.java
  src/main/java/org/opensearch/knn/index/codec/backward_codecs/KNN920Codec/KNN920Codec.java
  src/main/java/org/opensearch/knn/index/codec/backward_codecs/KNN920Codec/KNN920PerFieldKnnVectorsFormat.java
  src/main/java/org/opensearch/knn/index/codec/backward_codecs/KNN940Codec/KNN940Codec.java
  src/main/java/org/opensearch/knn/index/codec/backward_codecs/KNN940Codec/KNN940PerFieldKnnVectorsFormat.java
  src/main/java/org/opensearch/knn/index/codec/backward_codecs/KNN950Codec/KNN950Codec.java
  src/main/java/org/opensearch/knn/index/codec/backward_codecs/KNN950Codec/KNN950PerFieldKnnVectorsFormat.java
  src/main/java/org/opensearch/knn/index/codec/backward_codecs/KNN990Codec/KNN990Codec.java
  src/main/java/org/opensearch/knn/index/codec/backward_codecs/KNN990Codec/KNN990PerFieldKnnVectorsFormat.java
  src/main/java/org/opensearch/knn/index/codec/util/UnitTestCodec.java
  src/main/resources/META-INF/services/org.apache.lucene.codecs.Codec
  src/test/java/org/opensearch/knn/index/codec/KNN10010Codec/KNN10010CodecTests.java
  src/test/java/org/opensearch/knn/index/codec/KNN80Codec/KNN80CompoundFormatTests.java
  src/test/java/org/opensearch/knn/index/codec/KNN80Codec/KNN80DocValuesConsumerTests.java
  src/test/java/org/opensearch/knn/index/codec/KNN80Codec/KNN80DocValuesProducerTests.java
  src/test/java/org/opensearch/knn/index/codec/KNN87Codec/KNN87CodecTests.java
  src/test/java/org/opensearch/knn/index/codec/KNN990Codec/KNN990CodecTests.java
  src/test/java/org/opensearch/knn/index/codec/KNN990Codec/NativeEngines990KnnVectorsFormatTests.java
  src/test/java/org/opensearch/knn/index/codec/KNNCodecFactoryTests.java
  src/test/java/org/opensearch/knn/index/codec/KNNCodecServiceTests.java
  src/test/java/org/opensearch/knn/index/query/ExactSearcherTests.java
  src/test/java/org/opensearch/knn/index/query/KNNWeightTests.java
Labels: Refactoring

#2550 [Remote Vector Index Build] Add vector data upload implementation to RemoteIndexBuildStrategy
  CHANGELOG.md
  src/main/java/org/opensearch/knn/index/KNNSettings.java
  src/main/java/org/opensearch/knn/index/codec/nativeindex/NativeIndexBuildStrategyFactory.java
  src/main/java/org/opensearch/knn/index/codec/nativeindex/NativeIndexWriter.java
  src/main/java/org/opensearch/knn/index/codec/nativeindex/remote/DefaultVectorRepositoryAccessor.java
  src/main/java/org/opensearch/knn/index/codec/nativeindex/remote/DocIdInputStream.java
  src/main/java/org/opensearch/knn/index/codec/nativeindex/remote/RemoteIndexBuildStrategy.java
  src/main/java/org/opensearch/knn/index/codec/nativeindex/remote/VectorRepositoryAccessor.java
  src/main/java/org/opensearch/knn/index/codec/nativeindex/remote/VectorValuesInputStream.java
  src/main/java/org/opensearch/knn/index/codec/nativeindex/remote/package-info.java
  src/test/java/org/opensearch/knn/index/codec/nativeindex/remote/DefaultVectorRepositoryAccessorTests.java
  src/test/java/org/opensearch/knn/index/codec/nativeindex/remote/KnnVectorValuesInputStreamTests.java
  src/test/java/org/opensearch/knn/index/codec/nativeindex/remote/RemoteIndexBuildStrategyTests.java
  src/test/java/org/opensearch/knn/index/codec/nativeindex/remote/RemoteIndexBuildTests.java
  src/test/java/org/opensearch/knn/index/vectorvalues/TestVectorValues.java
  src/testFixtures/java/org/opensearch/knn/KNNRestTestCase.java
Labels: v3.0.0

#2485 [Backport main] Fix Faiss byte vector efficient filter bug (#2448)
  src/main/java/org/opensearch/knn/index/query/KNNWeight.java
  src/test/java/org/opensearch/knn/index/VectorDataTypeIT.java
  src/testFixtures/java/org/opensearch/knn/KNNRestTestCase.java
Labels: skip-changelog

#2462 Update training validation to be handled per algo type
  qa/restart-upgrade/src/test/java/org/opensearch/knn/bwc/FaissSQIT.java
  src/main/java/org/opensearch/knn/index/engine/AbstractKNNMethod.java
  src/main/java/org/opensearch/knn/index/engine/Encoder.java
  src/main/java/org/opensearch/knn/index/engine/TrainingConfigValidationOutput.java
  src/main/java/org/opensearch/knn/index/engine/faiss/AbstractFaissMethod.java
  src/main/java/org/opensearch/knn/index/engine/faiss/AbstractFaissPQEncoder.java
  src/main/java/org/opensearch/knn/index/engine/faiss/FaissHNSWMethod.java
  src/main/java/org/opensearch/knn/index/engine/faiss/FaissIVFMethod.java
  src/main/java/org/opensearch/knn/index/engine/faiss/FaissMethodResolver.java
  src/main/java/org/opensearch/knn/plugin/transport/TrainingJobRouterTransportAction.java
  src/main/java/org/opensearch/knn/plugin/transport/TrainingModelRequest.java
  src/test/java/org/opensearch/knn/index/FaissIT.java
  src/test/java/org/opensearch/knn/index/engine/faiss/FaissMethodResolverTests.java
  src/test/java/org/opensearch/knn/plugin/action/RestTrainModelHandlerIT.java
  src/test/java/org/opensearch/knn/plugin/transport/TrainingModelRequestTests.java
Labels: v3.0.0, skip-changelog
